const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const P=require('../scripts/fachkalender-plan.js');
const S=require('../scripts/fachkalender-school.js');
const F=require('../scripts/fachkalender-frozen.js');
const data=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/fachkalender.json'),'utf8'));
const baseYears=structuredClone(data.years);
const today='2026-09-30';
const closure={id:'school-test-october',title:'Projekttag',start:'2026-10-06',end:'2026-10-06',kind:'project',tracks:['7'],source:'Test'};
const old={version:1,years:{},closures:[],removedClosureIds:[]};
const settings={version:1,years:{},closures:[closure],removedClosureIds:[],revisions:[{until:today,settings:old}]};
assert.equal(S.validSettings(settings),true);
const groups=[{id:'group-a',track:'7',label:'7a',days:{2:2,5:2}},{id:'group-b',track:'7',label:'7b',days:{4:2}}];
const before=P.plan(data,'chemie','2026',data.closures,{},[],{},groups);
const after=F.build(data,baseYears,settings,'chemie','2026',{},[],{},groups,[],today);
function assignments(result,id,predicate){
 return result.events.filter(e=>e.kind==='unit'&&e.groupId===id).flatMap(e=>e.meetingDays.filter(predicate).map(day=>day+'='+e.code)).sort();
}
assert.deepEqual(assignments(after,'group-a',d=>d<today),assignments(before,'group-a',d=>d<today),'Past lessons must keep their original unit');
assert.deepEqual(assignments(after,'group-b',d=>d<today),assignments(before,'group-b',d=>d<today),'Parallel groups must freeze independently');
assert.equal(assignments(after,'group-a',d=>d===closure.start).length,0,'The new free day must be removed');
assert.ok(assignments(after,'group-a',d=>d>=today).length>0,'Future lessons must still be distributed');
const futureA=assignments(after,'group-a',d=>d>=today).map(item=>item.slice(0,10));
const expectedA=P.dates(today,data.years['2026'].end).filter(day=>!P.closed(day,'7',[...data.closures,closure])&&groups[0].days[P.parse(day).getUTCDay()]);
assert.deepEqual(futureA,expectedA,'Every remaining scheduled meeting is assigned exactly once');
assert.ok(after.events.filter(e=>e.kind==='unit'&&e.groupId==='group-a').every(e=>e.end<=data.years['2026'].end));
const absent=[{id:'absence-test',subject:'chemie',year:'2026',title:'Erkrankung',start:'2026-10-09',end:'2026-10-09',optionIds:['group-a']}];
const personal=F.build(data,baseYears,settings,'chemie','2026',{},[],{},groups,absent,today);
assert.equal(assignments(personal,'group-a',d=>d==='2026-10-09').length,0,'Only the absent group loses this meeting');
assert.equal(assignments(personal,'group-b',d=>d==='2026-10-09').length,0,'Other group has no Friday timetable');
assert.deepEqual(assignments(personal,'group-b',d=>d>=today),assignments(after,'group-b',d=>d>=today),'Other group stays unchanged');
console.log('PASS schoolwide updates freeze past lessons and adjust only affected future group meetings');

const clean={...old,revisions:[]};
const key='chemie:2026:7';
const anchor=F.snapshot(before.events,'7',today,0);
assert.equal(F.validAnchor(anchor),true,'Persisted planning snapshots must be valid');
const orders={[key]:['07.2','07.1','07.3']};
const full=F.build(data,baseYears,clean,'chemie','2026',orders,[],{},groups,[],today,{anchors:{[key]:anchor},changedTracks:['7'],rebuildTracks:['7']});
assert.notDeepEqual(assignments(full,'group-a',d=>d<today),assignments(before,'group-a',d=>d<today),'Full-year reordering must change even past assignments');
assert.ok(assignments(full,'group-a',d=>d<today).every(s=>s.endsWith('=07.2')));
const fullAnchor=F.snapshot(full.events,'7',today,0);
const reloaded=F.build(data,baseYears,clean,'chemie','2026',orders,[],{},groups,[],today,{anchors:{[key]:JSON.parse(JSON.stringify(fullAnchor))}});
assert.deepEqual(assignments(reloaded,'group-a',()=>true),assignments(full,'group-a',()=>true),'Full-year order persists after reload');
assert.throws(()=>F.build(data,baseYears,clean,'chemie','2026',orders,[],{},groups,[],today,{anchors:{[key]:anchor},changedTracks:['7']}),/Gesamtes Schuljahr/,'Remaining-only must reject moving the started unit');
const futureOrder={[key]:['07.1','07.3','07.2']};
const reorderedFuture=F.build(data,baseYears,clean,'chemie','2026',futureOrder,[],{},groups,[],today,{anchors:{[key]:anchor},changedTracks:['7']});
assert.deepEqual(assignments(reorderedFuture,'group-a',d=>d<today),assignments(before,'group-a',d=>d<today),'Future reordering keeps all past assignments');
assert.deepEqual(assignments(reorderedFuture,'group-b',d=>d<today),assignments(before,'group-b',d=>d<today));
const extra=[{id:'uvx-test',track:'7',title:'Eigenes Projekt',hours:10}];
const added=F.build(data,baseYears,clean,'chemie','2026',{},extra,{},groups,[],today,{anchors:{[key]:anchor},changedTracks:['7']});
assert.deepEqual(assignments(added,'group-a',d=>d<today),assignments(before,'group-a',d=>d<today),'Adding a unit preserves past assignments in remaining-only mode');
assert.ok(added.events.some(e=>e.customUnitId==='uvx-test'&&e.groupId==='group-a'));
assert.ok(added.events.filter(e=>e.customUnitId==='uvx-test').every(e=>e.start>=today));
const extraOrder={[key]:['uvx-test','07.1','07.2','07.3']};
const addedWhole=F.build(data,baseYears,clean,'chemie','2026',extraOrder,extra,{},groups,[],today,{anchors:{[key]:anchor},changedTracks:['7'],rebuildTracks:['7']});
assert.ok(addedWhole.events.filter(e=>e.kind==='unit'&&e.groupId==='group-a').sort((a,b)=>a.start.localeCompare(b.start))[0].extraUnit,'Custom units participate in full-year order');
const mixedGroups=[{id:'group-a',track:'7',label:'7a',days:{2:2,4:1,5:2}}];
const mixed=F.build(data,baseYears,clean,'chemie','2026',{},[],{},mixedGroups,[],today,{rebuildTracks:['7']});
const expectedMixed=P.dates(data.years['2026'].start,data.years['2026'].end).filter(d=>!P.closed(d,'7',data.closures)&&mixedGroups[0].days[P.parse(d).getUTCDay()]);
assert.deepEqual(assignments(mixed,'group-a',()=>true).map(s=>s.slice(0,10)),expectedMixed,'All single and double meetings are assigned exactly once');
assert.equal(mixed.events.filter(e=>e.kind==='unit'&&e.groupId==='group-a').reduce((n,e)=>n+e.plannedHours,0),expectedMixed.reduce((n,d)=>n+mixedGroups[0].days[P.parse(d).getUTCDay()],0));
const changedTimetable=F.build(data,baseYears,clean,'chemie','2026',{},[],{},mixedGroups,[],today,{anchors:{[key]:anchor},changedTracks:['7']});
assert.deepEqual(assignments(changedTimetable,'group-a',d=>d<today),assignments(before,'group-a',d=>d<today),'Timetable changes preserve past unit assignments in remaining-only mode');
const holiday2={...closure,id:'school-test-2',start:'2026-10-09',end:'2026-10-09'};
const secondSettings={...settings,closures:[closure,holiday2],revisions:[{until:today,scope:'year',settings:clean},{until:today,scope:'remaining',settings:{...old,closures:[closure]}}]};
assert.equal(S.validSettings(secondSettings),true,'Multiple same-day decisions are stored independently');
const replay=F.build(data,baseYears,secondSettings,'chemie','2026',orders,[],{},groups,[],today);
assert.ok(assignments(replay,'group-a',d=>d<today).every(s=>s.endsWith('=07.2')),'Schoolwide full-year decision updates past allocation');
assert.equal(assignments(replay,'group-a',d=>d===holiday2.start).length,0);
const replayAnchor=F.snapshot(replay.events,'7',today,2);
const replayReload=F.build(data,baseYears,secondSettings,'chemie','2026',orders,[],{},groups,[],today,{anchors:{[key]:replayAnchor}});
assert.deepEqual(assignments(replayReload,'group-a',()=>true),assignments(replay,'group-a',()=>true),'Already applied same-day revisions are not replayed on profile reload');
const q2groups=[{id:'q2-a',track:'Q2 LK',label:'Q2 LK A',days:{2:2,4:1,5:2}}];
const q2=F.build(data,baseYears,clean,'chemie','2026',{},[],{},q2groups,[],today,{rebuildTracks:['Q2 LK']});
const prep=q2.events.find(e=>e.kind==='prep'&&e.groupId==='q2-a');
assert.equal(prep.meetingDays.length,12,'Four weeks of Q2 preparation retain three meetings per week');
assert.ok(q2.events.filter(e=>e.kind==='unit'&&e.groupId==='q2-a').every(e=>e.end<prep.start));
console.log('PASS whole-year and remaining-only decisions, reloads, order locks, custom units, timetables, shared revisions and Q2 preparation');
