const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright'),root=path.resolve(__dirname,'../..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.css':'text/css','.js':'text/javascript','.wasm':'application/wasm','.html':'text/html','.json':'application/json'})[path.extname(file)]||'application/octet-stream'});res.end(e?'Not found':b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});try{
 const p=await browser.newPage({viewport:{width:1750,height:1100}}),errors=[],external=[],failed=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))external.push(r.url());});p.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
 await p.goto(origin+'/LearningApps2/uvvis-labor.html');await p.getByRole('button',{name:'Ohne Wikipedia beginnen',exact:true}).click();await p.waitForFunction(()=>document.querySelectorAll('.substance-card').length===77);await p.locator('#selected-structure svg').waitFor();assert.equal(external.length,0);assert.equal(failed.length,0);
 const invalid=await p.evaluate(async()=>{const rd=await initRDKitModule({locateFile:n=>"/LearningApps/fonts/"+n}),data=await(await fetch("data/uvvis-spectra.json")).json();return data.substances.filter(r=>{const m=rd.get_mol(r.smiles);if(!m)return true;const valid=m.is_valid();m.delete();return !valid;}).map(r=>r.id);});assert.deepEqual(invalid,[]);assert.equal(await p.locator("#spectrum").getAttribute("data-lo"),await p.locator("#range-start").inputValue());
 assert.equal(await p.locator('#scan').isEnabled(),false);await p.locator('#lid').click();await p.locator('#device-canvas canvas').waitFor();await p.waitForTimeout(850);await p.locator('#device').screenshot({path:'/tmp/uvvis-device-open.png'});await p.locator('#insert').click();assert.equal(await p.locator('#blank').isEnabled(),false);await p.locator('#lid').click();await p.locator('#blank').click();assert.equal(await p.locator('#scan').isEnabled(),false);await p.locator('#lid').click();await p.locator('#insert').click();await p.locator('#lid').click();assert.equal(await p.locator('#scan').isEnabled(),true);
 await p.locator('#rays').check();assert.equal(await p.locator('#inside').isChecked(),true);assert.ok((await p.locator('#device').getAttribute('class')).includes('rays'));assert.match(await p.locator('#read-a').textContent(),/0,/);
 await p.locator('#optics-probe').click();assert.equal(await p.locator('#optical-plan').getAttribute('data-phase'),'probe');await p.locator('#optics-next').click();assert.equal(await p.locator('#optical-plan').getAttribute('data-phase'),'reference');await p.locator('#optics-auto').click();
 await p.locator('#scan-speed').selectOption('2000');await p.locator('#scan').click();assert.equal(await p.locator('#concentration').isEnabled(),false);assert.equal(await p.locator('#lid').isEnabled(),false);await p.waitForFunction(()=>document.getElementById('export').disabled===false);assert.equal(await p.locator('.legend-item').count(),1);assert.ok(await p.locator('#spectrum path').count()>7);
 await p.locator('#concentration').fill('4');await p.locator('#concentration').press('Tab');await p.locator('#scan').click();await p.waitForFunction(()=>document.querySelectorAll('.legend-item').length===2);await p.locator('#plot-unit').selectOption('T');assert.ok((await p.locator('#spectrum').textContent()).includes('Transmission'));
 await p.locator('#wavelength').fill('591');await p.locator('#wavelength').press('Tab');await p.locator('#unknown-mode').click();await p.locator('#standard-blank').click();for(const c of ['5','10','15']){await p.locator('#standard-c').fill(c);await p.locator('#standard-measure').click();}assert.equal(await p.locator('#standards tr').count(),4);assert.match(await p.locator('#calibration-result').textContent(),/R² = 1/);await p.locator('#dilution').selectOption('5');await p.locator('#unknown-measure').click();const values=await p.evaluate(()=>({A:document.getElementById('unknown-a').textContent,rows:[...document.querySelectorAll('#standards tr')].map(tr=>[...tr.cells].map(c=>c.textContent))}));const val=s=>Number(s.replace(/\./g,'').replace(',','.'));const m=(val(values.rows[2][1])-val(values.rows[1][1]))/5,A=val(values.A.match(/A = ([\d,]+)/)[1]);await p.locator('#answer-c').fill(String(A/m*5));await p.locator('#check-c').click();assert.match(await p.locator('#unknown-feedback').textContent(),/Richtig/);
 await p.locator('#wavelength').fill('600');await p.locator('#wavelength').press('Tab');assert.equal(await p.locator('#standards tr').count(),0);assert.equal(await p.locator('#unknown-measure').isEnabled(),false);
 await p.locator('#search').fill('Methylorange');await p.locator('[data-id="PH-J03"]').click();assert.equal(await p.locator('#unknown-panel').isVisible(),false);assert.equal(await p.locator('#factor-label').isVisible(),true);assert.equal(await p.locator('#ph-select option').count(),12);assert.equal(await p.locator('#ph-select').inputValue(),'7');await p.locator('#ph-select').selectOption('2');assert.equal(await p.locator('#scan').isEnabled(),false);
 await p.locator('#search').fill('Indigo');await p.locator('[data-id="IC-FIG2"]').click();await p.locator('#selected-structure svg').waitFor();assert.match(await p.locator('#source-meta').textContent(),/digitalisiert/);
 await p.locator('#fullscreen').click();assert.ok(await p.evaluate(()=>!!document.fullscreenElement||document.getElementById('labor').classList.contains('pseudo-fullscreen')));assert.equal(await p.getByRole('button',{name:'Vollbild beenden',exact:true}).count(),1);await p.locator('#device').screenshot({path:'/tmp/uvvis-device-inside.png'});await p.locator('#lab-reset').click();await p.locator('#reset-dialog button[value="cancel"]').click();await p.locator('#fullscreen').click();
 const q=await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('uvvis-labor-v1'));return UVVisQuestions.find(q=>q.id===s.ids[s.index]);});await p.locator('#quiz-card').getByRole('button',{name:q.options[q.correct],exact:true}).click();assert.match(await p.locator('#xp').textContent(),/10 XP/);await p.reload();await p.getByRole('button',{name:'Ohne Wikipedia beginnen',exact:true}).click();assert.match(await p.locator('#xp').textContent(),/10 XP/);
 for(const width of [390,768,1750]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await p.setViewportSize({width:1750,height:1100});await p.locator('#labor').screenshot({path:'/tmp/uvvis-lab.png'});await p.locator('#theme').click();await p.locator('#farbstoffe').screenshot({path:'/tmp/uvvis-comparisons-dark.png'});assert.equal(external.length,0);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 console.log('PASS zero external requests/errors, 77 structures, closed-lid/blank workflow, scans/overlay, calibration+unknown+dilution, invalidation, pH/Indigo, fullscreen, persistent quiz and responsive widths.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
