(function(){'use strict';
 const $=id=>document.getElementById(id),C=window.GCLab,lib=window.GCLibrary?.substances;
 if(!C||!lib?.length){$('load-error').hidden=false;$('load-error').textContent='Die lokale Datenbibliothek konnte nicht geladen werden. Bitte lade die Seite erneut.';return;}
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const n=(x,d=3)=>Number.isFinite(x)?x.toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
 const seed=()=>Math.floor(Math.random()*4294967295),record=id=>lib.find(r=>r.id===id),colors=['#176b6c','#b46136','#8675a3','#8b842b','#4c82a4','#ca8174','#61844c','#a47a4a'];
 const presets={solvents:[['acetone',35],['ethylacetate',50],['toluene',40]],alcohols:[['ethanol',40],['propanol',35],['butanol',30]],aromatics:[['benzene',25],['toluene',30],['ethylbenzene',35],['mxylene',40],['pxylene',45],['oxylene',25]],aroma:[['limonene',45],['linalool',40],['eugenol',25],['methylsalicylate',30],['isoamylacetate',35]],alkanes:[['hexane',35],['heptane',35],['octane',35]]};
 const state={mode:'explore',mixture:[],qual:[],qualRevealed:false,qualAttempts:0,ready:false,blank:null,run:null,pending:null,running:false,cooling:false,temperature:null,coolingRaf:0,coolingMinutes:0,coolingDuration:0,elapsedMs:0,progress:1,rows:[],unknown:null,unknownC:55,runNumber:0,raf:0,coachStep:0};
 const storage={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);}catch{}}};
 const methodIds={detector:'detector',phase:'phase',length:'column-length',flow:'flow',temperature:'temperature',ramp:'ramp',endTemperature:'end-temperature',runtime:'runtime',split:'split',volume:'volume'};
 function method(){const s=Object.fromEntries(Object.entries(methodIds).map(([key,id])=>[key,$(id).value]));s.realistic=$('realistic').value==='yes';return C.settings(s);}
 function tell(text,error=false){$('measurement-status').textContent=text;$('measurement-status').classList.toggle('error',error);}
 function elapsedClock(modelMinutes,realMs,cooling=false){$('time-lapse-model').textContent=(cooling?'Abkühlmodell: ':'Messzeit: ')+n(modelMinutes,2)+' min';$('time-lapse-real').textContent='Wartezeit: '+n(realMs/1000,1)+' s';}
 function timeLapse(s){
  const seconds=Number($('speed').value),factor=s.runtime*60/seconds;
  $('time-lapse').dataset.phase=state.cooling?'cooling':state.running?'running':'idle';
  $('time-lapse-title').textContent=state.cooling?'Abkühlung im Zeitraffer':(state.running?'Zeitraffer läuft':'Zeitraffer')+' · '+n(factor,0)+'×';
  $('time-lapse-summary').textContent=state.cooling?'Vereinfachtes Abkühlmodell: '+n(state.coolingMinutes,1)+' Minuten in '+n(state.coolingDuration/1000,1)+' Sekunden. Keine gemessene Gerätekurve.':n(s.runtime,0)+' Minuten Messzeit werden in '+seconds+' Sekunden dargestellt. Die Geräteuhr zeigt die simulierte Messzeit, nicht deine Wartezeit.';
  if(!state.running&&!state.cooling)elapsedClock(state.run?s.runtime:0,state.run?state.elapsedMs:0);
 }
 function ovenProgram(s){
  const constant=s.ramp===0||s.endTemperature<=s.temperature,final=C.oven(s.runtime,s);
  $('oven-program-title').textContent=constant?'Ofenprogramm · konstante Temperatur (isotherm)':'Ofenprogramm · kontrolliertes Aufheizen';
  $('oven-program-summary').textContent=(constant?n(s.temperature,0)+' °C bleiben während der gesamten Messung konstant.':'Zunächst 0,8 min bei '+n(s.temperature,0)+' °C halten, dann mit '+n(s.ramp,0)+' °C/min aufheizen, höchstens bis '+n(s.endTemperature,0)+' °C. Nach '+n(s.runtime,0)+' min: '+n(final,1)+' °C.'+(final<s.endTemperature?' Die eingestellte Endtemperatur wird in diesem Lauf noch nicht erreicht.':' Die Endtemperatur wird danach gehalten.'))+' Im Zeitraffer entsprechen '+$('speed').value+' Sekunden hier '+n(s.runtime,0)+' Minuten Messzeit. Für eine Messung ohne Aufheizen: Heizrate 0 wählen.';
  timeLapse(s);
 }
 function actualTemperature(value){state.temperature=value;$('read-temp').textContent=n(value,1);const display=$('device-temperature');if(display)display.textContent=n(value,0)+' °C';}
 function device(){try{const s=method();if(state.temperature===null)state.temperature=s.temperature;window.GCDevice.render($('gc-device'),{...s,temperature:Math.round(state.temperature)},{inside:$('device-inside').checked,flow:$('device-flow').checked,running:state.running,cooling:state.cooling});$('detector-label').textContent=s.detector==='ms'?'GC-MS · Quadrupol':'GC-FID · Flammenionisation';$('read-flow').textContent=n(s.flow,1);actualTemperature(state.temperature);$('ms-panel').hidden=s.detector!=='ms';$('trace-kind').querySelector('[value="eic"]').disabled=s.detector!=='ms';if(s.detector!=='ms')$('trace-kind').value='tic';$('eic-label').hidden=$('trace-kind').value!=='eic';ovenProgram(s);}catch(e){tell(e.message,true);}}
 function cancelCooling(){cancelAnimationFrame(state.coolingRaf);state.coolingRaf=0;state.cooling=false;}
 function coolOven(s,message){
  cancelCooling();const from=state.temperature,profile=C.cooldown(from,s.temperature),start=performance.now();
  const done=()=>{state.cooling=false;state.coolingRaf=0;actualTemperature(s.temperature);$('read-state').textContent=state.ready?'BEREIT':'STANDBY';device();buttons();tell(message+' Ofen wieder bei '+n(s.temperature,0)+' °C.');};
  if(profile.done){done();return;}
  const duration=Math.max(2800,Number($('speed').value)*1000*profile.minutes/s.runtime);
  state.cooling=true;state.coolingMinutes=profile.minutes;state.coolingDuration=duration;$('read-state').textContent='KÜHLT AB';device();elapsedClock(0,0,true);buttons();tell(message+' Der Ofen kühlt im Zeitraffer auf '+n(s.temperature,0)+' °C ab. Die nächste Injektion ist danach möglich.');
  const frame=now=>{if(!state.cooling)return;const p=Math.min(1,(now-start)/duration);actualTemperature(C.cooldown(from,s.temperature,p*profile.minutes).temperature);elapsedClock(p*profile.minutes,p*duration,true);if(p>=1)done();else state.coolingRaf=requestAnimationFrame(frame);};
  state.coolingRaf=requestAnimationFrame(frame);
 }
 function buttons(){
  let valid=true;try{method();}catch{valid=false;}
  const busy=state.running||state.cooling;
  $('equilibrate').disabled=busy||!valid;$('blank').disabled=busy||!state.ready||!valid;$('inject').disabled=busy||!state.ready||!state.blank||!valid;$('stop').disabled=!state.running;$('finish-run').hidden=!state.running;
  $('method-controls').disabled=busy;
  for(const id of ['mixture-preset','add-compound','add-mixture','prepare-standard','prepare-unknown','quant-analyte','quant-method','dilution','new-quantitative','new-qualitative','standard-c'])$(id).disabled=busy;
  $('mixture-rows').querySelectorAll('input,button').forEach(el=>el.disabled=busy);
  ['explore','qualitative','quantitative'].forEach(mode=>$('mode-'+mode).disabled=busy);
  ['export-csv','export-svg','print-record'].forEach(id=>$(id).disabled=!state.run||state.running);
 }
 function invalidate(){cancelCooling();state.temperature=null;state.ready=false;state.blank=null;state.run=null;state.rows=[];state.unknown=null;state.pending=null;state.progress=1;$('read-state').textContent='STANDBY';$('read-time').textContent='0,000';$('run-progress').value=0;$('scan-time').value=0;$('library-matches').replaceChildren();$('view-end').value=$('runtime').value;device();renderRun();calibration();sample();buttons();tell('Methode geändert: Gerät erneut stabilisieren und Blindprobe aufnehmen. Die bisherige Kalibrierung gilt nicht mehr.');}
 function options(selected){return lib.map(r=>`<option value="${r.id}"${r.id===selected?' selected':''}>${escape(r.name)} · ${escape(r.formula)}</option>`).join('');}
 for(const id of ['add-compound','quant-analyte','library-select'])$(id).innerHTML=options(id==='quant-analyte'?'ethanol':lib[0].id);
 $('source-count').textContent=lib.length+' gemessene';
 function preset(key){state.mixture=(presets[key]||presets.solvents).map(([id,c])=>({id,c}));sample();}
 function internalRecord(){return record($('quant-analyte').value==='propanol'?'butanol':'propanol');}
 function sample(){
  const explore=state.mode==='explore';$('mixture-preset').closest('label').hidden=!explore;$('mixture-add').hidden=!explore;$('qualitative-panel').hidden=state.mode!=='qualitative';$('quantitative-controls').hidden=state.mode!=='quantitative';$('calibration-panel').hidden=state.mode!=='quantitative';$('show-components').disabled=state.mode==='qualitative'&&!state.qualRevealed;if($('show-components').disabled)$('show-components').checked=false;
  if(explore){$('mixture-rows').innerHTML=state.mixture.map((m,i)=>`<div class="mixture-row"><span>${escape(record(m.id).name)}</span><input type="number" min="0" max="500" step="5" value="${m.c}" data-index="${i}" aria-label="${escape(record(m.id).name)} in mg/L"><button data-remove="${i}" aria-label="${escape(record(m.id).name)} entfernen">×</button></div>`).join('');$('sample-label').textContent='Bekannte Probe · '+state.mixture.length+' Komponenten';}
  else{$('mixture-rows').replaceChildren();$('sample-label').textContent=state.mode==='qualitative'?'Unbekannte Probe Q · drei Komponenten':state.pending?.label||'Zuerst einen Standard oder die Unbekannte bereitstellen.';}
  $('internal-note').textContent=$('quant-method').value==='internal'?`Interner Standard: ${internalRecord().name}, 50 mg/L in jeder fertigen Messlösung, auch im Nullstandard. Eine geeignete Trennung muss geprüft werden.`:'Externe Kalibrierung: Analytflächen gegen Konzentrationen. Keine weiteren Stoffe im Standard.';
 }
 function newQual(){const choices=['ethanol','propanol','butanol','acetone','ethylacetate','hexane','heptane','toluene','octane'];const shuffled=choices.map(id=>[Math.random(),id]).sort((a,b)=>a[0]-b[0]);state.qual=shuffled.slice(0,3).map(([,id])=>({id,c:25+Math.round(Math.random()*35)}));state.qualRevealed=false;state.qualAttempts=0;$('qual-feedback').textContent='';$('qual-brief').textContent='Drei Stoffe aus der Bibliothek stecken in Probe Q. Nimm das Gemisch auf. Untersuche Retentionszeiten und EI-Muster. Wähle unten genau drei Kandidaten. Bei Koelution kann eine zweite Trennmethode helfen.';$('qual-answers').innerHTML='<div class="qual-checklist">'+lib.map(r=>`<label class="check"><input type="checkbox" value="${r.id}">${escape(r.name)}</label>`).join('')+'</div>';state.run=null;renderRun();sample();}
 function newQuant(){state.unknownC=15+Math.round(Math.random()*120);state.unknown=null;state.pending=null;$('concentration-answer').value='';$('concentration-feedback').textContent='';calibration();sample();}
 function setMode(mode){if(state.running||state.cooling)return;state.mode=mode;state.pending=null;['explore','qualitative','quantitative'].forEach(m=>{$('mode-'+m).classList.toggle('active',m===mode);$('mode-'+m).setAttribute('aria-pressed',String(m===mode));});state.run=null;renderRun();if(mode==='qualitative')newQual();if(mode==='quantitative')newQuant();sample();buttons();tell('Auftrag gewechselt. Eine bereits passende Blindprobe kann weiterverwendet werden.');}
 function prepare(kind){if(state.running||state.cooling)return;const c=Number($('standard-c').value);if(kind==='standard'&&(!Number.isFinite(c)||c<0||c>150)){tell('Standardkonzentration von 0 bis 150 mg/L eingeben.',true);return;}const factor=Number($('dilution').value);state.pending={kind,c,factor,label:kind==='standard'?`${record($('quant-analyte').value).name} · Standard ${n(c,1)} mg/L`:`Unbekannte U · Verdünnungsfaktor ${factor}`};sample();tell(state.pending.label+' bereit. Bei betriebsbereitem Gerät jetzt „Probe injizieren“ wählen.');}
 function injection(){if(state.mode==='explore')return {mixture:state.mixture,kind:'sample',label:'Gemisch · '+state.mixture.map(m=>record(m.id).name).join(' / ')};if(state.mode==='qualitative')return {mixture:state.qual,kind:'qualitative',label:'Unbekannte Probe Q'};if(!state.pending)throw Error('Zuerst einen Standard oder die Unbekannte bereitstellen.');const p={...state.pending},mixture=[{id:$('quant-analyte').value,c:p.kind==='standard'?p.c:state.unknownC/p.factor}];if($('quant-method').value==='internal')mixture.push({id:internalRecord().id,c:50});return {...p,mixture,analyte:$('quant-analyte').value,internal:$('quant-method').value==='internal',is:internalRecord().id};}
 function startRun(blank){if(state.running||state.cooling||!state.ready||(!blank&&!state.blank))return;try{const job=blank?{kind:'blank',mixture:[],label:'Blindprobe · ohne Analyt'}:injection();if(!blank&&state.mode==='explore'&&!job.mixture.some(m=>m.c>0))throw Error('Die Mischung enthält noch keine positive Konzentration.');const run=C.simulate(lib,job.mixture,method(),seed());run.job=job;run.number=++state.runNumber;run.date=new Date().toLocaleString('de-DE');state.run=run;state.running=true;state.progress=0;state.temperature=run.settings.temperature;state.elapsedMs=0;state.start=performance.now();state.duration=Number($('speed').value)*1000;state.runPeaks=[];$('run-progress').value=0;$('view-start').value=0;$('view-end').value=run.settings.runtime;$('scan-time').max=run.settings.runtime;$('library-matches').replaceChildren();$('read-state').textContent='MESSUNG';device();elapsedClock(0,0);buttons();tell(job.label+' · Messung läuft im Zeitraffer.');const frame=now=>{if(!state.running)return;state.progress=Math.min(1,(now-state.start)/state.duration);state.elapsedMs=Math.min(state.duration,now-state.start);$('run-progress').value=state.progress;const t=state.progress*run.settings.runtime;$('read-time').textContent=n(t);actualTemperature(C.oven(t,run.settings));elapsedClock(t,state.elapsedMs);drawChrom();if(state.progress>=1)finish();else state.raf=requestAnimationFrame(frame);};state.raf=requestAnimationFrame(frame);}catch(e){tell(e.message,true);}}
 function abort(){if(!state.running)return;const s=state.run.settings;cancelAnimationFrame(state.raf);state.running=false;state.run=null;state.progress=1;$('run-progress').value=0;renderRun();coolOven(s,'Messung abgebrochen. Keine neuen Kalibrier- oder Probendaten gespeichert.');}
 function finish(){if(!state.running)return;cancelAnimationFrame(state.raf);state.elapsedMs=Math.min(state.duration,Math.max(0,performance.now()-state.start));state.running=false;state.progress=1;const r=state.run;$('run-progress').value=1;$('read-time').textContent=n(r.settings.runtime);actualTemperature(C.oven(r.settings.runtime,r.settings));if(r.job.kind==='blank'){state.blank=r;state.runPeaks=[];}else{state.runPeaks=C.peaks(r,state.blank);if(r.job.kind==='standard'||r.job.kind==='unknown')saveQuant(r);}
  const last=Math.max(0,...state.runPeaks.map(p=>p.end));if(last&&last<r.settings.runtime*.65)$('view-end').value=Math.min(r.settings.runtime,Math.ceil((last+.25)*2)/2);$('scan-time').value=state.runPeaks[0]?.time||0;renderRun();coolOven(r.settings,r.job.kind==='blank'?'Blindprobe gespeichert.':'Messung abgeschlossen. Klicke auf einen Peak oder verschiebe den Zeitcursor.');}
 function trace(){if(!state.run)return [];if($('trace-kind').value==='eic'){try{return C.eic(state.run,Number($('eic-mass').value));}catch{return [];}}return state.run.points;}
 function axisSVG(width,height,{xmin=0,xmax=1,ymax=100,xlabel='',ylabel='',paper=false}={}){const left=65,right=24,top=32,bottom=52,w=width-left-right,h=height-top-bottom;const x=t=>left+(t-xmin)/(xmax-xmin)*w,y=v=>top+h-v/ymax*h;let html=paper?'<defs><pattern id="gc-grid-small" width="18" height="18" patternUnits="userSpaceOnUse"><path d="M18 0H0V18" fill="none" stroke="#a9bba1" stroke-width=".4" opacity=".5"/></pattern><pattern id="gc-grid-large" width="90" height="90" patternUnits="userSpaceOnUse"><rect width="90" height="90" fill="url(#gc-grid-small)"/><path d="M90 0H0V90" fill="none" stroke="#9cad93" stroke-width=".8" opacity=".5"/></pattern></defs>':'';if(paper)html+=`<rect x="${left}" y="${top}" width="${w}" height="${h}" fill="url(#gc-grid-large)"/>`;
  const fill=paper?'#46564b':'var(--muted)',line=paper?'#a6b5a0':'var(--line)';for(let i=0;i<=5;i++){const tx=xmin+(xmax-xmin)*i/5,ty=ymax*i/5;html+=`<path d="M${x(tx)} ${top}V${top+h}M${left} ${y(ty)}H${left+w}" stroke="${line}" stroke-width=".6"/><text x="${x(tx)}" y="${height-29}" text-anchor="middle" font-size="14" fill="${fill}">${n(tx,xmax>10?1:2)}</text><text x="${left-8}" y="${y(ty)+5}" text-anchor="end" font-size="13" fill="${fill}">${n(ty,ymax<2?2:0)}</text>`;}
  html+=`<path d="M${left} ${top}V${top+h}H${left+w}" stroke="${fill}" stroke-width="1.2" fill="none"/><text x="${width/2}" y="${height-4}" font-size="15" text-anchor="middle" fill="${fill}">${escape(xlabel)}</text><text x="${left}" y="18" font-size="14" fill="${fill}">${escape(ylabel)}</text>`;return {html,x,y,left,right,top,bottom,w,h};}
 function drawChrom(){const r=state.run,svg=$('chromatogram-plot'),points=trace();let xmin=Number($('view-start').value),xmax=Number($('view-end').value);if(!Number.isFinite(xmin)||!Number.isFinite(xmax)||xmin<0||xmax<=xmin){svg.innerHTML='<text x="60" y="150" fill="#8d4931" font-size="20">Gültiges Zeitfenster wählen: Ende muss nach Beginn liegen.</text>';return;}const cutoff=r?state.progress*r.settings.runtime:Infinity,visible=points.filter(p=>p[0]>=xmin&&p[0]<=Math.min(xmax,cutoff)),auto=Math.max(1,...visible.map(p=>p[1]))*1.17,ymax=$('y-scale').value==='auto'?auto:Number($('y-scale').value);const a=axisSVG(1000,400,{xmin,xmax,ymax,xlabel:'Zeit nach Injektion / min',ylabel:($('trace-kind').value==='eic'?'EIC m/z '+$('eic-mass').value:'Detektorsignal')+' / a.u.',paper:true});const path=pts=>pts.map((p,i)=>(i?'L':'M')+a.x(p[0]).toFixed(2)+' '+a.y(Math.max(0,Math.min(ymax,p[1]))).toFixed(2)).join(' ');let html=a.html;
  if(r&&!state.running&&$('trace-kind').value==='tic'){for(const p of state.runPeaks||[]){const pts=points.filter(q=>q[0]>=p.start&&q[0]<=p.end&&q[0]>=xmin&&q[0]<=xmax);if(pts.length)html+=`<path d="${path(pts)}L${a.x(pts.at(-1)[0])} ${a.y(0)}H${a.x(pts[0][0])}Z" fill="${colors[(p.number-1)%colors.length]}" opacity=".10"/>`;if(p.time>=xmin&&p.time<=xmax)html+=`<text x="${a.x(p.time)}" y="${Math.max(46,a.y(Math.min(ymax,p.height)) - 8)}" font-size="14" text-anchor="middle" fill="#5c6957">P${p.number}</text>`;}}
  if(r&&$('show-components').checked&&!(state.mode==='qualitative'&&!state.qualRevealed)){r.components.forEach((p,i)=>{if(p.mu===null)return;const pts=visible.map(q=>[q[0],C.peakShape(q[0],p)]);html+=`<path d="${path(pts)}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="1.5" stroke-dasharray="5 3"/>`;});}
  if(visible.length)html+=`<path d="${path(visible)}" fill="none" stroke="#1c4b45" stroke-width="1.7" stroke-linejoin="round"/>`;else html+=`<text x="500" y="190" text-anchor="middle" font-size="20" fill="#657560">${r?'Noch keine Daten in diesem Fenster':'Bereit für eine erste Messung'}</text>`;
  const cursor=Number($('scan-time').value);if(r&&!state.running&&cursor>=xmin&&cursor<=xmax)html+=`<path d="M${a.x(cursor)} ${a.top}V${a.top+a.h}" stroke="#ba653b" stroke-dasharray="5 4"/><text x="${Math.min(880,a.x(cursor)+7)}" y="32" fill="#945332" font-size="12">${n(cursor)} min</text>`;
  svg.innerHTML=html;svg.dataset.xmin=xmin;svg.dataset.xmax=xmax;}
 function spectrumSVG(peaks,width=900,height=330){const xmax=Math.max(60,Math.ceil(Math.max(0,...peaks.map(p=>p[0]))/20)*20),a=axisSVG(width,height,{xmax,ymax:110,xlabel:'Masse-zu-Ladung-Verhältnis m/z',ylabel:'Relative Intensität / %'});let html=a.html;if(!peaks.length)return html+`<text x="${width/2}" y="${height/2}" fill="var(--muted)" font-size="18" text-anchor="middle">Kein auswertbares Stoffsignal am Zeitcursor</text>`;for(const [mz,intensity] of peaks){html+=`<path d="M${a.x(mz)} ${a.y(0)}V${a.y(intensity)}" stroke="var(--accent)" stroke-width="2"/>`;if(intensity>=14)html+=`<text x="${a.x(mz)}" y="${a.y(intensity)-7}" fill="var(--ink)" font-size="12" text-anchor="middle">${mz}</text>`;}return html;}
 function scan(){const r=state.run,t=Number($('scan-time').value),peaks=r&&!state.running&&r.settings.detector==='ms'?C.spectrumAt(r,t):[];$('ms-plot').innerHTML=spectrumSVG(peaks);$('scan-description').textContent=r?`Scan bei ${n(t)} min · ${peaks.length?'EI-Muster aus den zu diesem Zeitpunkt ankommenden Komponenten':'kein hinreichendes Ionensignal'}`:'Wähle nach der Messung einen Peak.';$('library-matches').replaceChildren();drawChrom();}
 function selectPeak(index){const p=state.runPeaks[index];if(!p)return;$('scan-time').value=p.time;$('int-start').value=p.start.toFixed(3);$('int-end').value=p.end.toFixed(3);scan();}
 function renderRun(){const r=state.run;const p=r&&!state.running?(state.runPeaks||[]):[];$('paper-sample').textContent=r?r.job.label:'Noch keine Messung';$('paper-run').textContent=r?'RUN '+String(r.number).padStart(3,'0'):'RUN —';$('paper-method').textContent=r?`${r.settings.detector==='ms'?'GC-MS / EI 70 eV':'GC-FID'} · ${r.settings.length} m / ${r.settings.phase==='polar'?'polar':'unpolar'} · ${r.settings.temperature} °C + ${r.settings.ramp} °C/min · ${r.settings.flow} mL/min · Split ${r.settings.split}:1 · ${r.settings.volume} µL · ${r.date}`:'SIMULATION · lokale Referenzdaten';$('paper-count').textContent=p.length+' integrierte Peaks';const total=p.reduce((v,q)=>v+q.area,0);$('peak-table').innerHTML=p.length?p.map((q,i)=>`<tr><td><button data-peak="${i}" title="Spektrum und Integrationsgrenzen wählen">P${q.number} ↗</button></td><td>${n(q.time)}</td><td>${n(q.area,4)}</td><td>${n(100*q.area/total,1)} %</td><td>${q.overlap?'Überlappung prüfen':'getrennt? prüfen'}</td></tr>`).join(''):'<tr><td colspan="5">'+(r?'Keine integrierbaren Peaks. Blindprobe, Laufzeit oder Konzentration prüfen.':'Noch keine Messung.')+'</td></tr>';
  const uneluted=r?.components.filter(c=>c.mu===null)||[];$('run-warning').textContent=r?[r.saturated?'ACHTUNG: Detektor gesättigt. Kleinere Menge beziehungsweise größeren Split wählen.':'',uneluted.length?`${uneluted.length} Modellkomponente(n) verlassen die Säule nicht innerhalb dieses Laufs${state.mode==='qualitative'&&!state.qualRevealed?'.':': '+uneluted.map(p=>p.record.name).join(', ')+'.'}`:'',p.some(p=>p.overlap)?'Überlappende Peaks: automatische Einzelstoffflächen sind unsicher.':'',state.mode==='qualitative'?'Das Gemisch enthält drei Stoffe, auch wenn weniger Peaks getrennt werden.':''].filter(Boolean).join(' '):'';scan();}
 function saveQuant(r){const j=r.job,target=C.measureTarget(r,record(j.analyte),state.blank),is=j.internal?C.measureTarget(r,record(j.is),state.blank):null;const separation=j.internal?Math.abs(C.retention(record(j.analyte),r.settings)-C.retention(record(j.is),r.settings)):1;const expected=r.components.filter(p=>p.mu!==null);const tooClose=j.internal&&(separation<.15||expected.length===2&&separation<4*(expected[0].sigma+expected[1].sigma));if(!target||target.overlap||j.internal&&(!is||is.overlap||is.area<=0||tooClose)){tell('Keine belastbare quantitative Auswertung: Sättigung, fehlende Elution oder Koelution mit internem Standard. Methode verbessern oder externe Kalibrierung wählen.',true);return;}
  const row={c:j.c,area:target.area,isArea:is?.area||null,x:j.internal?j.c/50:j.c,y:j.internal?target.area/is.area:target.area,key:C.fingerprint(r.settings)};
  if(j.kind==='standard'){const index=state.rows.findIndex(q=>q.c===j.c);if(index>=0)state.rows[index]=row;else state.rows.push(row);state.rows.sort((a,b)=>a.c-b.c);tell(`Standard ${n(j.c,1)} mg/L gespeichert${index>=0?' (vorherige Stufe ersetzt)':''}. Weitere Stufe bereitstellen und injizieren.`);}else{state.unknown={area:row.area,isArea:row.isArea,y:row.y,factor:j.factor,key:row.key};tell('Unbekannte aufgenommen. Berechne die Konzentration aus deiner Kalibrierung.');}calibration();}
 function fit(){return C.regression(state.rows);}
 function estimate(){const f=fit(),u=state.unknown;if(!f||!u||f.slope<=0)return null;const x=(u.y-f.intercept)/f.slope;return {c:x*($('quant-method').value==='internal'?50:1)*u.factor,inRange:x>=f.min-1e-6&&x<=f.max+1e-6,fit:f};}
 function calibration(){const internal=$('quant-method').value==='internal',f=fit(),xmax=Math.max(internal?1:50,...state.rows.map(r=>r.x))*1.15,ymax=Math.max(.1,...state.rows.map(r=>r.y))*1.2;const a=axisSVG(850,330,{xmax,ymax,xlabel:internal?'cAnalyt / cIS (dimensionslos)':'Standardkonzentration / mg L⁻¹',ylabel:internal?'AAnalyt / AIS':'Peakfläche / a.u.·min'});let html=a.html;if(f)html+=`<path d="M${a.x(0)} ${a.y(f.intercept)}L${a.x(f.max)} ${a.y(f.slope*f.max+f.intercept)}" stroke="var(--copper)" stroke-width="2"/>`;for(const r of state.rows)html+=`<circle cx="${a.x(r.x)}" cy="${a.y(r.y)}" r="5" fill="var(--accent)"/>`;$('calibration-plot').innerHTML=html;$('calibration-table').innerHTML=state.rows.length?state.rows.map((r,i)=>`<tr><td>${n(r.c,1)}</td><td>${n(r.area,4)}</td><td>${r.isArea?n(r.isArea,4):'—'}</td><td>${n(r.y,4)}</td><td><button data-delete-cal="${i}" aria-label="Stufe ${r.c} löschen">×</button></td></tr>`).join(''):'<tr><td colspan="5">Noch keine Standards gemessen.</td></tr>';$('calibration-fit').textContent=f?`y = ${n(f.slope,5)} · x ${f.intercept>=0?'+':'−'} ${n(Math.abs(f.intercept),5)} · R² = ${n(f.r2,5)} · gültiger Konzentrationsbereich: 0–${Math.max(...state.rows.map(r=>r.c))} mg/L. ${internal?'x = cAnalyt/cIS, y = AAnalyt/AIS, cIS = 50 mg/L.':'x = Konzentration, y = Peakfläche.'}`:'Noch keine auswertbare Kalibrierung: Nullstandard und mindestens drei unterschiedliche positive Stufen messen.';const u=state.unknown;$('unknown-result').textContent=u?`Unbekannte: Analytfläche ${n(u.area,4)} a.u.·min${u.isArea?`, IS-Fläche ${n(u.isArea,4)}, Verhältnis ${n(u.y,5)}`:''}. Verdünnungsfaktor ${u.factor}. ${estimate()&&!estimate().inRange?'Außerhalb des Kalibrierbereichs: verdünnen oder den Bereich erweitern!':'Berechne die Konzentration der Originalprobe.'}`:'Unbekannte noch nicht gemessen.';}
 function checkConcentration(){const e=estimate(),v=Number($('concentration-answer').value);if(!$('concentration-answer').value){$('concentration-feedback').textContent='Bitte zuerst dein Ergebnis eingeben.';return;}if(!e){$('concentration-feedback').textContent='Zuerst vollständig kalibrieren und die Unbekannte messen.';return;}if(!e.inRange){$('concentration-feedback').textContent='Das Signal liegt außerhalb der Kalibrierung. Verdünne die Unbekannte und miss erneut.';return;}const good=Number.isFinite(v)&&Math.abs(v-e.c)<=Math.max(.5,e.c*.03);$('concentration-feedback').textContent=(good?'Richtig ausgewertet. ':'Prüfe deinen Rechenweg. ')+`Aus deinen Messwerten folgt ${n(e.c,2)} mg/L für die Originalprobe. Zuerst den Achsenabschnitt abziehen und durch die Steigung teilen${$('quant-method').value==='internal'?', dann mit 50 mg/L multiplizieren':''}; zuletzt mit dem Verdünnungsfaktor multiplizieren. Injektionsstreuung und Integrationsgrenzen begrenzen die Genauigkeit.`;$('concentration-feedback').className=good?'good':'error';}
 let rdkitPromise;
 function rdkit(){if(!rdkitPromise)rdkitPromise=new Promise((resolve,reject)=>{const start=()=>window.initRDKitModule({locateFile:name=>'../LearningApps/fonts/'+name}).then(resolve,reject);if(window.initRDKitModule)start();else{const script=document.createElement('script');script.src='../LearningApps/fonts/RDKit_minimal.js';script.onload=start;script.onerror=()=>reject(Error('Strukturzeichner nicht verfügbar'));document.head.append(script);}});return rdkitPromise;}
 let libraryToken=0;
 async function showLibrary(id){const r=record(id)||lib[0];$('library-select').value=r.id;const token=++libraryToken;$('library-spectrum').innerHTML=spectrumSVG(r.peaks);$('library-meta').innerHTML=`<h3>${escape(r.name)}</h3><dl><dt>Summenformel</dt><dd>${escape(r.formula)}</dd><dt>EI</dt><dd>${escape(r.energy)}</dd><dt>Originalgerät</dt><dd>${escape(r.instrument)} · ${escape(r.instrumentType)} (Sektorfeld-Referenz; kein mit dem Modell-Quadrupol gemessener Lauf)</dd><dt>MassBank-ID</dt><dd>${escape(r.accession)}</dd><dt>Autorenschaft</dt><dd>${escape(r.authors)}</dd><dt>Lizenz</dt><dd>${escape(r.license)} (laut Record, ohne Versionsangabe)</dd></dl><p><a href="${escape(r.originalURL)}" target="_blank" rel="noopener noreferrer">Originalrecord & Herkunft ↗</a> · <a href="${escape(r.originalFile)}" download>Unveränderten Record herunterladen</a></p><p class="small">Die Retentionszeiten und GC-Antwortfaktoren sind eigene Lehrmodellwerte, keine Daten dieses EI-Records.</p>`;$('library-structure').textContent='Strukturzeichner wird lokal geladen …';if(!$('library-dialog').open)$('library-dialog').showModal();try{const module=await rdkit();if(token!==libraryToken)return;const mol=module.get_mol(r.smiles);try{$('library-structure').innerHTML=mol.get_svg(420,240);}finally{mol.delete();}}catch{if(token===libraryToken)$('library-structure').textContent=r.formula+' · SMILES: '+r.smiles;}}
 function originals(){const sources=window.GCOriginals||[];$('original-gallery').innerHTML=sources.map((r,i)=>`<figure><button data-original="${i}" aria-label="${escape(r.title)} vergrößern"><img src="data/gc/chromatograms/${r.file}" alt="${escape(r.title)}" loading="lazy"></button><figcaption><h3>${escape(r.title)}</h3><p>${escape(r.description)}</p><p class="attribution">${escape(r.author)} · <a href="${escape(r.licenseURL)}" target="_blank" rel="noopener noreferrer">${escape(r.license)}</a> · <a href="${escape(r.page)}" target="_blank" rel="noopener noreferrer">Originalquelle ↗</a><br>${escape(r.changed)}</p></figcaption></figure>`).join('');$('original-gallery').addEventListener('click',e=>{const button=e.target.closest('[data-original]');if(!button)return;const r=sources[Number(button.dataset.original)];$('original-title').textContent=r.title;$('original-image').src='data/gc/chromatograms/'+r.file;$('original-image').alt=r.title;$('original-caption').innerHTML=`${escape(r.description)}<br>${escape(r.author)} · <a href="${escape(r.licenseURL)}" target="_blank" rel="noopener noreferrer">${escape(r.license)}</a> · <a href="${escape(r.page)}" target="_blank" rel="noopener noreferrer">Originalquelle</a> · ${escape(r.changed)}`;$('original-dialog').showModal();});}
 const pool=window.GCQuestions.build(lib),poolMap=new Map(pool.map(q=>[q.id,q]));let quiz;
 function shuffle(a){return a.map(v=>[Math.random(),v]).sort((a,b)=>a[0]-b[0]).map(p=>p[1]);}
 function newQuiz(){quiz={ids:window.GCQuestions.select(pool),index:0,answers:{},orders:{}};saveQuiz();renderQuiz();}
 function saveQuiz(){storage.set('gc-quiz-v1',JSON.stringify(quiz));}
 function loadQuiz(){try{const q=JSON.parse(storage.get('gc-quiz-v1'));if(q?.ids?.length===18&&q.ids.every(id=>poolMap.has(id))&&Number.isInteger(q.index)&&q.index>=0&&q.index<=18&&q.answers&&q.orders)quiz=q;}catch{}if(!quiz)newQuiz();else renderQuiz();}
 function renderQuiz(){const xp=Object.entries(quiz.answers).reduce((sum,[id,answer])=>sum+(poolMap.get(id)?.correct===answer?10:0),0);$('quiz-xp').textContent=xp+' XP';$('quiz-badge').textContent=xp>=140?'Chromatographie-Profi':xp>=80?'Spurenleser':'Laborneuling';$('quiz-progress').textContent=quiz.index<18?`Aufgabe ${quiz.index+1} / 18 · Pool: ${pool.length}`:`Runde abgeschlossen · Pool: ${pool.length}`;
  if(quiz.index>=18){$('quiz-card').innerHTML=`<h3>Du hast 18 Analyseaufgaben bearbeitet.</h3><p>${xp} von 180 XP. Wiederhole besonders die Erklärungen zu unsicheren Zuordnungen und Kalibrierungen. Mit „Neue Aufgabenrunde“ erhältst du eine neue Zufallsauswahl.</p><button id="quiz-again" class="primary">Neue Runde starten</button>`;return;}
  const q=poolMap.get(quiz.ids[quiz.index]);if(!quiz.orders[q.id]){quiz.orders[q.id]=shuffle(q.options.map((_,i)=>i));saveQuiz();}const answered=Object.prototype.hasOwnProperty.call(quiz.answers,q.id),answer=quiz.answers[q.id];$('quiz-card').innerHTML=`<p class="quiz-category">${escape(q.category)}</p><h3>${escape(q.question)}</h3>${q.spectrum?`<svg class="quiz-visual" viewBox="0 0 900 330" role="img" aria-label="Gemessenes EI-Referenzspektrum für die Vergleichsaufgabe">${spectrumSVG(q.spectrum)}</svg><button id="quiz-library">Referenzbibliothek zum Vergleichen öffnen</button>`:''}<div class="quiz-options">${quiz.orders[q.id].map(i=>`<button data-answer="${i}"${answered?' disabled':''} class="${answered?(i===q.correct?'correct':i===answer?'incorrect':''):''}">${escape(q.options[i])}</button>`).join('')}</div>${answered?`<p class="result" role="status">${answer===q.correct?'Richtig · +10 XP.':'Noch nicht richtig. Die grün markierte Antwort ist korrekt.'} ${escape(q.explanation)}</p><button id="quiz-next" class="primary">${quiz.index===17?'Runde abschließen':'Nächste Aufgabe'}</button>`:''}`;}
 const coachSteps=[
  ['Wähle deine Fragestellung','Beginne mit „Freies Experimentieren“ und dem Lösungsmittelgemisch. Später kannst du ein unbekanntes Gemisch identifizieren oder eine Konzentration durch eine selbst gemessene Kalibrierung bestimmen.','mode-explore'],
  ['Stelle deine Probe zusammen','Wähle ein vorbereitetes Gemisch oder ergänze einzelne Stoffe. Die Zahl neben jedem Stoff ist seine Konzentration in mg/L. In den Analyseaufträgen bleibt die Zusammensetzung der unbekannten Probe verborgen.','mixture-preset'],
  ['Prüfe die Messmethode','Beginne mit GC-MS, unpolarer 30-m-Säule, 60 °C und 8 °C/min. Die Einstellungen bestimmen die Trennung. Jede Methodenänderung macht die vorherige Blindprobe und Kalibrierung ungültig.','method-controls'],
  ['Stabilisiere das Gerät','Drücke „1 · Gerät stabilisieren“. In diesem Lehrmodell wird damit ein stabiler Gasstrom und ein bereiter Ofen angenommen; ein reales Gerät braucht dafür mehr Zeit.','equilibrate'],
  ['Miss die Blindprobe','Drücke „2 · Blindprobe messen“. Du siehst eine nahezu flache, leicht driftende Linie. Warte bis zum Ende oder nutze den Zeitrafferknopf. Diese Messung wird von den späteren Kurven abgezogen.','blank'],
  ['Injiziere die Probe','Drücke „3 · Probe injizieren“. Im Konzentrationsauftrag zuerst einen Standard bereitstellen! Die Kurve wächst von links nach rechts. Ein Split hält einen Teil der Probenmenge von der Säule fern.','inject'],
  ['Lies die Peaks und die Ionen','Klicke nach Ende der Messung auf eine Peakzeile. Der Zeitcursor und die Integrationsgrenzen wechseln zu diesem Peak. Bei GC-MS erscheint darunter das passende Spektrum. „Mit EI-Bibliothek vergleichen“ liefert Kandidaten, keinen Beweis.','peak-table'],
  ['Untersuche das Gemisch genauer','Verfolge bei GC-MS ein einzelnes m/z als EIC. Verändere bei schlechter Trennung die Methode und miss neu. In der Quantifizierung: Nullstandard sowie z. B. 25, 50 und 100 mg/L messen; erst danach die Unbekannte.','trace-kind']
 ];
 function coach(){const [title,text]=coachSteps[state.coachStep];$('coach-step').textContent=`Messassistent · Schritt ${state.coachStep+1} / ${coachSteps.length}`;$('coach-title').textContent=title;$('coach-text').textContent=text;$('coach-feedback').textContent=state.running?'Die Messung läuft. Du kannst sie im Hintergrund verfolgen.':state.blank?'Blindprobe vorhanden. Das Gerät ist für eine passende Probenmessung bereit.':state.ready?'Gerät bereit. Als Nächstes die Blindprobe messen.':'Das Gerät ist noch nicht stabilisiert.';$('coach-back').disabled=state.coachStep===0;$('coach-next').textContent=state.coachStep===coachSteps.length-1?'Assistent beenden':'Nächster Schritt';if(!$('coach-dialog').open)$('coach-dialog').showModal();}
 let fullPlaceholder;
 function fullpage(){if($('lab-fullpage').open)return;fullPlaceholder=document.createComment('GC-Labor Position');$('labor').before(fullPlaceholder);$('fullpage-body').append($('labor'));$('lab-fullpage').showModal();$('fullpage-body').scrollTop=0;$('fullpage-close').focus();}
 function restoreFullpage(){if(fullPlaceholder){fullPlaceholder.replaceWith($('labor'));fullPlaceholder=null;}$('lab-fullscreen').focus();}
 let resetAction;
 function confirmReset(kind){resetAction=kind;$('reset-dialog').returnValue='';$('reset-message').textContent=kind==='quiz'?'Der Aufgabenfortschritt und die XP werden gelöscht. Du erhältst 18 neu ausgewählte Aufgaben.':kind==='all'?'Alle aktuellen Messungen, Standards, Aufgaben und Erfahrungspunkte werden zurückgesetzt. Du erhältst eine neue Aufgabenrunde.':'Die aktuellen Messungen und Standards werden verworfen. Der Aufgabenfortschritt bleibt erhalten.';$('reset-dialog').showModal();}
 function resetLab(){abort();cancelCooling();state.temperature=null;for(const [key,id] of Object.entries(methodIds))$(id).value=String(C.defaults[key]);$('realistic').value='yes';$('speed').value='12';$('mixture-preset').value='solvents';$('quant-analyte').value='ethanol';$('quant-method').value='external';$('device-inside').checked=false;$('device-flow').checked=false;$('show-components').checked=false;$('trace-kind').value='tic';$('y-scale').value='auto';$('view-start').value=0;$('view-end').value=12;state.rows=[];state.runNumber=0;state.runPeaks=[];setMode('explore');preset('solvents');invalidate();tell('Labor zurückgesetzt. Wähle eine Methode oder stabilisiere das Gerät.');}
 function download(text,type,name){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function exportCSV(){const r=state.run;if(!r||state.running)return;const mz=Number($('eic-mass').value);if(r.settings.detector==='ms'&&(!Number.isInteger(mz)||mz<10||mz>220)){tell('Für den CSV-Export ein ganzzahliges m/z von 10 bis 220 wählen.',true);return;}const rows=[['GC LABOR','SIMULIERTES CHROMATOGRAMM'],['Probe',r.job.label],['Methode',JSON.stringify(r.settings)],['EI-Daten','MassBank; angepasste Spektrenmuster CC BY-NC-SA; Autorenschaft, Rohdaten und Einzelquellen: https://genaiedu.github.io/LearningApps2/data/gc/library.json'],['Dokumentation','https://genaiedu.github.io/LearningApps2/data/gc/README.md'],['Einheiten','Zeit min; Signal a.u.; EIC a.u.'],['Zeit_min','Gesamtsignal_au','Blindwertkorrigiert_au',r.settings.detector==='ms'?'EIC_mz_'+mz+'_au':'Kein_MS_Detektor']];const corrected=C.corrected(r,state.blank),eic=r.settings.detector==='ms'?C.eic(r,mz):null;r.points.forEach((p,i)=>rows.push([p[0].toFixed(6),p[1].toFixed(6),corrected[i][1].toFixed(6),eic?eic[i][1].toFixed(6):'']));download('\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8','gc-messung-'+r.number+'.csv');}
 function exportSVG(){if(!state.run)return;const graph=$('chromatogram-plot').innerHTML.replaceAll('var(--muted)','#526553').replaceAll('var(--line)','#bcc8b8');const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 570"><rect width="1100" height="570" fill="#fffcf3"/><text x="55" y="40" font-family="monospace" font-size="20" fill="#1c4b45">GC LABOR / SIMULIERTES CHROMATOGRAMM</text><text x="55" y="70" font-family="monospace" font-size="14" fill="#1c4b45">${escape($('paper-sample').textContent)}</text><text x="55" y="94" font-family="monospace" font-size="11" fill="#46564b">${escape($('paper-method').textContent)}</text><svg x="50" y="115" width="1000" height="400" viewBox="0 0 1000 400">${graph}</svg><text x="55" y="550" font-family="monospace" font-size="12" fill="#46564b">LEHRMODELL / KEIN REALER MESSBEFUND · ${escape($('paper-count').textContent)}</text></svg>`;download(svg,'image/svg+xml','gc-registrierpapier-'+state.run.number+'.svg');}
 // Events: method changes and sample preparation never silently reuse incompatible calibration data.
 Object.values(methodIds).concat('realistic').forEach(id=>$(id).addEventListener('change',invalidate));
 $('equilibrate').addEventListener('click',()=>{try{method();state.ready=true;$('read-state').textContent='BEREIT';buttons();tell('Gasfluss und Ofen stabilisiert (Lehrmodell). Jetzt die Blindprobe messen.');}catch(e){tell(e.message,true);}});
 $('blank').addEventListener('click',()=>startRun(true));$('inject').addEventListener('click',()=>startRun(false));$('stop').addEventListener('click',abort);$('finish-run').addEventListener('click',finish);
 ['explore','qualitative','quantitative'].forEach(m=>$('mode-'+m).addEventListener('click',()=>setMode(m)));
 $('mixture-preset').addEventListener('change',()=>{if($('mixture-preset').value!=='custom')preset($('mixture-preset').value);});
 $('mixture-rows').addEventListener('change',e=>{if(e.target.dataset.index!==undefined){const c=Number(e.target.value);if(!e.target.value||!Number.isFinite(c)||c<0||c>500){tell('Konzentration zwischen 0 und 500 mg/L eingeben.',true);sample();return;}state.mixture[Number(e.target.dataset.index)].c=c;$('mixture-preset').value='custom';}});
 $('mixture-rows').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){state.mixture.splice(Number(b.dataset.remove),1);$('mixture-preset').value='custom';sample();}});
 $('add-mixture').addEventListener('click',()=>{const id=$('add-compound').value;if(state.mixture.some(m=>m.id===id)){tell('Dieser Stoff ist bereits in der Mischung.',true);return;}if(state.mixture.length>=8){tell('Maximal acht Stoffe pro Mischung.',true);return;}state.mixture.push({id,c:30});$('mixture-preset').value='custom';sample();});
 $('new-qualitative').addEventListener('click',newQual);$('qual-check').addEventListener('click',()=>{if(!state.run||state.run.job.kind!=='qualitative'||state.running){$('qual-feedback').textContent='Zuerst die unbekannte Probe messen.';return;}const chosen=[...$('qual-answers').querySelectorAll('input:checked')].map(el=>el.value);state.qualAttempts++;const good=chosen.length===3&&state.qual.every(m=>chosen.includes(m.id));$('qual-feedback').textContent=good?'Die drei Kandidaten stimmen. Begründe trotzdem jeden Vorschlag mit Messzeit und mehreren Ionen, nicht nur mit einem ähnlichen Peak.':'Noch nicht vollständig passend. Wähle genau drei Stoffe. Prüfe die Spektren an verschiedenen Peakpositionen und gegebenenfalls ein EIC.';if(good){state.qualRevealed=true;sample();}});
 $('qual-reveal').addEventListener('click',()=>{if(!state.run||state.run.job.kind!=='qualitative'||state.running){$('qual-feedback').textContent='Nimm zuerst eine Messung auf.';return;}state.qualRevealed=true;$('qual-feedback').textContent='Enthalten: '+state.qual.map(m=>{const t=C.retention(record(m.id),state.run.settings);return record(m.id).name+' (Modell-tR '+(t===null?'nicht eluiert':n(t)+' min')+')';}).join('; ')+'. Vergleiche an diesen Zeiten die EI-Muster mit den gemessenen Referenzen. Koelution kann die Scanmuster mischen.';sample();});
 $('prepare-standard').addEventListener('click',()=>prepare('standard'));$('prepare-unknown').addEventListener('click',()=>prepare('unknown'));$('new-quantitative').addEventListener('click',newQuant);
 ['quant-analyte','quant-method'].forEach(id=>$(id).addEventListener('change',()=>{state.rows=[];newQuant();tell('Analyt oder Verfahren geändert. Neue passende Standards messen.');}));$('dilution').addEventListener('change',()=>{state.unknown=null;if(state.pending?.kind==='unknown')prepare('unknown');calibration();});$('check-concentration').addEventListener('click',checkConcentration);
 $('calibration-table').addEventListener('click',e=>{const b=e.target.closest('[data-delete-cal]');if(b){state.rows.splice(Number(b.dataset.deleteCal),1);calibration();}});
 $('device-inside').addEventListener('change',device);$('device-flow').addEventListener('change',()=>{if($('device-flow').checked)$('device-inside').checked=true;device();});
 $('speed').addEventListener('change',()=>{try{ovenProgram(method());}catch{}});
 ['view-start','view-end','y-scale','show-components','eic-mass'].forEach(id=>$(id).addEventListener('input',drawChrom));$('trace-kind').addEventListener('change',()=>{$('eic-label').hidden=$('trace-kind').value!=='eic';drawChrom();});$('view-all').addEventListener('click',()=>{$('view-start').value=0;$('view-end').value=state.run?.settings.runtime||$('runtime').value;drawChrom();});
 $('peak-table').addEventListener('click',e=>{const b=e.target.closest('[data-peak]');if(b)selectPeak(Number(b.dataset.peak));});$('scan-time').addEventListener('input',scan);
 $('chromatogram-plot').addEventListener('click',e=>{if(!state.run||state.running)return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*1000,lo=Number(e.currentTarget.dataset.xmin),hi=Number(e.currentTarget.dataset.xmax);$('scan-time').value=Math.max(0,Math.min(state.run.settings.runtime,lo+(x-65)/911*(hi-lo)));scan();});$('chromatogram-plot').addEventListener('keydown',e=>{if(state.run&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();$('scan-time').value=Number($('scan-time').value)+(e.key==='ArrowRight'?.01:-.01);scan();}});
 $('integrate-manual').addEventListener('click',()=>{if(!state.run||state.running){$('integration-result').textContent='Zuerst eine Messung abschließen.';return;}const a=Number($('int-start').value),b=Number($('int-end').value);if(a<0||b>state.run.settings.runtime||a>=b){$('integration-result').textContent='Gültige Grenzen innerhalb des Messlaufs wählen.';return;}const points=$('trace-kind').value==='eic'?trace():C.corrected(state.run,state.blank),area=C.integrate(points,a,b);$('integration-result').textContent=`${$('trace-kind').value==='eic'?'EIC':'Blindwertkorrigiertes Gesamtsignal'}: Fläche von ${n(a)} bis ${n(b)} min = ${n(area,5)} a.u.·min. Diese manuelle Fläche ändert die automatische Kalibrierung nicht.`;});
 $('compare-library').addEventListener('click',()=>{if(!state.run||state.running)return;const spectrum=C.spectrumAt(state.run,Number($('scan-time').value));if(!spectrum.length){$('library-matches').textContent='Kein ausreichend starkes Stoffsignal am Zeitcursor.';return;}$('library-matches').innerHTML=C.matches(spectrum,lib).slice(0,4).map(m=>`<button data-library="${m.record.id}">${escape(m.record.name)} · Ähnlichkeit ${n(m.score*100,1)} %</button>`).join('');});$('library-matches').addEventListener('click',e=>{const b=e.target.closest('[data-library]');if(b)showLibrary(b.dataset.library);});$('library-open').addEventListener('click',()=>showLibrary($('add-compound').value));$('library-select').addEventListener('change',()=>showLibrary($('library-select').value));$('library-close').addEventListener('click',()=>$('library-dialog').close());$('original-close').addEventListener('click',()=>$('original-dialog').close());
 $('lab-fullscreen').addEventListener('click',fullpage);$('fullpage-close').addEventListener('click',()=>$('lab-fullpage').close());$('lab-fullpage').addEventListener('close',restoreFullpage);
 $('coach-open').addEventListener('click',coach);$('coach-back').addEventListener('click',()=>{state.coachStep=Math.max(0,state.coachStep-1);coach();});$('coach-next').addEventListener('click',()=>{if(state.coachStep===coachSteps.length-1)$('coach-dialog').close();else{state.coachStep++;coach();}});$('coach-close').addEventListener('click',()=>$('coach-dialog').close());$('coach-show').addEventListener('click',()=>{const id=coachSteps[state.coachStep][2],el=$(id);$('coach-dialog').close();document.querySelectorAll('.coach-focus').forEach(e=>e.classList.remove('coach-focus'));el.classList.add('coach-focus');el.scrollIntoView({behavior:'smooth',block:'center'});if(!el.disabled&&el.matches('button,input,select'))el.focus({preventScroll:true});setTimeout(()=>el.classList.remove('coach-focus'),10000);});
 $('app-reset').addEventListener('click',()=>confirmReset('all'));$('lab-reset').addEventListener('click',()=>confirmReset('lab'));$('quiz-reset').addEventListener('click',()=>confirmReset('quiz'));$('reset-dialog').addEventListener('close',()=>{if($('reset-dialog').returnValue!=='reset')return;if(resetAction==='all'||resetAction==='lab')resetLab();if(resetAction==='all'||resetAction==='quiz')newQuiz();});
 $('quiz-card').addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(b){const id=quiz.ids[quiz.index];if(Object.prototype.hasOwnProperty.call(quiz.answers,id))return;quiz.answers[id]=Number(b.dataset.answer);saveQuiz();renderQuiz();}if(e.target.id==='quiz-next'){quiz.index++;saveQuiz();renderQuiz();}if(e.target.id==='quiz-again')confirmReset('quiz');if(e.target.id==='quiz-library')showLibrary(lib[0].id);});
 $('export-csv').addEventListener('click',exportCSV);$('export-svg').addEventListener('click',exportSVG);$('print-record').addEventListener('click',()=>window.print());
 function theme(dark){document.body.classList.toggle('dark',dark);$('theme').textContent=dark?'Helles Farbschema':'Dunkles Farbschema';storage.set('gc-dark',dark?'yes':'no');}theme(storage.get('gc-dark')==='yes');$('theme').addEventListener('click',()=>theme(!document.body.classList.contains('dark')));
 $('journey-temperature').addEventListener('click',()=>{const hot=$('journey-temperature').getAttribute('aria-pressed')!=='true';$('journey-temperature').setAttribute('aria-pressed',String(hot));$('journey-temperature').textContent=hot?'Temperatur wieder senken':'Temperatur erhöhen';$('journey-temperature').closest('.journey').classList.toggle('hot',hot);});
 function hero(){const r=C.simulate(lib,presets.aroma.map(([id,c])=>({id,c})),{temperature:70,ramp:10,runtime:12,realistic:false},23);const a=axisSVG(640,370,{xmax:12,ymax:Math.max(...r.points.map(p=>p[1]))*1.13,xlabel:'RETENTION TIME / min',ylabel:'SIGNAL',paper:true});const path=r.points.map((p,i)=>(i?'L':'M')+a.x(p[0]).toFixed(1)+' '+a.y(p[1]).toFixed(1)).join(' ');$('hero-chromatogram').innerHTML=a.html+`<path d="${path}" fill="none" stroke="#176b6c" stroke-width="2"/>`;}
 preset('solvents');newQual();state.mode='explore';sample();state.runPeaks=[];device();renderRun();calibration();buttons();originals();loadQuiz();hero();
})();
