(() => {
  'use strict';
  const D=window.REVOLUTION,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  if(!D?.sources)return;
  const storageKey='revolutionsfaeden-v1';
  const defaults=()=>({consent:null,a:'market',b:'royal',compare:true,event:'bastille',role:'market',roleEvent:'october',source:'rights',scene:'bread',cast:D.scenes[0].cast.slice(),concept:'freedom',paused:matchMedia('(prefers-reduced-motion: reduce)').matches,notes:{},criterion:'Rechtsgleichheit',period:'1789: erste Umbrüche'});
  let state=defaults();try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved&&typeof saved==='object')state={...state,...saved,notes:saved.notes&&typeof saved.notes==='object'?saved.notes:{}}}catch{}
  const valid=(list,id,fallback)=>list.some(x=>x.id===id)?id:fallback;
  state.a=valid(D.roles,state.a,'market');state.b=valid(D.roles,state.b,'royal');state.event=valid(D.events,state.event,'bastille');state.role=valid(D.roles,state.role,'market');state.roleEvent=valid(D.events,state.roleEvent,'october');state.source=valid(D.sources,state.source,'rights');state.scene=valid(D.scenes,state.scene,'bread');state.concept=valid(D.concepts,state.concept,'freedom');state.consent=typeof state.consent==='boolean'?state.consent:null;
  state.cast=Array.isArray(state.cast)?state.cast.filter(id=>D.roles.some(r=>r.id===id)):D.scenes[0].cast.slice();
  let storageOK=true,timer=null,remaining=60,deadline=0,speaker=0,promptIndex=0;
  function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));storageOK=true}catch{storageOK=false}$$('.storage-status').forEach(el=>el.textContent=storageOK?'Auf diesem Gerät gespeichert.':'Speichern im Browser nicht möglich. Bitte Notizen herunterladen.');}
  const role=id=>D.roles.find(r=>r.id===id),event=id=>D.events.find(e=>e.id===id);
  const wikiButton=page=>`<button type="button" class="wiki-button" data-wiki="${esc(page)}">${esc(page)} · Wikipedia lesen ↗</button>`;
  const imageSlot=id=>`<div class="image-slot" data-image="${esc(id)}"></div>`;
  const para=text=>text.map(t=>`<p>${esc(t)}</p>`).join('');
  const options=(items,label)=>items.map(x=>`<option value="${esc(x.id)}">${esc(label(x))}</option>`).join('');
  function changed(){save();restoreNotes();document.dispatchEvent(new Event('revolution-render'));}
  function noteKey(el){switch(el.dataset.note){case'comparison':return `comparison:${state.a}:${state.compare?state.b:'solo'}:${state.event}`;case'role':return `role:${state.role}:${state.roleEvent}`;case'source':return `source:${state.source}`;case'scene':return `scene:${state.scene}`;case'concept':return `concept:${state.concept}`;case'judgment':return `judgment:${state.criterion}:${state.period}`;default:return el.dataset.note}}
  function restoreNotes(){$$('[data-note]').forEach(el=>{el.dataset.noteKey=noteKey(el);el.value=state.notes[el.dataset.noteKey]||''})}
  $$('[data-note]').forEach(el=>el.addEventListener('input',()=>{state.notes[el.dataset.noteKey||noteKey(el)]=el.value;save()}));
  function exportNotes(){let lines=['REVOLUTIONSFÄDEN · Lernnotizen',new Date().toLocaleString('de-DE'),'','Schlüssel enthalten Rolle, Ereignis oder Quelle; alle Rollen sind didaktische Fallfiguren.',''];for(const [key,value]of Object.entries(state.notes)){if(typeof value==='string'&&value.trim())lines.push(key,'—'.repeat(40),value,'')}if(lines.length===6)lines.push('Noch keine eigenen Notizen.');return lines.join('\n')}
  function downloadNotes(){const blob=new Blob([exportNotes()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Revolutionsfaeden-Lernnotizen.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
  $('#save-work').addEventListener('click',downloadNotes);$('#download-notes').addEventListener('click',downloadNotes);
  function printHTML(html){$('#print-area').innerHTML=html;window.print()}
  $('#print-notes').addEventListener('click',()=>printHTML(`<h1>Revolutionsfäden · Meine Lernnotizen</h1><p>${esc(state.criterion)} · ${esc(state.period)}</p>${Object.entries(state.notes).filter(([,v])=>typeof v==='string'&&v.trim()).map(([k,v])=>`<section><h3>${esc(k)}</h3><p>${esc(v).replaceAll('\n','<br>')}</p></section>`).join('')||'<p>Noch keine eigenen Notizen.</p>'}`));
  const heroPaths=D.roles.map((r,i)=>`<path stroke="${r.color}" d="M-80 ${80+i*53} C320 ${i%2?60:790} 550 ${i%2?780:30} 850 ${120+i*34} S1240 ${700-i*35} 1550 ${100+i*62}"/>`).join('');$('#hero-lines').innerHTML=heroPaths;
  function motion(){document.body.classList.toggle('motion-paused',state.paused);$('#motion').textContent=state.paused?'Bewegung aktivieren':'Bewegung pausieren';$('#motion').setAttribute('aria-pressed',String(state.paused))}motion();$('#motion').addEventListener('click',()=>{state.paused=!state.paused;motion();save()});
  $('#context-grid').innerHTML=D.context.map(c=>`<article class="context-card"><h3>${esc(c.title)}</h3>${para(c.text)}${wikiButton(c.wiki)}</article>`).join('');
  function vote(){const allies=Number($('#allies').value),heads=$('#vote-mode').value==='heads';$('#allies-count').textContent=allies;const yes=heads?600+allies:allies>150?2:1,no=heads?600-allies:allies<150?2:1,total=heads?1200:3;$('#vote-bars').innerHTML=[['Dafür',yes,''],['Dagegen',no,'against']].map(([name,count,cl])=>`<div class="vote-bar ${cl}"><span>${name}</span><div><i style="width:${count/total*100}%"></i></div><b>${count}</b></div>`).join('');$('#vote-result').textContent=(yes>no?'Der Antrag erhält in diesem Modell eine Mehrheit.':yes===no?'Stimmengleichheit: keine Mehrheit für den Antrag.':'Keine Mehrheit für den Antrag.')+' '+(heads?'Jede Abgeordnetenstimme zählt einzeln.':allies===150?'Die Geistlichkeit ist im Modell geteilt und gibt keine einheitliche Standesstimme ab.':'Im Modell kommen die Übertritte aus der Geistlichkeit; der Adel stimmt dagegen. Eine Standesstimme folgt der Mehrheit innerhalb ihres Standes.');}$('#allies').addEventListener('input',vote);$('#vote-mode').addEventListener('change',vote);vote();
  for(const id of ['perspective-a','perspective-b','role-select'])$('#'+id).innerHTML=options(D.roles,r=>r.name);
  $('#perspective-a').value=state.a;$('#perspective-b').value=state.b;$('#compare').checked=state.compare;$('#role-select').value=state.role;
  function weave(){const cols=D.events.map((e,i)=>60+i*84),rows=D.roles.map((r,i)=>45+i*19);$('#weave').innerHTML=D.events.map((e,i)=>`<line class="event-guide ${e.id===state.event?'current':''}" x1="${cols[i]}" y1="20" x2="${cols[i]}" y2="280"/><text x="${cols[i]}" y="303" text-anchor="middle">${e.year<1789?'1788':Math.floor(e.year)}</text>`).join('')+D.roles.map((r,k)=>{const points=cols.map((x,i)=>[x,rows[k]+Math.sin(i*.85+k*.8)*16]);return `<path stroke="${r.color}" class="${r.id===state.a||state.compare&&r.id===state.b?'selected':''}" d="${points.map(([x,y],i)=>(i?'L':'M')+x+' '+y.toFixed(1)).join(' ')}"/>`}).join('')+D.roles.filter(r=>r.id===state.a||state.compare&&r.id===state.b).map(r=>{const i=D.events.findIndex(e=>e.id===state.event),k=D.roles.indexOf(r);return `<circle cx="${cols[i]}" cy="${(rows[k]+Math.sin(i*.85+k*.8)*16).toFixed(1)}" r="6"/>`}).join('');}
  function ownTimeline(r){const ids=new Set([...D.focus[r.id],state.event]),items=D.events.filter(e=>ids.has(e.id));return `<article class="own-timeline" style="--accent:${r.color}"><h3>${esc(r.name)}</h3><p class="route-note">${esc(r.place)} · ${esc(r.news)}</p><div class="timeline-list">${items.map(e=>`<button type="button" data-event="${e.id}" aria-current="${e.id===state.event}"><time>${esc(e.date)}</time>${esc(e.views[r.id][0])}</button>`).join('')}</div><p class="small">Ausgewählte Einschnitte für diese Perspektive. Die Daten bezeichnen Ereignisse, nicht automatisch deren Bekanntwerden am Wohnort.</p></article>`}
  function renderEvent(){const e=event(state.event),selected=[role(state.a),...(state.compare?[role(state.b)]:[])];weave();$('#event-picker').innerHTML=D.events.map(x=>`<button type="button" data-event="${x.id}" aria-pressed="${x.id===e.id}"><small>${esc(x.date)}</small>${esc(x.title)}</button>`).join('');$('#event-common').innerHTML=`<div class="event-layout"><div><span class="eyebrow">GEMEINSAME EREIGNISSPUR · ${esc(e.date)}</span><h3>${esc(e.title)}</h3>${para(e.facts)}<div class="unknown"><strong>Noch nicht wissen!</strong><p>${esc(e.unknown)}</p></div>${wikiButton(e.wiki)}</div>${imageSlot(e.image)}</div>`;$('#perspective-timelines').classList.toggle('single',!state.compare);$('#voice-comparison').classList.toggle('single',!state.compare);$('#perspective-timelines').innerHTML=selected.map(ownTimeline).join('');$('#voice-comparison').innerHTML=selected.map(r=>`<article class="voice-card" style="--accent:${r.color}"><span class="role-tag">${esc(r.name)} · ${esc(r.place)}</span><h3>${esc(e.views[r.id][0])}</h3><p>${esc(e.views[r.id][1])}</p><p class="fiction">Didaktische Perspektivrekonstruktion, kein Originalzitat. ${r.id==='london'||r.id==='colony'||r.id==='farmer'||r.id==='laborer'?'Nachrichten kommen vermittelt an; das Ereignisdatum ist kein belegtes Empfangsdatum.':''}</p></article>`).join('');changed()}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-event]');if(!b)return;state.event=b.dataset.event;renderEvent()});
  $('#perspective-a').addEventListener('change',e=>{state.a=e.target.value;renderEvent()});$('#perspective-b').addEventListener('change',e=>{state.b=e.target.value;renderEvent()});$('#compare').addEventListener('change',e=>{state.compare=e.target.checked;$('#perspective-b').disabled=!state.compare;renderEvent()});renderEvent();
  const routes={local:{days:0,destination:'NACHBARSCHAFT',text:'Eine unmittelbare Beobachtung erreicht Nachbarn schnell. Aber wer nur einen Ausschnitt gesehen hat, kennt noch nicht die Gründe und die ganze Ereigniskette.'},rural:{days:5,destination:'DORF',text:'Im Modell trifft nach fünf Tagen ein Brief ein und wird vorgelesen. Das Dorf verbindet die Nachricht mit seinen eigenen Abgaben- und Versorgungsfragen.'},london:{days:8,destination:'LONDON',text:'Im Modell wird die Nachricht nach acht Tagen aus Post und Presse bekannt. Übersetzung, Auswahl und politische Deutung beeinflussen das Gelesene.'},colony:{days:45,destination:'SAINT-DOMINGUE',text:'Im Modell erreicht ein Schiff nach 45 Tagen die Kolonie. In der Zwischenzeit kann sich die Lage in Frankreich verändert haben. Lokale Erfahrungen sind nicht weniger wichtig als die verspätete Nachricht.'}};
  function news(){const r=routes[$('#news-route').value],day=Number($('#news-day').value);$('#news-day-count').textContent='Tag '+day;$('#destination').textContent=r.destination;const fraction=r.days===0?1:Math.min(day/r.days,1);$('#messenger').style.left=(12+fraction*65)+'%';$('#news-result').innerHTML=`<strong>${day>=r.days?'Im Modell angekommen':'Im Modell noch unterwegs'}</strong><p>${esc(day>=r.days?r.text:'Die Beteiligten handeln mit dem, was sie vor Ort wissen. Eine noch nicht eingetroffene Pariser Nachricht darf ihre Entscheidung nicht begründen.')}</p><small>Frei gewählter Szenariowert, keine historische Ankunftszeit.</small>`;$('#news-advance').disabled=day>=70}$('#news-route').addEventListener('change',news);$('#news-day').addEventListener('input',news);$('#news-advance').addEventListener('click',()=>{$('#news-day').value=Math.min(70,Number($('#news-day').value)+1);news()});news();
  $('#deep-chapters').innerHTML=D.chapters.map((c,i)=>`<details class="deep-chapter" ${i===0?'open':''}><summary><span><small>${esc(c.period)}</small><strong>${esc(c.title)}</strong></span></summary><div class="chapter-body"><div>${para(c.text)}<p class="chapter-question"><strong>Perspektivfrage:</strong> ${esc(c.question)}</p>${wikiButton(c.wiki)}</div>${imageSlot(c.image)}</div></details>`).join('');
  $('#role-cards').innerHTML=D.roles.map(r=>`<button type="button" class="role-choice" data-role="${r.id}" style="--accent:${r.color}" aria-pressed="${r.id===state.role}"><small>${esc(r.place)}</small><strong>${esc(r.name)}</strong><small>${esc(r.question)}</small></button>`).join('');
  $('#role-date').innerHTML=options(D.events,e=>e.date+' · '+e.title);$('#role-date').value=state.roleEvent;
  function renderRole(){const r=role(state.role),e=event(state.roleEvent),allowed=D.sources.filter(s=>r.sources.includes(s.id)&&s.year<=e.year),later=D.sources.filter(s=>r.sources.includes(s.id)&&s.year>e.year);$('#role-dossier').style.setProperty('--accent',r.color);$('#role-dossier').innerHTML=`<div class="dossier-head"><div><p class="eyebrow">${esc(r.type)} · WISSENSHORIZONT: ${esc(e.date)}</p><h3>${esc(r.name)}</h3><p>${esc(r.life)}</p><p class="warning"><strong>Rollenregel:</strong> ${esc(e.unknown)}${r.id==='royal'&&e.year>1793.2?' Ludwig XVI. ist tot; ab Herbst 1793 auch Marie-Antoinette. Für spätere Zeitpunkte sprecht ihr über Hinterbliebene oder über Quellen, nicht als weiterlebender König.':''}${r.id==='girondin'&&e.year>1793.4?' Führende Girondisten sind verfolgt oder später hingerichtet. Die Fallfigur ist eine bedrohte Anhängerin bzw. ein späterer Überlebender, nicht automatisch ein weiter amtierender Politiker.':''}</p></div>${imageSlot(r.image)}</div><div class="dossier-grid">${[['Meine Forderung',r.want],['Was ich verlieren kann',r.risk],['Woher ich Nachrichten habe',r.news],['Mein Begriff von Freiheit',r.freedom],['Meine Gruppe ist nicht einheitlich',r.division],['Meine Frage an die anderen',r.question]].map(([h,t])=>`<section><h4>${esc(h)}</h4><p>${esc(t)}</p></section>`).join('')}</div><section class="role-current"><h4>${esc(e.views[r.id][0])}</h4><p>${esc(e.views[r.id][1])}</p><p><strong>Vorbereitung:</strong> Eine Forderung, eine Befürchtung, eine Frage, ein Beleg. Kennzeichne, was du selbst gesehen hast und was du nur gehört hast.</p></section><h4>Quellen zum Prüfen</h4><p class="small">Veröffentlichte Texte können zum Zeitpunkt passen, sind aber nicht automatisch jeder Figur bekannt. Begründe gegebenenfalls einen Zugang über Zeitung, Brief oder Vorlesen.</p><div class="source-links">${allowed.map(s=>`<button data-source="${s.id}">${esc(s.author)} · ${esc(s.date)} →</button>`).join('')||'<p>Aus der Auswahl ist noch kein passender Text veröffentlicht. Nutze den Kontext, kennzeichne die Grenzen und erfinde kein Zitat.</p>'}</div>${later.length?`<details><summary>Spätere Quellen – nicht als damaliges Wissen verwenden</summary><p>${later.map(s=>esc(s.author+' · '+s.date)).join('<br>')}</p></details>`:''}`;$$('[data-role]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.role===r.id)));changed()}
  $('#role-select').addEventListener('change',e=>{state.role=e.target.value;renderRole()});$('#role-date').addEventListener('change',e=>{state.roleEvent=e.target.value;renderRole()});$('#role-cards').addEventListener('click',e=>{const b=e.target.closest('[data-role]');if(!b)return;state.role=b.dataset.role;$('#role-select').value=state.role;renderRole();$('#role-dossier').scrollIntoView({behavior:state.paused?'auto':'smooth',block:'start'})});$('#print-role').addEventListener('click',()=>printHTML(`<h1>Revolutionsfäden · Rollenakte</h1>${$('#role-dossier').outerHTML}<h3>Meine Vorbereitung</h3><p>${esc($('#role-note').value).replaceAll('\n','<br>')}</p>`));renderRole();
  $('#source-select').innerHTML=options(D.sources,s=>s.date+' · '+s.author+' · '+s.title);$('#source-select').value=state.source;
  function renderSource(){const s=D.sources.find(x=>x.id===state.source);$('#source-card').innerHTML=`<p class="source-byline">${esc(s.date)} · ${esc(s.author)} · ${esc(s.genre)}</p><h3>${esc(s.title)}</h3><p>${esc(s.context)}</p><div class="quote-pair"><div><h4>ORIGINAL · ${s.lang==='fr'?'FRANZÖSISCH':'ENGLISCH'}</h4><blockquote lang="${s.lang}">${esc(s.original)}</blockquote></div><div ${$('#translation').checked?'':'hidden'}><h4>NEUE ÜBERSETZUNG · HEUTIGES DEUTSCH</h4><blockquote>${esc(s.translation)}</blockquote></div></div><p class="source-question"><strong>Arbeitsfrage:</strong> ${esc(s.question)}</p><details><summary>Grenzen der Quelle prüfen</summary><p>${esc(s.limit)}</p></details><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Originaltext und Fundstelle öffnen ↗</a><p class="small">Historischer Textauszug aus einem gemeinfreien Werk; gegebenenfalls gekürzt, Auslassungen gekennzeichnet. Übersetzung eigens für diese App. Digitale Editionen, redaktionelle Zusätze und Website-Inhalte können eigenen Bedingungen unterliegen.</p>`;changed()}
  $('#source-select').addEventListener('change',e=>{state.source=e.target.value;renderSource()});$('#translation').addEventListener('change',renderSource);document.addEventListener('click',e=>{const b=e.target.closest('[data-source]');if(!b)return;state.source=b.dataset.source;$('#source-select').value=state.source;renderSource();$('#quellenarbeit').scrollIntoView({behavior:state.paused?'auto':'smooth'})});renderSource();
  $('#image-gallery').innerHTML=Object.keys(D.images).map(imageSlot).join('');
  $('#scene-select').innerHTML=options(D.scenes,s=>s.title);$('#scene-select').value=state.scene;
  function timerStop(){if(timer)clearInterval(timer);timer=null;$('#timer-start').textContent='Redezeit starten'}
  function timerPaint(){$('#timer-output').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0')}
  function resetTimer(){timerStop();remaining=Number($('#timer-duration').value);timerPaint();$('#timer-status').textContent=''}
  function castPaint(){if(speaker>=state.cast.length)speaker=0;$('#cast-display').innerHTML=state.cast.map((id,i)=>{const r=role(id);return `<article class="speaker-card ${i===speaker?'current':''}" style="--accent:${r.color}"><strong>${esc(r.name)}</strong><span>${esc(r.question)}</span></article>`}).join('')||'<p>Wählt mindestens eine Stimme aus.</p>';$('#next-speaker').disabled=state.cast.length<2;$('#timer-start').disabled=!state.cast.length;$('#timer-status').textContent=state.cast.length?'Aktuelle Stimme: '+role(state.cast[speaker]).name:'Noch keine Rolle ausgewählt.'}
  function renderScene(){const s=D.scenes.find(x=>x.id===state.scene);$('#scene-brief').innerHTML=`<h3>${esc(s.title)}</h3><p>${esc(s.brief)}</p><p><strong>Konflikt:</strong> ${esc(s.conflict)}</p><p><strong>Auftrag:</strong> ${esc(s.task)}</p><button type="button" data-scene-role="${s.event}">Rollenakten auf diesen Wissensstand einstellen →</button>`;$('#stage-question').textContent=s.question;$('#cast-choices').innerHTML=D.roles.map(r=>`<label><input type="checkbox" value="${r.id}" ${state.cast.includes(r.id)?'checked':''}>${esc(r.name)}</label>`).join('');speaker=0;resetTimer();castPaint();$('#stage-prompt').textContent=D.prompts[promptIndex%D.prompts.length];changed()}
  $('#scene-select').addEventListener('change',e=>{state.scene=e.target.value;state.cast=D.scenes.find(s=>s.id===state.scene).cast.slice();renderScene()});$('#cast-choices').addEventListener('change',()=>{state.cast=$$('#cast-choices input:checked').map(x=>x.value);resetTimer();castPaint();save()});$('#scene-brief').addEventListener('click',e=>{const b=e.target.closest('[data-scene-role]');if(b){state.roleEvent=b.dataset.sceneRole;$('#role-date').value=state.roleEvent;renderRole();$('#rollen').scrollIntoView({behavior:state.paused?'auto':'smooth'})}});
  $('#timer-start').addEventListener('click',()=>{if(timer){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));timerStop();$('#timer-start').textContent='Fortsetzen';return}if(remaining<=0)remaining=Number($('#timer-duration').value);deadline=Date.now()+remaining*1000;$('#timer-start').textContent='Pause';timer=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));timerPaint();if(remaining===0){timerStop();$('#timer-status').textContent='Redezeit vorbei. Gedanken abschließen und die nächste Stimme hören.'}},200)});$('#timer-duration').addEventListener('change',resetTimer);$('#timer-reset').addEventListener('click',resetTimer);$('#next-speaker').addEventListener('click',()=>{speaker=(speaker+1)%state.cast.length;resetTimer();castPaint()});$('#prompt-next').addEventListener('click',()=>{$('#stage-prompt').textContent=D.prompts[++promptIndex%D.prompts.length]});renderScene();
  const stage=$('#stage-board');async function exitStage(){if(document.fullscreenElement){try{await document.exitFullscreen()}catch{}}stage.classList.remove('stage-expanded');$('#stage-exit').hidden=true;document.body.style.overflow=''}$('#stage-fullscreen').addEventListener('click',async()=>{try{if(!stage.requestFullscreen)throw new Error('fallback');await stage.requestFullscreen();$('#stage-exit').hidden=false}catch{stage.classList.add('stage-expanded');$('#stage-exit').hidden=false;document.body.style.overflow='hidden'}});$('#stage-exit').addEventListener('click',exitStage);document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)$('#stage-exit').hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&stage.classList.contains('stage-expanded'))exitStage()});
  $('#concept-tabs').innerHTML=D.concepts.map(c=>`<button type="button" data-concept="${c.id}" aria-pressed="${state.concept===c.id}">${esc(c.name)}</button>`).join('');function renderConcept(){const c=D.concepts.find(x=>x.id===state.concept);$('#concept-card').innerHTML=`<h3>${esc(c.question)}</h3><p>${esc(c.text)}</p><div class="concept-voices">${c.voices.map(([who,says])=>`<blockquote>${esc(says)}<cite>Didaktische Fallstimme · ${esc(who)}</cite></blockquote>`).join('')}</div><p><strong>Gesprächsauftrag:</strong> ${esc(c.task)}</p>`;$$('[data-concept]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.concept===c.id)));changed()}$('#concept-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-concept]');if(b){state.concept=b.dataset.concept;renderConcept()}});renderConcept();
  $('#legacy-grid').innerHTML=D.legacy.map(([h,t])=>`<article><h3>${esc(h)}</h3><p>${esc(t)}</p></article>`).join('');$('#glossary').innerHTML=`<h3>Begriffe zum Nachschlagen</h3><dl class="glossary-grid">${D.glossary.map(([t,d])=>`<div><dt>${esc(t)}</dt><dd>${esc(d)}</dd></div>`).join('')}</dl>`;$('#references').innerHTML=D.references.map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`).join('');
  $('#judgment-criterion').value=state.criterion;$('#judgment-period').value=state.period;for(const [id,prop]of [['judgment-criterion','criterion'],['judgment-period','period']])$('#'+id).addEventListener('change',e=>{state[prop]=e.target.value;changed()});
  $('#reset-app').addEventListener('click',()=>$('#reset-dialog').showModal());$('#reset-dialog').addEventListener('close',async()=>{if($('#reset-dialog').returnValue!=='reset')return;timerStop();await exitStage();try{localStorage.removeItem(storageKey)}catch{}location.reload()});
  window.RevolutionApp={consent:()=>state.consent,setConsent(value){state.consent=value;save()},escape:esc};
  restoreNotes();save();
})();
