/* Original instructional text. Formula conventions match the local solver. */
window.QMLessons={
  hamilton:[
    {title:'1 · Mit der klassischen Energie beginnen',html:String.raw`<p>Für ein Teilchen ohne Magnetfeld schreiben wir kinetische plus potentielle Energie:</p><div class="formula">\[H(x,p)=\frac{p^2}{2m}+V(x).\]</div><p>m ist die Masse, p der Impuls. V(x) legt fest, welche potentielle Energie das Teilchen am Ort x hätte. Wir brauchen also zuerst ein Modell für V.</p>`},
    {title:'2 · Den Impuls als Operator schreiben',html:String.raw`<p>In der Ortsdarstellung gilt die quantenmechanische Zuordnung:</p><div class="formula">\[\hat p=-i\hbar\frac{d}{dx},\qquad i^2=-1.\]</div><p>Auf eine Funktion angewendet heißt das: erst ableiten, dann mit −iℏ multiplizieren. Das ist kein Zahlenwert für den Impuls des Teilchens.</p>`},
    {title:'3 · Zweimal anwenden, nicht einmal',html:String.raw`<div class="formula">\[\hat p^2\psi=(-i\hbar)\frac d{dx}\left[(-i\hbar)\frac{d\psi}{dx}\right]=(-i)^2\hbar^2\psi''=-\hbar^2\psi''.\]</div><p>ℏ ist konstant und kann vor die Ableitung. Wegen (−i)² = −1 entsteht das Minuszeichen. ψ″ bedeutet die zweite Ortsableitung, also die Krümmung.</p>`},
    {title:'4 · Kinetische und potentielle Energie zusammensetzen',html:String.raw`<div class="formula">\[\hat T=-\frac{\hbar^2}{2m}\frac{d^2}{dx^2},\qquad \hat V\psi=V(x)\psi(x)\]</div><div class="formula">\[\boxed{\hat H=-\frac{\hbar^2}{2m}\frac{d^2}{dx^2}+V(x)}\]</div><p>Das Potential wirkt hier durch Multiplikation. Die kinetische Energie wirkt durch Ableiten. Wir wenden beide Teile auf dieselbe Wellenfunktion an und addieren.</p>`},
    {title:'5 · Das Eigenwertproblem stellen',html:String.raw`<div class="formula">\[\boxed{-\frac{\hbar^2}{2m}\psi''(x)+V(x)\psi(x)=E\psi(x)}\]</div><p>Gesucht sind gleichzeitig die Funktion ψ und die Zahl E. E ist an jedem Ort dieselbe Gesamtenergie. Die Funktion muss die Randbedingungen erfüllen und bei gebundenen Zuständen normierbar sein. Das ist die zeitunabhängige Schrödingergleichung.</p><p><strong>Einheitencheck:</strong> ℏ²/m hat die Einheit Energie · Länge²; die zweite Ableitung liefert Länge⁻². Jeder Summand hat damit die Einheit Energie · ψ.</p>`}
  ],
  box:[
    {title:'1 · Im Inneren V = 0 einsetzen',html:String.raw`<p>Im Intervall 0 &lt; x &lt; L ist die potentielle Energie null. Daher bleibt:</p><div class="formula">\[-\frac{\hbar^2}{2m}\psi''=E\psi.\]</div><p>Die unendlich hohen Wände werden als Randbedingungen ψ(0) = ψ(L) = 0 behandelt. Wir rechnen nicht mit dem undefinierten Produkt „∞ · 0“.</p>`},
    {title:'2 · Die zweite Ableitung allein stellen',html:String.raw`<p>Multipliziere beide Seiten mit −2m/ℏ²:</p><div class="formula">\[\psi''=-\frac{2mE}{\hbar^2}\psi.\]</div><p>Für E &gt; 0 nennen wir den positiven Faktor k²:</p><div class="formula">\[k^2=\frac{2mE}{\hbar^2},\qquad\psi''=-k^2\psi.\]</div><p>k hat die Einheit 1/Länge. Wir werden erst später bestimmen, welche Werte k annehmen darf.</p>`},
    {title:'3 · Welche Funktion liefert bei zweimaligem Ableiten ein Minuszeichen?',html:String.raw`<p>Versuche ψ(x) = sin(kx). Bei jeder Ableitung kommt wegen der Kettenregel ein Faktor k dazu:</p><div class="formula">\[\frac d{dx}\sin(kx)=k\cos(kx)\]</div><div class="formula">\[\frac{d^2}{dx^2}\sin(kx)=-k^2\sin(kx).\]</div><p>Auch cos(kx) erfüllt dieselbe Gleichung: erst −k sin(kx), dann −k² cos(kx). Beide Grundformen passen.</p>`},
    {title:'4 · Warum die allgemeine Lösung zwei Konstanten enthält',html:String.raw`<div class="formula">\[\psi(x)=A\sin(kx)+B\cos(kx).\]</div><p>Die Gleichung ist linear: Eine Summe der beiden Lösungen ist wieder eine Lösung. Eine Differentialgleichung zweiter Ordnung hat hier zwei unabhängige Grundlösungen; A und B werden durch die beiden Randbedingungen und anschließend die Normierung festgelegt.</p>`},
    {title:'5 · Die linke Wand anwenden',html:String.raw`<div class="formula">\[0=\psi(0)=A\sin(0)+B\cos(0)=0+B.\]</div><p>Also B = 0. Damit bleibt:</p><div class="formula">\[\psi(x)=A\sin(kx).\]</div><p>Die Cosinusform allein scheitert an der linken Wand, weil cos(0) = 1 ist.</p>`},
    {title:'6 · Die rechte Wand anwenden',html:String.raw`<div class="formula">\[0=\psi(L)=A\sin(kL).\]</div><p>A = 0 würde überall ψ = 0 ergeben. Diese Funktion kann nicht auf Wahrscheinlichkeit 1 normiert werden und ist kein Zustand. Also muss gelten:</p><div class="formula">\[\sin(kL)=0\quad\Longrightarrow\quad kL=n\pi.\]</div><p>Die Nullstellen des Sinus liegen bei ganzzahligen Vielfachen von π.</p>`},
    {title:'7 · Die erlaubten Wellenzahlen auswählen',html:String.raw`<div class="formula">\[k_n=\frac{n\pi}{L},\qquad n=1,2,3,\ldots\]</div><p>n = 0 liefert bei diesem Ansatz wieder die Nullfunktion. Negative n erzeugen nur das entgegengesetzte Vorzeichen derselben Raumform und keine zusätzliche Energie.</p><p><strong>Der Fall E = 0 muss extra geprüft werden:</strong> Dann ist ψ″ = 0, also ψ = ax + b. Beide Randbedingungen erzwingen a = b = 0. Für E &lt; 0 bestehen die Lösungen aus exponentiellen beziehungsweise hyperbolischen Funktionen; auch sie können hier nicht beide Nullränder erfüllen, ohne überall null zu sein.</p>`},
    {title:'8 · Von k zurück zur Energie',html:String.raw`<p>Aus der Definition k² = 2mE/ℏ² folgt nach Umstellen:</p><div class="formula">\[E=\frac{\hbar^2k^2}{2m}.\]</div><p>Jetzt kₙ = nπ/L einsetzen:</p><div class="formula">\[\boxed{E_n=\frac{n^2\pi^2\hbar^2}{2mL^2}=\frac{n^2h^2}{8mL^2}}.\]</div><p>Die Randbedingungen wählen die Wellenzahlen aus. Weil E von k² abhängt, wählen sie zugleich die Energien aus. Das ist Quantisierung.</p>`},
    {title:'9 · Die Größe A aus der Normierung bestimmen',html:String.raw`<p>Innerhalb des Kastens muss die gesamte Wahrscheinlichkeit 1 sein:</p><div class="formula">\[1=\int_0^L|\psi_n|^2dx=|A|^2\int_0^L\sin^2\left(\frac{n\pi x}{L}\right)dx.\]</div><p>Mit sin²u = (1 − cos(2u))/2 wird das Integral:</p><div class="formula">\[\left[\frac x2-\frac{L}{4n\pi}\sin\left(\frac{2n\pi x}{L}\right)\right]_0^L=\frac L2.\]</div><p>Die Sinusterme an beiden Grenzen sind null. Also |A|²L/2 = 1 und |A| = √(2/L).</p>`},
    {title:'10 · Die fertige Eigenfunktion',html:String.raw`<p>Eine globale Phase können wir frei wählen. Wir nehmen A positiv und reell:</p><div class="formula">\[\boxed{\psi_n(x)=\sqrt{\frac2L}\sin\left(\frac{n\pi x}{L}\right)}\quad(0&lt;x&lt;L).\]</div><p>Außerhalb ist ψₙ = 0. Im Inneren gibt es n − 1 Knoten, an denen ψ und die Dichte null sind. Das Vorzeichen wechselt von Bauch zu Bauch; die Dichte bleibt überall nichtnegativ.</p>`},
    {title:'11 · Noch einmal wirklich in die Gleichung einsetzen',html:String.raw`<div class="formula">\[\psi_n''=-\left(\frac{n\pi}{L}\right)^2\psi_n\]</div><div class="formula">\[-\frac{\hbar^2}{2m}\psi_n''=\frac{\hbar^2n^2\pi^2}{2mL^2}\psi_n=E_n\psi_n.\]</div><p>Damit sind die Differentialgleichung, beide Randbedingungen und die Normierung geprüft. Erst alle drei zusammen machen aus dem Sinus eine erlaubte Eigenfunktion.</p>`},
    {title:'12 · Was die Lösung bedeutet',html:String.raw`<p>E₁ ist größer als null. Das Teilchen kann in diesem Kasten keinen Zustand mit E = 0 haben. Bei halbem L vervierfacht sich jede Energie; bei doppelter Masse halbiert sie sich.</p><p>Die Dichte lautet:</p><div class="formula">\[|\psi_n(x)|^2=\frac2L\sin^2\left(\frac{n\pi x}{L}\right).\]</div><p>Mit einem Energieeigenwert ist nicht gleichzeitig ein genauer Ort festgelegt. Nutze oben das markierte Intervall, um die Wahrscheinlichkeit durch Integration zu bestimmen.</p>`}
  ],
  well:[
    {title:'1 · Drei Bereiche, eine Energie',html:String.raw`<p>Links: x &lt; −a. Innen: −a &lt; x &lt; a. Rechts: x &gt; a. E ist in allen drei Bereichen dieselbe Gesamtenergie. Für einen gebundenen Zustand setzen wir 0 &lt; E &lt; V₀.</p><div class="formula">\[\psi''=\frac{2m}{\hbar^2}(V-E)\psi.\]</div><p>Das Vorzeichen von V − E entscheidet, ob die Grundlösungen oszillieren oder exponentiell verlaufen.</p>`},
    {title:'2 · Im Inneren: wie zuvor Sinus und Cosinus',html:String.raw`<div class="formula">\[\psi''=-k^2\psi,\qquad k=\frac{\sqrt{2mE}}{\hbar}.\]</div><div class="formula">\[\psi_\mathrm{innen}=A\cos(kx)+B\sin(kx).\]</div><p>Wir haben den Koordinatenursprung in die Topfmitte gelegt. Weil V(−x) = V(x), können die nichtentarteten gebundenen Zustände gerade oder ungerade gewählt werden: Cosinus oder Sinus.</p>`},
    {title:'3 · Außen: das Vorzeichen wechselt',html:String.raw`<div class="formula">\[\psi''=\kappa^2\psi,\qquad\kappa=\frac{\sqrt{2m(V_0-E)}}{\hbar}.\]</div><p>Prüfe ψ = e^{κx}: erst ψ′ = κe^{κx}, dann ψ″ = κ²e^{κx}. Ebenso erfüllt e^{−κx} die Gleichung. Die allgemeine äußere Lösung enthält beide Exponentialformen.</p>`},
    {title:'4 · Wachsende Ausläufer ausschließen',html:String.raw`<p>Eine gebundene Wellenfunktion muss auf der ganzen Achse normierbar sein. Rechts verbieten wir e^{+κx}, links e^{−κx}, weil diese nach außen wachsen.</p><div class="formula">\[\psi_\mathrm{links}=C_L e^{\kappa(x+a)},\qquad\psi_\mathrm{rechts}=C_R e^{-\kappa(x-a)}.\]</div><p>So sind C_L und C_R direkt die Werte an den Rändern. Die Ausläufer fallen auf der Längenskala 1/κ ab.</p>`},
    {title:'5 · Was am Rand stetig sein muss',html:String.raw`<p>Bei einem endlichen Potentialsprung ohne Delta-Potential sind ψ und ψ′ stetig. Integriert man die Schrödingergleichung über ein immer kleineres Intervall um den Rand, verschwindet das Integral der endlichen rechten Seite: Es bleibt kein Sprung in ψ′.</p><div class="formula">\[\psi_\mathrm{innen}(a)=\psi_\mathrm{rechts}(a),\qquad\psi'_\mathrm{innen}(a)=\psi'_\mathrm{rechts}(a).\]</div><p>Anders als beim unendlichen Kasten gilt am Rand also nicht ψ = 0.</p>`},
    {title:'6 · Gerade Zustände anschließen',html:String.raw`<p>Innen ψ = A cos(kx), rechts ψ = C e^{−κ(x−a)}. Werte und Ableitungen bei x = a:</p><div class="formula">\[A\cos(ka)=C,\qquad-Ak\sin(ka)=-\kappa C.\]</div><p>Setze C aus der ersten in die zweite Gleichung ein und teile durch A cos(ka):</p><div class="formula">\[\boxed{k\tan(ka)=\kappa}.\]</div><p>Diese Gleichung bestimmt die erlaubten geraden Energieeigenwerte. Links ist der Anschluss aufgrund der Symmetrie ebenfalls erfüllt.</p>`},
    {title:'7 · Ungerade Zustände anschließen',html:String.raw`<p>Innen ψ = A sin(kx). An x = a folgt:</p><div class="formula">\[A\sin(ka)=C,\qquad Ak\cos(ka)=-\kappa C.\]</div><p>C ersetzen und durch A sin(ka) teilen:</p><div class="formula">\[\boxed{-k\cot(ka)=\kappa}.\]</div><p>Links trägt der Ausläufer bei ungeraden Zuständen das entgegengesetzte Vorzeichen. Gerade und ungerade Formen wechseln sich mit steigender Energie ab.</p>`},
    {title:'8 · Warum wir hier numerisch lösen',html:String.raw`<p>Setze z = ka und z₀ = a√(2mV₀)/ℏ. Dann ist κa = √(z₀² − z²):</p><div class="formula">\[z\tan z=\sqrt{z_0^2-z^2}\quad\text{oder}\quad-z\cot z=\sqrt{z_0^2-z^2}.\]</div><p>z steht gleichzeitig innerhalb einer Winkelfunktion und außerhalb. Die Wurzeln berechnen wir numerisch im Bereich 0 &lt; z &lt; z₀. Das Labor benutzt eine äquivalente, stetige Phasenbedingung, damit Polstellen nicht als Lösungen verwechselt werden:</p><div class="formula">\[z+\arcsin(z/z_0)=(j+1)\pi/2,\quad j=0,1,2,\ldots\]</div><p>Danach E = ℏ²z²/(2ma²). Ein Kandidat mit E = V₀ ist kein normierbarer gebundener Zustand.</p>`},
    {title:'9 · Innen und außen gemeinsam normieren',html:String.raw`<p>Schreibe innen A f(x), mit f(x) = cos(kx) beziehungsweise sin(kx). Beide Ausläufer müssen in die Normierung:</p><div class="formula">\[1=A^2\left(\int_{-a}^{a} f^2(x)\,dx+\frac{f^2(a)}{\kappa}\right).\]</div><p>Jeder äußere Bereich liefert f²(a)/(2κ). Das innere Integral ist a + sin(2ka)/(2k) für Cosinus und a − sin(2ka)/(2k) für Sinus. A ist der Kehrwert der Quadratwurzel der Summe.</p><div class="formula">\[P_\mathrm{außen}=A^2\frac{f^2(a)}{\kappa}.\]</div>`},
    {title:'10 · Endlich viele gebundene Zustände',html:String.raw`<p>Ein tieferer oder breiterer Topf lässt mehr gebundene Zustände zu. Dieser eindimensionale attraktive Topf hat schon bei kleiner positiver Tiefe einen geraden gebundenen Grundzustand; höhere Zustände können fehlen.</p><p>Für E ≥ V₀ gibt es zusätzlich ungebundene Streuzustände; sie sind nicht Teil der Auswahl im Labor. Die Ausläufer eines gebundenen Zustands liegen im klassisch verbotenen Bereich. Sie allein bedeuten nicht, dass das Teilchen aus dem Topf herausflieht; ein Tunnelprozess durch eine endliche Barriere ist ein anderes Problem.</p>`}
  ],
  oscillator:[
    {title:'1 · Die Parabel einsetzen',html:String.raw`<div class="formula">\[-\frac{\hbar^2}{2m}\psi''+\frac12m\omega^2x^2\psi=E\psi.\]</div><p>Der Ursprung liegt am Potentialminimum. Anders als beim Kasten sind die Ränder nicht zwei Wände. Wir verlangen Normierbarkeit auf −∞ &lt; x &lt; ∞.</p>`},
    {title:'2 · Eine passende Längenskala wählen',html:String.raw`<p>Setze ℓ = √(ℏ/(mω)) und die dimensionslose Koordinate ξ = x/ℓ. Wegen der Kettenregel:</p><div class="formula">\[\frac d{dx}=\frac1\ell\frac d{d\xi},\qquad\frac{d^2}{dx^2}=\frac1{\ell^2}\frac{d^2}{d\xi^2}.\]</div><p>Schreibe außerdem ε = 2E/(ℏω). Nach Division durch ℏω/2 wird die Gleichung:</p><div class="formula">\[\psi_{\xi\xi}+(\varepsilon-\xi^2)\psi=0.\]</div>`},
    {title:'3 · Zuerst den Grundzustand versuchen',html:String.raw`<p>Für große |ξ| brauchen wir eine abklingende Funktion. Versuche eine Gaußform:</p><div class="formula">\[\psi_0=C e^{-\xi^2/2},\qquad\psi_0'=-\xi\psi_0.\]</div><p>Noch einmal ableiten – jetzt mit Produktregel:</p><div class="formula">\[\psi_0''=-\psi_0-\xi\psi_0'= (\xi^2-1)\psi_0.\]</div><p>Einsetzen ergibt (ε − 1)ψ₀ = 0. Daher ε = 1 und E₀ = ℏω/2. Der normierbare Grundzustand besitzt also Nullpunktsenergie.</p>`},
    {title:'4 · Mehr Formen zulassen',html:String.raw`<p>Für die angeregten Zustände ergänzen wir die Gaußfunktion um eine noch unbekannte Funktion u:</p><div class="formula">\[\psi(\xi)=u(\xi)e^{-\xi^2/2}.\]</div><p>Mit der Produktregel:</p><div class="formula">\[\psi'=(u'-\xi u)e^{-\xi^2/2}\]</div><div class="formula">\[\psi''=\left[u''-2\xi u'+(\xi^2-1)u\right]e^{-\xi^2/2}.\]</div><p>Alle Ableitungen in diesem Schritt sind nach ξ, nicht nach x.</p>`},
    {title:'5 · Der Gaußfaktor kürzt sich heraus',html:String.raw`<p>Setze die zweite Ableitung in ψ″ + (ε − ξ²)ψ = 0 ein:</p><div class="formula">\[\left[u''-2\xi u'+(\xi^2-1)u+(\varepsilon-\xi^2)u\right]e^{-\xi^2/2}=0.\]</div><p>Die ξ²u-Terme heben sich auf. Da der Gaußfaktor für endliche ξ nicht null ist:</p><div class="formula">\[u''-2\xi u'+(\varepsilon-1)u=0.\]</div>`},
    {title:'6 · Eine Potenzreihe ansetzen',html:String.raw`<p>Eine Potenzreihe ist eine Summe aus immer höheren Potenzen. Wir setzen:</p><div class="formula">\[u(\xi)=\sum_{j=0}^{\infty}c_j\xi^j.\]</div><p>Nach Ableiten und Verschieben des Summenindex:</p><div class="formula">\[u''=\sum_{j=0}^{\infty}(j+2)(j+1)c_{j+2}\xi^j,\qquad\xi u'=\sum_{j=0}^{\infty}j c_j\xi^j.\]</div><p>Damit schreiben wir alle Summanden in derselben Potenz ξʲ. So lassen sich ihre Koeffizienten vergleichen.</p>`},
    {title:'7 · Die Rekursion gewinnen',html:String.raw`<p>Der Koeffizient vor jeder Potenz muss null sein:</p><div class="formula">\[(j+2)(j+1)c_{j+2}+(\varepsilon-1-2j)c_j=0.\]</div><div class="formula">\[\boxed{c_{j+2}=\frac{2j+1-\varepsilon}{(j+2)(j+1)}c_j}.\]</div><p>Aus c₀ entstehen die geraden Potenzen, aus c₁ die ungeraden. Die Energie steckt in ε und bestimmt alle folgenden Koeffizienten mit.</p>`},
    {title:'8 · Warum die Reihe abbrechen muss',html:String.raw`<p>Für große j nähert sich die Rekursion c_{j+2} ≈ (2/j)c_j. Eine nicht abbrechende Paritätsreihe wächst asymptotisch wie e^{ξ²}; mit dem Gaußfaktor bleibt Wachstum wie e^{ξ²/2} übrig.</p><p>Durch Mischen der geraden und ungeraden Lösungen kann man nicht das Wachstum an beiden Enden gleichzeitig entfernen. Für eine auf der ganzen Achse normierbare Lösung brauchen wir ein Polynom: Der Zähler muss bei j = n null werden.</p><div class="formula">\[2n+1-\varepsilon=0\quad\Longrightarrow\quad\varepsilon=2n+1.\]</div><p>Hier beginnt n bei 0, nicht bei 1 wie im Kasten.</p>`},
    {title:'9 · Das Energiespektrum',html:String.raw`<div class="formula">\[\frac{2E_n}{\hbar\omega}=2n+1\quad\Longrightarrow\quad\boxed{E_n=(n+\tfrac12)\hbar\omega},\qquad n=0,1,2,\ldots\]</div><p>Alle Nachbarabstände sind ℏω. Der Grundzustand hat ½ℏω. Im Kasten stiegen die Energien mit n²; hier steigen sie linear mit n.</p>`},
    {title:'10 · Die Polynome und die normierten Funktionen',html:String.raw`<p>Die abbrechenden Polynome heißen Hermite-Polynome (physikalische Konvention):</p><div class="formula">\[H_0=1,\quad H_1=2\xi,\quad H_2=4\xi^2-2,\quad H_{n+1}=2\xi H_n-2nH_{n-1}.\]</div><div class="formula">\[\boxed{\psi_n(x)=\frac{H_n(x/\ell)e^{-x^2/(2\ell^2)}}{\sqrt{2^n n!}\,\pi^{1/4}\sqrt\ell}}.\]</div><p>Die Normierung folgt aus ∫Hₙ²(ξ)e^{−ξ²}dξ = √π · 2ⁿn! und dx = ℓdξ. Im Labor wird die dimensionslose Funktion φₙ(ξ) = √ℓ ψₙ(x) dargestellt.</p>`},
    {title:'11 · Die Physik der Schwingung',html:String.raw`<p>ψₙ hat n innere Knoten. Ein Eigenzustand zeigt keine periodisch bewegte Aufenthaltswolke. Seine Dichte ist stationär. Die klassische Analogie wäre eine Masse zwischen zwei Umkehrpunkten – das ist nicht das, was die gezeichnete ψ-Kurve zeigt.</p><div class="formula">\[V(x_\mathrm{U})=E_n\quad\Longrightarrow\quad x_\mathrm{U}=\pm\ell\sqrt{2n+1}.\]</div><p>Jenseits der klassischen Umkehrpunkte bleibt eine quantenmechanische Wahrscheinlichkeit. Die Nullpunktsenergie ist kein Energieverlust durch Reibung.</p>`}
  ],
  hydrogen:[
    {title:'1 · Das Ein-Elektronen-Problem festlegen',html:String.raw`<p>Für die relative Koordinate von Elektron und Proton gilt μ = mₑmₚ/(mₑ + mₚ). Der Schwerpunktsanteil lässt sich abtrennen; wir untersuchen die innere Bewegung.</p><div class="formula">\[\left[-\frac{\hbar^2}{2\mu}\nabla^2-\frac{e^2}{4\pi\varepsilon_0r}\right]\psi=E\psi.\]</div><p>Gebundene Zustände haben E &lt; 0 bei Nullpotential im unendlichen Abstand. Die Coulombkonstante kürzen wir als g = e²/(4πε₀) ab.</p>`},
    {title:'2 · Kugelkoordinaten wählen',html:String.raw`<p>Das Potential hängt nur vom Abstand r ab. Deshalb verwenden wir r, Polarwinkel θ und Azimutwinkel φ:</p><div class="formula">\[\nabla^2=\frac1{r^2}\frac\partial{\partial r}\left(r^2\frac\partial{\partial r}\right)+\frac1{r^2\sin\theta}\frac\partial{\partial\theta}\left(\sin\theta\frac\partial{\partial\theta}\right)+\frac1{r^2\sin^2\theta}\frac{\partial^2}{\partial\varphi^2}.\]</div><p>Das Volumenelement ist d³r = r²sinθ dr dθ dφ. Es muss bei der Normierung mitgeführt werden.</p>`},
    {title:'3 · Radial- und Winkelanteil trennen',html:String.raw`<p>Setze ψ = R(r)Y(θ,φ), multipliziere die Eigenwertgleichung mit −2μr²/ℏ² und teile durch RY. Dann steht eine reine r-Funktion plus eine reine Winkel-Funktion gleich null.</p><div class="formula">\[\frac1R\frac d{dr}(r^2R')+\frac{2\mu r^2}{\hbar^2}(E+g/r)+\frac1Y\Delta_\Omega Y=0.\]</div><p>Beide Seiten müssen Konstanten sein. Wir schreiben die Winkelkonstante −l(l + 1):</p><div class="formula">\[\Delta_\Omega Y=-l(l+1)Y.\]</div><p>Warum l ganzzahlig wird, folgt aus den regulären Winkel-Lösungen im nächsten Schritt, nicht aus bloßem Umbenennen der Konstante.</p>`},
    {title:'4 · Den Azimutwinkel lösen',html:String.raw`<p>Mit Y = Θ(θ)Φ(φ) lässt sich der Winkelteil erneut trennen:</p><div class="formula">\[\Phi''+m_\ell^2\Phi=0,\qquad\Phi(\varphi)=e^{im_\ell\varphi}.\]</div><p>Nach einem vollen Umlauf muss dieselbe räumliche Wellenfunktion vorliegen: Φ(φ + 2π) = Φ(φ). Daher e^{2πimₗ} = 1 und mₗ ist ganzzahlig. mₗ ist hier eine magnetische Quantenzahl, nicht die Teilchenmasse.</p>`},
    {title:'5 · Den Polarwinkel lösen und normieren',html:String.raw`<p>Für Θ bleibt die zugeordnete Legendre-Gleichung:</p><div class="formula">\[\frac1{\sin\theta}\frac d{d\theta}(\sin\theta\,\Theta')+\left[l(l+1)-\frac{m_\ell^2}{\sin^2\theta}\right]\Theta=0.\]</div><p>Mit t = cosθ wird sie (1 − t²)Θ_{tt} − 2tΘ_t + [l(l + 1) − mₗ²/(1 − t²)]Θ = 0. Reguläre, einwertige Lösungen an beiden Polen erfordern l = 0, 1, 2, … und |mₗ| ≤ l.</p><div class="formula">\[P_l(t)=\frac1{2^l l!}\frac{d^l}{dt^l}(t^2-1)^l,\qquad P_l^q(t)=(-1)^q(1-t^2)^{q/2}\frac{d^qP_l}{dt^q},\quad q\ge0.\]</div><div class="formula">\[Y_{lq}=\sqrt{\frac{2l+1}{4\pi}\frac{(l-q)!}{(l+q)!}}\,P_l^q(\cos\theta)e^{iq\varphi},\qquad Y_{l,-q}=(-1)^qY_{lq}^*.\]</div><p>Die Normierung ist ∫|Y|²dΩ = 1; sie folgt aus ∫_{−1}^1[Pₗ^q(t)]²dt = 2(l + q)!/[(2l + 1)(l − q)!] und dem φ-Integral 2π. Das sind Kugelflächenfunktionen. Reelle Orbitale entstehen durch geeignete Kombinationen der ±q-Lösungen.</p>`},
    {title:'6 · Die Radialgleichung vereinfachen',html:String.raw`<div class="formula">\[-\frac{\hbar^2}{2\mu}\left(R''+\frac2rR'-\frac{l(l+1)}{r^2}R\right)-\frac grR=ER.\]</div><p>Setze u(r) = rR(r). Aus R = u/r folgt R″ + 2R′/r = u″/r. Nach Multiplikation mit r:</p><div class="formula">\[-\frac{\hbar^2}{2\mu}u''+\left[\frac{\hbar^2l(l+1)}{2\mu r^2}-\frac gr\right]u=Eu.\]</div><p>Die radiale Normierung lautet jetzt ∫₀^∞|u|²dr = 1. Die physikalische Lösung ist am Ursprung regulär und im Unendlichen abklingend.</p>`},
    {title:'7 · Energie und Abstand dimensionslos machen',html:String.raw`<p>Für E &lt; 0 setze κ = √(−2μE)/ℏ, ρ = 2κr und aμ = ℏ²/(μg) = 4πε₀ℏ²/(μe²). Definiere η = 1/(κaμ).</p><div class="formula">\[u_{\rho\rho}+\left[-\frac14+\frac\eta\rho-\frac{l(l+1)}{\rho^2}\right]u=0.\]</div><p>Für große ρ liefert die abklingende Grundform e^{−ρ/2}; nahe null liefert der reguläre Zweig ρ^{l+1}. Der andere Zweig ρ^{−l} wird wegen der Ursprungsbedingungen verworfen.</p>`},
    {title:'8 · Beide Randverhalten in einen Ansatz einbauen',html:String.raw`<p>Setze u = ρ^{l+1}e^{−ρ/2}v(ρ). Mit w = ρ^{l+1}e^{−ρ/2} gilt:</p><div class="formula">\[\frac{w'}w=\frac{l+1}\rho-\frac12,\qquad\frac{w''}w=\frac{l(l+1)}{\rho^2}-\frac{l+1}\rho+\frac14.\]</div><p>Produktregel: u″ = wv″ + 2w′v′ + w″v. Nach Einsetzen kürzen sich die ρ⁻²- und Konstantterme:</p><div class="formula">\[\rho v''+(2l+2-\rho)v'+(\eta-l-1)v=0.\]</div><p>Dies ist die Gleichung für die verallgemeinerten Laguerre-Polynome, falls die verbleibende Zahl eine passende nichtnegative ganze Zahl wird.</p>`},
    {title:'9 · Die Radialreihe und den Abbruch finden',html:String.raw`<p>Setze v = Σ_{j=0}^∞ cⱼρʲ ein und vergleiche die Koeffizienten vor ρʲ:</p><div class="formula">\[(j+1)(j+2l+2)c_{j+1}+(\eta-l-1-j)c_j=0\]</div><div class="formula">\[c_{j+1}=\frac{j+l+1-\eta}{(j+1)(j+2l+2)}c_j.\]</div><p>Für große j ist das Verhältnis ungefähr 1/j. Eine nicht abbrechende reguläre Reihe wächst wie e^ρ und überwindet den Faktor e^{−ρ/2}. Damit wäre u nicht normierbar. Der Zähler muss bei j = q null sein:</p><div class="formula">\[\eta=q+l+1\equiv n,\qquad q=0,1,2,\ldots\]</div><p>n ≥ 1 und 0 ≤ l ≤ n − 1. v ist nun proportional zu L_{n−l−1}^{2l+1}(ρ).</p>`},
    {title:'10 · Die Energieformel herleiten',html:String.raw`<p>Aus η = 1/(κaμ) = n folgt κ = 1/(naμ). Mit E = −ℏ²κ²/(2μ):</p><div class="formula">\[\boxed{E_n=-\frac{\hbar^2}{2\mu a_\mu^2n^2}=-\frac{\mu e^4}{2(4\pi\varepsilon_0)^2\hbar^2n^2}\approx-\frac{13{,}6\,\mathrm{eV}}{n^2}}.\]</div><p>Im nichtrelativistischen Coulombproblem hängt die Energie nur von n ab. Verschiedene l und mₗ können dieselbe Energie besitzen: Entartung. Für wasserstoffähnliche Ionen kommen Z² in der Energie und aμ/Z als Radiusmaß hinzu.</p>`},
    {title:'11 · Die Radialfunktion explizit normieren',html:String.raw`<p>Da u = rR, hat R die Form ρˡe^{−ρ/2}L_q^{2l+1}(ρ), mit ρ = 2r/(naμ) und q = n − l − 1.</p><div class="formula">\[R_{nl}(r)=\sqrt{\left(\frac2{na_\mu}\right)^3\frac{(n-l-1)!}{2n(n+l)!}}\,e^{-\rho/2}\rho^l L_{n-l-1}^{2l+1}(\rho).\]</div><p>Der Vorfaktor folgt aus ∫₀^∞|R|²r²dr = 1, r²dr = (naμ/2)³ρ²dρ und der Identität:</p><div class="formula">\[\int_0^\infty e^{-\rho}\rho^{2l+2}\left[L_{n-l-1}^{2l+1}(\rho)\right]^2d\rho=\frac{2n(n+l)!}{(n-l-1)!}.\]</div><p>Eine explizite Definition, mit α = 2l + 1, ist L_q^α(ρ) = Σ_{j=0}^q (−1)ʲ · (q + α)!/[(q − j)!(α + j)!j!] · ρʲ. Damit ist die Lösung auch ohne bloßen Verweis auf eine Spezialfunktion vollständig angegeben.</p>`},
    {title:'12 · Winkel- und Radialteil zusammenfügen',html:String.raw`<div class="formula">\[\boxed{\psi_{nlm_\ell}(r,\theta,\varphi)=R_{nl}(r)Y_{lm_\ell}(\theta,\varphi)}\]</div><div class="formula">\[\int|\psi|^2d^3r=\left(\int_0^\infty|R|^2r^2dr\right)\left(\int|Y|^2d\Omega\right)=1.\]</div><p>Im Grundzustand n = 1, l = mₗ = 0 gilt:</p><div class="formula">\[\psi_{100}=\frac{e^{-r/a_\mu}}{\sqrt{\pi a_\mu^3}}.\]</div><p>Ein reelles 2p𝓏-Orbital lautet:</p><div class="formula">\[\psi_{210}=\frac1{4\sqrt{2\pi a_\mu^3}}\frac r{a_\mu}e^{-r/(2a_\mu)}\cos\theta.\]</div><p>Der Faktor cosθ erzeugt zwei Vorzeichenbereiche und einen Winkelknoten in der xy-Ebene. Die radiale Wahrscheinlichkeit P(r)dr ist r²|R(r)|²dr, nicht |R|²dr. Das Wasserstoffproblem ist hier gelöst; viele Elektronen benötigen zusätzliche Näherungen.</p>`}
  ]
};
window.QMQuiz=[
  {q:'Warum ist beim Kasten n = 0 kein erlaubter Zustand?',answers:['Weil dann die Wellenfunktion überall null wäre.','Weil null eine negative Energie wäre.','Weil das Teilchen am Rand ruhen müsste.'],correct:0,why:'Die Nullfunktion lässt sich nicht auf Gesamtwahrscheinlichkeit 1 normieren. Auch die separate E = 0-Lösung ax + b wird durch beide Randbedingungen zur Nullfunktion.'},
  {q:'Der Kasten wird halb so breit. Was geschieht mit E₁?',answers:['E₁ halbiert sich.','E₁ verdoppelt sich.','E₁ vervierfacht sich.'],correct:2,why:'E₁ ist proportional zu 1/L². L/2 liefert den Faktor 4. Die Masse bleibt dabei unverändert.'},
  {q:'ψ ist in einem Bereich negativ. Was bedeutet das?',answers:['Die Ortswahrscheinlichkeit ist negativ.','Die Phase beziehungsweise das Vorzeichen ist anders; |ψ|² bleibt positiv.','Dort ist kein Teilchen möglich.'],correct:1,why:'Für die Ortswahrscheinlichkeit zählt das Betragsquadrat. Das Vorzeichen wird bei Überlagerungen wichtig; es ist keine negative Wahrscheinlichkeit.'},
  {q:'Was muss beim endlichen Potentialsprung stetig sein?',answers:['Nur die Energie, ψ darf springen.','ψ muss am Rand null werden.','ψ und ψ′ sind stetig.'],correct:2,why:'Bei einem endlichen Sprung ohne Delta-Potential gelten beide Anschlussbedingungen. ψ = 0 am Rand ist dagegen die Bedingung des unendlichen Kastens.'},
  {q:'Warum hören wir im Saitenlabor Töne, aber nicht „das Elektron“?',answers:['Der Ton ist eine klassische Analogie; die stationäre Quantendichte schwingt nicht so.','Elektronen hätten genau die Frequenzen einer Gitarrensaite.','Der Lautsprecher löst die Schrödingergleichung.'],correct:0,why:'Die Saite macht die räumlichen Knoten anschaulich. Bei ihr gilt fₙ = nf₁, im Kasten dagegen Eₙ = n²E₁. ψ ist keine mechanische Auslenkung.'},
  {q:'Welche Energieabstände hat der harmonische Oszillator?',answers:['Die Abstände wachsen wie beim Kasten.','Alle Nachbarabstände sind ℏω.','Der Grundzustand hat exakt null Energie.'],correct:1,why:'Eₙ = (n + ½)ℏω beginnt bei n = 0. Der Abstand Eₙ₊₁ − Eₙ ist immer ℏω; E₀ beträgt ½ℏω.'},
  {q:'Welche Rolle spielt die Normierbarkeit?',answers:['Sie legt nur die Farbe der Kurve fest.','Sie ist nur bei klassischen Saiten nötig.','Sie schließt bei gebundenen Zuständen nach außen wachsende Lösungen aus.'],correct:2,why:'Die Gesamtwahrscheinlichkeit muss endlich und auf 1 normierbar sein. Das verwirft wachsende Ausläufer und trägt beim Oszillator und Wasserstoff zur Quantisierung bei.'},
  {q:'Kann die exakte Wasserstofflösung direkt alle Kohlenstofforbitale liefern?',answers:['Ja, nur die Zahl n wird ausgetauscht.','Nein, die Elektronenabstoßung und der Vielteilchenzustand benötigen zusätzliche Behandlung.','Ja, denn alle Atome haben dieselben Eigenwerte.'],correct:1,why:'Die Ein-Elektronen-Coulomblösung ist exakt nur im beschriebenen Modell. Bei mehreren Elektronen kommt der Wechselwirkungsterm zwischen den Elektronen hinzu.'}
];
