(function(){
  'use strict';
  const C=SchroedingerCore,$=id=>document.getElementById(id),fmt=(x,d=3)=>Number(x).toLocaleString('de-DE',{maximumFractionDigits:d,minimumFractionDigits:d});
  // Insert all authored steps once; hidden steps remain available to MathJax.
  document.querySelectorAll('[data-lesson]').forEach(host=>{
    const steps=QMLessons[host.dataset.lesson];let index=0,all=false;
    host.innerHTML='<div class="lesson-heading"><span class="lesson-count"></span><button class="lesson-all" aria-pressed="false">Alle Schritte ansehen</button></div><div class="lesson-progress"><span></span></div><div class="lesson-steps">'+steps.map((s,i)=>'<article class="lesson-step'+(i===0?' active':'')+'"><h3>'+s.title+'</h3>'+s.html+'</article>').join('')+'</div><div class="lesson-nav"><button class="lesson-back">← Schritt zurück</button><button class="lesson-next primary">Nächster Schritt →</button></div>';
    function render(){host.classList.toggle('all',all);host.querySelectorAll('.lesson-step').forEach((el,i)=>el.classList.toggle('active',i===index));host.querySelector('.lesson-count').textContent=all?steps.length+' Schritte · Gesamtansicht':'Schritt '+(index+1)+' von '+steps.length;host.querySelector('.lesson-progress span').style.width=(index+1)/steps.length*100+'%';host.querySelector('.lesson-back').disabled=all||index===0;host.querySelector('.lesson-next').disabled=all||index===steps.length-1;host.querySelector('.lesson-next').textContent=index===steps.length-1?'Herleitung vollständig ✓':'Nächster Schritt →';host.querySelector('.lesson-all').setAttribute('aria-pressed',String(all));host.querySelector('.lesson-all').textContent=all?'Schrittweise ansehen':'Alle Schritte ansehen';}
    host.querySelector('.lesson-next').onclick=()=>{index=Math.min(steps.length-1,index+1);render();};host.querySelector('.lesson-back').onclick=()=>{index=Math.max(0,index-1);render();};host.querySelector('.lesson-all').onclick=()=>{all=!all;render();};render();
  });
  const sidebar=$('sidebar'),mobile=matchMedia('(max-width:900px)');
  function menuState(){const expanded=mobile.matches?sidebar.classList.contains('open'):!document.body.classList.contains('collapsed');$('menu').setAttribute('aria-expanded',String(expanded));}
  $('menu').onclick=()=>{if(mobile.matches)sidebar.classList.toggle('open');else document.body.classList.toggle('collapsed');menuState();};
  $('menu-close').onclick=()=>{sidebar.classList.remove('open');if(!mobile.matches)document.body.classList.add('collapsed');menuState();};
  mobile.addEventListener('change',()=>{sidebar.classList.remove('open');menuState();});menuState();
  document.querySelectorAll('.sidebar nav a').forEach(a=>a.onclick=()=>{if(mobile.matches){sidebar.classList.remove('open');menuState();}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){sidebar.classList.remove('open');menuState();exitFallback();stopSound();}});
  const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)document.querySelectorAll('.sidebar nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+entry.target.id));},{rootMargin:'-10% 0px -65% 0px'});document.querySelectorAll('main>section[id]').forEach(el=>observer.observe(el));
  let dark=matchMedia('(prefers-color-scheme:dark)').matches;try{const saved=localStorage.getItem('schroedinger-theme');if(saved)dark=saved==='dark';}catch(_){}
  function theme(){document.body.classList.toggle('dark',dark);$('theme').setAttribute('aria-pressed',String(dark));$('theme').textContent=dark?'Heller Modus':'Dunkler Modus';}
  $('theme').onclick=()=>{dark=!dark;theme();try{localStorage.setItem('schroedinger-theme',dark?'dark':'light');}catch(_){}};theme();
  let fallback=null;
  function exitFallback(){if(!fallback)return;fallback.classList.remove('fullscreen-fallback');fallback=null;document.body.classList.remove('fallback-open');syncFullscreen();}
  async function fullscreen(target){stopSound();if(fallback){exitFallback();return;}if(document.fullscreenElement){await document.exitFullscreen();return;}try{if(!target.requestFullscreen)throw Error();await target.requestFullscreen();}catch(_){if(target===document.documentElement){$('page-fullscreen').textContent='Vollbild nicht verfügbar';return;}fallback=target;target.classList.add('fullscreen-fallback');document.body.classList.add('fallback-open');}syncFullscreen();}
  function syncFullscreen(){document.querySelectorAll('[data-fullscreen]').forEach(b=>b.textContent=(document.fullscreenElement?.id===b.dataset.fullscreen||fallback?.id===b.dataset.fullscreen)?'Vollbild beenden':'Labor im Vollbild');$('page-fullscreen').textContent=document.fullscreenElement?'Vollbild beenden':'App im Vollbild';}
  document.querySelectorAll('[data-fullscreen]').forEach(b=>b.onclick=()=>fullscreen($(b.dataset.fullscreen)));$('page-fullscreen').onclick=()=>fullscreen(document.documentElement);document.addEventListener('fullscreenchange',syncFullscreen);
  // SVG charts use independent physical vertical axes, never probability-as-energy.
  const p={left:66,right:650,top:42,bottom:183};
  function axes(xmin,xmax,ymin,ymax,title,xlabel,ylabel){
    const X=x=>p.left+(x-xmin)/(xmax-xmin)*(p.right-p.left),Y=y=>p.bottom-(y-ymin)/(ymax-ymin)*(p.bottom-p.top);
    let html='<text x="18" y="23">'+title+'</text><text x="'+p.left+'" y="40" style="font-size:12px">'+ylabel+'</text>';
    for(let i=0;i<5;i++){const y=ymin+(ymax-ymin)*i/4;html+='<line class="grid" x1="'+p.left+'" x2="'+p.right+'" y1="'+Y(y)+'" y2="'+Y(y)+'"/><text x="'+(p.left-8)+'" y="'+(Y(y)+5)+'" text-anchor="end" style="font-size:12px">'+fmt(y,2)+'</text>';}
    for(let i=0;i<5;i++){const x=xmin+(xmax-xmin)*i/4;html+='<text x="'+X(x)+'" y="201" text-anchor="middle" style="font-size:12px">'+fmt(x,2)+'</text>';}
    html+='<line class="axis" x1="'+p.left+'" x2="'+p.right+'" y1="'+p.bottom+'" y2="'+p.bottom+'"/><text x="740" y="217" text-anchor="end" style="font-size:13px">'+xlabel+'</text>';
    return {html,X,Y};
  }
  function path(f,X,Y,min,max,N=500){return Array.from({length:N+1},(_,i)=>{const x=min+(max-min)*i/N;return (i?'L':'M')+X(x).toFixed(2)+','+Y(f(x)).toFixed(2);}).join(' ');}
  function curve(id,f,xmin,xmax,density,xlabel,ylabel,{bounds=[],interval=null}={}){
    let max=0;for(let i=0;i<=800;i++)max=Math.max(max,Math.abs(f(xmin+(xmax-xmin)*i/800)));max=Math.max(max*1.15,1e-5);
    const a=axes(xmin,xmax,density?0:-max,max,density?'Wahrscheinlichkeitsdichte |ψ|²':'Wellenfunktion ψ',xlabel,ylabel);let html=a.html;
    if(interval&&interval[1]>interval[0]){html+='<path class="shade" d="M'+a.X(interval[0])+','+a.Y(0)+' '+path(f,a.X,a.Y,interval[0],interval[1]).replace(/^M/,'L')+' L'+a.X(interval[1])+','+a.Y(0)+' Z"/>';}
    for(const b of bounds)html+='<line class="mark" x1="'+a.X(b)+'" x2="'+a.X(b)+'" y1="'+p.top+'" y2="'+p.bottom+'"/>';
    if(!density)html+='<line class="axis" x1="'+p.left+'" x2="'+p.right+'" y1="'+a.Y(0)+'" y2="'+a.Y(0)+'"/>';
    $(id).innerHTML=html+'<path class="'+(density?'density':'wave')+'" d="'+path(f,a.X,a.Y,xmin,xmax)+'"/>';
  }
  function energies(id,values,selected,xmin,xmax,ceiling,potential,xlabel){
    const a=axes(xmin,xmax,0,ceiling,'Potential und Energieeigenwerte',xlabel,'E / V [eV]');let html=a.html+potential(a);
    for(const state of values){const y=a.Y(state.energy);html+='<g class="energy-choice" tabindex="0" role="button" data-level="'+state.index+'" aria-label="Zustand '+state.label+' mit '+fmt(state.energy)+' Elektronenvolt auswählen"><title>Zustand '+state.label+'</title><line x1="'+(p.left+6)+'" x2="'+p.right+'" y1="'+y+'" y2="'+y+'" stroke="transparent" stroke-width="14"/><line class="energy-line'+(state.index===selected?' selected':'')+'" x1="'+(p.left+6)+'" x2="'+p.right+'" y1="'+y+'" y2="'+y+'"/><text x="'+(p.right+8)+'" y="'+(y+4)+'" style="font-size:12px">'+state.label+'</text></g>';}
    $(id).innerHTML=html;
  }
  function bindLevels(id,input){const click=el=>{if(!el)return;$(input).value=el.dataset.level;$(input).dispatchEvent(new Event('input'));};$(id).addEventListener('click',event=>click(event.target.closest('[data-level]')));$(id).addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();click(event.target.closest('[data-level]'));}});}
  function box(){const n=+$('box-n').value,L=+$('box-L').value,m=+$('box-m').value,state=C.box(n,L,m);$('box-n-out').value=n;$('box-L-out').value=fmt(L,2);let lo=+$('box-from').value,hi=+$('box-to').value;const reversed=lo>hi;[lo,hi]=[Math.min(lo,hi),Math.max(lo,hi)];
    $('box-result').innerHTML='<b>E'+n+' = '+fmt(state.energy,4)+' eV</b>λ = '+fmt(state.lambda)+' nm · '+(n-1)+' innere Knoten';
    energies('box-energy',Array.from({length:6},(_,i)=>({index:i+1,label:'n='+ (i+1),energy:C.box(i+1,L,m).energy})),n,0,L,C.box(6,L,m).energy*1.13,a=>'<path class="potential" d="M'+a.X(0)+','+a.Y(C.box(6,L,m).energy*1.1)+' V'+a.Y(0)+' H'+a.X(L)+' V'+a.Y(C.box(6,L,m).energy*1.1)+'"/><text x="'+(a.X(0)+18)+'" y="52" style="font-size:14px">∞</text><text x="'+(a.X(L)-18)+'" y="52" text-anchor="end" style="font-size:14px">∞</text>','x [nm]');
    curve('box-wave',state.psi,0,L,false,'x [nm]','ψ [nm⁻¹ᐟ²]');curve('box-density',state.density,0,L,true,'x [nm]','|ψ|² [nm⁻¹]',{interval:[lo*L,hi*L]});$('box-probability').value='P = '+fmt(100*state.probability(lo,hi),2)+' % für '+fmt(lo,2)+' ≤ x/L ≤ '+fmt(hi,2)+(reversed?' (Grenzen sortiert)':'');
  }
  let wellStates=[];
  function well(rebuild=true){const width=+$('well-width').value,depth=+$('well-depth').value,old=+$('well-state').value||0;wellStates=C.finiteWell(width,depth);if(rebuild){$('well-state').replaceChildren(...wellStates.map((s,i)=>new Option('Zustand '+(i+1)+' · '+(s.even?'gerade':'ungerade'),String(i))));$('well-state').value=Math.min(old,wellStates.length-1);}const index=+$('well-state').value,state=wellStates[index],a=width/2,extent=a+Math.min(5*width,Math.max(1.5*width,6/state.kappa));$('well-width-out').value=fmt(width,2)+' nm';$('well-depth-out').value=fmt(depth,2)+' eV';$('well-result').innerHTML='<b>'+wellStates.length+' gebundene '+(wellStates.length===1?'Form':'Formen')+'</b>E = '+fmt(state.energy,4)+' eV<br>P außen = '+fmt(state.outside*100,2)+' %<br>Ausläuferlänge 1/κ = '+fmt(1/state.kappa)+' nm';
    energies('well-energy',wellStates.map(s=>({index:s.index,label:String(s.index+1),energy:s.energy})),index,-extent,extent,depth*1.2,v=>'<path class="potential" d="M'+v.X(-extent)+','+v.Y(depth)+' H'+v.X(-a)+' V'+v.Y(0)+' H'+v.X(a)+' V'+v.Y(depth)+' H'+v.X(extent)+'"/>','x [nm]');
    curve('well-wave',state.psi,-extent,extent,false,'x [nm]','ψ [nm⁻¹ᐟ²]',{bounds:[-a,a]});curve('well-density',state.density,-extent,extent,true,'x [nm]','|ψ|² [nm⁻¹]',{bounds:[-a,a]});
  }
  function oscillator(){const n=+$('osc-n').value,q=+$('osc-quantum').value,state=C.oscillator(n,q);$('osc-n-out').value=n;$('osc-quantum-out').value=fmt(q,2)+' eV';$('osc-result').innerHTML='<b>E'+n+' = '+fmt(state.energy)+' eV</b>Nachbarabstand: '+fmt(q)+' eV<br>'+n+' innere Knoten<br>Umkehrpunkte: ξ = ±'+fmt(state.turning);energies('osc-energy',Array.from({length:6},(_,i)=>({index:i,label:'n='+i,energy:(i+.5)*q})),n,-4.5,4.5,6.6*q,a=>'<path class="potential" d="'+path(x=>.5*q*x*x,a.X,a.Y,-Math.sqrt(13.2),Math.sqrt(13.2))+'"/>','ξ = x/ℓ');curve('osc-wave',state.psi,-4.5,4.5,false,'ξ = x/ℓ','φ = √ℓ · ψ',{bounds:[-state.turning,state.turning]});curve('osc-density',state.density,-4.5,4.5,true,'ξ = x/ℓ','|φ|² (Dichte pro ξ)',{bounds:[-state.turning,state.turning]});}
  ['box-n','box-L','box-m','box-from','box-to'].forEach(id=>$(id).oninput=box);['well-width','well-depth'].forEach(id=>$(id).oninput=()=>well());$('well-state').oninput=()=>well(false);['osc-n','osc-quantum'].forEach(id=>$(id).oninput=oscillator);bindLevels('box-energy','box-n');bindLevels('well-energy','well-state');bindLevels('osc-energy','osc-n');box();well();oscillator();
  // Only the classical string evolves in time. Sound is local and opt-in.
  let motion=false,phase=0,last=0,audio=null,tone=null,gain=null,soundRequest=0,soundPending=false;
  const soundFrequency=()=>+$('string-n').value*+$('string-f').value;
  function string(motionOnly=false){const n=+$('string-n').value,f=+$('string-f').value;$('string-n-out').value=n;$('string-f-out').value=f;const X=x=>55+x*790,Y=y=>150-y*75,d=path(x=>Math.sin(n*Math.PI*x)*(motion?Math.cos(phase):1),X,Y,0,1,350);if(motionOnly){$('string-path')?.setAttribute('d',d);return;}let html='<line x1="55" x2="845" y1="150" y2="150" stroke="var(--line)"/><path d="M55 60V240 M845 60V240" stroke="var(--ink)" stroke-width="5"/><path id="string-path" d="'+d+'" fill="none" stroke="var(--phase)" stroke-width="4"/>';for(let j=0;j<=n;j++)html+='<circle cx="'+X(j/n)+'" cy="150" r="5" fill="var(--accent)"/>';html+='<text x="55" y="278">Festes Ende</text><text x="720" y="278">Festes Ende</text><text x="315" y="28">'+n+' Bäuche · '+(n-1)+' innere Knoten</text>';$('string-svg').innerHTML=html;$('string-result').innerHTML='<b>Mode '+n+' · f'+n+' = '+(n*f)+' Hz</b>λ'+n+' = 2L/'+n+' · Saitenfrequenz wächst mit n, Kastenenergie mit n².';}
  function soundLabels(){$('string-sound').setAttribute('aria-pressed',String(Boolean(tone)));$('string-sound').textContent=tone?'Ton ausschalten':'Ton einschalten';}
  function stopSound(){soundRequest++;soundPending=false;if(tone){try{tone.stop();}catch(_){}tone.disconnect();tone=null;}if(gain){gain.disconnect();gain=null;}audio?.suspend().catch(()=>{});soundLabels();}
  async function startSound(){if(soundPending||tone)return;const request=++soundRequest;soundPending=true;try{audio??=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();if(request!==soundRequest)return;tone=audio.createOscillator();gain=audio.createGain();tone.type='sine';tone.frequency.value=soundFrequency();gain.gain.value=+$('string-volume').value;tone.connect(gain);gain.connect(audio.destination);tone.start();soundLabels();}catch(_){$('string-result').textContent='Ton ist in diesem Browser nicht verfügbar. Die Saitenansicht bleibt nutzbar.';}finally{if(request===soundRequest)soundPending=false;}}
  $('string-sound').onclick=()=>tone||soundPending?stopSound():startSound();$('string-motion').onclick=()=>{motion=!motion;last=0;$('string-motion').setAttribute('aria-pressed',String(motion));$('string-motion').textContent=motion?'Schwingung anhalten':'Schwingung starten';string();};['string-n','string-f'].forEach(id=>$(id).oninput=()=>{if(tone)tone.frequency.setTargetAtTime(soundFrequency(),audio.currentTime,.025);string();});$('string-volume').oninput=()=>{if(gain)gain.gain.setTargetAtTime(+$('string-volume').value,audio.currentTime,.025);};
  function animate(time){if(motion&&!document.hidden){if(last)phase+=Math.min(.05,(time-last)/1000)*2*Math.PI*.55;last=time;string(true);}else last=0;requestAnimationFrame(animate);}requestAnimationFrame(animate);string();
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSound();});window.addEventListener('pagehide',stopSound);new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)stopSound();},{threshold:.01}).observe($('string-lab'));
  QMQuiz.forEach((q,i)=>{const card=document.createElement('form');card.className='quiz-card';card.innerHTML='<fieldset><legend>'+(i+1)+' · '+q.q+'</legend>'+q.answers.map((a,j)=>'<label><input type="radio" name="q'+i+'" value="'+j+'">'+a+'</label>').join('')+'</fieldset><button class="primary" type="submit">Antwort prüfen</button><div class="quiz-feedback" role="status" hidden></div>';card.onsubmit=event=>{event.preventDefault();const feedback=card.querySelector('.quiz-feedback'),choice=card.querySelector('input:checked');feedback.hidden=false;feedback.textContent=choice?((+choice.value===q.correct?'Richtig. ':'Noch nicht. ')+q.why):'Wähle zuerst eine Antwort.';};$('quiz').append(card);});
  // Hidden advanced mathematics is pre-typeset, then measured again on opening.
  window.QMMath?.startup.promise.then(()=>QMMath.typesetPromise([...document.querySelectorAll('.lesson')])).catch(()=>{});
  $('hydrogen-derivation').addEventListener('toggle',()=>{if($('hydrogen-derivation').open)window.QMMath?.startup.promise.then(()=>QMMath.typesetPromise([$('hydrogen-derivation')])).catch(()=>{});});
})();
