(() => {
  'use strict';
  const D=window.SeuchenData, $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  if(!D)return;
  const key='zeitspuren-seuchen-v1';
  const initial=()=>({consent:null,visited:[],sources:[],score:0,done:[],notes:'',a:'pest',b:'corona'});
  let state;try{state={...initial(),...JSON.parse(localStorage.getItem(key)||'{}')}}catch{state=initial()}
  const save=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}};
  const cases=D.cases, images=D.images, sourceByCase=id=>D.sources.filter(s=>s.case===id);
  const fileUrl=img=>`https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(img.file)}?width=1300`;
  const imageCredits=$('#image-credits');
  imageCredits.innerHTML=Object.values(images).map(im=>`<div class="credit"><strong>${esc(im.title)}</strong><br>${esc(im.credit)}<br><a target="_blank" rel="noopener" href="https://commons.wikimedia.org/wiki/File:${encodeURIComponent(im.file.replaceAll(' ','_'))}">Lizenz und Originaldatei ↗</a></div>`).join('');
  const setConsent=ok=>{state.consent=ok;save();$('#consent-dialog').close();updateConsent();if(ok)loadImages()};
  function updateConsent(){const yes=state.consent===true;$('#consent-status').textContent=yes?'Externe Bilder dürfen geladen werden.':'Externe Inhalte sind '+(state.consent===false?'abgelehnt.':'noch nicht freigegeben.'); document.querySelectorAll('[data-image]').forEach(el=>{if(yes&&!el.querySelector('img')){const im=images[el.dataset.image];if(im){const img=document.createElement('img');img.src=fileUrl(im);img.alt=im.title;img.loading='lazy';img.referrerPolicy='no-referrer';el.append(img)}}});document.querySelectorAll('[data-case-image]').forEach(el=>{if(yes&&!el.querySelector('img')){const im=images[el.dataset.caseImage];if(im){const img=document.createElement('img');img.src=fileUrl(im);img.alt=im.title;img.loading='lazy';img.referrerPolicy='no-referrer';el.append(img)}}});document.querySelectorAll('.detail-image').forEach(img=>{if(yes&&img.dataset.src&&!img.src)img.src=img.dataset.src})}
  function loadImages(){updateConsent()}
  if(state.consent===null)$('#consent-dialog').showModal();else updateConsent();
  $('#consent-dialog').addEventListener('close',()=>{if(state.consent===null){state.consent=$('#consent-dialog').returnValue==='yes';save();updateConsent()}});
  $('#consent-edit').addEventListener('click',()=>{$('#consent-dialog').showModal()});
  $('#consent-dialog').addEventListener('close',()=>{if($('#consent-dialog').returnValue==='yes'){state.consent=true;save();loadImages()}else if($('#consent-dialog').returnValue==='no'){state.consent=false;save();updateConsent()}});

  function renderCases(){
    $('#timeline').innerHTML=cases.map((c,i)=>`<button type="button" data-case="${c.id}" aria-current="${state.visited.includes(c.id)?'true':'false'}">${esc(c.year)}</button>`).join('');
    $('#case-grid').innerHTML=cases.map((c,i)=>`<button class="case-card" type="button" data-case="${c.id}" data-index="0${i+1}" aria-pressed="false"><span class="case-thumb" data-case-image="${esc(c.image)}">${state.consent===true?`<img loading="lazy" referrerpolicy="no-referrer" alt="${esc(images[c.image]?.title||'Historische Abbildung')}" src="${esc(fileUrl(images[c.image]))}">`:''}</span><span class="date">${esc(c.date)}</span><strong>${esc(c.name)}</strong><small>${esc(c.tag)}</small></button>`).join('');
    document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>showCase(b.dataset.case)));
  }
  const fields=[['damals','Damals vermutete man','then'],['heute','Was die Forschung heute weiß','now'],['maßnahmen','Maßnahmen','measures'],['wirkung','Wie erfolgreich waren sie?','success'],['gesellschaft','Gesellschaftliche Folgen','society'],['ungleichheit','Wer konnte wie handeln?','inequality'],['quellenblick','Quellenkritischer Hinweis','caution']];
  function showCase(id){const c=cases.find(x=>x.id===id);if(!c)return;state.visited=[...new Set([...state.visited,id])];save();
    document.querySelectorAll('.case-card').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.case===id)));document.querySelectorAll('.timeline button').forEach(x=>x.setAttribute('aria-current',String(x.dataset.case===id)));
    const im=images[c.image], sources=sourceByCase(id);
    const pathogen=c.pathogen?`<span class="detail-pathogen">Erreger: ${esc(({pestis:'Yersinia pestis · Bakterium',variola:'Variola-Virus',vibrio:'Vibrio cholerae · Bakterium',h1n1:'Influenza-A-Virus · H1N1',sars:'SARS-CoV-2 · Coronavirus'})[c.pathogen]||c.pathogen)}</span>`:'<span class="detail-pathogen">Erreger bis heute nicht sicher bestimmt</span>';
    $('#case-detail').innerHTML=`<div class="detail-top"><div><span class="eyebrow">${esc(c.date)} · ${esc(c.place)}</span><h3>${esc(c.name)}</h3></div><span class="detail-pathogen">${esc(c.tag)}</span></div><p class="detail-lede">${esc(c.intro)}</p>${im?`<figure><img class="detail-image" data-src="${esc(fileUrl(im))}" alt="${esc(im.title)}" ${state.consent===true?`src="${esc(fileUrl(im))}"`:''} loading="lazy"><figcaption class="image-caption">${esc(im.title)} · ${esc(im.credit)} · <a href="https://commons.wikimedia.org/wiki/File:${encodeURIComponent(im.file.replaceAll(' ','_'))}" target="_blank" rel="noopener">Bildquelle und Lizenz ↗</a><br>${esc(im.note)}</figcaption></figure>`:''}<div>${pathogen}</div><div class="detail-grid">${fields.map(([label,title,k])=>`<section class="detail-block ${k==='society'||k==='success'?'wide':''}"><h4>${title}</h4><p>${esc(c[k])}</p></section>`).join('')}</div><details class="assessment"><summary>Quellen aus dieser Fallakte lesen (${sources.length})</summary><p>Die Quellenarbeit springt direkt zum Fall und zeigt Originaltext, neue deutsche Übertragung und eine Frage zur Analyse.</p><div class="refs">${sources.map(s=>`<a href="#quelle-${s.id}" data-source-jump="${s.id}">${esc(s.code)} · ${esc(s.title)} →</a>`).join('')}</div></details><div class="refs">${c.refs.map(([name,url])=>`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(name)} ↗</a>`).join('')}<button type="button" class="wiki-case" data-wiki="${esc(c.wiki)}">${esc(c.wiki)} · Wikipedia lesen ↗</button></div>`;
    $('#case-detail').classList.add('active');document.querySelectorAll('[data-source-jump]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();$('#source-filter').value=id;renderSources();document.getElementById(`quelle-${a.dataset.sourceJump}`)?.scrollIntoView({behavior:'smooth',block:'center'})}));$('#case-detail .wiki-case').addEventListener('click',e=>openWiki(e.currentTarget.dataset.wiki));updateBadges();
  }
  renderCases();
  if(state.visited.length)showCase(state.visited.at(-1));

  const filter=$('#source-filter');cases.forEach(c=>filter.add(new Option(`${c.year} · ${c.name}`,c.id)));
  filter.addEventListener('change',renderSources);
  function renderSources(){const id=filter.value;const list=D.sources.filter(s=>id==='all'||s.case===id);$('#source-count').textContent=`${list.length} ${list.length===1?'Quelle':'Quellen'}`;
    $('#source-grid').innerHTML=list.map(s=>{const c=cases.find(x=>x.id===s.case);return `<article class="source-card" id="quelle-${s.id}"><div class="source-meta">${esc(s.code)} · ${esc(c?.name||'')} · ${esc(s.language)}</div><h3>${esc(s.title)}</h3><p class="source-byline">${esc(s.author)} · ${esc(s.date)} · ${esc(s.genre)}</p><p class="source-context">${esc(s.context)}</p><div class="quote-pair"><div class="quote-panel"><h4>Original · ${esc(s.language)}</h4>${s.original.map(t=>`<blockquote lang="${s.lang==='grc'?'grc':s.lang==='it'?'it':s.lang==='en'?'en':'de'}">${esc(t)}</blockquote>`).join('<br><br>')}</div><div class="quote-panel translation"><h4>Übertragung in heutiges Deutsch</h4>${s.modern.map(t=>`<blockquote>${esc(t)}</blockquote>`).join('<br><br>')}</div></div><details><summary>Arbeitsfrage und Deutungshinweis</summary><p><strong>Arbeitsfrage:</strong> ${esc(s.question)}</p><p><strong>Deutungshinweis:</strong> ${esc(s.guide)}</p><p><strong>Grenze der Quelle:</strong> ${esc(s.limits)}</p><button type="button" data-source-done="${s.id}">${state.sources.includes(s.id)?'Quelle bearbeitet ✓':'Als bearbeitet markieren'}</button></details><a target="_blank" rel="noopener" href="${esc(s.url)}">Originalquelle und Fundstelle öffnen ↗</a><p class="source-rights">${esc(s.rights)}</p></article>`}).join('');document.querySelectorAll('[data-source-done]').forEach(b=>b.addEventListener('click',()=>{state.sources=[...new Set([...state.sources,b.dataset.sourceDone])];save();renderSources();updateBadges()}));}
  renderSources();

  function fillCompare(){for(const id of ['compare-a','compare-b']){$(id==='#compare-a'?'#compare-a':'#compare-b').innerHTML=cases.map(c=>`<option value="${c.id}">${esc(c.year)} · ${esc(c.name)}</option>`).join('')};$('#compare-a').value=cases.some(c=>c.id===state.a)?state.a:'pest';$('#compare-b').value=cases.some(c=>c.id===state.b)?state.b:'corona';$('#compare-note').value=state.notes||'';drawCompare()}
  function drawCompare(){const a=cases.find(c=>c.id===$('#compare-a').value),b=cases.find(c=>c.id===$('#compare-b').value);if(!a||!b)return;state.a=a.id;state.b=b.id;save();const rows=[['Erreger','now'],['Wissen zur Zeit','then'],['Maßnahmen','measures'],['Erfolg und Unsicherheit','success'],['Gesellschaft','society'],['Ungleichheit','inequality']];$('#compare-result').innerHTML=[a,b].map(c=>`<article class="compare-column"><h3>${esc(c.name)} <small>${esc(c.date)}</small></h3><dl>${rows.map(([label,k])=>`<dt>${label}</dt><dd>${esc(k==='now'?(c.pathogen?(({pestis:'Yersinia pestis (Bakterium)',variola:'Variola-Virus',vibrio:'Vibrio cholerae (Bakterium)',h1n1:'Influenza A (H1N1)',sars:'SARS-CoV-2'})[c.pathogen]||''): 'nicht sicher bestimmt')+'. '+c[k]:c[k])}</dd>`).join('')}</dl></article>`).join('')}
  $('#compare-a').addEventListener('change',drawCompare);$('#compare-b').addEventListener('change',drawCompare);$('#compare-note').addEventListener('input',e=>{state.notes=e.target.value;save();$('#note-saved').textContent='Gespeichert auf diesem Gerät.'});fillCompare();

  const Q=[
    {q:'Thukydides beschreibt, dass Ärzte besonders häufig starben, wenn sie Erkrankten nahe kamen. Was lässt sich daraus am sichersten schließen?',c:'Er beobachtet einen Zusammenhang, kennt aber den Erreger nicht.',w:['Er beweist, dass die Krankheit durch Bakterien übertragen wurde.','Er beschreibt einen Zusammenhang; der Erreger bleibt damit unbestimmt.','Alle Ärzte Athens starben an derselben Krankheit.'],x:'Die Beobachtung ist historisch wichtig, ersetzt aber keine Erregerbestimmung.'},
    {q:'Warum ist „Pest“ für die Seuche von Athen eine unsichere Erregerdiagnose?',c:'Das Wort konnte allgemein eine schwere Seuche bezeichnen; ein Erregernachweis fehlt.',w:['Pest gab es vor dem Mittelalter noch nicht.','Das Wort konnte allgemein eine Seuche meinen; der spezifische Erreger ist nicht gesichert.','Thukydides verwendete nur medizinische Fachbegriffe.'],x:'Symptome aus antiken Texten erlauben meist keine sichere Rückdiagnose.'},
    {q:'Was ist beim Vergleich von Boccaccios Bericht mit einer Statistik zu beachten?',c:'Das Decameron ist literarisch gestaltet und keine Bevölkerungszählung.',w:['Literarische Texte enthalten grundsätzlich keine historischen Informationen.','Das Decameron ist literarisch gestaltet und keine Bevölkerungszählung.','Boccaccio schrieb vor dem Ausbruch.'],x:'Quellen können historische Erkenntnisse liefern, wenn Perspektive und Gattung mitgedacht werden.'},
    {q:'Eine Stadt beschließt erst 1377 eine Wartezeit für ankommende Schiffe. Was darfst du daraus nicht folgern?',c:'Dass Florenz 1348 bereits genau dieselbe Quarantäne praktizierte.',w:['Dass städtische Schutzregeln sich entwickelten.','Dass Florenz 1348 bereits genau dieselbe Quarantäne praktizierte.','Dass die Maßnahmen in bestimmten Städten dokumentiert sind.'],x:'Spätere Entwicklungen nicht rückwirkend auf frühere Ausbrüche übertragen.'},
    {q:'Warum sind mittelalterliche Pestpogrome keine wirksame Seuchenmaßnahme?',c:'Die Brunnenvergiftungsbeschuldigung war unbelegt und richtete Gewalt gegen jüdische Gemeinden.',w:['Weil Brunnenwasser nie Krankheit übertragen kann.','Die Brunnenvergiftungsbeschuldigung war unbelegt und richtete Gewalt gegen jüdische Gemeinden.','Weil es in Städten keine Brunnen gab.'],x:'Die falsche Anschuldigung erklärt den Erreger nicht und legitimierte Verfolgung.'},
    {q:'Was unterscheidet Variolation von Jenners später beschriebenem Verfahren?',c:'Bei der Variolation wird Pockenmaterial übertragen; Jenner untersuchte Material aus Kuhpocken.',w:['Variolation ist eine moderne Impfung mit mRNA.','Bei Variolation wurde Pockenmaterial übertragen; Jenner untersuchte Kuhpockenmaterial.','Beide Verfahren waren risikofrei.'],x:'Die Verfahren sind historisch verschieden und nicht ohne Weiteres gleichzusetzen.'},
    {q:'Montagu nennt Variolation „völlig harmlos“. Wie sollte man diese Formulierung lesen?',c:'Als wertende Aussage einer begeisterten Briefschreiberin, nicht als Sicherheitsnachweis.',w:['Als heutige medizinische Empfehlung.','Als wertende Aussage, die mit anderen Quellen und Risiken geprüft werden muss.','Als Beleg, dass das Verfahren nie Nebenwirkungen hatte.'],x:'Der Ton einer Quelle kann ihre Überzeugung zeigen, aber nicht selbst die Sicherheit belegen.'},
    {q:'Was zeigt John Snows Karte besonders gut?',c:'Die räumliche Häufung von Todesfällen in der Nähe einer Wasserpumpe.',w:['Den Erreger unter dem Mikroskop.','Die räumliche Häufung von Todesfällen im Umfeld einer Pumpe.','Dass jede betroffene Person aus derselben Familie kam.'],x:'Die Karte macht Muster sichtbar; weitere Befragungen stützen die Hypothese.'},
    {q:'Warum beweist das Entfernen des Pumpengriffs allein nicht, dass es die Choleraepidemie beendete?',c:'Die Fallzahlen sanken bereits vorher und weitere Ursachen müssen berücksichtigt werden.',w:['Weil Wasser Cholera nicht übertragen kann.','Die Fallzahlen sanken bereits vorher; weitere Befunde und Einflüsse müssen berücksichtigt werden.','Weil John Snow keine Pumpe untersuchte.'],x:'Zeitliche Abfolge allein reicht nicht für einen Kausalnachweis.'},
    {q:'Warum hieß die Pandemie von 1918 „Spanische Grippe“?',c:'Das ist kein gesicherter Herkunftsnachweis; Spaniens offenere Presse berichtete auffälliger.',w:['Weil das Virus nachweislich in Spanien entstand.','Weil Spaniens Presse im neutralen Land vergleichsweise offen berichtete.','Weil Spanien die ersten Impfstoffe entwickelte.'],x:'Kriegszensur in anderen Staaten beeinflusste, was öffentlich sichtbar wurde.'},
    {q:'Was kann ein Gesundheitsplakat von 1918 belegen – und was nicht?',c:'Es zeigt eine beabsichtigte Botschaft, aber nicht automatisch ihre Wirkung.',w:['Dass alle Menschen der Empfehlung folgten.','Eine beabsichtigte Botschaft, aber nicht automatisch ihre Wirkung.','Wie viele Menschen die Krankheit überlebten.'],x:'Für tatsächliches Verhalten braucht man weitere Quellen.'},
    {q:'Welche Aussage über Corona unterscheidet Erreger und Krankheit korrekt?',c:'SARS-CoV-2 ist das Virus; COVID-19 ist die dadurch verursachte Krankheit.',w:['COVID-19 ist der Erreger; SARS-CoV-2 die Krankheit.','SARS-CoV-2 ist das Virus; COVID-19 die Krankheit.','Beide Begriffe bezeichnen ausschließlich Impfstoffe.'],x:'Die Unterscheidung hilft, Quellen fachlich genau zu lesen.'},
    {q:'Was bedeutet die NRW-Verordnung vom 22. März 2020 als Quelle?',c:'Sie dokumentiert eine konkrete Regel zu einem bestimmten Zeitpunkt und mit Ausnahmen.',w:['Sie beschreibt alle Regeln während der gesamten Pandemie.','Sie dokumentiert eine Regel für einen bestimmten Zeitpunkt und Ort, einschließlich Ausnahmen.','Sie belegt, dass jede Person der Regel folgte.'],x:'Eine Rechtsnorm zeigt, was gelten sollte, nicht automatisch die Alltagspraxis.'},
    {q:'Warum sind die sozialen Folgen von Corona nicht allein mit „Lockdown“ erklärt?',c:'Gesundheitsrisiko, Krisenangst, Lebensbedingungen und Maßnahmen wirkten zusammen.',w:['Weil es keine Schulschließungen gab.','Weil Gesundheit, Angst, Lebensbedingungen und Maßnahmen zusammenwirkten.','Weil alle Menschen gleich betroffen waren.'],x:'Historische Urteile sollten Zeit, Gruppe und Wirkungsweg benennen.'},
    {q:'Welche Frage hilft beim Vergleich „zu Hause bleiben“ in 1918 und 2020?',c:'Wer konnte es sich leisten, Arbeit und Einkommen tatsächlich zu unterbrechen?',w:['Welche Zeit war moderner?','Wer konnte sich Rückzug leisten und wie war die soziale Absicherung?','Welche Pandemie war schlimmer?'],x:'Soziale Möglichkeiten bestimmen, ob eine Regel praktisch umsetzbar ist.'},
    {q:'Eine Quelle fordert, Kranke zu meiden. Was muss man prüfen, bevor man sie als erfolgreiche Maßnahme bewertet?',c:'Ob die Empfehlung befolgt wurde und ob Daten ihre Wirkung zeigen.',w:['Ob die Formulierung alt klingt.','Ob die Empfehlung befolgt wurde und ob Daten eine Wirkung zeigen.','Ob der Autor berühmt war.'],x:'Forderung und tatsächliche Wirkung sind unterschiedliche historische Fragen.'},
    {q:'Welcher Vergleich ist historisch sorgfältig?',c:'Beide Fälle nutzten Kontaktbeschränkung, aber Wissen und Lebensbedingungen unterschieden sich.',w:['Alle Seuchen sind gleich, weil Menschen Angst haben.','Ein ähnliches Mittel kann in unterschiedlichen Zeiten andere Voraussetzungen und Folgen haben.','Heute ist jede Maßnahme automatisch erfolgreicher.'],x:'Vergleiche Gemeinsamkeiten und Unterschiede gleichzeitig.'},
    {q:'Wer fehlt in vielen schriftlichen Quellen besonders häufig?',c:'Menschen, die nicht schreiben konnten oder wenig Zugang zu öffentlichen Ämtern hatten.',w:['Nur Herrscher.','Menschen ohne Zugang zu Schrift, Ämtern und Veröffentlichung.','Alle Menschen über 30 Jahre.'],x:'Überlieferung ist sozial ungleich: Wer schreibt und wessen Texte überleben, ist wichtig.'},
    {q:'Was zeigt die Ausrottung der Pocken?',c:'Langfristiger Erfolg beruhte auf koordinierter weltweiter Bekämpfung, nicht einem Einzelversuch allein.',w:['Ein Experiment allein löste sofort die Krankheit weltweit aus.','Koordinierte langfristige Bekämpfung kann Erreger weltweit zurückdrängen.','Impfungen wirken immer ohne gesellschaftliche Organisation.'],x:'Das Ergebnis umfasst Forschung, Programme, Zusammenarbeit und Zugang.'},
    {q:'Wie prüfst du eine Behauptung über den Erfolg einer Maßnahme am besten?',c:'Du suchst nach zeitlichen, räumlichen und vergleichenden Belegen sowie anderen Erklärungen.',w:['Du übernimmst sie, wenn sie in einem alten Buch steht.','Du suchst nach mehreren passenden Belegen und prüfst Alternativerklärungen.','Du schließt vom Ende einer Epidemie auf die letzte Maßnahme.'],x:'Eine plausible Erklärung braucht mehr als eine zeitliche Reihenfolge.'},
    {q:'Eine Infektionswelle endet nach einer Kontaktregel. Was ist die vorsichtigste Formulierung?',c:'Die Regel könnte beigetragen haben; weitere Faktoren müssen untersucht werden.',w:['Die Regel hat die Welle sicher beendet.','Die Regel könnte beigetragen haben; weitere Faktoren müssen untersucht werden.','Die Regel war sicher wirkungslos.'],x:'Vorsichtige Sprache passt zur Unsicherheit historischer Kausalität.'},
    {q:'Warum ist eine heutige Mikroskopaufnahme eines Virus keine historische Aufnahme?',c:'Sie zeigt das Virus mit moderner Technik und wurde viel später hergestellt.',w:['Weil Viren nicht fotografiert werden können.','Sie zeigt eine moderne Laboraufnahme und stammt nicht aus der damaligen Zeit.','Weil sie ein Bakterium zeigt.'],x:'Die Bildunterschrift muss erklären, was und wann die Aufnahme zeigt.'},
    {q:'Was ist eine gute erste Quellenfrage?',c:'Wer schrieb den Text wann, für wen und mit welchem Zweck?',w:['Welche Antwort will ich am liebsten lesen?','Wer schrieb den Text wann, für wen und mit welchem Zweck?','Ist der Text lang genug?'],x:'Perspektive, Zeitpunkt und Zweck helfen, den Aussagewert einzuschätzen.'},
    {q:'Welche Aussage verbindet Maßnahme und Gerechtigkeit?',c:'Eine Schutzmaßnahme kann nützen, während ihre Kosten ungleich verteilt sind.',w:['Wenn eine Maßnahme wirkt, leiden alle gleich.','Eine Maßnahme kann nützen und ihre Kosten trotzdem ungleich verteilen.','Gerechtigkeit spielt in Krisen keine Rolle.'],x:'Wirkung und gesellschaftliche Verteilung sind zwei getrennte Bewertungsfragen.'},
    {q:'Was lässt sich aus einem persönlichen Bericht über Angst sicher entnehmen?',c:'Der Bericht gibt Einblick in eine individuelle Erfahrung, nicht in die aller Menschen.',w:['Alle Bewohner empfanden dasselbe.','Der Bericht gibt Einblick in eine individuelle Perspektive.','Die Krankheit war besonders ansteckend.'],x:'Einzelzeugnisse sind wertvoll, aber nicht automatisch repräsentativ.'},
    {q:'Warum ist Corona in dieser Lernreise gleichgewichtig mit älteren Fällen?',c:'Auch die jüngste Erfahrung wird mit denselben historischen Fragen und Quellenmaßstäben untersucht.',w:['Weil jüngere Krankheiten wichtiger sind.','Weil der jüngste Fall mit denselben Fragen nach Wissen, Handlung und Folgen untersucht werden kann.','Weil es über ältere Seuchen keine Quellen gibt.'],x:'Gleiche Analysefragen bedeuten keine Gleichsetzung der Situationen.'},
    {q:'Welche Frage macht eine Bewertung konkreter?',c:'Welche Wirkung hatte die Maßnahme für welche Gruppe und in welcher Phase?',w:['War die Maßnahme gut oder schlecht?','Welche Wirkung hatte sie für welche Gruppe und in welcher Phase?','Wer hat am lautesten darüber gesprochen?'],x:'Zeit, Ort, Gruppe und Beleg präzisieren das Urteil.'},
    {q:'Woran erkennst du in einer Quelle eine Maßnahme statt einer Beobachtung?',c:'An einer Aufforderung oder Regel, die ein gewünschtes Verhalten vorgibt.',w:['An jedem Satz mit einem Datum.','An einer Aufforderung oder Vorschrift, die Verhalten vorgibt.','An jeder Beschreibung eines Symptoms.'],x:'Modalverben und Imperative können Hinweise sein; Kontext bleibt wichtig.'},
    {q:'Was ist bei einem Vergleich von Pest und Corona besonders wichtig?',c:'Keine Erregergleichheit unterstellen und die verschiedenen Wissensstände benennen.',w:['Beide durch dasselbe Virus verursacht nennen.','Die unterschiedlichen Erreger und Wissensstände benennen.','Nur die Zahl der Toten vergleichen.'],x:'Der Vergleich betrifft gesellschaftliche Fragen und nicht eine Gleichheit der Erreger.'},
    {q:'Welche Aussage ist eine Quellenkritik?',c:'Ein amtlicher Beschluss zeigt die Regel, aber noch nicht, ob Menschen sie befolgten.',w:['Der Beschluss ist alt.','Ein amtlicher Beschluss zeigt die Regel, aber nicht automatisch Befolgung.','Die Regel klingt streng.'],x:'Die Reichweite der Quelle wird begrenzt und präzise benannt.'},
    {q:'Was kann eine historische Karte allein nicht erklären?',c:'Warum einzelne Menschen ihr Verhalten änderten und welche Ressourcen sie hatten.',w:['Wo sich Todesfälle häuften.','Warum einzelne Menschen handelten und welche Ressourcen sie hatten.','Welche Straßen es gab.'],x:'Karten zeigen räumliche Muster; Alltag und Ursachen benötigen weitere Quellen.'},
    {q:'Wann ist ein Vergleich nicht bloß eine Analogie?',c:'Wenn er Ähnlichkeiten und Unterschiede mit Belegen für beide Situationen begründet.',w:['Wenn man nur ein gemeinsames Wort findet.','Wenn Gemeinsamkeiten und Unterschiede belegt und eingeordnet werden.','Wenn die Fälle möglichst weit auseinanderliegen.'],x:'Vergleichen heißt Beziehungen begründet darstellen.'}
  ];
  let round=[],qi=0;
  function newRound(){round=[...Q].sort(()=>Math.random()-.5).slice(0,8);qi=0;showQuestion()}
  function showQuestion(){if(qi>=round.length){$('#quiz-card').innerHTML=`<h3 class="quiz-question">Runde geschafft.</h3><p>Du hast ${round.length} Aufgaben bearbeitet. Lies in den Fallakten weiter oder starte eine neue Runde.</p><button class="quiz-next" id="round-again">Neue Aufgabenrunde</button>`;$('#round-again').onclick=newRound;$('#quiz-progress').textContent='Runde beendet';return}
    const q=round[qi],answers=[{t:q.c,ok:true},...q.w.map(t=>({t,ok:false}))].sort(()=>Math.random()-.5);
    $('#quiz-progress').textContent=`Aufgabe ${qi+1} von ${round.length}`;$('#quiz-card').innerHTML=`<p class="quiz-context">Denk an die Leitfrage: Wissen · Handlung · Folgen</p><h3 class="quiz-question">${esc(q.q)}</h3><div class="answer-list">${answers.map((a,i)=>`<button class="answer" type="button" data-answer="${i}">${esc(a.t)}</button>`).join('')}</div><div id="quiz-feedback"></div>`;
    document.querySelectorAll('[data-answer]').forEach((b,i)=>b.addEventListener('click',()=>{document.querySelectorAll('.answer').forEach(x=>x.disabled=true);const a=answers[i];b.classList.add(a.ok?'correct':'incorrect');if(a.ok){state.score++;state.done.push(q.q);save();$('#score').textContent=state.score}else document.querySelectorAll('.answer').forEach((x,j)=>{if(answers[j].ok)x.classList.add('correct')});$('#quiz-feedback').innerHTML=`<div class="quiz-feedback"><strong>${a.ok?'Richtig.':'Noch nicht.'}</strong> ${esc(q.x)} <br><button type="button" class="quiz-next" id="quiz-next">Weiter →</button></div>`;$('#quiz-next').onclick=()=>{qi++;showQuestion();updateBadges()}}))}
  $('#score').textContent=state.score;$('#new-round').addEventListener('click',newRound);newRound();
  function updateBadges(){const defs=[['first','Erste Akte geöffnet',state.visited.length>=1],['four','Sechs Zeiten erkundet',state.visited.length>=6],['reader','Quellenleser · 3 Quellen bearbeitet',state.sources.length>=3],['compare','Vergleich im eigenen Worten',state.notes.trim().length>=60],['historian','Quellenkritisch · 8 richtige Antworten',state.score>=8]];$('#badges').innerHTML=defs.map(([,label,ok])=>`<span class="badge ${ok?'earned':''}">${ok?'✦':'◇'} ${label}</span>`).join('')}
  updateBadges();
  $('#compare-note').addEventListener('input',()=>setTimeout(updateBadges,0));
  $('#reset-open').addEventListener('click',()=>$('#reset-dialog').showModal());$('#reset-dialog').addEventListener('close',()=>{if($('#reset-dialog').returnValue==='yes'){const consent=state.consent;localStorage.removeItem(key);state=initial();state.consent=consent;$('#score').textContent='0';$('#compare-note').value='';renderCases();renderSources();fillCompare();newRound();updateBadges();$('#case-detail').classList.remove('active');$('#reset-open').focus()}});

  async function openWiki(page){if(state.consent!==true){$('#consent-dialog').showModal();$('#wiki-status').textContent='Bitte stimme dem Laden externer Inhalte zu.';return}const d=$('#wiki-dialog');d.showModal();$('#wiki-title').textContent=page.replaceAll('_',' ');$('#wiki-status').textContent='Artikel wird geladen …';$('#wiki-body').innerHTML='';const url=`https://de.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(page)}`;$('#wiki-link').href=`https://de.wikipedia.org/wiki/${encodeURIComponent(page)}`;try{const r=await fetch(url);if(!r.ok)throw new Error();const a=await r.json();$('#wiki-title').textContent=a.title||page;$('#wiki-status').textContent='Kurzüberblick aus der deutschsprachigen Wikipedia. Für die Fallanalyse beachte die im Text genannten Unsicherheiten.';$('#wiki-body').innerHTML=`${a.thumbnail?.source?`<img src="${esc(a.thumbnail.source)}" alt="">`:''}<p>${esc(a.extract||'')}</p>`}catch{$('#wiki-status').textContent='Der Wikipedia-Artikel konnte gerade nicht geladen werden. Du kannst ihn direkt in einem neuen Tab öffnen.'}}
  $('#wiki-open').addEventListener('click',()=>openWiki('Pest'));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));
})();
