(function(){
  'use strict';
  const $=id=>document.getElementById(id),C=window.SpiegelCore,TAU=Math.PI*2;
  const reduced=matchMedia('(prefers-reduced-motion: reduce)'),fmt=(n,d=1)=>n.toLocaleString('de-DE',{maximumFractionDigits:d,minimumFractionDigits:d});
  const colors={a:'#ee956d',b:'#69cec6',gold:'#e5c681',ink:'#172c32',muted:'#668081'};
  let paused=reduced.matches,time=0,last=0,lastPaint=0;
  let mirrorY=.6,mirrorX=.18,overlay=false,dragging=false;
  const film={index:0,playing:false,elapsed:0};
  const scenes=[
    {tag:'CHEMIE-NOBELPREIS · 7. OKTOBER 2026',title:'Gleiche Atome.<br><em>Was ist anders?</em>',text:'Thalidomid: Zwei Versionen mit gleicher Summenformel und gleichen Nachbaratomen. Wie kann ein Unterschied bleiben? Wir folgen dem Rätsel bis zur gezielten chemischen Auswahl.',mode:'cover'},
    {tag:'01 · EIN RÄUMLICHER UNTERSCHIED',title:'Drehen ist<br><em>nicht spiegeln.</em>',text:'Wie deine Hände: Zwei Moleküle können Spiegelbilder sein, ohne jemals deckungsgleich zu werden. Sie heißen Enantiomere.',mode:'mirror'},
    {tag:'02 · DER ANFANG KANN WINZIG SEIN',title:'51 zu 49.<br><em>Nur 2 % Überschuss.</em>',text:'Der Enantiomerenüberschuss ist die Differenz der Anteile. 51 % A minus 49 % B ergibt 2 % ee.',mode:'mixture'},
    {tag:'03 · KAGANS ENTDECKUNG',title:'Chemie folgt<br><em>nicht immer einer Geraden.</em>',text:'Der Überschuss im Katalysator und im Produkt müssen nicht proportional sein. Ein kleiner Vorteil kann überproportional wachsen.',mode:'curve'},
    {tag:'04 · DIE ZWEITE SPUR · AUTOKATALYSE',title:'Ein Produkt hilft,<br><em>mehr Produkt zu bilden.</em>',text:'Das violette Schulversuchs-Rätsel führt zur Rückkopplung. Soai verbindet dieses Prinzip mit räumlicher Auswahl – in einer anderen, asymmetrischen Reaktion.',mode:'loop'},
    {tag:'05 · DIE RÜCKKOPPLUNG',title:'Mehr Produkt.<br><em>Mehr Verstärkung.</em>',text:'Neue Produktmoleküle wirken wiederum mit. In geeigneten Systemen wird aus einer kleinen Vorgabe ein großer Enantiomerenüberschuss.',mode:'amplify'},
    {tag:'06 · WARUM DAS WICHTIG IST',title:'Auch das Leben<br><em>hat Händigkeit.</em>',text:'Proteine und Rezeptoren sind chiral. Die Experimente zeigen einen möglichen Verstärkungsweg – nicht die bewiesene Entstehung des Lebens.',mode:'life'},
    {tag:'07 · ZWEI FORSCHUNGSWEGE',title:'Kagan. Soai.<br><em>Nobelpreis 2026.</em>',text:'Nichtlineare Effekte und asymmetrische Autokatalyse: Zwei Entdeckungen verändern unseren Blick auf die selektive Bildung von Spiegelbild-Molekülen.',mode:'people'},
    {tag:'08 · JETZT SELBST ENTDECKEN',title:'Verändere die Vorgabe.<br><em>Sieh, was passiert.</em>',text:'Drehbare Moleküle, veränderbare Mischungen und transparente Verstärkungsmodelle. Ohne Aufgaben. Mit Raum zum Entdecken.',mode:'cover',final:true}
  ];
  const sceneNotes=[
    {title:'Ein Rätsel, das eine Formel nicht beantwortet.',paragraphs:['Vom Wirkstoff Thalidomid gibt es zwei Versionen mit derselben Summenformel. Jedes Atom besitzt in der anderen Version die entsprechenden gleichen Nachbaratome. Trotzdem können biologische Unterschiede auftreten. Was übersehen wir, wenn wir nur Atome und Bindungen auflisten? Die animierten Modelle sind allgemeine Erklärmodelle, keine Thalidomid-Strukturen.','Contergan ist unser historischer Anlass, nicht die Entdeckung, für die Kagan und Soai ausgezeichnet wurden. Die Seite erklärt zunächst den verborgenen Unterschied und ordnet danach die späteren Tierversuche sowie die Umwandlung im menschlichen Körper ein. Eine gezielte Herstellung allein garantiert keine Arzneimittelsicherheit.']},
    {title:'Eine Drehung verändert die Ansicht, nicht die Händigkeit.',paragraphs:['Am dargestellten Zentrum sitzen vier unterschiedliche Gruppen in einer räumlichen, tetraedrischen Anordnung. Wenn das Modell rotiert, kommen andere Gruppen nach vorn. Ihre Verknüpfung und die Händigkeit des Moleküls bleiben dabei erhalten. Das Spiegelbild hat dagegen die entgegengesetzte räumliche Anordnung.','Deckungsgleich wären die Modelle nur dann, wenn jede entsprechende Gruppe gleichzeitig an derselben Stelle liegen könnte. Eine bloß ähnliche Silhouette aus einer Blickrichtung reicht nicht. Im interaktiven Milchsäure-Modell unterhalb der Präsentation lassen sich die Ansichten drehen und die Modelle transparent übereinanderlegen.']},
    {title:'„Überschuss“ ist etwas anderes als „Anteil“.',paragraphs:['Stell dir 100 Moleküle vor: 51 sind A, 49 sind B. 49 Moleküle jeder Form sind gedanklich ausgeglichen. Zwei A-Moleküle bleiben als Überschuss. Deshalb beträgt der Enantiomerenüberschuss 2 %, obwohl A einen Anteil von 51 % hat. Die Abkürzung ee kommt vom englischen enantiomeric excess.','Eine 50:50-Mischung heißt Racemat und hat 0 % ee. Auch eine winzige Abweichung ist eine asymmetrische Vorgabe. Die Punkte illustrieren diese Zusammensetzung; ihre Bewegung zeigt keine experimentell bestimmten Molekülbahnen.']},
    {title:'Der Katalysator beeinflusst, welche Form neu entsteht.',paragraphs:['Ein Katalysator ermöglicht einen günstigeren Reaktionsweg. Ist seine Umgebung chiral, können die Wege zu den beiden Produkt-Enantiomeren unterschiedlich leicht ablaufen. Im Diagramm steht die Zusammensetzung des Katalysators auf der waagerechten und die des Produkts auf der senkrechten Achse.','Die gestrichelte Linie bedeutet eine proportionale Zuordnung: 20 % A-Überschuss im Katalysator würden zu 20 % A-Überschuss im Produkt führen. Das gezeichnete Erklärmodell liegt für A-Überschuss darüber: Aus 20 % werden etwa 38,5 %. Kagans Forschung zeigte, dass reale Systeme solche nichtlinearen Beziehungen besitzen können; die konkrete Kurve hier ist keine Messkurve.']},
    {title:'Das Besondere ist die Rückkopplung.',paragraphs:['Bei der Autokatalyse gehört ein Produkt der Reaktion selbst zum katalytisch wirksamen System. Sobald davon mehr entsteht, kann zusätzliches katalytisch wirksames Material vorliegen, das die weitere Bildung erleichtert. Die umlaufende Animation stellt diesen Rückkopplungsgedanken dar, keinen vollständigen Mechanismus.','In der Soai-Reaktion sind während der Reaktion zinkhaltige, vom Produkt abgeleitete Verbände beteiligt. Nach der Aufarbeitung erhält man den Alkohol. „Das Produkt katalysiert sich selbst“ ist daher eine kurze Beschreibung des Prinzips, keine Behauptung, dass ein isoliertes Alkoholmolekül ohne weitere Stoffe beliebig viele Kopien von sich erzeugt.']},
    {title:'Mehr Moleküle allein bedeuten noch keinen größeren ee.',paragraphs:['Wenn beide Formen im selben Verhältnis wachsen, bleibt der prozentuale Überschuss gleich: Aus 51 A und 49 B können 102 A und 98 B werden; beide Mischungen besitzen 2 % ee. Zur asymmetrischen Verstärkung muss sich das Verhältnis der beiden Formen verändern.','In geeigneten autokatalytischen Systemen wird die anfangs leicht häufigere Form überproportional begünstigt. Das animierte Zahlenmodell illustriert eine solche Verstärkung. Die reale Soai-Reaktion beruht auf komplexeren Verbänden; ihre experimentellen Verstärkungswerte werden nicht mit dieser Animation berechnet.']},
    {title:'Räumliche Unterschiede treffen auf räumliche Biologie.',paragraphs:['Auch Enzyme und Rezeptoren sind räumlich aufgebaut. Zwei Enantiomere können daher unterschiedlich mit ihnen wechselwirken: Was für die eine Form eine günstige Anordnung ist, muss für das Spiegelbild nicht ebenso günstig sein. Welche Wirkung daraus folgt, hängt vom konkreten Stoff und biologischen System ab.','Die Animation steht allgemein für räumliche biologische Strukturen. Sie beweist keinen Entstehungsweg des Lebens. Soais Forschung zeigt, dass die Verstärkung kleiner Asymmetrien chemisch möglich ist. Die historische Frage, wie die besondere Händigkeit biologischer Stoffe auf der Erde entstand, ist damit nicht vollständig beantwortet.']},
    {title:'Verstärkung und Selbstverstärkung sind nicht dasselbe.',paragraphs:['Kagans nichtlineare Effekte betreffen die Beziehung zwischen der Zusammensetzung eines Katalysators und der seines Produkts. Dafür ist nicht erforderlich, dass das Produkt selbst katalytisch wirkt. Die wichtigen Arbeiten dazu erschienen 1986.','Soais asymmetrische Autokatalyse verknüpft die Bildung eines chiralen Produkts mit der Katalyse seiner weiteren Bildung. 1995 berichteten Soai und Mitarbeitende über dieses Verstärkungsprinzip. Der Nobelpreis 2026 würdigt die Entdeckung nichtlinearer Effekte und der Autokatalyse in der asymmetrischen organischen Synthese.']},
    {title:'Die Erklärung wird jetzt Schritt für Schritt ausführlicher.',paragraphs:['Die folgenden Kapitel beginnen bei den räumlichen Spiegelbildern und der Bedeutung von ee. Anschließend erklären sie Katalyse und asymmetrische Synthese, lesen das Diagramm an einem Zahlenbeispiel und verfolgen mehrere Modellchargen. Danach wird das echte Soai-Reaktionsschema erläutert.','Die Modelle sind zum freien Erkunden da, nicht als Aufgaben oder Prüfung. Bei jedem Modell steht, was verändert werden kann, wie seine Anzeige zu verstehen ist und wo seine Grenzen liegen. Wikipedia-Lesefenster und die wissenschaftlichen Quellen ermöglichen anschließend eine weitere Vertiefung.']}
  ];
  const surfaces=new Map();
  let trekOverlay=false,trekReflected=false;
  function updateTrek(){const stage=$('trek-stage');stage.classList.toggle('is-overlaid',trekOverlay);stage.classList.toggle('is-reflected',trekReflected);$('trek-overlay').setAttribute('aria-pressed',trekOverlay);$('trek-reflect').setAttribute('aria-pressed',trekReflected);$('trek-overlay').textContent=trekOverlay?'Nebeneinander zeigen':'Gesichter übereinanderlegen';$('trek-reflect').textContent=trekReflected?'Spiegelung aufheben':'Lokai spiegeln';$('trek-status').textContent=trekReflected?(trekOverlay?'Gespiegelt und überlagert: Konturen und Farbseiten stimmen im schematischen Modell überein.':'Lokai ist gespiegelt: Jetzt liegt Schwarz auf derselben Bildseite wie bei Bele.'):(trekOverlay?'Überlagert: Die Konturen passen, aber jede Farbfläche liegt über der entgegengesetzten Farbe.':'Nebeneinander: gleiche Konturen, entgegengesetzte Farbseiten.');}
  $('trek-overlay').onclick=()=>{trekOverlay=!trekOverlay;updateTrek();};$('trek-reflect').onclick=()=>{trekReflected=!trekReflected;updateTrek();};$('trek-reset').onclick=()=>{trekOverlay=false;trekReflected=false;updateTrek();};
  function surface(id){const el=$(id),ctx=el.getContext('2d'),item={el,ctx,w:0,h:0,visible:true};surfaces.set(id,item);return item;}
  ['film-canvas','mirror-canvas','mixture-canvas','curve-canvas','feedback-canvas'].forEach(surface);
  function resize(item){const r=item.el.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(r.width<1||r.height<1)return;item.w=r.width;item.h=r.height;item.el.width=Math.round(r.width*d);item.el.height=Math.round(r.height*d);item.ctx.setTransform(d,0,0,d,0,0);}
  const ro=new ResizeObserver(entries=>{entries.forEach(({target})=>resize(surfaces.get(target.id)));fitFilm();paint();});surfaces.forEach(s=>ro.observe(s.el));
  const io=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{surfaces.get(target.id).visible=isIntersecting;}),{rootMargin:'100px'});surfaces.forEach(s=>io.observe(s.el));
  function clear(s){s.ctx.clearRect(0,0,s.w,s.h);}
  function text(ctx,str,x,y,size=13,color=colors.ink,align='center',font='Outfit'){ctx.fillStyle=color;ctx.font=`${size}px ${font}, sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(str,x,y);}
  function sphere(ctx,x,y,r,color,alpha=1){ctx.save();ctx.globalAlpha=alpha;const g=ctx.createRadialGradient(x-r*.35,y-r*.42,r*.06,x,y,r);g.addColorStop(0,'#ffffff');g.addColorStop(.23,color);g.addColorStop(1,shade(color,.43));ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,Math.max(.2,r),0,TAU);ctx.fill();ctx.restore();}
  function shade(hex,f){const n=parseInt(hex.slice(1),16);return `rgb(${Math.round((n>>16)*f)},${Math.round((n>>8&255)*f)},${Math.round((n&255)*f)})`;}
  function glow(ctx,x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color+'25');g.addColorStop(1,color+'00');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
  const vertices=[[1,1,1],[-1,-1,1],[-1,1,-1],[1,-1,-1]],ligands=['OH','COOH','CH₃','H'],ligandColors=['#ee956d','#69cec6','#a8b4ce','#e5c681'];
  function molecule(ctx,x,y,r,rotationY,rotationX,mirror=false,dark=false,labels=true,alpha=1){
    const points=vertices.map((v,i)=>{const p=C.rotate([mirror?-v[0]:v[0],v[1],v[2]],rotationY,rotationX),pers=1/(1-p[2]*.13);return {x:x+p[0]*r*.56*pers,y:y+p[1]*r*.56*pers,z:p[2],i,scale:pers};});
    ctx.save();ctx.globalAlpha=alpha;
    const all=[...points.map(p=>({z:p.z/2,type:'bond',p})),...points.map(p=>({z:p.z,type:'atom',p})),{z:0,type:'center'}].sort((a,b)=>a.z-b.z);
    for(const item of all){if(item.type==='bond'){const p=item.p;ctx.strokeStyle=dark?'#b3cdcdbb':'#a2b5ad';ctx.lineWidth=Math.max(3,r*.055);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.strokeStyle=dark?'#e7f0e244':'#faffff';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-1,y-2);ctx.lineTo(p.x-1,p.y-2);ctx.stroke();}else if(item.type==='center'){sphere(ctx,x,y,r*.17,dark?'#8eaaae':'#60797d');if(labels)text(ctx,'C',x,y,r*.12,'#ffffff');}else{const p=item.p;sphere(ctx,p.x,p.y,r*(p.i===3?.125:.19)*p.scale,ligandColors[p.i]);if(labels){const dx=p.x-x,dy=p.y-y,len=Math.hypot(dx,dy)||1;const offset=r*.29;const label=ligands[p.i];text(ctx,label,p.x+dx/len*offset,p.y+dy/len*offset,Math.max(12,r*.14),dark?'#eff3df':colors.ink);}}}
    ctx.restore();return points;
  }
  function drawMirror(){const s=surfaces.get('mirror-canvas');if(!s.w)return;clear(s);const {ctx,w,h}=s,r=Math.min(w*.19,h*.31);if(!overlay){ctx.strokeStyle='#8ea89b80';ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(w/2,25);ctx.lineTo(w/2,h-20);ctx.stroke();ctx.setLineDash([]);const g=ctx.createLinearGradient(w/2-24,0,w/2+24,0);g.addColorStop(0,'#71998b00');g.addColorStop(.5,'#71998b18');g.addColorStop(1,'#71998b00');ctx.fillStyle=g;ctx.fillRect(w/2-24,20,48,h-40);molecule(ctx,w*.26,h*.5,r,mirrorY,mirrorX,false);molecule(ctx,w*.74,h*.5,r,-mirrorY,mirrorX,true);}else{molecule(ctx,w*.5,h*.5,r*1.15,mirrorY,mirrorX,false,false,true,.9);molecule(ctx,w*.5,h*.5,r*1.15,mirrorY,mirrorX,true,false,false,.32);text(ctx,'Gleicher Mittelpunkt ≠ gleiche räumliche Anordnung',w*.5,h-28,Math.min(14,w/28),colors.muted);}}
  const dots=Array.from({length:180},(_,i)=>({angle:i*2.39996323,r:Math.sqrt((i+.5)/180),phase:i*.71}));
  function cloud(ctx,x,y,r,share,t,n=180,drift=5){for(let i=0;i<n;i++){const d=dots[i],angle=d.angle;const dx=Math.cos(angle)*d.r*r+Math.sin(t*.55+d.phase)*drift,dy=Math.sin(angle)*d.r*r+Math.cos(t*.45+d.phase)*drift;const isA=(i*73)%n<Math.round(share*n);ctx.fillStyle=isA?colors.a:colors.b;ctx.globalAlpha=.45+.55*(1-d.r*.7);ctx.beginPath();ctx.arc(x+dx,y+dy,Math.max(2,r*.017)*(1+d.r*.35),0,TAU);ctx.fill();}ctx.globalAlpha=1;}
  function drawMixture(){const s=surfaces.get('mixture-canvas');if(!s.w)return;clear(s);cloud(s.ctx,s.w/2,s.h/2,Math.min(s.w*.43,s.h*.43),Number($('mixture-range').value)/100,time);}
  function updateMixture(){const a=Number($('mixture-range').value),b=100-a; $('share-a').textContent=a+' %';$('share-b').textContent=b+' %';$('mixture-value').textContent=a;$('mixture-ee').textContent=Math.abs(a-b)+' %';$('mixture-detail').textContent=`|${a} % − ${b} %| = ${Math.abs(a-b)} % ee · ${a===b?'Racemat: kein Enantiomer überwiegt.':(a>b?'A':'B')+' überwiegt.'}`;drawMixture();}
  $('mixture-range').addEventListener('input',updateMixture);document.querySelectorAll('[data-mixture]').forEach(b=>b.addEventListener('click',()=>{$('mixture-range').value=b.dataset.mixture;updateMixture();}));
  function excessLabel(e,d=1){return Math.abs(e)<1e-10?'0 % · ausgeglichen':fmt(Math.abs(e)*100,d)+' % '+(e>0?'A':'B');}
  function chart(ctx,x,y,w,h,mode,e,dark=false,compact=false){
    const color=dark?'#c6d9d9':colors.muted,grid=dark?'#47636966':'#d5ddd2';
    ctx.lineWidth=1;ctx.strokeStyle=grid;for(let i=0;i<=4;i++){const f=i/4;ctx.beginPath();ctx.moveTo(x+f*w,y);ctx.lineTo(x+f*w,y+h);ctx.moveTo(x,y+f*h);ctx.lineTo(x+w,y+f*h);ctx.stroke();if(!compact){text(ctx,String(i*50-100),x+f*w,y+h+19,11,color);text(ctx,String(100-i*50),x-25,y+f*h,11,color);}}
    ctx.strokeStyle=dark?'#82a1a5':'#82979a';ctx.lineWidth=1.5;ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(x,y+h);ctx.lineTo(x+w,y);ctx.stroke();ctx.setLineDash([]);
    ctx.lineWidth=3;ctx.strokeStyle=dark?colors.gold:'#9d5538';ctx.beginPath();for(let i=0;i<=120;i++){const a=-1+i/60,b=C.response(a,mode),px=x+(a+1)*w/2,py=y+(1-b)*h/2;if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.stroke();
    const px=x+(e+1)*w/2,py=y+(1-C.response(e,mode))*h/2;ctx.strokeStyle=dark?'#bcd1ca88':'#829a9c';ctx.setLineDash([3,5]);ctx.beginPath();ctx.moveTo(px,y+h);ctx.lineTo(px,py);ctx.lineTo(x,py);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=dark?colors.gold:'#a05b3d';ctx.beginPath();ctx.arc(px,py,6,0,TAU);ctx.fill();
  }
  function drawCurve(){const s=surfaces.get('curve-canvas');if(!s.w)return;clear(s);const {ctx,w,h}=s;chart(ctx,64,44,w-88,h-105,$('curve-mode').value,Number($('curve-range').value)/100);text(ctx,'Produkt: Überschuss (%)',64,18,12,colors.muted,'left');text(ctx,'Katalysator: Überschuss (%)',w/2,h-17,12,colors.muted);}
  function updateCurve(){const e=Number($('curve-range').value)/100,mode=$('curve-mode').value,p=C.pairs(e);$('curve-input').textContent=excessLabel(e,0);$('curve-output').textContent=excessLabel(C.response(e,mode));$('curve-description').textContent=mode==='positive'?'Nur gleichhändige Paare arbeiten im Modell. Gemischte Paare sind inaktiv. Der Produkt-Überschuss wird dadurch verstärkt.':mode==='linear'?'Die Zusammensetzung des Produkts folgt proportional dem Katalysator. Der Überschuss bleibt gleich.':'Die gewählte Vergleichskurve schwächt den Überschuss ab. Sie illustriert Nichtlinearität in die andere Richtung.';$('pair-view').hidden=mode!=='positive';$('pair-view').replaceChildren();if(mode==='positive')for(const [name,share,labels] of [['AA',p.aa,['a','a']],['AB',p.ab,['a','b']],['BB',p.bb,['b','b']]]){const el=document.createElement('div');el.className='pair'+(name==='AB'?' inactive':'');const b=document.createElement('b');b.textContent=name;const icons=document.createElement('div');icons.className='pair-icons';labels.forEach(l=>{const i=document.createElement('i');i.className=l;icons.append(i);});const span=document.createElement('span');span.textContent=fmt(share*100)+' % · '+(name==='AB'?'inaktiv':'aktiv');el.append(b,icons,span);$('pair-view').append(el);}drawCurve();}
  $('curve-range').addEventListener('input',updateCurve);$('curve-mode').addEventListener('change',updateCurve);
  function values(){return C.batches(Number($('seed-range').value)/100,10);}
  function updateFeedback(){const v=values(),i=Number($('batch-range').value),e=v[i];$('seed-value').textContent=excessLabel(v[0]);$('batch-value').textContent=i;$('batch-label').textContent=i===0?'Startmischung':`Produkt der ${i}. Modellcharge`;$('feedback-percent').textContent=fmt(Math.abs(e)*100)+' % ee';$('feedback-detail').textContent=e===0?'Exakt ausgeglichen bleibt ausgeglichen. Dieses symmetrische Modell bevorzugt keine Seite von selbst.':`${e>0?'A':'B'} überwiegt. Aus ${fmt(Math.abs(v[0])*100)} % anfänglichem Überschuss werden nach ${i} ${i===1?'Runde':'Runden'} ${fmt(Math.abs(e)*100)} % ee.`;$('feedback-step').disabled=i===10;$('growth-bars').replaceChildren();v.forEach((e,n)=>{const bar=document.createElement('div');bar.className=n>i?'inactive':n===i?'current':'';bar.title=`${n===0?'Start':'Charge '+n}: ${excessLabel(e)}`;const fill=document.createElement('i');fill.style.setProperty('--height',Math.max(2,Math.abs(e)*70)+'px');const num=document.createElement('small');num.textContent=n;bar.append(fill,num);$('growth-bars').append(bar);});drawFeedback();}
  $('seed-range').addEventListener('input',updateFeedback);$('batch-range').addEventListener('input',updateFeedback);$('feedback-step').onclick=()=>{$('batch-range').value=Math.min(10,Number($('batch-range').value)+1);updateFeedback();};$('feedback-reset').onclick=()=>{$('batch-range').value=0;updateFeedback();};document.querySelectorAll('[data-seed]').forEach(b=>b.onclick=()=>{$('seed-range').value=b.dataset.seed;$('batch-range').value=0;updateFeedback();});
  function ring(ctx,x,y,r,t,color=colors.gold){ctx.strokeStyle=color+'66';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,r,-Math.PI*.35,Math.PI*1.5);ctx.stroke();const a=Math.PI*1.5;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x+Math.cos(a)*r,y+Math.sin(a)*r);ctx.lineTo(x+Math.cos(a)*r-6,y+Math.sin(a)*r+10);ctx.lineTo(x+Math.cos(a)*r-12,y+Math.sin(a)*r);ctx.fill();for(let i=0;i<3;i++){const angle=t*.35+i*TAU/3;ctx.fillStyle=color;ctx.beginPath();ctx.arc(x+Math.cos(angle)*r,y+Math.sin(angle)*r,3,0,TAU);ctx.fill();}}
  function drawFeedback(){const s=surfaces.get('feedback-canvas');if(!s.w)return;clear(s);const {ctx,w,h}=s,e=values()[Number($('batch-range').value)],r=Math.min(w*.33,h*.34);glow(ctx,w/2,h*.48,r*1.4,colors.gold);ring(ctx,w/2,h*.48,r*1.14,time);cloud(ctx,w/2,h*.48,r*.8,(e+1)/2,time,180,3);text(ctx,'PRODUKT → KATALYSE → MEHR PRODUKT',w/2,h-24,Math.min(11,w/37),'#b6d0cc','center','Mono');}
  let pointer=null;
  $('mirror-canvas').addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY};dragging=true;e.currentTarget.setPointerCapture(e.pointerId);});
  $('mirror-canvas').addEventListener('pointermove',e=>{if(!pointer)return;mirrorY+=(e.clientX-pointer.x)*.012;mirrorX=C.clamp(mirrorX+(e.clientY-pointer.y)*.012,-Math.PI,Math.PI);pointer={x:e.clientX,y:e.clientY};drawMirror();});
  for(const evt of ['pointerup','pointercancel','lostpointercapture'])$('mirror-canvas').addEventListener(evt,()=>{pointer=null;dragging=false;});
  $('mirror-canvas').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')mirrorY-=.15;if(e.key==='ArrowRight')mirrorY+=.15;if(e.key==='ArrowUp')mirrorX-=.15;if(e.key==='ArrowDown')mirrorX+=.15;drawMirror();}});
  $('mirror-overlay').onclick=()=>{overlay=!overlay;$('mirror-overlay').setAttribute('aria-pressed',overlay);$('mirror-overlay').textContent=overlay?'Nebeneinander zeigen':'Übereinanderlegen';$('mirror-explanation').textContent=overlay?'B liegt transparent über A. Die Mittelpunkte stimmen überein, aber nicht alle vier Gruppen. Drehen erhält die Händigkeit.':'Vier verschiedene Gruppen: H, OH, CH₃ und COOH. Farben markieren Gruppen, nicht elektrische Ladungen.';drawMirror();};
  $('mirror-reset').onclick=()=>{mirrorX=.18;mirrorY=.6;drawMirror();};
  function lineGrid(ctx,w,h,dark=true){ctx.strokeStyle=dark?'#7c9e9b0d':'#b4c4b01a';ctx.lineWidth=1;const step=44;for(let x=0;x<w;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}}
  function drawFilm(){const s=surfaces.get('film-canvas');if(!s.w)return;clear(s);const {ctx,w,h}=s,mode=scenes[film.index].mode,mobile=w<700&&h>w*.8;
    lineGrid(ctx,w,h);const r=Math.min(mobile?w*.28:w*.18,mobile?h*.21:h*.32),x=mobile?w*.5:w*.755,y=mobile?h-r*1.25-40:h*.51;glow(ctx,x-r*.6,y-r*.15,r*1.6,colors.a);glow(ctx,x+r*.6,y+r*.1,r*1.6,colors.b);
    const t=time;
    if(mode==='cover'||mode==='mirror'){
      const gap=mode==='cover'?.45:.54;const rr=r*(mobile?.6:.7);ctx.strokeStyle='#a5cebc44';ctx.setLineDash([4,7]);ctx.beginPath();ctx.moveTo(x,y-r*1.15);ctx.lineTo(x,y+r*1.15);ctx.stroke();ctx.setLineDash([]);
      const angle=.65+Math.sin(t*.21)*.65;molecule(ctx,x-r*gap,y-r*.12,rr,angle,.3,false,true,mode==='mirror');molecule(ctx,x+r*gap,y+r*.12,rr,-angle,.3,true,true,mode==='mirror');
      ctx.strokeStyle='#99bfaa38';ctx.beginPath();ctx.ellipse(x,y,r*1.25,r*.94,-.3,0,TAU);ctx.stroke();text(ctx,'A',x-r*.55,y+r*.9,18,colors.a);text(ctx,'B',x+r*.55,y+r*.9,18,colors.b);
    }else if(mode==='mixture'||mode==='amplify'){
      const e=mode==='mixture'?.02:C.response(.02+Math.sin(t*.16)*.01);const amplified=mode==='amplify'?C.batches(e,5)[5]:e;cloud(ctx,x,y,r*.9,(amplified+1)/2,t,180,4);ring(ctx,x,y,r*1.05,t,mode==='amplify'?colors.gold:'#82aba5');text(ctx,mode==='mixture'?'51 % A  /  49 % B':fmt(Math.abs(amplified)*100,0)+' % ee · Modell',x,y+r*1.25,Math.min(19,r*.17),colors.gold,'center','Mono');
    }else if(mode==='curve'){
      const side=r*1.7;chart(ctx,x-side*.5,y-side*.45,side,side*.85,'positive',.2,true,true);text(ctx,'Katalysator',x,y+side*.51,12,'#bfd0cd');text(ctx,'Produkt',x-side*.5,y-side*.45-20,12,'#bfd0cd','left');
    }else if(mode==='loop'){
      ring(ctx,x,y,r,t);molecule(ctx,x,y,r*.65,.6+t*.12,.3,false,true,false);text(ctx,'PRODUKT',x,y-r*1.24,12,colors.gold,'center','Mono');text(ctx,'wirkt an eigener Bildung mit',x,y+r*1.28,Math.min(15,w*.027),'#bfd0cd');
    }else if(mode==='life'){
      // A schematic double strand: an illustration of biological structure,
      // not an enantiomer assignment or proof of a biological origin.
      const bottom=y+r*1.25,top=y-r*1.25;for(let i=0;i<24;i++){const f=i/23,a=f*Math.PI*3+t*.2,yy=top+f*(bottom-top),dx=Math.sin(a)*r*.54;ctx.strokeStyle='#b8d5be77';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-dx,yy);ctx.lineTo(x+dx,yy);ctx.stroke();sphere(ctx,x-dx,yy,r*.053,colors.a);sphere(ctx,x+dx,yy,r*.053,colors.b);}text(ctx,'BIOLOGIE IST RÄUMLICH',x,bottom+24,Math.min(12,w*.025),colors.gold,'center','Mono');
    }else if(mode==='people'){
      const rr=r*.6;for(const [dx,name,year,color] of [[-.55,'KAGAN','1986',colors.a],[.55,'SOAI','1995',colors.b]]){ctx.strokeStyle=color+'88';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x+r*dx,y,rr,0,TAU);ctx.stroke();text(ctx,name,x+r*dx,y-8,Math.min(18,r*.17),color,'center','Mono');text(ctx,year,x+r*dx,y+22,Math.min(15,r*.14),'#cbded8');}text(ctx,'2026',x,y+r,Math.min(36,r*.35),colors.gold,'center','Lora');
    }
  }
  scenes.forEach((s,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`Szene ${i+1}: ${s.tag}`);b.onclick=()=>showScene(i);$('film-dots').append(b);});
  function fitFilm(){const screen=$('film-screen'),full=document.fullscreenElement===$('auftakt')||$('auftakt').classList.contains('fullscreen-fallback');const wanted=!full&&screen.clientWidth<700?Math.max(650,$('film-copy').offsetHeight+330)+'px':'';if(screen.style.height!==wanted)screen.style.height=wanted;}
  function updateSceneNotes(){const note=sceneNotes[film.index];$('scene-comment-title').textContent=note.title;$('scene-comment-text').replaceChildren(...note.paragraphs.map(str=>{const p=document.createElement('p');p.textContent=str;return p;}));}
  function showScene(index){film.index=C.clamp(index,0,scenes.length-1);film.elapsed=0;const s=scenes[film.index],copy=$('film-copy');copy.classList.remove('fade-in');copy.replaceChildren();const tag=document.createElement('p');tag.className='eyebrow';tag.textContent=s.tag;const title=document.createElement('h2');title.innerHTML=s.title;const p=document.createElement('p');p.textContent=s.text;copy.append(tag,title,p);if(s.final){const a=document.createElement('a');a.className='film-final';a.href='#entdecken';a.textContent='In die Spiegelwelt eintauchen ↓';a.onclick=async()=>{setPlaying(false);await leaveFullscreen();$('entdecken').scrollIntoView({behavior:reduced.matches?'instant':'smooth'});};copy.append(a);}void copy.offsetWidth;copy.classList.add('fade-in');$('film-number').textContent=String(film.index+1).padStart(2,'0');$('film-prev').disabled=film.index===0;$('film-next').textContent=film.index===0?'Start →':film.index===scenes.length-1?'Neustart ↺':'Weiter →';[...$('film-dots').children].forEach((b,i)=>b.setAttribute('aria-current',i===film.index));$('screen-note').textContent=s.mode==='curve'||s.mode==='amplify'?'Illustratives Zahlenmodell · keine experimentellen Messwerte':'Eigene Visualisierung · schematische Moleküldarstellung';updateSceneNotes();if(film.index===scenes.length-1)setPlaying(false);fitFilm();drawFilm();}
  function setPlaying(value){film.playing=value;film.elapsed=0;$('film-play').textContent=value?'Pause':'Selbstablauf';$('film-play').setAttribute('aria-pressed',value);}
  $('film-next').onclick=()=>showScene(film.index===scenes.length-1?0:film.index+1);$('film-prev').onclick=()=>showScene(film.index-1);$('film-play').onclick=()=>{if(film.index===scenes.length-1)showScene(0);setPlaying(!film.playing);};$('film-tempo').onchange=()=>{film.elapsed=0;};
  const cinema=$('auftakt');let fallback=false,focusBefore=null,scrollBefore=0;
  function updateFullscreen(){const full=document.fullscreenElement===cinema||fallback;$('film-fullscreen').textContent=full?'Vollbild beenden':'Vollbild';$('film-fullscreen').setAttribute('aria-pressed',full);fitFilm();}
  async function leaveFullscreen(){if(document.fullscreenElement===cinema){try{await document.exitFullscreen();}catch(_){}}if(fallback){fallback=false;cinema.classList.remove('fullscreen-fallback');document.body.classList.remove('fullscreen-lock');window.scrollTo(0,scrollBefore);focusBefore?.focus({preventScroll:true});}updateFullscreen();}
  $('film-fullscreen').onclick=async()=>{if(fallback||document.fullscreenElement===cinema){await leaveFullscreen();return;}focusBefore=document.activeElement;scrollBefore=scrollY;try{if(!cinema.requestFullscreen)throw Error();await cinema.requestFullscreen();}catch(_){fallback=true;cinema.classList.add('fullscreen-fallback');document.body.classList.add('fullscreen-lock');$('film-fullscreen').focus();}updateFullscreen();};
  document.addEventListener('fullscreenchange',updateFullscreen);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&fallback){leaveFullscreen();return;}if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.target.id==='mirror-canvas')return;const active=document.fullscreenElement===cinema||fallback||cinema.contains(document.activeElement);if(!active)return;if(e.key==='ArrowRight'){e.preventDefault();$('film-next').click();}if(e.key==='ArrowLeft'){e.preventDefault();$('film-prev').click();}if(e.code==='Space'&&e.target.tagName!=='BUTTON'&&e.target.tagName!=='A'){e.preventDefault();setPlaying(!film.playing);}});
  function updateMotion(){ $('motion-toggle').textContent=paused?'Animationen fortsetzen':'Animationen pausieren';$('motion-toggle').setAttribute('aria-pressed',paused);paint();}
  $('motion-toggle').onclick=()=>{paused=!paused;updateMotion();};reduced.addEventListener('change',()=>{paused=reduced.matches;updateMotion();});
  document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden)setPlaying(false);});
  function paint(){for(const [id,s] of surfaces){if(!s.visible)continue;if(id==='film-canvas')drawFilm();if(id==='mirror-canvas')drawMirror();if(id==='mixture-canvas')drawMixture();if(id==='curve-canvas')drawCurve();if(id==='feedback-canvas')drawFeedback();}}
  function frame(now){const dt=last?Math.min((now-last)/1000,.06):0;last=now;const dialogOpen=!!document.querySelector('dialog[open]');if(!document.hidden&&!dialogOpen){if(!paused)time+=dt;if(film.playing&&surfaces.get('film-canvas').visible){film.elapsed+=dt;if(film.elapsed>=Number($('film-tempo').value))showScene(film.index+1);}if(now-lastPaint>1000/30&&!paused){lastPaint=now;drawFilmIfVisible();if(surfaces.get('mixture-canvas').visible)drawMixture();if(surfaces.get('feedback-canvas').visible)drawFeedback();if(surfaces.get('mirror-canvas').visible&&!dragging){mirrorY+=dt*.075;drawMirror();}}}requestAnimationFrame(frame);}
  function drawFilmIfVisible(){if(surfaces.get('film-canvas').visible)drawFilm();}
  updateMixture();updateCurve();updateFeedback();showScene(0);updateMotion();surfaces.forEach(resize);paint();document.fonts.ready.then(paint);requestAnimationFrame(frame);
  // No external image request before the same explicit consent used by the reader.
  const commons={soaiPortrait:{url:'https://www.nobelprize.org/uploads/2026/10/2-2_3-6ac5fc699d670-scaled.jpg',alt:'Kensō Soai, gezeichnet von Niklas Elmehed für Nobel Prize Outreach.'},kagan:{url:'https://www.nobelprize.org/uploads/2026/10/1-2_3-6ac5fc622a9b2-scaled.jpg',alt:'Henri B. Kagan, gezeichnet von Niklas Elmehed für Nobel Prize Outreach.'},medal:{url:'https://upload.wikimedia.org/wikipedia/commons/3/32/Nobel_prize_medal.svg',alt:''},hands:{url:'https://upload.wikimedia.org/wikipedia/commons/e/e8/Chirality_with_hands.svg',alt:'Zwei Hände unter spiegelbildlichen Aminosäure-Modellen mit den Gruppen H, R, COOH und NH₂.'},soai:{url:'https://upload.wikimedia.org/wikipedia/commons/4/45/Soai_Reaction_%C3%9CV2.svg',alt:'Soai-Reaktionsschema: zwei getrennte Versuche mit S- beziehungsweise R-Vorgabe und entsprechendem stark angereichertem Produkt.'}};
  let imageEpoch=0,imagesAllowed=false;
  function resetImages(){imagesAllowed=false;imageEpoch++;document.querySelectorAll('[data-commons]').forEach(slot=>{slot.replaceChildren(document.createTextNode(slot.dataset.commons==='medal'?'':'Externe Abbildung nicht geladen. Über „Wikipedia-Auswahl“ freigeben.'));});}
  function loadImages(){imagesAllowed=true;const epoch=++imageEpoch;document.querySelectorAll('[data-commons]').forEach(slot=>{const source=commons[slot.dataset.commons],img=document.createElement('img');img.alt=source.alt;img.decoding='async';img.referrerPolicy='no-referrer';img.onload=()=>{if(imagesAllowed&&epoch===imageEpoch)slot.replaceChildren(img);};img.onerror=()=>{if(imagesAllowed&&epoch===imageEpoch)slot.textContent=slot.dataset.commons==='medal'?'':'Abbildung momentan nicht erreichbar. Bildquelle über den Link öffnen; die lokalen Modelle bleiben nutzbar.';};img.src=source.url;});}
  let firstConsent=true;$('consent').addEventListener('close',()=>{$('consent').returnValue==='allow'?loadImages():resetImages();if(firstConsent){firstConsent=false;requestAnimationFrame(()=>$('film-next').focus({preventScroll:true}));}});$('wiki-revoke').addEventListener('click',resetImages);
  // A passive listener schedules one paint; no continuously running extra loop.
  const backdropMotion=matchMedia('(prefers-reduced-motion: reduce)');
  const peopleBackdrop=document.querySelector('.people-section');
  let backdropFrame=0;
  function paintBackdrop(){
    backdropFrame=0;
    document.body.style.setProperty('--backdrop-scroll',backdropMotion.matches?'0px':`${-scrollY*.2}px`);
    // Compensate the section's own movement so its pattern also moves at 20%.
    if(peopleBackdrop){const top=peopleBackdrop.getBoundingClientRect().top+scrollY;peopleBackdrop.style.setProperty('--people-backdrop-scroll',backdropMotion.matches?'0px':`${(scrollY-top)*.8}px`);}
  }
  function scheduleBackdrop(){if(!backdropFrame)backdropFrame=requestAnimationFrame(paintBackdrop);}
  addEventListener('scroll',scheduleBackdrop,{passive:true});
  addEventListener('resize',scheduleBackdrop,{passive:true});
  backdropMotion.addEventListener('change',scheduleBackdrop);
  paintBackdrop();
})();
