(function(){
  'use strict';
  const $=id=>document.getElementById(id),KEY='themen-los:v1';
  const input=$('group-count'),form=$('draw-form'),result=$('result'),status=$('status');
  function element(tag,text){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;}
  function valid(value){return value&&Number.isInteger(value.count)&&value.count>=1&&value.count<=26&&Array.isArray(value.topics)&&value.topics.length===value.count&&new Set(value.topics).size===value.count&&value.topics.every(i=>Number.isInteger(i)&&i>=0&&i<value.count);}
  function randomIndex(limit){try{const bucket=new Uint32Array(1),ceiling=Math.floor(4294967296/limit)*limit;do{crypto.getRandomValues(bucket);}while(bucket[0]>=ceiling);return bucket[0]%limit;}catch(_){return Math.floor(Math.random()*limit);}}
  function show(value){result.replaceChildren();$('clear').hidden=!valid(value);if(!valid(value)){status.textContent='Noch nicht ausgelost.';const empty=element('p');empty.className='empty';empty.append(element('span','1 → A'),document.createTextNode('Hier erscheint eure ausgeloste Zuordnung.'));empty.firstChild.setAttribute('aria-hidden','true');result.append(empty);return;}const table=element('table'),caption=element('caption','Ausgelost für '+value.count+' '+(value.count===1?'Gruppe':'Gruppen')),head=element('thead'),headRow=element('tr'),body=element('tbody');for(const title of ['Gruppe','Thema']){const th=element('th',title);th.scope='col';headRow.append(th);}head.append(headRow);value.topics.forEach((topic,index)=>{const row=element('tr'),group=element('th','Gruppe '+(index+1));group.scope='row';row.append(group,element('td','Thema '+String.fromCharCode(65+topic)));body.append(row);});table.append(caption,head,body);result.append(table);status.textContent='Themen A'+(value.count>1?'–'+String.fromCharCode(64+value.count):'')+' · Jeder Buchstabe genau einmal vergeben.';}
  try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(valid(saved)){input.value=String(saved.count);show(saved);}}catch(_){}
  form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;const count=Number(input.value);if(!Number.isInteger(count)||count<1||count>26){status.textContent='Bitte eine ganze Gruppenzahl zwischen 1 und 26 eingeben.';return;}const topics=Array.from({length:count},(_,i)=>i);for(let i=topics.length-1;i>0;i--){const j=randomIndex(i+1);[topics[i],topics[j]]=[topics[j],topics[i]];}const value={count,topics};show(value);try{localStorage.setItem(KEY,JSON.stringify(value));}catch(_){$('storage').textContent='Das Ergebnis konnte nicht dauerhaft gespeichert werden. Notiert eure Zuordnung vor dem Schließen.';}};
  input.oninput=()=>{if(result.querySelector('table'))status.textContent='Neue Gruppenzahl noch nicht ausgelost. Die Tabelle zeigt weiterhin das bisherige Ergebnis.';};
  $('clear').onclick=()=>{try{localStorage.removeItem(KEY);}catch(_){}input.value='6';show(null);};
  let theme='light';try{theme=localStorage.getItem(KEY+':theme')==='dark'?'dark':'light';}catch(_){}
  function appearance(){document.body.dataset.theme=theme;$('theme').textContent=theme==='dark'?'Helles Farbschema':'Dunkles Farbschema';}
  $('theme').onclick=()=>{theme=theme==='dark'?'light':'dark';appearance();try{localStorage.setItem(KEY+':theme',theme);}catch(_){}};appearance();
  $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else status.textContent='Dieser Browser unterstützt hier keinen Vollbildmodus.';}catch(_){status.textContent='Vollbild konnte nicht gestartet werden. Nutzt bei Bedarf den Vollbildmodus eures Browsers.';}};
  document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Vollbild beenden':'Vollbild';});
})();
