(function(){
  'use strict';
  const $=id=>document.getElementById(id), C=window.TypoCore;
  const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  const on=(ids,fn,event='input')=>ids.forEach(id=>$(id).addEventListener(event,fn));
  const dec=(value,digits=2)=>Number(value).toLocaleString('de-DE',{minimumFractionDigits:digits,maximumFractionDigits:digits});
  const fonts=new Map();let catalogue,artAllowed=false,artEpoch=0,artImage=null;
  function icons(){window.lucide?.createIcons({attrs:{'aria-hidden':'true','focusable':'false'}});}
  icons();

  // Decoration never controls the reading experience or forces movement.
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,heroIndex=0;
  const heroFamilies=['EB Garamond','Source Sans 3','Libre Bodoni','Dancing Script','Libre Baskerville'];
  function motion(){document.body.classList.toggle('motion-paused',paused);$('motion-toggle').setAttribute('aria-pressed',String(paused));$('motion-toggle').querySelector('span').textContent=paused?'Animation fortsetzen':'Animation pausieren';}
  $('motion-toggle').onclick=()=>{paused=!paused;motion();};reduced.addEventListener('change',e=>{paused=e.matches;motion();});motion();
  setInterval(()=>{if(paused||document.hidden)return;heroIndex=(heroIndex+1)%heroFamilies.length;const name=heroFamilies[heroIndex];$('hero-letter').style.fontFamily='"'+name+'"';$('hero-font').textContent=name;},6000);
  let scheduled=false;
  function scrollProgress(){const total=document.documentElement.scrollHeight-innerHeight;$('reading-progress').style.width=(total>0?scrollY/total*100:0)+'%';scheduled=false;}
  addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(scrollProgress);}},{passive:true});scrollProgress();
  const navLinks=[...document.querySelectorAll('.chapter-nav a')];
  const navObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)navLinks.forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id));},{rootMargin:'-15% 0px -70% 0px'});
  navLinks.forEach(a=>navObserver.observe(document.querySelector(a.hash)));

  function connection(remote){$('connection-diagram').classList.toggle('remote',remote);$('connection-local').setAttribute('aria-pressed',String(!remote));$('connection-remote').setAttribute('aria-pressed',String(remote));$('connection-explanation').textContent=remote?'Die Webseite lädt zusätzliche Schriftdateien beim Fontdienst. Dorthin gelangen IP-Adresse und technische Verbindungsdaten.':'HTML und Schriftdateien kommen vom eigenen Webangebot. Keine zusätzliche Fontverbindung zu Google.';}
  $('connection-local').onclick=()=>connection(false);$('connection-remote').onclick=()=>connection(true);
  $('anatomy-font').onchange=()=>$('anatomy-word').style.fontFamily='"'+$('anatomy-font').value+'"';
  const pairs={humanist:['Inter','Source Sans 3','groteskbetont','humanistisch'],geometric:['Poppins','Source Sans 3','geometrisch','humanistisch'],rounded:['Nunito','Inter','gerundet','groteskbetont']};
  $('sans-pair').onchange=()=>{const pair=pairs[$('sans-pair').value];['a','b'].forEach((id,i)=>{$('sans-sample-'+id).style.fontFamily='"'+pair[i]+'"';$('sans-label-'+id).textContent=pair[i]+' · '+pair[i+2];});};
  $('variable-weight').oninput=()=>{const v=$('variable-weight').value;$('variable-value').textContent=v;$('variable-specimen').style.fontWeight=v;};

  async function loadFonts(){
    try{const r=await fetch('data/typografie-fonts.json',{credentials:'omit'});if(!r.ok)throw Error();catalogue=await r.json();catalogue.families.forEach(f=>fonts.set(f.name,f));$('catalog-count').textContent=fonts.size;$('hero-count').textContent=fonts.size;renderFonts();updateBook();}
    catch(_){$('catalog-status').textContent='Das Schriftverzeichnis konnte nicht geladen werden. Die übrigen Werkstätten und Downloads bleiben nutzbar.';const retry=node('button',null,'Verzeichnis erneut laden');retry.onclick=()=>{retry.remove();loadFonts();};$('catalog-status').after(retry);}
  }
  const groupLabels={serif:'Serif / Antiqua',sans:'Sans Serif',script:'Hand- und Schreibschrift',display:'Display / Schmuck',mono:'Monospace'};
  function renderFonts(){
    if(!catalogue)return;
    const term=$('font-search').value.toLocaleLowerCase('de'),group=$('font-group').value;
    const list=catalogue.families.filter(f=>(group==='all'||f.group===group)&&[f.name,f.designer,f.classification,f.advice].join(' ').toLocaleLowerCase('de').includes(term));
    $('font-grid').replaceChildren();$('catalog-status').textContent=list.length+' von '+catalogue.families.length+' Familien · Stand '+catalogue.checked;
    for(const f of list){
      const card=node('article','font-card'),title=node('h3',null,f.name);card.append(title,node('p','font-category',groupLabels[f.group]+' · '+f.classification));
      const sample=node('p','font-sample',$('specimen-input').value||'Lesen heißt weiterdenken.');sample.style.fontFamily='"'+f.name+'"';card.append(sample);
      const label=node('label','font-cuts','Vorhandener Schnitt');const select=node('select');select.setAttribute('aria-label',f.name+' · vorhandenen Schnitt auswählen');
      const cuts=[];
      for(const file of f.files){const weights=Array.isArray(file.weight)?[file.weight[0],400,500,600,700,file.weight[1]].filter(w=>w>=file.weight[0]&&w<=file.weight[1]):[file.weight];for(const weight of weights){const key=weight+'-'+file.style;if(cuts.some(c=>c.key===key))continue;cuts.push({key,weight,style:file.style});}}
      cuts.sort((a,b)=>a.style.localeCompare(b.style)||a.weight-b.weight);
      cuts.forEach(c=>{const option=node('option',null,c.weight+(c.style==='italic'?' · echte Kursive':''));option.value=c.key;option.selected=c.weight===400&&c.style==='normal';select.append(option);});
      select.onchange=()=>{const cut=cuts.find(c=>c.key===select.value);sample.style.fontWeight=cut.weight;sample.style.fontStyle=cut.style;};label.append(select);card.append(label,node('p','font-advice',f.advice));
      if(f.new)card.append(node('span','new-tag','Für das Atelier ergänzt'));
      const info=node('details'),summary=node('summary',null,'Dateien, Gestalter & Verwendung');info.append(summary,node('p',null,'Gestaltung: '+f.designer+'. Lizenz: '+f.license+'.'));
      const links=node('p');const licence=node('a',null,'Lokaler Lizenztext');licence.href=f.licensePath;const source=node('a',null,'Offizielles Fontprojekt ↗');source.href=f.source;source.target='_blank';source.rel='noopener noreferrer';links.append(licence,document.createTextNode(' · '),source);info.append(links);
      for(const file of f.files){const a=node('a','font-file',file.path.split('/').pop()+' · '+(file.axes&&Object.keys(file.axes).length?'variabel '+Object.keys(file.axes).join(', '):'statischer Schnitt'));a.href=file.path;a.download='';info.append(a);}
      if(f.features?.length)info.append(node('p','small','OpenType-Tags im vorhandenen Bestand: '+f.features.join(', ')+'. Tags allein garantieren nicht jede Kombination für jedes Zeichen.'));
      if(f.desktop){const a=node('a',null,'Desktop-Paket · Original-TTF'+(f.desktopStatic?' / OTF':'')+' + Lizenz ↓');a.href=f.desktop;a.download='';const p=node('p');p.append(a);info.append(p);}
      if(f.desktopStatic){const p=node('p','small','Zusätzliche statische Desktop-Schnitte: ');const a=node('a',null,'Originalprojekt der Schriftgestalter ↗');a.href=f.desktopStatic.source;a.target='_blank';a.rel='noopener noreferrer';p.append(a);info.append(p);}
      const usage=node('p','small',f.uses.length?'Direkte Dateireferenzen in '+f.uses.length+' HTML-/CSS-Dateien. Kein Laufzeit-Nachweis.':'Für dieses Atelier ergänzt; nicht im vorherigen Bestand referenziert.');info.append(usage);
      const ul=node('ul');f.uses.slice(0,8).forEach(use=>{const li=node('li'),a=node('a',null,use.repo+'/'+use.path);a.href=use.url;a.target='_blank';a.rel='noopener noreferrer';li.append(a);ul.append(li);});if(f.uses.length>8)ul.append(node('li',null,'Weitere '+(f.uses.length-8)+' Referenzen im vollständigen Bestandsdatensatz.'));info.append(ul);
      if(f.uses.length>8){const a=node('a',null,'Vollständigen Bestandsdatensatz ansehen');a.href='data/typografie-fonts.json';info.append(a);}
      card.append(info);$('font-grid').append(card);
    }
  }
  on(['font-search','font-group'],renderFonts);$('specimen-input').oninput=()=>document.querySelectorAll('.font-sample').forEach(p=>p.textContent=$('specimen-input').value||'Lesen heißt weiterdenken.');loadFonts();

  const originalProof=[...$('text-proof').querySelectorAll('p')].map(p=>p.textContent);
  const breaks={'Weiterdenken':'Wei\u00adter\u00adden\u00adken','Aufmerksamkeit':'Auf\u00admerk\u00adsam\u00adkeit','Verantwortung':'Ver\u00adant\u00adwor\u00adtung','Gestaltung':'Ge\u00adstal\u00adtung','Zusammenspiel':'Zu\u00adsam\u00admen\u00adspiel','Zeilenabstand':'Zei\u00adlen\u00adab\u00adstand','Wortabständen':'Wort\u00adab\u00adstän\u00adden','Absatzanfängen':'Ab\u00adsatz\u00adan\u00adfän\u00adgen','Entscheidungen':'Ent\u00adschei\u00addun\u00adgen'};
  function updateProof(){
    const proof=$('text-proof'),size=+$('text-size').value,leading=+$('text-leading').value/100,measure=+$('text-measure').value;
    $('size-value').textContent=size+' px';$('leading-value').textContent=dec(leading);$('measure-value').textContent=measure+' ch';
    Object.assign(proof.style,{fontFamily:'"'+$('body-font').value+'"',fontSize:size+'px',lineHeight:leading,maxWidth:measure+'ch',textAlign:$('text-align').value,hyphens:$('hyphen-toggle').checked?'manual':'none'});
    proof.querySelector('h3').style.fontFamily='"'+$('heading-font').value+'"';proof.classList.toggle('spaced',$('paragraph-mode').value==='space');
    [...proof.querySelectorAll('p')].forEach((p,i)=>p.textContent=$('hyphen-toggle').checked?originalProof[i].replace(/Weiterdenken|Aufmerksamkeit|Verantwortung|Gestaltung|Zusammenspiel|Zeilenabstand|Wortabständen|Absatzanfängen|Entscheidungen/g,w=>breaks[w]):originalProof[i]);
    const warning=$('text-align').value==='justify'&&!$('hyphen-toggle').checked?'Ohne erlaubte Trennungen können im Blocksatz große Wortabstände entstehen.':$('text-align').value==='center'||$('text-align').value==='right'?'Vergleiche den Rücksprung am Zeilenende: Es fehlt eine feste linke Anfangskante.':'Verfolge einen Absatz und den Rücksprung in die nächste Zeile.';
    $('typesetting-status').textContent='Zusätzlicher rechnerischer Zeilenraum: '+dec(size*(leading-1),1)+' px. Die Spalte ist höchstens '+measure+' ch breit; auf kleinen Bildschirmen wird sie schmaler. '+warning;
  }
  on(['body-font','heading-font','text-size','text-leading','text-measure','text-align','paragraph-mode','hyphen-toggle'],updateProof);
  $('reset-typesetting').onclick=()=>{Object.entries({'body-font':'EB Garamond','heading-font':'Source Sans 3','text-size':20,'text-leading':150,'text-measure':56,'text-align':'left','paragraph-mode':'indent'}).forEach(([id,v])=>$(id).value=v);$('hyphen-toggle').checked=true;updateProof();};updateProof();
  function poster(classic){$('tschichold-poster').classList.toggle('classic',classic);$('tschichold-poster').classList.toggle('modern',!classic);$('layout-classic').setAttribute('aria-pressed',String(classic));$('layout-modern').setAttribute('aria-pressed',String(!classic));}
  $('layout-classic').onclick=()=>poster(true);$('layout-modern').onclick=()=>poster(false);
  function updateCanon(){const [w,h]=$('page-format').value==='classic'?[150,225]:[210,297],v=C.canon(w,h);document.querySelectorAll('.book-page').forEach(p=>p.style.aspectRatio=w+'/'+h);$('spread').classList.toggle('hide-grid',!$('show-grid').checked);$('canon-values').textContent='Innen '+dec(v.inner,1)+' mm · außen '+dec(v.outer,1)+' mm · Kopf '+dec(v.top,1)+' mm · Fuß '+dec(v.bottom,1)+' mm. Textblock '+dec(v.textWidth,1)+' × '+dec(v.textHeight,1)+' mm.';}
  on(['page-format','show-grid'],updateCanon);updateCanon();
  function updateBook(){
    const name=$('book-font').value,font=fonts.get(name),hasCaps=font?font.features?.includes('smcp'):name==='EB Garamond';
    $('book-proof').style.fontFamily='"'+name+'"';$('book-body').classList.toggle('spaced',$('book-paragraphs').value==='space');$('book-body').classList.toggle('loud',$('book-headings').value==='loud');
    $('book-running').classList.toggle('no-smallcaps',!$('book-caps').checked||!hasCaps);$('book-running').style.letterSpacing=(+$('caps-spacing').value/100)+'em';$('book-running').title=hasCaps?'Echte Kapitälchen vorhanden':'Diese Fontdatei enthält keine smcp-Kapitälchen; keine künstliche Nachahmung.';
    $('caps-spacing-value').textContent=dec(+$('caps-spacing').value/100)+' em';$('book-footnote').style.fontSize=$('foot-size').value+'px';$('book-footnote').style.marginTop=$('foot-gap').value+'px';$('foot-size-value').textContent=$('foot-size').value+' px';$('foot-gap-value').textContent=$('foot-gap').value+' px';$('book-folio').style.textAlign={outer:'right',center:'center',inside:'left'}[$('folio-position').value];
    let note=$('book-feature-note');if(!note){note=node('p','small');note.id='book-feature-note';$('book-proof').after(note);}note.textContent=hasCaps?'Der Kolumnentitel verwendet echte smcp-Formen, wenn der Schalter eingeschaltet ist.':'Für '+name+' ist im lokalen Bestand kein smcp nachgewiesen. Der Kolumnentitel bleibt in normalen Buchstaben, statt verkleinerte Versalien als echte Kapitälchen auszugeben.';
  }
  on(['book-font','book-paragraphs','book-headings','book-caps','caps-spacing','foot-size','foot-gap','folio-position'],updateBook);
  $('book-reset').onclick=()=>{Object.entries({'book-font':'EB Garamond','book-paragraphs':'indent','book-headings':'restrained','caps-spacing':6,'foot-size':14,'foot-gap':20,'folio-position':'outer'}).forEach(([id,v])=>$(id).value=v);$('book-caps').checked=true;updateBook();};updateBook();
  $('ligature-toggle').onchange=()=>$('ligature-proof').style.fontVariantLigatures=$('ligature-toggle').checked?'common-ligatures':'none';
  $('kerning-toggle').onchange=()=>$('kerning-proof').style.fontKerning=$('kerning-toggle').checked?'normal':'none';

  const palettes={paper:['#202823','#f5f1e8'],night:['#f4ead5','#18251f'],sage:['#263e31','#e6ecdf'],blue:['#18364c','#e8eff4'],bad:['#b2b7a6','#e6e9df']};
  function updateColor(){const fg=$('foreground').value,bg=$('background').value,ratio=C.contrast(fg,bg);const proof=$('color-proof');Object.assign(proof.style,{color:fg,backgroundColor:bg});Object.assign(proof.querySelector('.color-text').style,{color:fg,backgroundColor:bg});proof.dataset.texture=$('texture').value;
    const report=$('contrast-report');report.replaceChildren(node('b',null,dec(ratio)+':1'),node('p',null,(ratio>=4.5?'✓ AA für normalen Text erfüllt.':'✕ AA für normalen Text nicht erfüllt.')+' '+(ratio>=3?'✓ AA für große Schrift erfüllt.':'✕ Auch für große Schrift zu wenig Kontrast.')),node('small',null,'Berechnung des flachen Farbpaars; keine vollständige WCAG-Prüfung.'));
  }
  $('palette').onchange=()=>{[$('foreground').value,$('background').value]=palettes[$('palette').value];updateColor();};on(['foreground','background','texture'],updateColor);updateColor();
  async function loadArt(){
    if(!artAllowed){const dialog=$('art-consent');dialog.returnValue='';dialog.showModal();const allowed=await new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='yes'),{once:true}));if(!allowed)return;artAllowed=true;}
    const epoch=++artEpoch;$('art-load').disabled=true;$('art-load').textContent='Kunstbild wird geladen …';$('art-remove').hidden=false;
    try{const [a,b]=await Promise.all([fetch('data/kunst-hauptwerke.json'),fetch('data/kunstbilder.json')]);if(!a.ok||!b.ok)throw Error();const works=(await a.json()).works,images=(await b.json()).images;const pool=works.map(w=>({work:w,image:images.find(i=>i.id===w.id)})).filter(x=>x.image&&/^https:\/\/(thumb|upload)\.wikimedia\.org\//.test(x.image.imageURL));if(!pool.length)throw Error();const chosen=C.shuffle(pool)[0],img=node('img');img.alt='';img.referrerPolicy='no-referrer';img.decoding='async';artImage=img;
      await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error()),20000);img.onload=()=>{clearTimeout(timeout);resolve();};img.onerror=()=>{clearTimeout(timeout);reject(Error());};img.src=chosen.image.imageURL;});
      if(!artAllowed||epoch!==artEpoch)return;$('art-background').replaceChildren(img);const source=node('a',null,'Bildquelle und Rechte');source.href=chosen.image.imageSource;source.target='_blank';source.rel='noopener noreferrer';$('art-credit').replaceChildren(document.createTextNode(chosen.work.title+' · '+chosen.work.artist+' · '+chosen.image.imageLicense+' · '),source);
    }catch(_){if(artAllowed&&epoch===artEpoch)$('art-credit').textContent='Das optionale Bild ist momentan nicht erreichbar. Text und Farbwerkstatt bleiben vollständig nutzbar.';}
    finally{if(epoch===artEpoch){$('art-load').disabled=false;$('art-load').textContent='Anderes Kunstbild auswählen';}}
  }
  $('art-load').onclick=loadArt;$('art-remove').onclick=()=>{artAllowed=false;artEpoch++;if(artImage)artImage.removeAttribute('src');$('art-background').replaceChildren();$('art-credit').textContent='Bildfreigabe zurückgenommen.';$('art-remove').hidden=true;$('art-load').disabled=false;$('art-load').textContent='Ein Kunstbild aus unserem Archiv laden';};
  function updateIcons(){const size=$('icon-size').value,stroke=+$('icon-stroke').value/100;$('icon-size-value').textContent=size+' px';$('icon-stroke-value').textContent=dec(stroke);$('icon-gallery').querySelectorAll('svg').forEach(s=>{s.style.width=size+'px';s.style.height=size+'px';s.style.strokeWidth=stroke;});}
  on(['icon-size','icon-stroke'],updateIcons);updateIcons();
  const mathExamples={fraction:['x_{1,2}=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}','Zähler und Nenner stehen übereinander; die Wurzel umfasst den gesamten Ausdruck.'],integral:['\\int_0^1 x^2\\,\\mathrm{d}x=\\frac{1}{3}','Grenzen gehören zum Integral. Hier steht das Differential d bewusst aufrecht.'],units:['v=3{,}2\\,\\mathrm{m\\,s^{-1}},\\qquad \\sin(\\alpha)=\\frac{a}{c}','Variable v und Winkel α sind kursiv; Einheit und Funktionsname sin stehen aufrecht.'],matrix:['A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}','Die Klammern passen zur zweizeiligen Matrix. Ein normaler Klammerbuchstabe reicht dafür nicht.']};
  let mathQueue=Promise.resolve(),mathEpoch=0;
  function updateMath(){const epoch=++mathEpoch,example=mathExamples[$('math-example').value];mathQueue=mathQueue.then(async()=>{try{if(!window.MathJax?.startup?.promise)throw Error();await window.MathJax.startup.promise;if(epoch!==mathEpoch)return;window.MathJax.typesetClear?.([$('math-demo')]);$('math-demo').textContent='\\['+example[0]+'\\]';$('math-code').textContent=example[0];$('math-description').textContent=example[1];await window.MathJax.typesetPromise([$('math-demo')]);if(epoch===mathEpoch)$('math-status').textContent='MathJax und mathematische Schriftdateien werden lokal geladen.';}catch(_){$('math-status').textContent='Formelsatz gerade nicht verfügbar. Der TeX-Code bleibt lesbar.';}});}
  $('math-example').onchange=updateMath;updateMath();

  const examples={bericht:{title:'Wie Schrift das Lesen verändert',body:'Dieser Kurzbericht untersucht, wie Schriftgröße, Zeilenlänge und Abstand zusammenwirken. Verglichen werden zwei Satzproben mit identischem Text.\n\nDie schmalere Probe erleichtert den Rücksprung in die nächste Zeile. Eine größere x-Höhe lässt die Buchstaben bei gleichem Schriftgrad kräftiger erscheinen.\n\nDie Beobachtungen sind ein Ausgangspunkt. Vor einer Veröffentlichung werden unterschiedliche Bildschirmgrößen und der tatsächliche Druck geprüft.'},brief:{title:'Einladung zu einem Gestaltungsworkshop',body:'wir möchten gemeinsam untersuchen, wie Schriftwahl und Seitenaufteilung die Verständlichkeit eines Textes beeinflussen.\n\nFür den Workshop bringen alle Teilnehmenden einen kurzen eigenen Text mit. An derselben Textprobe vergleichen wir unterschiedliche Gestaltungsentscheidungen.\n\nBitte teilen Sie uns mit, ob Sie teilnehmen können.'},einladung:{title:'Ein Abend für gute Gedanken',body:'Wir laden herzlich zu einem gemeinsamen Abend ein. Mit kleinen Gestaltungsproben entdecken wir, wie Form und Inhalt zusammenwirken.\n\nBitte geben Sie uns bis eine Woche vorher Bescheid, ob Sie dabei sind. Wir freuen uns auf das Gespräch.'},protokoll:{title:'Gestaltungsgruppe · Sitzung',body:'Die Gruppe vereinbart, den Text zunächst linksbündig zu setzen und den Titel auf eine klare Hierarchie zu beschränken.\n\nDie Schriftgröße wird auf zwei Bildschirmgrößen überprüft. Für die Zahlenübersicht werden Tabellenziffern verwendet.\n\nNächster Schritt: Eine Person prüft die mobile Ansicht, eine andere die Druckvorschau. Ergebnisse werden in der nächsten Sitzung verglichen.'}};
  function fields(){return Object.fromEntries(new FormData($('tex-form')));}
  function generate(){const data=fields(),s=C.texDocument(data);$('tex-output').textContent=s;const preview=$('tex-preview');preview.classList.toggle('invitation',data.kind==='einladung');preview.replaceChildren(node('h3',null,data.title||'Ohne Titel'),node('p','preview-meta',[data.author,data.date].filter(Boolean).join(' · ')));if(data.kind==='brief')preview.append(node('p','preview-meta',data.recipient),node('p',null,'Sehr geehrte Damen und Herren,'));data.body.replace(/\r\n?/g,'\n').split(/\n\s*\n/).forEach(p=>preview.append(node('p',null,p)));$('tex-status').textContent='Code aktualisiert · '+(data.engine==='luatex'?'LuaLaTeX':'pdfLaTeX')+' · DIN A4. Die Eingaben bleiben lokal.';return s;}
  $('tex-form').onsubmit=e=>{e.preventDefault();generate();};$('tex-kind').onchange=()=>{$('recipient-label').hidden=$('tex-kind').value!=='brief';};$('tex-form').addEventListener('input',()=>$('tex-status').textContent='Eingaben geändert. Beim Kopieren oder Download wird der Code aktualisiert.');
  $('tex-example').onclick=()=>{const ex=examples[$('tex-kind').value];$('tex-title').value=ex.title;$('tex-body').value=ex.body;generate();};$('tex-clear').onclick=()=>{['tex-title','tex-author','tex-date','tex-recipient','tex-body'].forEach(id=>$(id).value='');generate();};
  $('tex-copy').onclick=async()=>{const s=generate();try{await navigator.clipboard.writeText(s);$('tex-status').textContent='Code in die Zwischenablage kopiert.';}catch(_){const range=document.createRange();range.selectNodeContents($('tex-output'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);$('tex-status').textContent='Code markiert. Bitte über das Kopiermenü deines Geräts kopieren.';}};
  $('tex-download').onclick=async()=>{const s=generate();let name=$('tex-filename').value.trim().replace(/[\\/:*?"<>|\u0000-\u001f]/g,'-').slice(0,100)||'mein-dokument.tex';if(!/\.tex$/i.test(name))name+='.tex';const blob=new Blob([s],{type:'text/plain;charset=utf-8'});try{if(window.showSaveFilePicker){const handle=await showSaveFilePicker({suggestedName:name,types:[{description:'LaTeX-Quelldatei',accept:{'text/plain':['.tex']}}]});const writer=await handle.createWritable();await writer.write(blob);await writer.close();}else{const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);} $('tex-status').textContent='Download vorbereitet. Dein Browser bestimmt den Speicher- oder Teilen-Dialog.';}catch(e){$('tex-status').textContent=e.name==='AbortError'?'Speichern abgebrochen. Dein Text bleibt erhalten.':'Speichern nicht möglich. Bitte den Code kopieren.';}};generate();

  const questions=[
    ['Eine Schrift ist lokal eingebunden. Was bedeutet das?', ['Die Fontdatei wird vom eigenen Webangebot geladen.','Es gibt überhaupt keine Internetverbindung.','Jeder Besucher muss die Schrift installieren.'],'Der eigene Hostinganbieter wird weiterhin kontaktiert; der zusätzliche Fontdienst wird vermieden.'],
    ['Eine Sans wird als dynamisch bezeichnet. Was ist gemeint?',['Ihr Formprinzip erinnert an Bewegung und Schreibduktus.','Die Buchstaben werden automatisch animiert.','Sie muss ein Variable Font sein.'],'Dynamisches Schriftbild und variable Dateitechnik sind verschiedene Eigenschaften.'],
    ['Ein Titel ist gut lesbar, aber der Absatz darunter sehr blass. Was prüfst du zuerst?',['Das Kontrastverhältnis von Text und Hintergrund.','Ob der Titel eine Schmuckschrift ist.','Ob möglichst viele Farben verwendet werden.'],'Normaler Text braucht auf WCAG-AA-Niveau grundsätzlich mindestens 4,5:1.'],
    ['Auf einem schmalen Handybildschirm entstehen Löcher im Blocksatz. Was ist sinnvoll?',['Trennung und Wortabstände prüfen, gegebenenfalls linksbündig setzen.','Noch mehr Leerzeichen hinzufügen.','Alle Wörter in Versalien setzen.'],'Die Satzart muss zur Spaltenbreite und zum Umbruchsystem passen.'],
    ['Wie werden echte Kapitälchen erzeugt?',['Durch eigens gezeichnete Formen in einer geeigneten Schrift.','Durch beliebiges Verkleinern großer Buchstaben.','Durch Fettdruck aller Kleinbuchstaben.'],'Echte Kapitälchen besitzen zum übrigen Schriftbild passende Strichstärken.'],
    ['Ein Absatz folgt im klassischen Buchsatz direkt auf eine Zwischenüberschrift. Was ist ein sinnvoller Ausgangspunkt?',['Ohne Erstzeileneinzug beginnen.','Drei Leerzeilen und einen großen Einzug einfügen.','Alles kursiv setzen.'],'Die Überschrift kennzeichnet den Neubeginn bereits. Folgeabsätze erhalten den konsistenten Einzug.'],
    ['Was passiert, wenn du Dancing Script stark sperrst?',['Die vorgesehenen Buchstabenverbindungen können zerreißen.','Die Schrift wird automatisch eine Grotesk.','Der Kontrast verbessert sich rechnerisch.'],'Verbundene Schreibschriften brauchen ihren eigenen Rhythmus und ihre Anschlussformen.'],
    ['Wofür eignen sich Tabellenziffern?',['Für Zahlenkolonnen mit gleichen Ziffernbreiten.','Nur für handschriftliche Einladungstitel.','Sie machen jeden Buchstaben gleich breit.'],'Tabellarische Ziffern sind eine Funktion der Ziffern; die übrige Schrift kann proportional bleiben.'],
    ['Was unterscheidet Kerning von Sperrung?',['Kerning korrigiert Paare, Sperrung eine ganze Zeichenfolge.','Kerning ändert die Hintergrundfarbe.','Beide Begriffe bezeichnen den Zeilenabstand.'],'AV und To brauchen oft eine andere Paarbehandlung als etwa HH.'],
    ['Was ist am Namen „Google Fonts“ für die Datenschutzfrage entscheidend?',['Die tatsächliche Einbindung und die dabei entstehenden Verbindungen.','Alle Schriften mit diesem Namen sind verboten.','Schriftlizenzen ersetzen Datenschutzregeln vollständig.'],'Offene Fontlizenz und personenbezogene Verbindungsdaten betreffen verschiedene Fragen.'],
    ['Welche Ränder hat eine klassische Doppelseite?',['Innen-, Außen-, Kopf- und Fußsteg.','Nur links und rechts, unabhängig von der Bindung.','Vier zufällige freie Flächen ohne Beziehung.'],'Die Ränder werden als zusammenhängende Komposition geplant und an die Bindung angepasst.'],
    ['12 pt Schrift, 15 pt Zeilenabstand: Wie viel zusätzlicher Raum ist rechnerisch enthalten?',['3 pt.','15 pt.','27 pt.'],'Die Differenz beträgt 3 pt; die tatsächliche Wirkung hängt von den Buchstabenformen ab.'],
    ['Was braucht ein alleinstehender Lucide-Symbolknopf?',['Einen zugänglichen Namen, etwa „Herunterladen“.','Nur eine möglichst schöne Form.','Eine vom Besucher installierte Iconschrift.'],'Ein Symbol ist nicht für alle eindeutig. Lucide-SVGs sind keine notwendige Schriftinstallation.'],
    ['Wie bleiben Lucide-Symbole lokal?',['Die SVGs oder Bibliothek liegen im eigenen Webangebot.','Ein CDN-Link ist immer lokal, sobald er im HTML steht.','Nur die Fontdateien müssen lokal sein.'],'Auch ein Iconskript kann sonst eine zusätzliche Verbindung zu einem Anbieter herstellen.'],
    ['Warum genügt eine normale Textschrift nicht für jeden mathematischen Ausdruck?',['Formelsatz benötigt besondere Zeichen, Größenvarianten und Anordnung.','Mathematische Zeichen sind immer Fotos.','Jede Textschrift enthält automatisch alle Wurzeln und Klammergrößen.'],'MathJax und geeignete Mathematikfonts können diese Aufgaben übernehmen.'],
    ['Was gehört bei lokalem MathJax zur Prüfung?',['Hauptskript, Erweiterungen und nachgeladene Fontteile.','Nur das erste sichtbare Minuszeichen.','Nur der Dateiname der HTML-Seite.'],'Seltene Zeichen können weitere Dateien benötigen; auch diese Pfade müssen lokal eingerichtet sein.'],
    ['Ist MathJax ein vollständiger LaTeX-Compiler für einen Brief?',['Nein, es rendert mathematische Ausdrücke im Browser.','Ja, es erstellt automatisch ein druckfertiges Dokument.','Ja, aber nur bei Serifenschriften.'],'Ein vollständiges Dokument wird beispielsweise mit pdfLaTeX oder LuaLaTeX kompiliert.'],
    ['Du wechselst in Word eine Schrift für alle Absätze. Was ist der verlässliche Weg?',['Die zugehörige Formatvorlage ändern.','Jeden Absatz einzeln markieren und formatieren.','Die Abstände mit Leerzeichen nachbauen.'],'Eine gemeinsame Formatvorlage hält wiederkehrende Ebenen konsistent.'],
    ['Wie setzt du eine Fußnote?',['Mit der echten Fußnotenfunktion des Satzprogramms.','Als beliebig kleinen Absatz auf irgendeiner späteren Seite.','Als Teil des Dateinamens.'],'Die Funktion verknüpft Hinweis und Note und bezieht den Umbruch ein.'],
    ['Was bedeutet eine leere Zeile im LaTeX-Quelltext?',['Ein neuer Absatz beginnt.','Es wird immer eine ganze leere Druckzeile eingefügt.','Die Schrift wird kursiv.'],'Absatz und sichtbarer Abstand sind zwei unterschiedliche Dinge.'],
    ['Was musst du bei einem Onlinecompiler beachten?',['Texte und hochgeladene Dateien gelangen zu dessen Servern.','Der Compiler sieht die lokalen Fontdateien automatisch.','Deine Eingabe bleibt dort garantiert nur auf deinem Gerät.'],'Die Fontdateien und geeignete Engine müssen im Projekt vorhanden sein; vertrauliche Daten nicht unbedacht hochladen.'],
    ['Welche Aussage über Tschichold passt?',['Er arbeitete sowohl mit neuer asymmetrischer Typografie als auch klassischem Buchsatz.','Er erlaubte grundsätzlich nur symmetrische Seiten.','Er erfand Google Fonts.'],'Medium und Funktion sind wichtig: Plakat, Buch und Browser brauchen nicht dieselbe Lösung.'],
    ['Was ist eine Ligatur?',['Eine gemeinsam gestaltete Glyphe für mehrere zugrunde liegende Buchstaben.','Eine neue Bedeutung des Wortes.','Eine automatische Übersetzung.'],'Die Buchstaben bleiben als Zeichen erhalten, wenn der Font sie bei der Darstellung verbindet.'],
    ['Wie lautet der Bereichsstrich korrekt?',['2024–2026.','2024 - 2026 mit einem kurzen Bindestrich.','2024_2026.'],'Der Halbgeviertstrich zwischen Bereichsgrenzen wird in diesem Fall ohne Leerzeichen gesetzt.'],
  ];
  let round=[],questionIndex=0,score=0,answered=false;
  function startQuiz(){round=C.shuffle(questions).slice(0,6);questionIndex=0;score=0;showQuestion();}
  function showQuestion(){answered=false;$('quiz-next').hidden=true;$('quiz-feedback').textContent='';$('quiz-progress').textContent='Fall '+(questionIndex+1)+' von 6 · '+score+' begründet richtig';const q=round[questionIndex];$('quiz-question').textContent=q[0];$('quiz-options').replaceChildren();C.shuffle(q[1].map((text,i)=>({text,right:i===0}))).forEach(option=>{const button=node('button',null,option.text);button.onclick=()=>{if(answered)return;answered=true;if(option.right)score++;$('quiz-options').querySelectorAll('button').forEach(b=>b.disabled=true);button.classList.add(option.right?'correct':'incorrect');button.textContent=(option.right?'✓ ':'✕ ')+option.text;$('quiz-feedback').textContent=(option.right?'Richtig. ':'Hier passt: '+q[1][0]+' ')+q[2];$('quiz-next').hidden=false;$('quiz-next').textContent=questionIndex<5?'Zum nächsten Fall →':'Runde abschließen →';};$('quiz-options').append(button);});}
  $('quiz-reset').onclick=startQuiz;$('quiz-next').onclick=()=>{if(!answered)return;if(questionIndex<5){questionIndex++;showQuestion();}else{$('quiz-progress').textContent='Runde abgeschlossen';$('quiz-question').textContent=score+' von 6 Entscheidungen richtig begründet.';$('quiz-options').replaceChildren();$('quiz-feedback').textContent='Entscheidend sind die Gründe. Probiere passende Gegenbeispiele in den Werkstätten aus oder beginne eine neue Runde.';$('quiz-next').hidden=true;}};startQuiz();
})();
