(function(){
  'use strict';
  const $=id=>document.getElementById(id),C=window.UVVis,KEY='uvvis-labor-v1',colors=['#755585','#be694c','#478c94','#a78b34','#747bc6','#65916b'];
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const format=(n,d=3)=>Number.isFinite(n)?n.toLocaleString('de-DE',{maximumFractionDigits:d}):'—';
  const names={'A01':'Benzol','A02':'Toluol','A10':'Phenol','A16':'Anilin','A17':'N,N-Dimethylanilin','J01':'Azobenzol','J03':'Methylorange','J17':'Kongorot','L02':'Malachitgrün','L03':'Kristallviolett','L04':'Fuchsin','L06':'Methylgrün','L07':'Methylblau','L09':'Phenolrot','L10':'Kresolrot','L11':'Thymolblau','N01':'Fluorescein','N05':'Eosin Y','N08':'Bengalrosa'};
  let data=[],record=null,curves=[],scanning=false,scanFrame=0,scanCurrent=null,blankReady=false,inserted=false,lidOpen=false,mode='explore',standards=[],unknownOriginal=null,unknownA=null,unknownMeasured=false,rdkitPromise=null,structureObserver,structureCache=new Map(),resetTarget='lab';
  function state(){return {c:Number($('concentration').value),factor:Number($('factor').value),path:Number($('path').value),pH:Number($('ph-select').value),material:$('material').value,bandwidth:Number($('bandwidth').value),realistic:$('instrument-model').value==='realistic'};}
  function say(s){$('measurement-status').textContent=s;}
  function safeSource(parent,text,url){const a=document.createElement('a');a.textContent=text;a.href=url;a.target='_blank';a.rel='noopener noreferrer';parent.append(a);}
  function loadRDKit(){if(rdkitPromise)return rdkitPromise;const asset=name=>new URL('../../LearningApps/fonts/'+name,new URL('scripts/uvvis-labor.js',document.baseURI)).href;rdkitPromise=(async()=>{if(!window.initRDKitModule)await new Promise((ok,no)=>{const s=document.createElement('script');s.src=asset('RDKit_minimal.js');s.onload=ok;s.onerror=no;document.head.append(s);});return window.initRDKitModule({locateFile:asset});})();return rdkitPromise;}
  async function structure(slot,r){
    if(!slot||slot.dataset.drawn==='true')return;slot.dataset.drawn='true';
    try{const rd=await loadRDKit();let svg=structureCache.get(r.id);if(!svg){const mol=rd.get_mol(r.smiles);if(!mol)throw Error();try{svg=mol.get_svg(300,160);}finally{mol.delete();}structureCache.set(r.id,svg);}if(slot.isConnected){slot.innerHTML=svg;const s=slot.querySelector('svg');s?.setAttribute('role','img');s?.setAttribute('aria-label','Strukturformel von '+r.name);}}
    catch(_){slot.textContent='Strukturzeichnung momentan nicht verfügbar. SMILES: '+r.smiles;slot.style.fontSize='11px';}
  }
  function list(){
    const q=$('search').value.trim().toLocaleLowerCase('de-DE'),cat=$('category').value;
    const filtered=data.filter(r=>(!cat||r.category===cat)&&(!q||(r.name+' '+r.originalName+' '+r.cas).toLocaleLowerCase('de-DE').includes(q)));
    $('list-status').textContent=filtered.length+' Stoffeinträge · Struktur anklicken zum Auswählen';structureObserver?.disconnect();$('substance-list').replaceChildren();
    for(const r of filtered){const b=document.createElement('button');b.className='substance-card'+(r===record?' selected':'');b.setAttribute('aria-pressed',r===record?'true':'false');b.dataset.id=r.id;b.innerHTML='<span class="structure" data-structure="'+escape(r.id)+'">Struktur wird geladen …</span><strong>'+escape(r.name)+'</strong><small>'+escape(r.category)+'</small>';b.onclick=()=>select(r);$('substance-list').append(b);structureObserver.observe(b.querySelector('.structure'));}
  }
  function select(r){
    stopScan(false);record=r;blankReady=false;inserted=false;resetCalibration();$('selected-name').textContent=r.name;
    const slot=$('selected-structure');slot.dataset.drawn='false';slot.textContent='Struktur wird geladen …';structure(slot,r);
    $('source-meta').textContent='CAS '+r.cas+' · '+r.solvent+' · '+(r.unit==='epsilon'?'ε-Messkurve':'Original-Absorbanz')+(r.digitized?' · grafisch digitalisiert':'');
    const d=$('source-detail');d.replaceChildren();for(const text of [r.credit,r.instrument,r.peakReference,r.note,r.rights])if(text){const p=document.createElement('p');p.className='small';p.textContent=text;d.append(p);}
    safeSource(d,'Originalquelle ↗',r.source);d.append(document.createTextNode(' · '));safeSource(d,'Originaldaten ↗',r.dataURL);if(r.cid){d.append(document.createTextNode(' · '));safeSource(d,'Struktur auf PubChem ↗','https://pubchem.ncbi.nlm.nih.gov/compound/'+r.cid);}
    $('concentration-label').hidden=r.unit!=='epsilon';$('factor-label').hidden=r.unit==='epsilon';$('ph-label').hidden=!r.curves;$('ph-select').replaceChildren();if(r.curves)for(const c of r.curves){const o=new Option('pH '+format(c.pH,2),c.pH);$('ph-select').add(o);}$('ph-select').selectedIndex=r.curves?r.curves.length-1:0;
    const peak=C.peak(r.points,Math.max(250,r.points[0][0]),r.points.at(-1)[0]);const max=peak?.[1]||1;$('concentration').value=r.unit==='epsilon'?Math.max(.01,Math.round(.65/max*1e6*100)/100):10;$('factor').value=1;
    setRange();$('wavelength').value=peak?Math.round(peak[0]):466;
    if(mode==='unknown'&&r.unit!=='epsilon'){mode='explore';applyMode();say('Diese Original-Absorbanzreihe erlaubt nur relative Verdünnung. Für molare Quantifizierung eine ε-Substanz auswählen.');}else say('Substanz gewählt. Öffne den Probenraum und setze den Blank ein.');
    list();update();drawSpectrum();
  }
  function setRange(){if(!record)return;const pts=C.spectrum(record,Number($('ph-select').value))||record.points,bw=Number($('bandwidth').value)/2;const lo=Math.ceil(Math.max(pts[0][0],C.cutoff(record.solvent,$('material').value))+bw),hi=Math.floor(Math.min(850,pts.at(-1)[0])-bw);$('range-start').value=lo;$('range-end').value=hi;$('range-note').textContent='Verfügbar: '+format(pts[0][0],1)+'–'+format(pts.at(-1)[0],1)+' nm. Modell-Cutoff: '+C.cutoff(record.solvent,$('material').value)+' nm; Bandbreitenrand zusätzlich berücksichtigt.';}
  function settingsValid(){const s=state();return record&&[s.c,s.factor,s.path,s.bandwidth].every(Number.isFinite)&&s.c>=0&&s.c<=10000&&s.factor>=0&&s.factor<=10&&s.path>0;}
  function sampleSettings(){const s=state();if(mode==='unknown'){if(!unknownMeasured||unknownOriginal===null)return null;s.c=unknownOriginal/Number($('dilution').value);}return s;}
  function ready(){return record&&settingsValid()&&blankReady&&inserted&&!lidOpen;}
  function update(){
    $('blank').disabled=!record||!settingsValid()||lidOpen||!inserted||scanning;
    $('insert').disabled=!record||!lidOpen||scanning;
    $('insert').textContent=blankReady?'2 · Probe einsetzen':'Blank einsetzen';
    $('blank').textContent=blankReady?'Blank erneut messen':'1 · Blank messen';
    $('scan').disabled=!ready()||scanning||(mode==='unknown'&&!unknownMeasured);
    $('stop').disabled=!scanning;$('export').disabled=!curves.length;
    for(const id of ['standard-measure','standard-blank'])$(id).disabled=!record||!blankReady||lidOpen||scanning||record.unit!=='epsilon';
    $('unknown-measure').disabled=!ready()||!C.regression(standards)||scanning;
    $('concentration').disabled=mode==='unknown'||scanning;
    for(const id of ['factor','ph-select','path','material','bandwidth','range-start','range-end','instrument-model','scan-speed','search','category','explore-mode','unknown-mode','lid','lab-reset'])$(id).disabled=scanning;
    document.querySelectorAll('.substance-card').forEach(b=>b.disabled=scanning);
    $('device').classList.toggle('open',lidOpen);$('lid').textContent=lidOpen?'Probenraum schließen':'Probenraum öffnen';
    const settings=sampleSettings(),reading=ready()&&settings?C.measure(record,Number($('wavelength').value),settings,()=>.5):null;
    for(const [id,key,dec] of [['read-a','A',4],['read-i0','I0',2],['read-i','I',2]])$(id).textContent=reading?format(reading[key],dec):'—';$('read-t').textContent=reading?format(reading.T*100,2)+' %':'—';window.UVVisOptics?.update(reading);
    const λ=Number($('wavelength').value),color=λ<380?'#8c79d8':λ<460?'#456cde':λ<500?'#3ea9c6':λ<570?'#76b668':λ<600?'#e0c658':λ<640?'#e69344':'#c65b52';$('device').style.setProperty('--beam',color);$('device').style.setProperty('--transmission',reading?Math.max(.08,reading.T):.65);$('device-lambda').textContent=format(λ,0)+' nm';$('device-A').textContent=reading?'A '+format(reading.A,3):'BEREIT';$('lamp-label').textContent=λ<350?'Deuterium · UV':'Halogen · Vis';window.UVVisDevice3D?.update(lidOpen,λ,reading);
  }
  function openLid(){if(scanning)return;lidOpen=!lidOpen;if(lidOpen)say('Probenraum offen. Blank oder Probe einsetzen; für die Messung anschließend schließen.');else say(blankReady?'Probenraum geschlossen. Die eingesetzte Probe kann gemessen werden.':'Probenraum geschlossen. Jetzt den Blindwert messen.');update();}
  $('lid').onclick=openLid;
  $('insert').onclick=()=>{if(!lidOpen||!record)return;inserted=true;$('cell-kind').textContent=blankReady?'PROBE':'BLANK';say(blankReady?'Probe eingesetzt. Probenraum schließen, dann Scan starten.':'Blank mit gleicher Lösungsmittel-/Puffermatrix eingesetzt. Probenraum schließen, dann Blank messen.');update();};
  $('blank').onclick=()=>{if(lidOpen||!inserted||!record)return;blankReady=true;inserted=false;$('cell-kind').textContent='LEER';say('Blindwert gespeichert: A = 0 für die Referenz. Öffne den Probenraum, setze die Probe ein und schließe ihn wieder.');update();};
  function stopScan(message=true){if(!scanning)return;scanning=false;cancelAnimationFrame(scanFrame);if(scanCurrent?.points.length){curves.push(scanCurrent);curves=curves.slice(-6);}scanCurrent=null;drawSpectrum();update();if(message)say('Scan gestoppt. Die bis hierhin aufgenommenen Punkte bleiben erhalten.');}
  $('stop').onclick=()=>stopScan();
  $('scan').onclick=()=>{
    const settings=sampleSettings(),start=Number($('range-start').value),end=Number($('range-end').value);
    if(!ready()||!settings)return;
    if(!Number.isFinite(start)||!Number.isFinite(end)||start>=end||start<190||end>850){say('Gültigen Scanbereich von 190 bis 850 nm wählen; der Anfang muss kleiner als das Ende sein.');return;}
    const pts=C.spectrum(record,settings.pH);if(start<Math.max(pts[0][0],C.cutoff(record.solvent,settings.material))+settings.bandwidth/2||end>pts.at(-1)[0]-settings.bandwidth/2){say('Dieser Bereich liegt teilweise außerhalb der Messdaten oder unterhalb des Modell-Cutoffs. Bitte den verfügbaren Bereich beachten.');return;}
    const label=mode==='unknown'?'Unbekannte Probe':record.unit==='epsilon'?'c = '+format(settings.c,2)+' µmol/L':'Probenfaktor '+format(settings.factor,2)+(record.curves?' · pH '+format(settings.pH,2):'');
    scanCurrent={name:record.name,label,source:record.source,solvent:record.solvent,settings:{...settings,c:mode==='unknown'?null:settings.c},range:[start,end],points:[],color:colors[curves.length%colors.length],complete:false};scanning=true;update();$('scan-progress').value=0;say('Scan läuft: Der Monochromator fährt die Wellenlängen nacheinander an.');const begun=performance.now(),duration=Number($('scan-speed').value);let next=start;
    function frame(now){if(!scanning)return;const fraction=Math.min(1,(now-begun)/duration),limit=start+(end-start)*fraction;for(;next<=limit;next++){const m=C.measure(record,next,settings);scanCurrent.points.push([next,m?.A??null,m?.T??null]);}$('wavelength').value=Math.round(limit);$('scan-progress').value=fraction*100;update();drawSpectrum();if(fraction<1)scanFrame=requestAnimationFrame(frame);else{scanCurrent.complete=true;stopScan(false);say('Scan abgeschlossen. Kurve gespeichert. Ändere Bedingungen oder Substanz für einen Vergleich.');}}
    scanFrame=requestAnimationFrame(frame);
  };
  function chart(el,series,{lo,hi,ylabel='Absorbanz A',xlabel='Wellenlänge λ / nm',ymax=null,marker=null,scatter=false}={}){
    const box=el.viewBox.baseVal,W=box.width,H=box.height,left=85,right=28,top=36,bottom=65,pw=W-left-right,ph=H-top-bottom;
    const visible=series.flatMap(s=>s.points.filter(p=>p[0]>=lo&&p[0]<=hi&&Number.isFinite(p[1])).map(p=>p[1]));const max=ymax??Math.max(.1,...visible)*1.12;
    const X=x=>left+(x-lo)/(hi-lo)*pw,Y=y=>top+ph-(y/max)*ph;let out='';
    for(let i=0;i<=5;i++){const x=lo+(hi-lo)*i/5,y=max*i/5;out+='<path class="grid" d="M'+X(x)+' '+top+'V'+(top+ph)+'M'+left+' '+Y(y)+'H'+(W-right)+'" fill="none"/><text x="'+X(x)+'" y="'+(H-bottom+28)+'" text-anchor="middle">'+format(x,0)+'</text><text x="'+(left-12)+'" y="'+(Y(y)+5)+'" text-anchor="end">'+format(y,max>100?0:2)+'</text>';}
    out+='<path class="axis" d="M'+left+' '+top+'V'+(H-bottom)+'H'+(W-right)+'" fill="none" stroke-width="2"/><text x="'+left+'" y="20">'+escape(ylabel)+'</text><text x="'+(W/2)+'" y="'+(H-15)+'" text-anchor="middle">'+escape(xlabel)+'</text>';
    for(const s of series){if(scatter){for(const p of s.points)if(Number.isFinite(p[1])&&p[0]>=lo&&p[0]<=hi)out+='<circle cx="'+X(p[0])+'" cy="'+Y(p[1])+'" r="5" fill="'+s.color+'"/>';continue;}let d='',pen=false;for(const p of s.points){if(p[0]<lo||p[0]>hi||!Number.isFinite(p[1])){pen=false;continue;}d+=(pen?'L':'M')+X(p[0]).toFixed(2)+' '+Y(Math.max(0,p[1])).toFixed(2);pen=true;}out+='<path d="'+d+'" fill="none" stroke="'+s.color+'" stroke-width="2.6"/>';}
    if(marker!==null&&marker>=lo&&marker<=hi)out+='<path d="M'+X(marker)+' '+top+'V'+(H-bottom)+'" stroke="#ac6144" stroke-dasharray="4 5" fill="none"/><text x="'+X(marker)+'" y="'+(top+15)+'" text-anchor="middle">'+format(marker,0)+' nm</text>';
    if(!visible.length)out+='<text x="'+W/2+'" y="'+H/2+'" text-anchor="middle">Noch keine Messkurve · erst Blank und Probe messen</text>';
    el.innerHTML=out;el.dataset.lo=lo;el.dataset.hi=hi;
  }
  function drawSpectrum(){
    const list=[...curves,...(scanCurrent?[scanCurrent]:[])],unit=$('plot-unit').value;
    const lo=list.length?Math.min(...list.map(c=>c.range[0])):Number($('range-start').value),hi=list.length?Math.max(...list.map(c=>c.range[1])):Number($('range-end').value);
    chart($('spectrum'),list.map(c=>({points:c.points.map(p=>[p[0],unit==='T'?(p[2]===null?null:p[2]*100):p[1]]),color:c.color})),{lo,hi:hi>lo?hi:lo+1,ylabel:unit==='T'?'Transmission / %':'Absorbanz A',ymax:unit==='T'?100:null,marker:Number($('wavelength').value)});
    $('curve-legend').replaceChildren();curves.forEach((c,i)=>{const div=document.createElement('div');div.className='legend-item';const line=document.createElement('i');line.style.background=c.color;div.append(line,document.createTextNode(c.name+' · '+c.label+' · l '+c.settings.path+' cm · '+c.settings.bandwidth+' nm · '+(c.settings.realistic?'mit Geräteeffekten':'ideal')+(c.complete?'':' · Teilscan')));const b=document.createElement('button');b.textContent='Entfernen';b.disabled=scanning;b.onclick=()=>{curves.splice(i,1);drawSpectrum();update();};div.append(b);$('curve-legend').append(div);});
  }
  $('spectrum').onclick=e=>{if(scanning)return;const rect=$('spectrum').getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*900,lo=Number($('spectrum').dataset.lo),hi=Number($('spectrum').dataset.hi);$('wavelength').value=Math.round(Math.max(lo,Math.min(hi,lo+(x-85)/787*(hi-lo))));if(mode==='unknown')resetCalibration();update();drawSpectrum();};
  $('wavelength').onchange=()=>{if(mode==='unknown')resetCalibration();update();drawSpectrum();};
  $('plot-unit').onchange=drawSpectrum;
  $('clear-curves').onclick=()=>{if(scanning)return;curves=[];drawSpectrum();update();};
  $('export').onclick=()=>{const rows=['# UV/VisLabor: simulierte Messung auf Basis veröffentlichter Daten','Kurve;Substanz;Bedingungen;Quelle;lambda_nm;Absorbanz;Transmission'];curves.forEach((c,i)=>c.points.forEach(p=>rows.push([i+1,c.name,c.label+' | '+c.solvent+' | l='+c.settings.path+' cm | Bandbreite='+c.settings.bandwidth+' nm | '+(c.settings.realistic?'Streulicht/Rauschen':'ideal'),c.source,...p].map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';'))));const url=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='uvvis-messkurven.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  function resetCalibration(){standards=[];unknownOriginal=null;unknownA=null;unknownMeasured=false;$('unknown-a').textContent='Unbekannte Probe noch nicht gemessen.';$('unknown-feedback').textContent='';drawCalibration();}
  function drawCalibration(){
    $('standards').innerHTML=standards.map(r=>'<tr><td>'+format(r.c,3)+'</td><td>'+format(r.A,5)+'</td></tr>').join('');const fit=C.regression(standards),maxc=Math.max(20,...standards.map(r=>r.c));let series=[{points:standards.map(r=>[r.c,r.A]),color:colors[0]}];
    chart($('calibration-plot'),series,{lo:0,hi:maxc*1.1,xlabel:'c / µmol L⁻¹',scatter:true});
    if(fit){$('calibration-result').textContent='A = '+format(fit.slope,6)+' · c + '+format(fit.intercept,5)+' · R² = '+format(fit.r2,5)+' · c in µmol/L';if(fit.slope<=0||fit.r2<.99)$('calibration-result').textContent+=' · Achtung: ungeeignete oder deutlich nichtlineare Kalibrierung.';const el=$('calibration-plot'),H=340,ym=Math.max(.1,...standards.map(r=>r.A))*1.12;el.insertAdjacentHTML('beforeend','<path d="M85 '+(36+239-fit.intercept/ym*239)+'L'+(85+787*fit.max/(maxc*1.1))+' '+(36+239-(fit.intercept+fit.slope*fit.max)/ym*239)+'" fill="none" stroke="'+colors[1]+'" stroke-dasharray="5 4"/>');}
    else $('calibration-result').textContent='Mindestens drei verschiedene Konzentrationsstufen erforderlich.';
  }
  $('standard-measure').onclick=()=>addStandard(Number($('standard-c').value));$('standard-blank').onclick=()=>addStandard(0);
  function addStandard(c){if(!blankReady||lidOpen||!record||record.unit!=='epsilon')return;if(!Number.isFinite(c)||c<0||c>10000){say('Gültige Standardkonzentration eingeben.');return;}const s={...state(),c},m=C.measure(record,Number($('wavelength').value),s);if(!m){say('Messwellenlänge außerhalb des verwendbaren Bereichs.');return;}if(m.A>2){say('Standard absorbiert zu stark (A > 2). Niedrigere Konzentration verwenden.');return;}standards=standards.filter(r=>r.c!==c);standards.push({c,A:m.A});standards.sort((a,b)=>a.c-b.c);unknownMeasured=false;unknownA=null;$('unknown-a').textContent='Kalibrierung verändert. Unbekannte Probe erneut messen.';drawCalibration();say('Standard gemessen: '+format(c,2)+' µmol/L, A = '+format(m.A,4));update();}
  $('unknown-measure').onclick=()=>{if(!ready())return;const fit=C.regression(standards);if(!fit||fit.slope<=0||fit.r2<.99){$('unknown-feedback').textContent='Zuerst eine geeignete, annähernd lineare Kalibrierung erstellen (R² ≥ 0,99).';return;}const F=Number($('dilution').value);if(unknownOriginal===null)unknownOriginal=(fit.min+(.2+Math.random()*.6)*(fit.max-fit.min))*F;const m=C.measure(record,Number($('wavelength').value),{...state(),c:unknownOriginal/F});if(!m||m.A>2){$('unknown-feedback').textContent='Diese Probe ist nicht zuverlässig messbar. Verdünnen und erneut messen.';return;}unknownA=m.A;unknownMeasured=true;$('unknown-a').textContent='Unbekannte Messlösung: A = '+format(unknownA,5)+' bei '+$('wavelength').value+' nm. Vorverdünnung: Faktor '+F+'.';$('unknown-feedback').textContent='Berechne c = (A − b) / m und berücksichtige die Vorverdünnung.';update();};
  $('dilution').onchange=()=>{unknownMeasured=false;unknownA=null;$('unknown-a').textContent='Verdünnung geändert. Unbekannte Probe erneut messen.';update();};
  $('new-unknown').onclick=()=>{unknownOriginal=null;unknownA=null;unknownMeasured=false;$('unknown-a').textContent='Neue Probe bereit. Kalibrierung bleibt erhalten.';$('unknown-feedback').textContent='';$('answer-c').value='';update();};
  $('check-c').onclick=()=>{const fit=C.regression(standards),ans=Number($('answer-c').value);if(unknownA===null||!fit||!$('answer-c').value){$('unknown-feedback').textContent='Zuerst kalibrieren, die unbekannte Probe messen und ein Ergebnis eintragen.';return;}const measured=(unknownA-fit.intercept)/fit.slope,F=Number($('dilution').value);if(measured<fit.min||measured>fit.max){$('unknown-feedback').textContent='Die Messlösung liegt außerhalb des Kalibrierbereichs. Nicht extrapolieren: Verdünnung oder Standards anpassen.';return;}const expected=measured*F,ok=Math.abs(ans-expected)<=Math.max(.02,expected*.02);$('unknown-feedback').textContent=ok?'Richtig: Aus deiner Kalibrierung folgen '+format(expected,3)+' µmol/L für die ursprüngliche Probe. Tatsächlich simuliert: '+format(unknownOriginal,3)+' µmol/L.':'Prüfe (A − b) / m und den Verdünnungsfaktor. Rechne mit c in µmol/L; nutze die ausgegebene Steigung.';};
  function applyMode(){const unknown=mode==='unknown';$('unknown-panel').hidden=!unknown;$('explore-mode').classList.toggle('active',!unknown);$('unknown-mode').classList.toggle('active',unknown);$('explore-mode').setAttribute('aria-pressed',String(!unknown));$('unknown-mode').setAttribute('aria-pressed',String(unknown));resetCalibration();update();}
  $('explore-mode').onclick=()=>{mode='explore';applyMode();say('Spektren erforschen: Konzentration oder relative Verdünnung frei wählen.');};
  $('unknown-mode').onclick=()=>{if(record?.unit!=='epsilon'){say('Für molare Konzentrationsbestimmung eine Substanz mit ε-Messkurve auswählen, z. B. Kristallviolett.');return;}mode='unknown';applyMode();$('standard-c').value=$('concentration').value;say('Quantifizierung: Blank und Probe einsetzen, dann mehrere Standards bei derselben Wellenlänge messen.');};
  for(const id of ['concentration','factor','ph-select','path','material','bandwidth','instrument-model'])$(id).onchange=()=>{stopScan(false);if(mode==='unknown')resetCalibration();if(['ph-select','path','material'].includes(id)){blankReady=false;inserted=false;say('Matrix oder Küvette geändert: Bitte neuen Blank einsetzen und messen.');}else say('Bedingungen geändert. Ein neuer Scan übernimmt diese Einstellungen.');if(['ph-select','material','bandwidth'].includes(id))setRange();update();};
  $('inside').onchange=()=>{$('device').classList.toggle('inside',$('inside').checked);};
  $('rays').onchange=()=>{if($('rays').checked){$('inside').checked=true;$('device').classList.add('inside');}$('device').classList.toggle('rays',$('rays').checked);};
  const parts={lamp:'Lampen: Die Deuteriumlampe liefert UV-Licht, die Halogenlampe sichtbares Licht. Im Modell liegt der Wechsel bei 350 nm. Die Lichtquelle ist breitbandig, bevor der Monochromator auswählt.',mono:'Monochromator: Spiegel lenken Licht zum Beugungsgitter. Verschiedene Wellenlängen werden in verschiedene Richtungen abgelenkt. Ein Austrittsspalt wählt ein schmales Band. Beim Scan verändert sich die Auswahl.',split:'Sektorspiegel: Ein rotierender Spiegel lenkt das monochromatische Licht abwechselnd durch Messlösung und Vergleichslösung. Spiegel führen beide Wege zum selben Detektor. Mit den Schaltflächen lässt sich jeder Weg einzeln untersuchen.',cells:'Küvetten: Oben die Messlösung, unten die passende Lösungsmittel-/Pufferreferenz. Die Probe schwächt ihren Strahl abhängig von λ, Konzentration und Schichtdicke. Die farbige Füllung ist nur eine symbolische Darstellung, keine exakte Farbberechnung.',detector:'Detektor: Er wandelt die Lichtintensität in elektrische Signale um. Aus dem korrigierten Verhältnis I / I₀ entstehen T und A. Die Intensitäten werden nacheinander am selben Detektor erfasst; die Auswertung bildet das Verhältnis. Die Darstellung ist nicht maßgetreu.'};
  document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{$('part-info').textContent=parts[b.dataset.part];$('inside').checked=true;$('device').classList.add('inside');});
  $('fullscreen').onclick=async()=>{const el=$('labor');try{if(document.fullscreenElement)await document.exitFullscreen();else if(el.classList.contains('pseudo-fullscreen'))el.classList.remove('pseudo-fullscreen');else if(el.requestFullscreen)await el.requestFullscreen();else el.classList.add('pseudo-fullscreen');}catch(_){el.classList.toggle('pseudo-fullscreen');}syncFullscreen();};
  function syncFullscreen(){$('fullscreen').textContent=document.fullscreenElement||$('labor').classList.contains('pseudo-fullscreen')?'Vollbild beenden':'Labor im Vollbild';}
  document.addEventListener('fullscreenchange',syncFullscreen);document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('labor').classList.remove('pseudo-fullscreen');syncFullscreen();}});
  function resetLab(){stopScan(false);curves=[];blankReady=false;inserted=false;lidOpen=false;mode='explore';$('inside').checked=false;$('rays').checked=false;$('device').className='';$('cell-kind').textContent='LEER';$('scan-progress').value=0;window.UVVisOptics?.reset();applyMode();if(record)select(record);drawSpectrum();say('Labor zurückgesetzt. Theorie und Aufgabenstand bleiben erhalten.');}
  function askReset(target){resetTarget=target;$('reset-title').textContent=target==='app'?'Gesamte App zurücksetzen?':'Labor zurücksetzen?';$('reset-text').textContent=target==='app'?'Nur der Lernstand, XP und die Messkurven dieser App werden entfernt. Andere Apps bleiben unverändert.':'Die Messkurven und Kalibrierung werden entfernt. Der Aufgabenstand bleibt erhalten.';if(document.fullscreenElement)$('labor').append($('reset-dialog'));$('reset-dialog').showModal();}
  $('lab-reset').onclick=()=>askReset('lab');$('app-reset').onclick=()=>askReset('app');$('reset-dialog').addEventListener('close',()=>{if($('reset-dialog').returnValue!=='reset')return;resetLab();if(resetTarget==='app'){try{localStorage.removeItem(KEY);}catch(_){}quizState=null;newQuiz();}});
  $('theme').onclick=()=>{document.body.classList.toggle('dark');$('theme').textContent=document.body.classList.contains('dark')?'Helles Farbschema':'Dunkles Farbschema';};
  function beer(){const c=Number($('beer-c').value),l=Number($('beer-l').value),a=25000*c*1e-6*l,t=10**(-a);$('beer-result').textContent='c = '+format(c,0)+' µmol/L · l = '+format(l,1)+' cm → A = '+format(a,3)+' → T = '+format(t*100,1)+' %';$('beer-light').style.width=t*100+'%';}$('beer-c').oninput=beer;$('beer-l').oninput=beer;beer();
  function aux(){const benz=data.find(r=>r.id==='A01'),ani=data.find(r=>r.id==='A16');if(!benz||!ani)return;chart($('aux-plot'),[{points:benz.points,color:colors[0]},{points:ani.points,color:colors[1]}],{lo:250,hi:310,ylabel:'ε / L mol⁻¹ cm⁻¹'});const b=C.peak(benz.points,250,310),a=C.peak(ani.points,265,310),back=$('aux-direction').value==='back';$('aux-result').textContent='Violett: Benzol ('+format(b[0],0)+' nm) · Kupfer: Anilin ('+format(a[0],0)+' nm). '+(back?'Anilin → Benzol: hypsochrom und hypochrom.':'Benzol → Anilin: bathochrom und hyperchrom.');}
  $('aux-direction').onchange=aux;
  function phCompare(){const r=data.find(r=>r.id==='PH-J03');if(!r)return;const first=Number($('ph-first').value),second=Number($('ph-second').value),p=C.spectrum(r,first),q=C.spectrum(r,second);chart($('ph-plot'),[{points:p,color:colors[0]},{points:q,color:colors[1]}],{lo:350,hi:650});const a=C.peak(p,350,650),b=C.peak(q,350,650);$('ph-result').textContent='Violett: pH '+format(first,2)+' · Maximum '+format(a[0],0)+' nm. Kupfer: pH '+format(second,2)+' · Maximum '+format(b[0],0)+' nm. '+(Math.abs(a[0]-b[0])<3?'Ähnliche Bandlage: vergleiche nun die Intensitäten.':b[0]>a[0]?'In dieser Richtung verschiebt sich das Hauptmaximum bathochrom.':'In dieser Richtung verschiebt sich das Hauptmaximum hypsochrom.');}
  $('ph-first').onchange=phCompare;$('ph-second').onchange=phCompare;
  // Quiz: only this application's learning state is saved. Answers are kept
  // as IDs, so a shuffled display never changes which answer is correct.
  let quizState=null;
  try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.ids)&&s.ids.length===24&&s.ids.every(id=>window.UVVisQuestions.some(q=>q.id===id))&&Number.isInteger(s.index)&&s.index>=0&&s.index<=24&&Number.isFinite(s.xp)&&s.xp>=0)quizState=s;}catch(_){}
  function saveQuiz(){try{localStorage.setItem(KEY,JSON.stringify(quizState));}catch(_){}}
  function newQuiz(){const pool=window.UVVisQuestions,groups=[...new Set(pool.map(q=>q.group))];const chosen=groups.flatMap(g=>C.shuffle(pool.filter(q=>q.group===g)).slice(0,4));quizState={ids:C.shuffle(chosen).map(q=>q.id),index:0,xp:0,attempts:0,done:false,order:[]};renderQuiz();saveQuiz();}
  function renderQuiz(){const qs=quizState;$('xp').textContent=qs.xp+' XP';$('badge').textContent=qs.xp>=200?'Spektrenprofi':qs.xp>=120?'Analytikexpertin / -experte':qs.xp>=60?'Messforscherin / -forscher':'Laborneuling';$('quiz-bar').value=qs.index+(qs.done?1:0);$('quiz-progress').textContent=qs.index<24?'Aufgabe '+(qs.index+1)+' / 24 · Gesamtpool: '+window.UVVisQuestions.length+' Aufgaben':'Runde abgeschlossen · '+qs.xp+' von maximal 240 XP';$('quiz-next').disabled=!qs.done;$('quiz-hint').disabled=qs.index>=24;$('quiz-feedback').textContent='';const card=$('quiz-card');card.replaceChildren();if(qs.index>=24){card.innerHTML='<h3>Du hast die Runde geschafft.</h3><p>Nutze das Labor, um unsichere Antworten experimentell zu überprüfen, oder starte eine neue zufällige Runde.</p>';$('quiz-next').disabled=true;return;}const q=window.UVVisQuestions.find(q=>q.id===qs.ids[qs.index]);if(!qs.order?.length)qs.order=C.shuffle(q.options.map((_,i)=>i));const h=document.createElement('h3');h.textContent=q.group;const p=document.createElement('p');p.textContent=q.question;card.append(h,p);const opts=document.createElement('div');opts.className='quiz-options';for(const i of qs.order){const b=document.createElement('button');b.textContent=q.options[i];b.disabled=qs.done;if(qs.done&&i===q.correct)b.className='correct';b.onclick=()=>{if(qs.done)return;if(i===q.correct){qs.xp+=qs.attempts?5:10;qs.done=true;renderQuiz();$('quiz-feedback').textContent='Richtig. '+q.explanation;saveQuiz();}else{qs.attempts++;b.classList.add('wrong');b.disabled=true;$('quiz-feedback').textContent='Noch nicht. '+q.hint;saveQuiz();}};opts.append(b);}card.append(opts);}
  $('quiz-hint').onclick=()=>{const q=window.UVVisQuestions.find(q=>q.id===quizState.ids[quizState.index]);$('quiz-feedback').textContent=q?.hint||'';};$('quiz-next').onclick=()=>{if(!quizState.done)return;quizState.index++;quizState.done=false;quizState.attempts=0;quizState.order=[];renderQuiz();saveQuiz();};$('quiz-new').onclick=newQuiz;
  function device(){
    $('device').innerHTML='<span hidden><span id="cell-kind">LEER</span><span id="device-lambda"></span><span id="device-A"></span><span id="lamp-label"></span></span>';
  }
  device();window.UVVisOptics.mount();window.UVVisDevice3D.mount();drawCalibration();drawSpectrum();if(!quizState)newQuiz();else renderQuiz();
  structureObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){const r=data.find(r=>r.id===e.target.dataset.structure);if(r)structure(e.target,r);structureObserver.unobserve(e.target);}},{root:$('substance-list'),rootMargin:'100px'});
  async function init(){try{const response=await fetch('data/uvvis-spectra.json');if(!response.ok)throw Error();const json=await response.json();data=json.substances.map(r=>({...r,originalName:r.name,name:names[r.id]||r.name}));$('substance-count').textContent=data.length;$('load-status').textContent=data.length+' Stoffeinträge · '+data.filter(r=>r.curves).reduce((s,r)=>s+r.curves.length,0)+' tatsächlich gemessene pH-Spektren · Strukturen lokal';for(const category of [...new Set(data.map(r=>r.category))])$('category').add(new Option(category,category));select(data.find(r=>r.id==='L03')||data[0]);const div=$('aux-structures');for(const id of ['A01','A16']){const r=data.find(r=>r.id===id),slot=document.createElement('div');slot.className='structure';div.append(slot);structure(slot,r);}aux();const ph=data.find(r=>r.id==='PH-J03');for(const c of ph.curves){$('ph-first').add(new Option('pH '+format(c.pH,2),c.pH));$('ph-second').add(new Option('pH '+format(c.pH,2),c.pH));}$('ph-second').selectedIndex=ph.curves.length-1;phCompare();}catch(error){$('load-status').textContent='Messdaten konnten nicht geladen werden. Bitte die App über ihre Webadresse öffnen und erneut laden. Theorie und Aufgaben bleiben verfügbar.';console.error(error);}}
  function wikipediaOptics(allow){const slot=$('wiki-optics-image');if(!slot)return;slot.replaceChildren();if(allow){const img=document.createElement('img');img.alt='Animierter Strahlengang eines Zweistrahl-UV/Vis-Spektrometers: Messlösung und Vergleichslösung werden abwechselnd durchstrahlt.';img.referrerPolicy='no-referrer';img.loading='lazy';img.src='https://upload.wikimedia.org/wikipedia/commons/f/fd/Aufbau_UVVIS.gif';slot.append(img);}else{const p=document.createElement('p');p.textContent='Diese externe Animation wird erst nach deiner Wikipedia-Zustimmung geladen.';const b=document.createElement('button');b.textContent='Wikipedia-Einstellungen öffnen';b.onclick=()=>$('wiki-settings').click();slot.append(p,b);}}
  $('consent').addEventListener('close',()=>wikipediaOptics($('consent').returnValue==='allow'));$('wiki-revoke').addEventListener('click',()=>wikipediaOptics(false));$('wiki-optics-consent').onclick=()=>$('wiki-settings').click();
  $('search').oninput=list;$('category').onchange=list;init();
})();
