(function(){
  'use strict';
  const data=window.WetterWelten,$=id=>document.getElementById(id),KEY='wetterwelten:v1';
  const topbar=document.querySelector('.topbar');function headerSize(){document.documentElement.style.setProperty('--top',Math.ceil(topbar.getBoundingClientRect().height)+'px');}headerSize();if(window.ResizeObserver)new ResizeObserver(headerSize).observe(topbar);else window.addEventListener('resize',headerSize);
  const allTasks=data.groups.flatMap(g=>g.tasks),taskMap=new Map(allTasks.map(t=>[t.id,t]));
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  function rng(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
  function shuffle(items,random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function freshSeed(){try{return crypto.getRandomValues(new Uint32Array(1))[0];}catch(_){return Date.now()>>>0;}}
  const defaults=()=>({seed:freshSeed(),results:{},notes:{},checks:{},theme:'light',paused:matchMedia('(prefers-reduced-motion: reduce)').matches});
  let state=defaults(),storageOK=true;
  try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&Number.isInteger(saved.seed)&&saved.seed>=0&&saved.seed<=4294967295){state.seed=saved.seed;state.theme=saved.theme==='dark'?'dark':'light';state.paused=Boolean(saved.paused);if(saved.notes&&typeof saved.notes==='object')for(const [key,value] of Object.entries(saved.notes))if(typeof value==='string'&&value.length<=30000)state.notes[key]=value;if(saved.checks&&typeof saved.checks==='object')for(const [key,value] of Object.entries(saved.checks))if(/^(\d|1[01])$/.test(key))state.checks[key]=value===true;if(saved.results&&typeof saved.results==='object')for(const [id,r]of Object.entries(saved.results)){if(taskMap.has(id)&&r&&[1,2].includes(r.attempts)&&['retry','correct','missed'].includes(r.status)&&[0,.5,1].includes(r.score))state.results[id]={attempts:r.attempts,status:r.status,score:r.status==='correct'?r.score:0,answer:r.answer};}}}catch(_){storageOK=false;}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){storageOK=false;}if(!storageOK)$('storage-status').textContent='Der Browser erlaubt gerade keine zuverlässige lokale Speicherung. Die App funktioniert, aber sichere deinen Plan als Text; nach dem Schließen kann der Fortschritt verloren gehen.';}
  function selection(){const random=rng(state.seed);return data.groups.map(g=>({group:g,tasks:shuffle(g.tasks,random).slice(0,3)}));}
  let selected=selection(),mediaAllowed=false;
  const photoSlots=new Set();
  function externalLink(title,url){const a=el('a',title+' ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';return a;}
  function wiki(title){const b=el('button','W Wikipedia · '+title,'wiki');b.dataset.wiki=title;return b;}
  function loadPhoto(slot){const m=slot.media,stage=slot.stage;stage.replaceChildren();if(!mediaAllowed){const p=el('p',undefined,'photo-placeholder');p.append(el('span','▧'),document.createTextNode('Bild nicht geladen. '+m.title+' · '+m.date));stage.append(p);return;}const img=el('img');img.alt=m.title+'. '+m.caption;img.loading='lazy';img.decoding='async';img.referrerPolicy='no-referrer';img.onerror=()=>{if(!mediaAllowed||!stage.contains(img))return;const p=el('p','Bild momentan nicht erreichbar. Erklärung und Bildnachweis bleiben verfügbar.','photo-placeholder'),b=el('button','Erneut laden');b.onclick=()=>loadPhoto(slot);p.append(el('br'),b);stage.replaceChildren(p);};img.src=m.url;stage.append(img);if(slot.zoom){const b=el('button','Bild vergrößern ⤢','photo-zoom');b.onclick=()=>openPhoto(slot.key);stage.append(b);}}
  function mountPhoto(container,key,zoom=true){const m=data.media[key];if(!m)return;const figure=el('figure'),stage=el('div',undefined,'photo-stage'),caption=el('figcaption');caption.append(el('strong',m.title),el('br'),document.createTextNode(m.caption),el('br'),el('small',m.credit+' · '+m.license+' · '+m.date+' · '),externalLink('Bildquelle',m.source));if(m.licenseURL)caption.append(document.createTextNode(' · '),externalLink('Lizenz',m.licenseURL));const task=el('details',undefined,'photo-task');task.append(el('summary','Bild lesen: '+m.prompt),el('p',m.reading));figure.append(stage,caption,task);container.append(figure);const slot={key,media:m,stage,zoom};photoSlots.add(slot);loadPhoto(slot);return slot;}
  document.querySelectorAll('[data-photo]').forEach(n=>mountPhoto(n,n.dataset.photo));
  let photoOpener=null,zoomSlot=null;
  function openPhoto(key){photoOpener=document.activeElement;$('photo-title').textContent=data.media[key].title;$('photo-content').replaceChildren();zoomSlot=mountPhoto($('photo-content'),key,false);$('photo-view').showModal();}
  $('photo-close').onclick=()=>$('photo-view').close();$('photo-view').addEventListener('close',()=>{if(zoomSlot){photoSlots.delete(zoomSlot);zoomSlot=null;}$('photo-content').replaceChildren();photoOpener?.focus({preventScroll:true});});
  function permissionUpdate(allowed){mediaAllowed=allowed;for(const slot of photoSlots)if(slot.stage.isConnected)loadPhoto(slot);else photoSlots.delete(slot);if(!allowed&&$('photo-view').open)$('photo-view').close();setTimeout(()=>{$('privacy-status').textContent=allowed?'Externe Bilder von Wikimedia, NASA und NOAA sowie Wikipedia-Artikel sind bis zum erneuten Laden freigegeben. Du kannst diese Zustimmung zurücknehmen.':'Externe Inhalte nicht freigegeben. Alle Lerntexte, Modelle und Aufgaben bleiben nutzbar.';},0);}
  $('consent').addEventListener('close',()=>permissionUpdate($('consent').returnValue==='allow'));
  $('wiki-revoke').addEventListener('click',()=>permissionUpdate(false));

  function projectCards(){const host=$('projects');data.projects.forEach((p,index)=>{if(index===0||index===6){host.append(el('h3',index===0?'Sechs Gruppenprojekte':'Acht kleinere Einzelprojekte'),el('p',index===0?'Ein großer Mechanismus, ein konkretes Ereignis – verteilt die Arbeit mit klaren Zuständigkeiten.':'Wähle ein Thema. Begrenze dich auf eine Systemskizze, einen örtlichen Beleg und eine erklärte Folge; kein verkleinertes Großreferat. Auch allein führst du dein Board, bist selbst Boardmaster und gibst die JSON-Datei ab.'));}const a=el('article',undefined,'project'),head=el('div',undefined,'project-header'),label=el('div');label.append(el('p',p.scope,'eyebrow'),el('h3',p.title));head.append(el('span',String(index+1).padStart(2,'0'),'project-number'),label);a.append(head,el('p',p.question,'question'));if(p.images.length){const gallery=el('div',undefined,'two gallery');p.images.forEach(key=>{const slot=el('div');gallery.append(slot);mountPhoto(slot,key);});a.append(gallery);}const brief=el('div',undefined,'project-brief');for(const [title,items] of [['Das Prinzip untersuchen',p.mechanism],['Die konkrete Situation recherchieren',p.local]]){const col=el('div'),ul=el('ul');col.append(el('h4',title));items.forEach(text=>ul.append(el('li',text)));col.append(ul);brief.append(col);}a.append(brief,el('h4','Euer selbst erarbeitetes Ergebnis'),el('p',p.product));const source=el('div',undefined,'card small');source.append(el('h4','Startpunkte – eure Recherche geht weiter'));p.sources.forEach(([title,url])=>{source.append(externalLink(title,url),el('br'));});source.append(wiki(p.wiki),el('p','Geeignete Suchbegriffe: '+p.search),el('p','Bilder suchen: '));const imageLinks=el('div',undefined,'actions');imageLinks.append(externalLink('Wikimedia Commons', 'https://commons.wikimedia.org/w/index.php?search='+encodeURIComponent(p.commons)+'&title=Special:MediaSearch&type=image'),externalLink('NASA-Bildsuche','https://images.nasa.gov/search?q='+encodeURIComponent(p.commons)),externalLink('NOAA-Fotobibliothek','https://www.noaa.gov/noaa-collections/collections/photo-library'));source.append(imageLinks,el('p','Öffnet vor der Verwendung die Bildseite. Prüft Urheber, Aufnahmeort, Datum, Lizenz und mögliche Fremdrechte. „Bei Google gefunden“ ist keine Bildquelle. Beachtet besonders: Ein Symbolbild ist kein Beleg des Ereignisses.'));a.append(source);host.append(a);});}
  projectCards();
  const referenceIntro=$('referate').querySelector('.notice');referenceIntro.append(el('p','Die Startquellen sind Orientierung, kein fertiger Erwartungshorizont. Recherchiert selbst weiter, wählt eure Belege aus und entwickelt eure Erklärung. Für Einzelarbeit stehen darunter acht kleinere Themen zur Verfügung.'));
  const topic=$('team-topic');data.projects.slice(6).forEach(p=>topic.append(el('option',p.title)));
  const ki=el('div',undefined,'card');ki.append(el('h3','KI darf helfen. Ihr müsst das Thema vertreten können.'),el('p','Ihr dürft KI zum Ordnen von Recherche, zum Prüfen eurer Gliederung und zum Entwerfen von Texten oder Folien einsetzen. Der Vortrag darf dadurch nicht zu einem fremden Text werden, den ihr nur ablest.'),el('p','Prüft Quellen, Zahlen, Ursachen und Bildrechte selbst. Jede Person muss ihren Beitrag mit eigenen Worten erklären, Rückfragen beantworten und eine Aussage anhand der Belege verteidigen können. Eine KI-Antwort oder eine erfundene Quellenangabe ist kein Fachbeleg.'),el('p','Dokumentiert auf den betreffenden Kanbankarten, wofür ihr KI genutzt habt, was ihr übernommen und was ihr fachlich geprüft oder korrigiert habt. Eine überzeugende Erklärung wiegt mehr als ein perfekt klingender, unverstandener Text.'));
  $('vortragen').append(ki);
  const assessment=el('div',undefined,'notice');assessment.append(el('h3','Das Board ist ein bewertetes Produkt – JSON abgeben'),el('p','Die Projektbewertung erfolgt anhand eurer Kanbankarten und der darin nachvollziehbaren Beiträge. Gebt der Lehrkraft den JSON-Export aus der Schülerboard-App ab. Ein Screenshot, die Folien allein oder der Textplan aus dieser Wetter-App ersetzen die Board-Datei nicht.'),el('p','Für jede relevante Karte muss eindeutig feststehen, wer Verantwortung für das gesamte Kartenergebnis übernimmt. Benennt genau eine verantwortliche Person; Mitarbeit wird zusätzlich dokumentiert. Haltet Arbeitsprodukt bzw. Verweis, Quellen, Fertig-Kriterien, Prüfung und bei Bedarf Blockaden oder Übergaben fest. „Alle“ ist keine eindeutige Zuständigkeit.'),el('p','Die Lehrkraft beurteilt Qualität, fachliche Prüfung und nachvollziehbare individuelle Arbeit – nicht bloß die Zahl der Karten. Verantwortliche Personen müssen ihre Beiträge im Vortrag und bei Rückfragen glaubwürdig vertreten können. Sichert während des Projekts regelmäßig und exportiert zur Abgabe den letzten vollständigen Stand. Die Datei kann Namen enthalten; gebt sie nur auf dem vereinbarten schulischen Weg weiter.'),el('p','Bei Einzelarbeit steht die eigene Person auf den Karten. Vereinbart die Qualitätsprüfung mit der Lehrkraft: Die Schülerboard-App benötigt mindestens zwei eingetragene Personen und verlangt im regulären Prüfablauf eine andere prüfende Person. Vereinbart dafür eine reale prüfende Person, etwa die Lehrkraft oder einen Mitschüler; das macht euren Vortrag nicht zum Gruppenprojekt. Erfindet keine zweite Person, um diese Vorgabe zu umgehen; besprecht den zulässigen Ablauf und dokumentiert offene Prüfungen.'));
  $('kanban').append(assessment);

  function credits(){const grid=el('div',undefined,'credits');Object.values(data.media).forEach(m=>{const c=el('article');c.append(el('h3',m.title),el('p',m.credit),el('p',m.date+' · '+m.license),externalLink('Bildquelle und Nachweis',m.source));if(m.licenseURL)c.append(document.createTextNode(' · '),externalLink('Lizenzbedingungen',m.licenseURL));grid.append(c);});$('image-credits').append(grid);}
  credits();
  function taskSeed(id){return [...id].reduce((v,c)=>(Math.imul(v,31)+c.charCodeAt(0))>>>0,state.seed);}
  function answerCorrect(t,answer){if(t.type==='number'){const v=Number(String(answer).replace(',','.').trim());return String(answer).trim()!==''&&Number.isFinite(v)&&Math.abs(v-t.answer)<=t.tolerance;}if(!Array.isArray(answer))return false;const a=t.type==='order'?answer:[...answer].sort((a,b)=>a-b),b=t.type==='order'?t.correct:[...t.correct].sort((a,b)=>a-b);return a.length===b.length&&a.every((value,i)=>value===b[i]);}
  function solution(t){if(t.type==='number')return t.answer+' '+t.unit;if(t.type==='order')return t.correct.map((i,n)=>(n+1)+'. '+t.options[i]).join(' → ');return t.correct.map(i=>t.options[i]).join(' / ');}
  function renderTask(t,host){const result=state.results[t.id],locked=result&&result.status!=='retry',card=el('article',undefined,'task'+(locked?' done':''));card.id='task-'+t.id;const type={single:'Eine Antwort wählen',multi:'Alle zutreffenden Antworten wählen',order:'Reihenfolge ordnen',number:'Zahl eingeben'};card.append(el('p',type[t.type],'task-type'),el('h4',t.prompt));if(t.photo){const slot=el('div');mountPhoto(slot,t.photo);card.append(slot);}const form=el('form'),answerBox=el('div',undefined,'answer-options');let answer=Array.isArray(result?.answer)?[...result.answer]:null;
    if(t.type==='order'){let order=answer?.length===t.options.length&&new Set(answer).size===t.options.length&&answer.every(i=>Number.isInteger(i)&&i>=0&&i<t.options.length)?answer:shuffle(t.correct,rng(taskSeed(t.id)));if(!result&&order.every((v,i)=>v===i))order=[...order.slice(1),order[0]];answer=order;function draw(){answerBox.replaceChildren();answer.forEach((i,pos)=>{const row=el('div',undefined,'order-item'),text=el('span');text.append(el('strong',String(pos+1)+'.'),document.createTextNode(t.options[i]));const controls=el('div',undefined,'order-controls');for(const [symbol,delta,name] of [['↑',-1,'nach oben'],['↓',1,'nach unten']]){const b=el('button',symbol);b.type='button';b.setAttribute('aria-label',t.options[i]+' '+name);b.disabled=locked||pos+delta<0||pos+delta>=answer.length;b.onclick=()=>{[answer[pos],answer[pos+delta]]=[answer[pos+delta],answer[pos]];draw();answerBox.children[pos+delta].querySelector('button:not(:disabled)')?.focus();};controls.append(b);}row.append(text,controls);answerBox.append(row);});}draw();}
    else if(t.type==='number'){const label=el('label','Deine Antwort in '+t.unit),input=el('input');input.type='text';input.inputMode='decimal';input.id='input-'+t.id;input.value=typeof result?.answer==='string'?result.answer:'';input.disabled=locked;input.autocomplete='off';label.append(input);answerBox.append(label);}
    else{shuffle(t.options.map((_,i)=>i),rng(taskSeed(t.id))).forEach(i=>{const label=el('label'),input=el('input');input.type=t.type==='multi'?'checkbox':'radio';input.name=t.id;input.value=String(i);input.checked=answer?.includes(i)||false;input.disabled=locked;label.append(input,document.createTextNode(t.options[i]));answerBox.append(label);});}
    form.append(answerBox);const buttons=el('div',undefined,'actions'),check=el('button',locked?'Abgeschlossen':'Antwort prüfen','primary');check.type='submit';check.disabled=locked;buttons.append(check);const feedback=el('div');feedback.setAttribute('tabindex','-1');feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');if(result){feedback.className='feedback '+(result.status==='correct'?'success':'error');if(result.status==='retry')feedback.textContent='Noch nicht richtig. Nutze den Hinweis: Ein zweiter Versuch ist möglich.';else feedback.append(el('strong',result.status==='correct'?'Richtig · '+result.score+' XP':'Zwei Versuche beendet · 0 XP'),el('p','Lösung: '+solution(t)),el('p',t.explanation));}const hint=el('details');hint.append(el('summary','Hinweis anzeigen'),el('p',t.hint));form.append(buttons,feedback,hint);form.onsubmit=event=>{event.preventDefault();let value;if(t.type==='number')value=form.querySelector('input').value;else if(t.type==='order')value=[...answer];else value=[...form.querySelectorAll('input:checked')].map(n=>Number(n.value));if((Array.isArray(value)&&!value.length)||(typeof value==='string'&&!value.trim())){feedback.className='feedback error';feedback.textContent='Gib zuerst eine Antwort ein.';return;}const attempts=(result?.attempts||0)+1,correct=answerCorrect(t,value);state.results[t.id]={attempts,status:correct?'correct':attempts>=2?'missed':'retry',score:correct?(attempts===1?1:.5):0,answer:value};save();const next=el('div');renderTask(t,next);const fresh=next.firstElementChild;for(const slot of photoSlots)if(card.contains(slot.stage))photoSlots.delete(slot);card.replaceWith(fresh);fresh.querySelector('.feedback')?.focus?.({preventScroll:true});progress();};card.append(form);host.append(card);
  }
  function renderQuiz(){for(const slot of photoSlots)if($('quiz').contains(slot.stage))photoSlots.delete(slot);$('quiz').replaceChildren();selected.forEach(({group,tasks})=>{const section=el('section',undefined,'quiz-group');section.append(el('h3',group.title));const link=el('a','Erklärung nochmals ansehen ↑');link.href='#'+group.id;link.className='small';section.append(link);tasks.forEach(t=>renderTask(t,section));$('quiz').append(section);});progress();}
  function progress(){const chosen=selected.flatMap(x=>x.tasks),points=chosen.reduce((s,t)=>s+(state.results[t.id]?.score||0),0),done=chosen.filter(t=>['correct','missed'].includes(state.results[t.id]?.status)).length;$('points').textContent=points.toLocaleString('de-DE')+' / 24 XP';$('progress').value=done;$('completed').textContent=done+' von 24 Missionen abgeschlossen';$('rank').textContent=points>=20?'Wetter-Erklärprofi':points>=14?'System-Forscher':points>=7?'Wetter-Entdecker':'Wetter-Spürnase';$('badges').replaceChildren();selected.forEach(({group,tasks})=>{const score=tasks.reduce((s,t)=>s+(state.results[t.id]?.score||0),0),badge=el('span',(score>=2?'✓ ':'○ ')+group.badge,'badge'+(score>=2?'':' locked'));badge.title=group.title+': '+score.toLocaleString('de-DE')+' / 3 XP';$('badges').append(badge);});$('quiz-summary').textContent=done===24?'Runde abgeschlossen: '+points.toLocaleString('de-DE')+' / 24 XP. Nutze die Erklärungen zu unsicheren Aufgaben und wende dein Wissen im Projekt an.':done+' Missionen abgeschlossen. Du kannst jederzeit zum Lernteil zurückkehren.';}
  renderQuiz();
  function appearance(){document.body.dataset.theme=state.theme;document.body.classList.toggle('paused',state.paused);$('theme').textContent=state.theme==='dark'?'Helles Farbschema':'Dunkles Farbschema';$('theme').setAttribute('aria-label',$('theme').textContent+' einschalten');$('motion').textContent=state.paused?'Animationen fortsetzen':'Animationen pausieren';$('motion').setAttribute('aria-pressed',String(state.paused));}
  $('theme').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';appearance();save();};$('motion').onclick=()=>{state.paused=!state.paused;appearance();save();};appearance();
  async function fullscreen(target){try{if(document.fullscreenElement)await document.exitFullscreen();else if(target.requestFullscreen)await target.requestFullscreen();else $('announcement').textContent='Dieser Browser unterstützt hier keinen Vollbildmodus.';}catch(_){$('announcement').textContent='Vollbild konnte nicht gestartet werden. Verwende bei Bedarf den Vollbildmodus deines Browsers.';}}
  $('fullscreen').onclick=()=>fullscreen(document.documentElement);document.querySelectorAll('[data-full]').forEach(b=>b.onclick=()=>fullscreen($(b.dataset.full)));document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Vollbild beenden':'Vollbild';document.querySelectorAll('[data-full]').forEach(b=>b.textContent=document.fullscreenElement===$(b.dataset.full)?'Vollbild beenden':'Modul-Vollbild');});
  function sun(){const deg=Number($('sun-angle').value),s=Math.sin(deg*Math.PI/180),half=50/s,dx=180/Math.tan(deg*Math.PI/180);$('angle-value').textContent=deg+'°';$('light-beam').setAttribute('d',`M${320-half-dx} 25L${320+half-dx} 25L${320+half} 205L${320-half} 205Z`);$('lit-ground').setAttribute('d',`M${320-half} 205H${320+half}`);$('sun-result').textContent='Relative Bestrahlung pro Fläche: '+Math.round(s*100)+' % des senkrechten Einfalls. Die beleuchtete Fläche ist '+(1/s).toLocaleString('de-DE',{maximumFractionDigits:2})+'-mal so groß.';}
  $('sun-angle').oninput=sun;sun();
  function pressed(selector,value,attribute){document.querySelectorAll(selector).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[attribute]===value)));}
  function wind(hemi){pressed('[data-hemi]',hemi,'hemi');const paths=$('wind-paths');paths.replaceChildren();for(let i=0;i<4;i++){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',hemi==='north'?'M460 155C460 75 320 45 240 105C185 155 250 200 294 181':'M460 155C460 235 320 265 240 205C185 155 250 110 294 129');p.setAttribute('transform',`rotate(${i*90} 320 155)`);p.setAttribute('fill','none');p.setAttribute('stroke','#608477');p.setAttribute('stroke-width','4');p.setAttribute('marker-end','url(#wind-arrow)');p.classList.add('wind-flow');paths.append(p);}$('wind-result').textContent=hemi==='north'?'Nordhalbkugel: bodennah gegen den Uhrzeigersinn und schräg nach innen. Coriolis lenkt die Bewegung nach rechts ab.':'Südhalbkugel: bodennah im Uhrzeigersinn und schräg nach innen. Coriolis lenkt die Bewegung nach links ab.';}
  document.querySelectorAll('[data-hemi]').forEach(b=>b.onclick=()=>wind(b.dataset.hemi));wind('north');
  const svgNS='http://www.w3.org/2000/svg';function svg(tag,attrs,text){const n=document.createElementNS(svgNS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));if(text)n.textContent=text;return n;}
  const rows=[{lat:'90° N',y:40,label:'Polarhoch',dir:0},{lat:'60° N',y:100,label:'Subpolare Tiefdruckzone',dir:-1},{lat:'30° N',y:160,label:'Subtropisches Hoch',dir:1},{lat:'0°',y:205,label:'ITCZ · Aufsteigen',dir:0},{lat:'30° S',y:250,label:'Subtropisches Hoch',dir:1},{lat:'60° S',y:310,label:'Subpolare Tiefdruckzone',dir:-1},{lat:'90° S',y:370,label:'Polarhoch',dir:0}];rows.forEach(r=>{$('latitude-lines').append(svg('line',{x1:100,y1:r.y,x2:900,y2:r.y,stroke:'currentColor',opacity:.2}),svg('text',{x:85,y:r.y+5,'text-anchor':'end'},r.lat),svg('text',{x:115,y:r.y-8},r.label));});
  const zoneData={itcz:{range:[185,225],text:'Äquatornah: Passate strömen zusammen, Luft steigt in Konvektion auf. Viele Wolken und häufige kräftige Niederschläge; Lage saisonal veränderlich.'},trades:{range:[150,260],text:'Zwischen Subtropen und ITCZ: bodennah Nordostpassat im Norden und Südostpassat im Süden. Beide bringen Luft mit einer westwärts gerichteten Komponente zur Konvergenzzone.'},highs:{range:[140,270],text:'Um etwa 30° Nord und Süd: im Mittel Absinken und subtropische Hochdruckgebiete. Kompression erwärmt Luft, relative Feuchte sinkt; trockenes Wetter ist begünstigt.'},west:{range:[95,315],text:'Mittlere Breiten: Westwinde und wandernde Tiefs transportieren Luft, Wärme und Feuchte. Die schematische Ferrel-Zelle ist indirekt und durch Wetterwirbel geprägt.'},polar:{range:[25,385],text:'Hohe Breiten: im Mittel polare Hochs und bodennahe Ostwinde. An den Grenzen zur wärmeren Luft entstehen wechselhafte Wetterlagen; auch hier gibt es keinen starren Alltag.'}};
  function zone(name){pressed('[data-zone]',name,'zone');const h=$('circ-highlight');h.replaceChildren();const bands={itcz:[[185,40]],trades:[[160,40],[210,40]],highs:[[145,30],[235,30]],west:[[105,45],[260,45]],polar:[[40,50],[320,50]]};bands[name].forEach(([y,height])=>h.append(svg('rect',{x:100,y,width:800,height,fill:'#ba8a4a',opacity:.2,rx:8})));const winds=$('circ-winds');winds.replaceChildren();const arrows=[{y:72,dx:-70,dy:14,label:'Polare Ostwinde'},{y:130,dx:75,dy:-22,label:'Westwinde'},{y:183,dx:-75,dy:20,label:'Nordostpassat'},{y:230,dx:-75,dy:-20,label:'Südostpassat'},{y:285,dx:75,dy:22,label:'Westwinde'},{y:343,dx:-70,dy:-14,label:'Polare Ostwinde'}];arrows.forEach(r=>{for(let i=0;i<2;i++)winds.append(svg('path',{d:`M${530+i*150} ${r.y}l${r.dx} ${r.dy}`,fill:'none',stroke:'#436c69','stroke-width':3,'marker-end':'url(#circ-arrow)',class:'wind-flow'}));winds.append(svg('text',{x:755,y:r.y+5},r.label));});$('zone-result').textContent=zoneData[name].text;}
  document.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>zone(b.dataset.zone));zone('itcz');
  function season(name){pressed('[data-season]',name,'season');const summer=name==='july';$('land-label').textContent=summer?'relativ stark erwärmt':'relativ stark abgekühlt';$('monsoon-arrow').textContent=summer?'↑ ↑ ↑':'↓ ↓ ↓';$('ocean-label').textContent=summer?'Feuchtequelle':'relativ wärmer als das Land';$('season-result').textContent=summer?'Sommer: feuchte bodennahe Strömung vom Indischen Ozean nach Südasien unterstützt den Sommermonsun. Hebung fördert Regen.':'Winter: bodennah strömt Luft in weiten Teilen aus dem Kontinent. Je nach Küste und Anströmung kann sie über dem Meer wieder Feuchte aufnehmen – nicht überall bedeutet Wintermonsun Trockenheit.';}
  document.querySelectorAll('[data-season]').forEach(b=>b.onclick=()=>season(b.dataset.season));season('july');
  function enso(name){pressed('[data-enso]',name,'enso');const values={neutral:{warm:'M65 200H570L520 230L65 270Z',thermo:'M65 270Q400 260 835 215',arrow:'M700 110H220',cloud:220,up:'M780 290V215',text:'Typischer Zustand: Passate treiben Oberflächenwasser westwärts. Warmes Wasser und kräftige Konvektion liegen besonders im Westen; vor Südamerika steigt kühleres Wasser auf.'},nino:{warm:'M65 200H835V260L65 270Z',thermo:'M65 270Q400 265 835 260',arrow:'M620 110H410',cloud:610,up:'M780 290V272',text:'El Niño: Passate sind im Mittel geschwächt, warmes Wasser reicht weiter nach Osten. Der Auftrieb wird geschwächt, Konvektion verlagert sich und Fernwirkungen verändern regionale Wetterchancen.'},nina:{warm:'M65 200H450L390 235L65 280Z',thermo:'M65 280Q400 270 835 205',arrow:'M790 110H170',cloud:180,up:'M780 295V205',text:'La Niña: Verstärkte Passate und ausgeprägterer Kaltwasserauftrieb begünstigen einen kühleren zentralen/östlichen äquatorialen Pazifik. Die regionale Wetterwirkung hängt von Jahreszeit und Lage ab.'}}[name];$('warm-water').setAttribute('d',values.warm);$('thermocline').setAttribute('d',values.thermo);$('trade-arrow').setAttribute('d',values.arrow);$('rain-cloud').setAttribute('transform',`translate(${values.cloud} 140)`);$('upwelling').setAttribute('d',values.up);$('enso-result').textContent=values.text;}
  document.querySelectorAll('[data-enso]').forEach(b=>b.onclick=()=>enso(b.dataset.enso));enso('neutral');
  document.querySelectorAll('[data-note]').forEach(n=>{n.value=state.notes[n.dataset.note]||'';n.addEventListener('input',()=>{state.notes[n.dataset.note]=n.value;save();});});
  data.checks.forEach((text,i)=>{const label=el('label'),input=el('input');input.type='checkbox';input.checked=state.checks[i]||false;input.onchange=()=>{state.checks[i]=input.checked;save();quality();};label.append(input,document.createTextNode(text));$('quality-checks').append(label);});function quality(){const count=Object.values(state.checks).filter(Boolean).length;$('quality-result').textContent=count+' von '+data.checks.length+' Kriterien geprüft. Das ist eure Selbsteinschätzung, keine automatische Bewertung.';}quality();
  function planText(){const labels={topic:'Thema',team:'Team / Namen',boardmaster:'Boardmaster',deadline:'Termin',question:'Leitfrage',mechanism:'Mechanismus',local:'Konkreter Ort und Folgen',sources:'Quellenlog',audience:'Publikumsaufgabe'};return 'WETTERWELTEN · REFERATSPLAN\n'+new Date().toLocaleDateString('de-DE')+'\n\n'+Object.entries(labels).map(([k,v])=>v+'\n'+(state.notes[k]||'Noch offen')).join('\n\n')+'\n\nQUALITÄTSCHECK\n'+data.checks.map((t,i)=>(state.checks[i]?'[x] ':'[ ] ')+t).join('\n')+'\n\nABGABE\nZusätzlich den echten JSON-Export aus der Schüler-Kanbanboard-App abgeben. Dieser Textplan ist kein Board-Export. Auf jeder Karte: eindeutig verantwortliche Person, Ergebnis, Quellen, Fertig-Kriterien und Prüfstand. KI darf helfen, Inhalte müssen geprüft und selbst erklärbar sein.\n';}
  $('export-plan').onclick=()=>{const blob=new Blob([planText()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='wetterwelten-referatsplan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('print-plan').onclick=()=>{document.querySelectorAll('#werkstatt textarea').forEach(n=>{n.style.height='auto';n.style.height=n.scrollHeight+'px';});window.print();};window.addEventListener('afterprint',()=>document.querySelectorAll('#werkstatt textarea').forEach(n=>n.style.height=''));
  let resetMode='all';function resetRequest(mode){resetMode=mode;$('reset-title').textContent=mode==='round'?'Neue Aufgabenrunde beginnen?':'Diese Lernreise zurücksetzen?';$('reset-text').textContent=mode==='round'?'Deine bisherigen Missionsergebnisse, Punkte und Abzeichen werden gelöscht. Du erhältst 24 neu zusammengestellte Aufgaben; einzelne können erneut vorkommen. Notizen und Referatsplan bleiben erhalten.':'Alle WetterWelten-Ergebnisse, Notizen, Referatsplan, Qualitätschecks und Darstellungswahl werden auf diesem Gerät gelöscht. Andere Apps und dein separates Kanbanboard bleiben unverändert. Sichere vorher deinen Plan und die Board-JSON.';$('reset-dialog').returnValue='';$('reset-dialog').showModal();}
  $('new-round').onclick=()=>resetRequest('round');$('reset').onclick=()=>resetRequest('all');$('reset-dialog').addEventListener('close',()=>{if($('reset-dialog').returnValue!=='confirm')return;if(resetMode==='round'){state.seed=freshSeed();state.results={};}else{state=defaults();document.querySelectorAll('[data-note]').forEach(n=>n.value='');$('quality-checks').querySelectorAll('input').forEach(n=>n.checked=false);appearance();quality();$('sun-angle').value='60';sun();wind('north');zone('itcz');season('july');enso('neutral');permissionUpdate(false);$('wiki-revoke').click();}selected=selection();save();renderQuiz();$('announcement').textContent=resetMode==='round'?'Neue Aufgabenrunde erstellt.':'WetterWelten zurückgesetzt. Externe Freigabe ist zurückgenommen.';});
  const mobile=matchMedia('(max-width:800px)');function navSize(){if(mobile.matches)$('navigation').open=false;else $('navigation').open=true;}navSize();mobile.addEventListener('change',navSize);$('navigation').querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{if(mobile.matches)$('navigation').open=false;}));
  if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){document.querySelectorAll('.sidebar a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id));}},{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('main section[id]').forEach(n=>observer.observe(n));}
  save();
  // Exposed only for deterministic local regression tests, not grading.
  window.WetterWeltenTest={selection,answerCorrect,solution};
})();
