/* Original learning tasks and project prompts. Remote media are never prefetched here. */
(function(root){
  'use strict';
  const commons='https://commons.wikimedia.org/wiki/File:';
  function image(title,url,file,credit,license,date,caption,prompt,reading,licenseURL='') {return {title,url,source:commons+encodeURIComponent(file),credit,license,licenseURL,date,caption,prompt,reading};}
  const media={
    earth:image('Eine Erde, viele Wolken','https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/The_Blue_Marble_%28remastered%29.jpg/1280px-The_Blue_Marble_%28remastered%29.jpg','The Blue Marble (remastered).jpg','NASA / Besatzung Apollo 17','Public domain','7. Dezember 1972','Blue Marble: Aufnahme auf dem Weg zum Mond, keine heutige Wetterkarte.','Welche Flächen sind Wolken, welche Eis? Warum ist das nicht überall eindeutig?','Das Foto zeigt großräumige Muster, aber keine Windpfeile oder Luftdruckwerte. Antarktisches Eis und Wolken können ähnlich hell erscheinen.'),
    global:image('Das Drei-Zellen-Modell','https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Earth_Global_Circulation_-_en.svg/1280px-Earth_Global_Circulation_-_en.svg.png','Earth Global Circulation - en.svg','Kaidor','CC BY-SA 3.0','2013','Englisch beschriftetes Schema: Hadley-, Ferrel- und Polarzelle, keine Momentaufnahme.','Finde aufsteigende Luft und die subtropischen Absinkgebiete. Was lässt diese Zeichnung weg?','Die Zeichnung mittelt Wetter über Raum und Zeit. Fronten, Kontinente und die wechselnden Zugbahnen einzelner Tiefs sind hier nicht dargestellt.','https://creativecommons.org/licenses/by-sa/3.0/'),
    itcz:image('Ein äquatornahes Wolkenband','https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/IntertropicalConvergenceZone-EO.jpg/1280px-IntertropicalConvergenceZone-EO.jpg','IntertropicalConvergenceZone-EO.jpg','NASA Earth Observatory / NOAA GOES-11','Public domain','undatiertes Satellitenkomposit','Wolkendaten und eingefärbte Landbedeckung zusammengesetzt. Helles Wolkenband: ITCZ.','Wo liegt das breite Wolkenband? Warum ist es kein exakt geschlossener Ring?','Die ITCZ besteht aus vielen Konvektionsgebieten. Ihre Lage wird unter anderem durch Jahreszeit, Meerestemperatur und Kontinente beeinflusst.'),
    sahara:image('Die Sahara aus dem All','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Sahara_satellite_hires.jpg/1280px-Sahara_satellite_hires.jpg','Sahara satellite hires.jpg','NASA','Public domain','2002 · Satellitenmosaik','Die helle Wüstenregion Nordafrikas. Ein Mosaik erklärt Landschaft, nicht das Wetter eines einzigen Tages.','Vergleiche Wüste und grünere Regionen. Kann man daraus allein die heutigen Niederschläge ablesen?','Nein. Landschaft zeigt langfristige Bedingungen; ein Wetterbefund verlangt eine datierte Messung. Subtropisches Absinken ist ein wichtiger, aber nicht der einzige Faktor.'),
    monsoon:image('Monsunwolken an der Küste','https://upload.wikimedia.org/wikipedia/commons/d/d6/Monsoon_clouds_arriving_at_Port_Blair%2C_Andaman.jpg','Monsoon clouds arriving at Port Blair, Andaman.jpg','RIDHVAN SHARMA','CC BY-SA 4.0','22. Mai 2021','Port Blair, Andamanen. Anschauliches Monsunmotiv, kein Foto der Pakistanflut.','Was siehst du sicher – und was könntest du über Wind und Niederschlag nur vermuten?','Sicher sind sichtbare Wolken und die Küstenlandschaft. Eine jahreszeitliche Windumstellung oder Regenmenge lässt sich aus einem Einzelbild nicht messen.','https://creativecommons.org/licenses/by-sa/4.0/'),
    katrina:image('Katrina von oben','https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Katrina_2005-08-28_1702Z.jpg/1280px-Katrina_2005-08-28_1702Z.jpg','Katrina 2005-08-28 1702Z.jpg','Jeff Schmaltz, MODIS Rapid Response Team, NASA/GSFC','Public domain','28. August 2005','MODIS-Satellitenaufnahme im Golf von Mexiko, vor dem Landgang am 29. August.','Finde Auge, Augenwand und äußere Wolkenbänder. Warum heißt ein sichtbares Auge nicht „ungefährlich“?','Das Auge ist von sehr aktiver Augenwand umgeben. Ein Satellitenfoto misst weder die gesamte Sturmflut noch die Verletzlichkeit der betroffenen Orte.'),
    'katrina-local':image('Überflutetes New Orleans','https://upload.wikimedia.org/wikipedia/commons/3/3d/KatrinaNewOrleansFlooded_edit2.jpg','KatrinaNewOrleansFlooded edit2.jpg','U.S. Coast Guard, Kyle Niemi · via AP; bearbeitete Commons-Version','Public domain','29. August 2005','Blick über Interstate 10 / West End Boulevard in Richtung Lake Pontchartrain.','Welche Alltagsfunktionen fallen hier aus? Welche Ursachen sind im Foto selbst nicht zu sehen?','Verkehr, Wohnen und Versorgung sind betroffen. Regen, Sturmflut und Deichbrüche müssen anhand anderer Quellen auseinandergehalten werden.'),
    pakistan:image('Sindh: ein Vorher-Nachher-Vergleich','https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/2022_Pakistan_Floods_-_August_27%2C_2021_vs._August_27%2C_2022_in_Sindh.jpg/1280px-2022_Pakistan_Floods_-_August_27%2C_2021_vs._August_27%2C_2022_in_Sindh.jpg','2022 Pakistan Floods - August 27, 2021 vs. August 27, 2022 in Sindh.jpg','NASA / Aqua MODIS / Worldview','Public domain','27. August 2021 und 27. August 2022','Falschfarbenvergleich (Bänder 7–2–1), keine natürliche Farbfotografie.','Welche Flächen haben sich verändert? Welche Zusatzinformation brauchst du, bevor du Farben deutest?','Man benötigt die Bandkombination und Farbinterpretation. Der Vergleich zeigt veränderte Wasserflächen; er erklärt allein noch nicht die gesamte Ursachenbilanz.'),
    'pakistan-local':image('Ein Dorf in Sindh unter Wasser','https://upload.wikimedia.org/wikipedia/commons/3/32/Flood_in_Sindh_2022.jpg','Flood in Sindh 2022.jpg','Ali Hyder Junejo','CC BY 2.0','13. Oktober 2022','Dorf Umeed Ali Junejo im Distrikt Qambar Shahdadkot; anhaltende Folgen der Flut.','Warum können Folgen lange nach dem stärksten Regen anhalten?','Wasserabfluss, zerstörte Wege und Gebäude, verlorene Ernten und unterbrochene Versorgung können den Alltag noch lange bestimmen. Prüfe die konkreten Folgen mit Ereignisquellen.','https://creativecommons.org/licenses/by/2.0/'),
    'pakistan-air':image('Wasserflächen in Sindh','https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Flood_in_Pakistan_2022.png/1280px-Flood_in_Pakistan_2022.png','Flood in Pakistan 2022.png','Ali Hyder Junejo','CC BY 2.0','3. September 2022','Luftaufnahme der überschwemmten Region Sindh.','Welche Dimension der Flut wird sichtbar? Was fehlt für eine Quantifizierung?','Die räumliche Ausdehnung wird anschaulich. Für Fläche, Tiefe oder betroffene Bevölkerung braucht man Kartierung, Maßstab und weitere Daten.','https://creativecommons.org/licenses/by/2.0/'),
    kyrill:image('Kyrill über Europa','https://upload.wikimedia.org/wikipedia/commons/b/b5/STMeurope018_MO.jpg','STMeurope018 MO.jpg','NOAA / NASA, OSEI','Public domain','18. Januar 2007','Satellitenbild mit ergänzten Windangaben in Knoten (kn). 1 kn ≈ 1,85 km/h.','Suche das Wolkensystem und beachte die Einheit. Sind die eingezeichneten Werte überall Flächenmessungen?','Eine kombinierte Darstellung enthält unterschiedliche Informationen. Die Zahlen sind lokale Windangaben; sie machen nicht jede Wolkenfläche zu einer Windmessung.'),
    'kyrill-forest':image('Wald nach Kyrill','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Wald_nach_Kyrill.JPG/1280px-Wald_nach_Kyrill.JPG','Wald nach Kyrill.JPG','Mirek256','CC BY-SA 3.0','20. Januar 2007','Sturmschäden im Lausitzer Gebirge.','Wie unterscheiden sich Wettergefahr und längerfristige Folgen für einen Wald?','Wind bricht oder entwurzelt Bäume unmittelbar. Waldstruktur, Aufarbeitung, Wege, Lebensräume und künftige Stabilität bleiben anschließend verändert.','https://creativecommons.org/licenses/by-sa/3.0/'),
    'kyrill-trains':image('Ein Sturm, viele ausgefallene Züge','https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Kings_Cross_2007-01-18_all_cancelled_1.JPG/1280px-Kings_Cross_2007-01-18_all_cancelled_1.JPG','Kings Cross 2007-01-18 all cancelled 1.JPG','Edward Betts','Public domain','18. Januar 2007','Abfahrtstafel in London King’s Cross während des Sturms.','Wie kann eine Sturmlage Menschen betreffen, die nicht direkt im stärksten Wind stehen?','Verkehrsnetze verbinden viele Orte. Ausfälle und Vorsichtsmaßnahmen können weit über den Bereich der stärksten lokalen Böen hinaus wirken.'),
    ahr:image('Spuren der Flut in Ahrweiler','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Consequences_of_the_floodings_in_Ahrweiler%2C_Germany.9.jpg/1280px-Consequences_of_the_floodings_in_Ahrweiler%2C_Germany.9.jpg','Consequences of the floodings in Ahrweiler, Germany.9.jpg','Jean-Christophe Verhaegen / European Commission','CC BY 4.0','20. Juli 2021','Folgen des Hochwassers in Ahrweiler; Aufnahme nach der Flut.','Trenne in deiner Beschreibung sichtbaren Schaden von vermuteter Ursache.','Schäden lassen sich beobachten. Die Wirkung von Regen, Relief, Abfluss und Warnsystemen muss mit weiteren Belegen untersucht werden.','https://creativecommons.org/licenses/by/4.0/'),
    paris:image('Sommer am Seineufer','https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Paris_Plages_summer_event_along_the_banks_of_the_Seine_River%2C_featuring_palm_trees_and_red_umbrellas.jpg/1280px-Paris_Plages_summer_event_along_the_banks_of_the_Seine_River%2C_featuring_palm_trees_and_red_umbrellas.jpg','Paris Plages summer event along the banks of the Seine River, featuring palm trees and red umbrellas.jpg','Aliva Sahoo','CC BY-SA 3.0','24. Juli 2026 laut Commons / EXIF','Paris Plages. Sommermotiv, kein Messnachweis für die Juni-Hitzewelle.','Welche Möglichkeiten zur Entlastung siehst du? Was lässt das Foto über die Lufttemperatur offen?','Schatten und Aufenthaltsräume sind sichtbar. Ein Foto ohne Messung belegt weder eine Temperatur noch die gesundheitliche Wirksamkeit einer Maßnahme.','https://creativecommons.org/licenses/by-sa/3.0/'),
    'paris-thermal':{title:'Paris als Oberflächentemperaturkarte',url:'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia26/pia26190/PIA26190.jpg?w=1400&fit=clip',source:'https://science.nasa.gov/photojournal/ecostress-captures-paris-during-europe-heat-wave/',credit:'NASA / JPL-Caltech · PIA26190 · ECOSTRESS',license:'NASA-eigenes Bild · Nutzung gemäß NASA-Richtlinien',licenseURL:'https://www.nasa.gov/nasa-brand-center/images-and-media/',date:'1. Juli 2025 · 06:57 Ortszeit; veröffentlicht 3. Juli 2025',caption:'Vergleichsaufnahme aus 2025, NICHT der Hitzewelle 2026. Gemessen wird die Temperatur von Oberflächen, nicht die Lufttemperatur einer Wetterstation.',prompt:'Wo sind kühlere und wärmere Oberflächen? Warum darfst du diese Zahlen nicht mit einer Lufttemperatur in 2 m Höhe gleichsetzen?',reading:'Satelliten messen Strahlung von Oberflächen. Vegetation, Materialien, Feuchte und Verschattung beeinflussen diese Temperatur. Lufttemperatur ist eine andere Messgröße.'},
    enso:image('Typische Fernwirkungen von El Niño','https://upload.wikimedia.org/wikipedia/commons/e/e9/NOAA_Nino.jpg','NOAA Nino.jpg','NOAA Climate.gov · Rebecca Lindsey, fachlich geprüft von Tom Di Liberto','Public domain','2016 · klimatologische Übersicht','Typische saisonale Muster, KEINE Prognosekarte für 2026. Regionen reagieren je nach Jahreszeit unterschiedlich.','Warum gibt es eine Winter- und eine Sommerkarte? Gilt jede farbige Fläche bei jedem Ereignis gleich?','Die Karten zeigen typische statistische Zusammenhänge. Ereignisse unterscheiden sich; eine solche Karte garantiert nicht die Wetterfolge an einem bestimmten Ort.'),
    panama:image('Der Kanal und seine Landschaft','https://upload.wikimedia.org/wikipedia/commons/0/0d/Panama_Canal_PIA03368_lrg.jpg','Panama Canal PIA03368 lrg.jpg','NASA · PIA03368','Public domain','Archivbild 2002 laut Commons','Übersicht über den Kanalraum. Archivaufnahme, kein Bild des Wasserstandes 2026.','Finde Seen und Verbindungen. Wieso ist ein Kanal zwischen zwei Ozeanen trotzdem auf Regenwasser angewiesen?','Die Schleusen heben Schiffe über das Meeresniveau. Das Speichersystem nutzt Süßwasser aus dem Einzugsgebiet; die Ozeane ersetzen diesen Vorrat nicht einfach.'),
    'panama-locks':image('Ein Schiff in Agua Clara','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Agua_Clara_Locks_09_2019_0822.jpg/1280px-Agua_Clara_Locks_09_2019_0822.jpg','Agua Clara Locks 09 2019 0822.jpg','Mariordo (Mario Roberto Durán Ortiz)','CC BY-SA 4.0','22. September 2019','Agua-Clara-Schleusen. Archivmotiv zum Verfahren, kein Foto der Einschränkungen 2026.','Warum kann weniger verfügbares Wasser zu weniger Durchfahrten oder geringerer Beladung führen?','Schleusenbetrieb benötigt Wasser; Wasserstände begrenzen außerdem den möglichen Tiefgang. Belegt die konkreten Einschränkungen 2026 mit Angaben der Kanalbehörde.','https://creativecommons.org/licenses/by-sa/4.0/')
  };
  const projects=[
    {title:'Tropische Wirbelstürme → Katrina 2005',question:'Wie wird aus warmem Meerwasser eine Katastrophe für eine Küstenstadt?',images:['katrina','katrina-local'],wiki:'Hurrikan Katrina',scope:'Gruppenprojekt',mechanism:['Erklärt die Rolle von Verdunstung, Kondensation, Druck und Rotation. Welche weiteren Bedingungen braucht ein tropischer Wirbelsturm?','Unterscheidet Windschaden, Regenüberflutung und Sturmflut. Was sagt die Hurrikan-Kategorie – und was nicht?'],local:['Rekonstruiert den 28.–31. August 2005: Intensität vor dem Landgang, Landgang und Überflutung.','Wählt einen Stadtteil oder einen Lebensbereich in New Orleans: Evakuierung, Wohnen, Verkehr oder Versorgung. Wer war besonders verletzlich?'],product:'Eine selbst erläuterte Wirbelsturm-Grafik, eine kurze datierte Zeitleiste und ein belegtes lokales Beispiel. Keine bloße Sammlung spektakulärer Katastrophenbilder.',sources:[['NOAA/NWS · Ereignisbericht','https://www.weather.gov/mob/katrina'],['NASA · Sturmstruktur','https://science.nasa.gov/earth/earth-observatory/hurricane-katrina-15399/']],search:'Katrina New Orleans 2005 storm surge levee evacuation',commons:'Hurricane Katrina'},
    {title:'Monsun → Pakistanflut 2022',question:'Warum wird aus lebenswichtigem Regen eine lang anhaltende Überflutung?',images:['pakistan','pakistan-local','pakistan-air'],wiki:'Überschwemmungskatastrophe in Pakistan 2022',scope:'Gruppenprojekt',mechanism:['Erklärt jahreszeitliche Windumstellung und Feuchtetransport. Welche Rolle spielen Hebung und Gebirge?','Trennt Regen, Flussabfluss und stehendes Wasser. Warum beschreibt „Monsun“ nicht einfach eine Katastrophe?'],local:['Untersucht einen Ort oder Distrikt in Sindh: Häuser, Schulen, Landwirtschaft oder Trinkwasser.','Sucht eine datierte Regenangabe und eine belegte längerfristige Folge. Warum bleiben Folgen nach dem Regen bestehen?'],product:'Eine eigene Ursache-Folge-Kette sowie ein Vorher-Nachher-Bild mit erklärten Farben und ein lokales Folgenprofil. Macht Unsicherheiten bei der Klimazuschreibung sichtbar.',sources:[['WMO · Regen und Ereignisattribution','https://wmo.int/media/news/climate-change-likely-increased-intense-rainfall-pakistan-study'],['NASA Worldview · datierte Satellitenbilder','https://worldview.earthdata.nasa.gov/']],search:'Pakistan floods 2022 Sindh monsoon school agriculture rainfall WMO',commons:'2022 floods in Pakistan'},
    {title:'Westwindzone & Wintersturm → Kyrill 2007',question:'Wie erreicht ein wanderndes Tief Wälder, Bahnnetze und unseren Alltag?',images:['kyrill','kyrill-forest','kyrill-trains'],wiki:'Orkan Kyrill',scope:'Gruppenprojekt',mechanism:['Erklärt Polarfront, Tiefentwicklung, Druckgradient und Höhenströmung. Warum ist ein Wintersturm kein Hurrikan?','Zeigt die Zugbahn und erklärt den Unterschied zwischen Wind und Böe. Achtet auf km/h, m/s und Knoten.'],local:['Wählt Waldschäden im Sauerland/Lausitzer Gebirge oder den Bahnbetrieb am 18. Januar 2007.','Ermittelt zwei belegte Folgen und unterscheidet unmittelbare Gefahr von längerfristiger Störung.'],product:'Eine erläuterte Zugbahnkarte und eine Quellen-Tabelle mit Messgröße, Ort, Zeitpunkt und Einheit. Verbindet sie mit einem konkreten Lebensbereich.',sources:[['DWD · Fünf Jahre nach Kyrill (PDF)','https://www.dwd.de/DE/presse/pressemitteilungen/DE/2012/20120116_5jahre_kyrill.pdf?__blob=publicationFile&v=4'],['NOAA · Jetstream','https://www.noaa.gov/jetstream/global/jet-stream']],search:'Kyrill 18 Januar 2007 DWD Böen Bahn Wald Sauerland',commons:'Kyrill (storm)'},
    {title:'Lang anhaltender Starkregen → Ahrtal 2021',question:'Wie wird ein langsam ziehendes Tief in einem engen Tal zur Flut?',images:['ahr'],wiki:'Hochwasser in West- und Mitteleuropa 2021',scope:'Gruppenprojekt',mechanism:['Erklärt Feuchtenachschub, Hebung und lange Verweildauer. Welche Rolle spielt das Einzugsgebiet?','Unterscheidet Regenmenge, Flusspegel und Abfluss. Eine Zahl ohne Einheit ist keine Erklärung.'],local:['Wählt einen Ort an der Ahr und rekonstruiert den 14./15. Juli 2021 mit datierten Belegen.','Untersucht Erreichbarkeit, Warnung, Wohnen oder zerstörte Infrastruktur. Vermeidet eine einseitige Ursache ohne Beleg.'],product:'Eine eigene Skizze des Einzugsgebietes, eine datierte Ereignisfolge und eine begründete Vorsorgemöglichkeit. Sucht selbst ein weiteres passendes Bild oder eine Karte.',sources:[['DWD · Tief Bernd (PDF)','https://www.dwd.de/DE/leistungen/besondereereignisse/niederschlag/20210721_bericht_starkniederschlaege_tief_bernd.pdf?__blob=publicationFile&v=6'],['Wissenschaftliche Untersuchung · Folgen und Warnung','https://nhess.copernicus.org/articles/25/581/2025/']],search:'DWD Tief Bernd Juli 2021 Ahr Einzugsgebiet Warnung Pegel',commons:'July 2021 floods in Ahrweiler, Germany'},
    {title:'Blocking & Hitze → Frankreich / Paris 2026',question:'Warum wird eine großräumige Hitzelage in einer Stadt zur besonderen Belastung?',images:['paris-thermal','paris'],wiki:'Hitzewelle',scope:'Gruppenprojekt · aktueller Fall',mechanism:['Erklärt eine anhaltende Hochdrucklage und mögliche Verstärkung durch trockene Böden. Prüft den belegten Ablauf 2026, statt jedes Hoch „Blocking“ zu nennen.','Unterscheidet Luft- und Oberflächentemperatur. Welche Größen beschreiben Belastung bei Tag und Nacht?'],local:['Untersucht Paris während der Juni-Hitzewelle 2026: Wohnsituation, Schule oder besonders gefährdete Menschen.','Findet einen aktuellen Messbefund und eine konkret dokumentierte Schutzmaßnahme. Was belegt die Quelle tatsächlich?'],product:'Eine lesbare, selbst erläuterte Datengrafik und ein lokales Fallprofil. Ältere Wärmebilder dürfen illustrieren, aber nicht als Messung von 2026 ausgegeben werden.',sources:[['Météo-France · Sommerbilanz 2026','https://meteofrance.com/presse/bilan-climatique-de-lete-2026-juin-juillet-aout'],['Stadt Paris · Lage und Maßnahmen am 25. Juni 2026','https://presse.paris.fr/communiques/vigilance-rouge-canicule-extreme-point-de-situation-au-25-juin-et-appel-a-la-prudence-et-a-la-responsabilite'],['NASA · Wärmebild aus 2025 als Vergleich','https://science.nasa.gov/photojournal/ecostress-captures-paris-during-europe-heat-wave/']],search:'Météo France été 2026 canicule juin Paris vigilance 25 juin',commons:'Paris Plages'},
    {title:'El Niño → Wasser und Schiffe in Panama 2026',question:'Wie kann der Pazifik verändern, wie viel ein Schiff auf einem Kanal laden darf?',images:['panama','panama-locks'],wiki:'Panamakanal',scope:'Gruppenprojekt · aktueller Fall',mechanism:['Vergleicht typische und El-Niño-Bedingungen: Passate, Oberflächenwasser und Konvektion. Was sind Fernwirkungen?','Unterscheidet beobachteten ENSO-Zustand, Stärkeprognose und lokale Folgen. Warum genügt eine Weltkarte typischer Muster nicht als lokaler Beweis?'],local:['Untersucht die Regenzeit 2026 im Kanaleinzugsgebiet und den Bericht zu Wasserspeichern, Durchfahrten und Tiefgang.','Wie konkurrieren Versorgung der Bevölkerung und Kanalbetrieb um Wasser? Welche Maßnahmen sind dokumentiert?'],product:'Eine eigene West-Ost-Skizze und eine belegte Kette vom Regen bis zur Schleuse. Kennzeichnet Quellenstand und Prognosen; prüft neue Lageberichte vor dem Vortrag.',sources:[['NOAA/CPC · ENSO-Lagebericht','https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_advisory/ensodisc.shtml'],['Kanalbehörde · Wasser und Betrieb','https://pancanal.com/agua/']],search:'Panama Canal agua 2026 El Niño rainfall Gatun draft transit CPC September 2026',commons:'Panama Canal'},
    {title:'See- und Landwind → Ein Tag an der Nordseeküste',question:'Warum kann am warmen Strand plötzlich kühlere Luft vom Meer ankommen?',images:[],wiki:'Land-See-Windsystem',scope:'Kleineres Einzelprojekt',mechanism:['Erkläre unterschiedliche Erwärmung und Abkühlung von Land und Wasser. Zeichne je einen bodennahen Windpfeil für Tag und Nacht.','Warum kann ein kräftiger großräumiger Wind das lokale Windsystem überlagern?'],local:['Wähle Cuxhaven oder einen anderen benannten Nordseeort und einen dokumentierten, möglichst windschwachen Sommertag. Suche stündliche Windrichtung, Temperatur und Zeitpunkt.','Prüfe, ob ein Windwechsel zur Seewind-Erklärung passt. Wenn nicht, erläutere die Überlagerung – erfinde keinen passenden Befund.'],product:'Eine Tag-Nacht-Skizze und eine kleine Tabelle für einen konkreten Ort und Tag; ein eigenes oder frei nutzbares Küstenbild. Kleinerer Umfang: ein System, ein Tag, ein begründetes Ergebnis.',sources:[['DWD · Regionale Flugklimatologie, Land-/Seewind (PDF)','https://www.dwd.de/DE/leistungen/pbfb_verlag_vub/pdf_einzelbaende/vub_16_gesamt_pdf.pdf?__blob=publicationFile&v=5'],['DWD Open Data · Messreihen recherchieren','https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/']],search:'DWD Cuxhaven Seewind stündlich Windrichtung Sommer',commons:'Cuxhaven'},
    {title:'Berg- und Talwind → Göschenen in einer Herbstnacht',question:'Warum zeigt ein Tal am Tag und in der Nacht andere Windrichtungen?',images:[],wiki:'Berg- und Talwind-Zirkulation',scope:'Kleineres Einzelprojekt',mechanism:['Skizziere die Tag-Nacht-Zirkulation und unterscheide Talwind von Hangwind. Warum ist das kein wechselnder Passat?','Kann ein nächtlicher Bergwind nur abkühlen? Suche im Fallbericht nach einer Erklärung für Mischung und Erwärmung.'],local:['Nutze den MeteoSchweiz-Fallbericht aus Oktober 2022 zu Göschenen. Lies Datum, Windverlauf und Temperatur aus der Quelle – nicht nur ihre Überschrift.','Erkläre eine konkrete Folge für den Talort. Unterscheide dabei allgemeines Schema und beobachtete Besonderheit.'],product:'Eine eigene Tal-Skizze und die erläuterte Tagesgang-Grafik bzw. eine eigene Tabelle aus dem Bericht. Ein begrenzter Fall statt einer vollständigen Präsentation über alle Alpenwinde.',sources:[['MeteoSchweiz · Sonnig und mild, Bergwind in Göschenen','https://www.meteoschweiz.admin.ch/ueber-uns/meteoschweiz-blog/de/2022/10/voruebergehend-recht-sonnig-und-mild.html']],search:'MeteoSchweiz Göschenen Bergwind Oktober 2022 Talwind',commons:'Göschenen'}
  ];
  projects.push(
    {title:'Föhn → Wetterwechsel in Altdorf',question:'Warum wird es in einem Alpental plötzlich wärmer und trockener?',images:[],wiki:'Föhn',scope:'Kleineres Einzelprojekt',mechanism:['Zeichne ein Gebirgsprofil mit Luv, Lee und Luftbewegung. Erkläre die Erwärmung absinkender Luft; unterscheide sie von einer Wärmequelle im Tal.','Verbinde die alpine Druckverteilung mit dem örtlichen Wind. Nicht jeder Föhnfall lässt sich allein durch Regen auf der Luvseite erklären.'],local:['Untersuche den Altdorfer Föhnbeginn im MeteoSchweiz-Bericht aus Januar 2025. Notiere das genaue Datum und vergleiche Temperatur, Feuchte und Wind vor und nach Beginn.','Beschreibe eine konkrete Alltagsfolge. Trenne beobachtete Folgen von plausiblen, aber nicht dokumentierten Vermutungen.'],product:'Eine eigene Gebirgsskizze und drei kommentierte Messwerte. Begrenze dich auf einen Föhnbeginn, nicht die gesamte Föhnklimatologie.',sources:[['MeteoSchweiz · Die drei Föhn-Begleiter/-innen, Januar 2025','https://www.meteoschweiz.admin.ch/ueber-uns/meteoschweiz-blog/de/2025/01/die-drei-foehn-begleiterinnen.html']],search:'MeteoSchweiz Altdorf Januar 2025 Föhn Temperatur Luftfeuchte',commons:'Foehn Alps'},
    {title:'Strahlungsnebel → Ein Morgen im Tal',question:'Warum kann eine vertraute Straße am Morgen plötzlich kaum sichtbar sein?',images:[],wiki:'Nebel',scope:'Kleineres Einzelprojekt',mechanism:['Erkläre nächtliche Abkühlung, Taupunkt und Kondensation. Zeichne, warum eine windschwache Lage und ein Tal Nebel begünstigen können.','Ordne die Situation in eine passende Großwetterlage ein. Warum ist nicht jeder Nebel ein Strahlungsnebel?'],local:['Wähle einen dokumentierten Herbstmorgen in einem benannten Talort, etwa an Mosel oder Neckar. Suche Datum, Sichtweite und Wetterverlauf; eine eigene sichere Beobachtung ist ebenfalls möglich.','Beschreibe eine konkrete Folge für Schulweg oder Verkehr und prüfe die Erklärung anhand von Wetterdaten. Beobachte nie im Straßenverkehr oder durch Betreten gefährlicher Stellen.'],product:'Eine Ursache-Folge-Skizze und ein örtlicher Kurzbericht mit datiertem Beleg. Ein eigenes Foto von einem sicheren Standort oder ein lizenziertes Archivbild muss passend gekennzeichnet sein.',sources:[['NOAA/NWS · Strahlungsnebel','https://www.weather.gov/safety/fog-radiation'],['DWD Open Data · Wetterbeobachtungen','https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/']],search:'Strahlungsnebel Moseltal Neckartal Sichtweite Datum DWD',commons:'Radiation fog'},
    {title:'Lake-Effect-Schnee → Orchard Park, November 2022',question:'Warum kann ein Ort im Schnee versinken, während es in der Nähe deutlich weniger schneit?',images:[],wiki:'Lake Effect',scope:'Kleineres Einzelprojekt',mechanism:['Erkläre den Kaltluftvorstoß über den relativ warmen Eriesee: Wärme- und Feuchteaufnahme, Aufsteigen und schmale Schneebänder.','Zeichne Windrichtung, See und Leeseite. Warum ist die Windrichtung für den betroffenen Ort entscheidend?'],local:['Nutze den NOAA-Ereigniseintrag zur Schneelage vom 17.–20. November 2022. Vergleiche Orchard Park und einen zweiten genannten Messort; prüfe Einheiten und Zeitraum.','Recherchiere genau eine belegte Folge für Mobilität, Räumung oder eine Veranstaltung. Verwechsle den Novemberfall nicht mit dem Dezember-Blizzard 2022.'],product:'Eine See-Wind-Skizze, zwei verglichene Schneemessungen und eine belegte örtliche Folge. Keine vollständige Geschichte aller Schneestürme in Buffalo.',sources:[['NOAA/NWS · Lake-Effect-Schnee','https://www.weather.gov/safety/winter-lake-effect-snow'],['NOAA/NCEI · Ereignisdaten November 2022','https://www.ncei.noaa.gov/stormevents/eventdetails.jsp?id=1066487']],search:'Orchard Park November 17 20 2022 lake effect snow NOAA impacts',commons:'November 2022 Great Lakes winter storm'},
    {title:'Tropennacht → Temperaturverlauf im Juli 2019',question:'Warum fehlt während einer Hitzewelle manchmal die nächtliche Abkühlung?',images:[],wiki:'Tropennacht',scope:'Kleineres Einzelprojekt',mechanism:['Erkläre den meteorologischen Begriff: Das nächtliche Lufttemperaturminimum bleibt mindestens bei 20 °C. Prüfe das Messzeitfenster der verwendeten Daten.','Verbinde die großräumige Hitzelage mit Wärmespeicherung und nächtlicher Abkühlung an einem Ort. Nicht jede Tropennacht wird allein durch Bebauung verursacht.'],local:['Wähle aus dem DWD-Bericht zur Hitzewelle Juli 2019 einen genannten Messort und eine dokumentierte Nacht. Suche den Verlauf oder das Minimum und gib Ort, Datum und Messgröße an.','Beschreibe eine belegte oder klar als Überlegung gekennzeichnete Folge für Schlaf, Lüften oder Erholung. Lufttemperatur draußen ist nicht automatisch die Temperatur einer Wohnung.'],product:'Eine selbst beschriftete Temperaturkurve mit 20-°C-Linie und eine begründete Maßnahme. Keine zweite komplette Präsentation über die Hitzewelle.',sources:[['DWD · Hitzewelle Juli 2019 (PDF)','https://www.dwd.de/DE/leistungen/besondereereignisse/temperatur/20190801_hitzerekord_juli2019.pdf?__blob=publicationFile&v=2'],['DWD · Tropennächte und städtische Wärmeinsel: Messzeitfenster','https://www.dwd.de/DE/leistungen/uhi/info_methodic/08_berechnung_raster_indikatoren_uhi.html']],search:'DWD Juli 2019 Tropennacht Nachtminimum Station Temperatur',commons:'Urban heat island'},
    {title:'Hagel → Reutlingen am 28. Juli 2013',question:'Wie können in einem Sommergewitter große Eiskörner entstehen?',images:[],wiki:'Hagel',scope:'Kleineres Einzelprojekt',mechanism:['Skizziere Gewitterwolke, Aufwind und das Wachstum von Hagelkörnern durch unterkühlte Wassertröpfchen. Warum kann Hagel bei warmer Luft am Boden fallen?','Ordne die Gewitterlage in den Luftmassen- und Temperaturkontrast ein. Unterscheide Hagel von Graupel und Schnee.'],local:['Recherchiere den Reutlinger Fall vom 28. Juli 2013. Prüfe bei Angaben zur Hagelgröße, ob sie genau aus Reutlingen oder einem anderen Ort stammen.','Wähle einen Lebensbereich, etwa Gewächshäuser, Dächer oder Fahrzeuge, und belege eine konkrete Folge.'],product:'Eine eigene Wolkenskizze und ein lokales Schadensbeispiel mit Quelle. Begrenze dich auf Hagelbildung und diesen einen Fall.',sources:[['KIT · Wettergefahren-Frühwarnung, Gewitterlage Ende Juli 2013','https://www.wettergefahren-fruehwarnung.de/Ereignis/20130731_e.html'],['SWR · Rückblick auf das Reutlinger Ereignis','https://www.swr.de/swraktuell/baden-wuerttemberg/tuebingen/10-jahre-hagel-unwetter-reutlingen-tuebingen-100.html']],search:'Reutlingen 28 Juli 2013 Hagel Aufwind Schäden Gewächshaus',commons:'Hail Reutlingen 2013'},
    {title:'Spätfrost → Obstblüte im Frühjahr 2023',question:'Warum können Blüten trotz eines insgesamt wärmeren Klimas erfrieren?',images:[],wiki:'Frost',scope:'Kleineres Einzelprojekt',mechanism:['Unterscheide einen Kaltlufteinbruch von zusätzlicher Auskühlung in einer klaren Nacht. Erkläre, warum frühe Blüte und Frost zeitlich zusammenfallen können.','Vergleiche Temperatur in 2 m Höhe und Temperatur an Pflanzen: Warum reicht eine Wetterstationszahl nicht für jede Schadensaussage?'],local:['Beginne mit dem DWD-Bericht vom 12. April 2023 und wähle einen benannten Obstbauort am Rhein sowie ein belegtes Frostereignis aus dieser Frühjahrsphase. Recherchiere die örtliche Beobachtung selbst.','Dokumentiere Pflanzenart, Entwicklungsstand und eine belegte Schutzmaßnahme oder Schadensmeldung. Ein regionales Risiko beweist nicht, dass jeder Betrieb Schäden hatte.'],product:'Ein kurzer Kalender mit Blüte und Frost, eine erklärte Skizze und eine örtliche Quelle. Untersuche eine Pflanzenart statt die gesamte Landwirtschaft.',sources:[['DWD · Pflanzenentwicklung und Spätfrost, April 2023 (PDF)','https://www.dwd.de/DE/presse/pressemitteilungen/DE/2023/20230412_pm_spaetfrostschaeden.pdf?__blob=publicationFile&v=2'],['DWD · Messhöhe, Pflanzenstadien und Schadfrostrisiko (PDF)','https://www.dwd.de/DE/klimaumwelt/aktuelle_meldungen/230406/spaetfrost_download.pdf?__blob=publicationFile&v=1']],search:'Rhein Obstblüte Spätfrost April 2023 Obstbau Ort Schutz',commons:'Frost fruit blossoms'}
  );
  function q(prompt,answer,wrong,explanation,hint='Lies die passende Erklärung noch einmal und unterscheide Ursache und Folge.',photo=''){return {type:'single',prompt,options:[answer,...wrong],correct:[0],explanation,hint,photo};}
  function m(prompt,options,correct,explanation,hint){return {type:'multi',prompt,options,correct,explanation,hint:hint||'Mehrere Antworten können zutreffen. Prüfe jede Aussage einzeln.'};}
  function o(prompt,items,explanation){return {type:'order',prompt,options:items,correct:items.map((_,i)=>i),explanation,hint:'Beginne mit der Voraussetzung. Was folgt daraus, was ist erst das Ergebnis?'};}
  function n(prompt,answer,unit,explanation){return {type:'number',prompt,answer,unit,tolerance:.01,explanation,hint:'1 mm Niederschlag entspricht 1 L pro Quadratmeter. Multipliziere mit der Fläche.'};}
  const groups=[
    {id:'antrieb',title:'Energie & Wind',badge:'Energiepfad',tasks:[
      q('Warum ist die mittlere Sonneneinstrahlung pro Bodenfläche in den Tropen größer?', 'Sonnenstrahlen treffen im Mittel steiler auf die Fläche.', ['Die Tropen liegen wesentlich näher an der Sonne.','Warme Luft zieht mehr Sonnenlicht an.'],'Steilerer Einfall verteilt ein Lichtbündel auf weniger Fläche. Wolken, Albedo und Tageslänge wirken zusätzlich.'),
      q('Was setzt Luft durch einen Druckunterschied in Bewegung?', 'Die Druckgradientkraft.', ['Die Corioliskraft allein.','Die Farbe der Wolken.'],'Der Druckunterschied beschleunigt Luft vom höheren zum niedrigeren Druck; Coriolis lenkt bewegte Luft ab.'),
      q('Was ist Luftdruck?', 'Kraft der darüberliegenden Luftsäule pro Fläche.', ['Die Windgeschwindigkeit in einem Tief.','Die Menge des Wasserdampfs allein.'],'Luft hat Gewicht. Druck ist nicht dasselbe wie Windgeschwindigkeit oder Feuchte.'),
      q('Eng beieinanderliegende Isobaren bedeuten meist …', 'einen großen Druckunterschied auf kurzer Strecke.', ['gleiche Temperatur an allen Orten.','gar keinen Windantrieb.'],'Ein steiler Druckgradient begünstigt starken Wind. Die wirkliche Geschwindigkeit hängt auch von Reibung und Strömung ab.'),
      q('Ein Westwind weht …', 'aus Westen nach Osten.', ['aus Osten nach Westen.','immer senkrecht nach oben.'],'Wind wird nach der Richtung benannt, aus der er kommt.'),
      q('Wie wirkt Coriolis auf der Nordhalbkugel?', 'Nach rechts relativ zur Bewegungsrichtung.', ['Immer nach Osten.','Nach links relativ zur Bewegungsrichtung.'],'„Rechts“ bezieht sich auf den Bewegungsvektor, nicht auf eine feste Himmelsrichtung.'),
      q('Welche Aufgabe hat die globale Zirkulation für den Energiehaushalt?', 'Sie transportiert Wärme zwischen Regionen.', ['Sie produziert die Sonnenenergie.','Sie beseitigt alle Temperaturunterschiede.'],'Die Zirkulation verteilt Energie, gleicht Unterschiede aber nicht vollständig aus.'),
      m('Welche Aussagen über bodennahen Wind stimmen?', ['Reibung bremst bewegte Luft.','Wind kann Isobaren schräg in Richtung Tief überqueren.','Coriolis erzeugt Wind auch ohne jeden Antrieb.','Ein Hoch garantiert Windstille.'],[0,1],'Bodenreibung beeinflusst den Kräfteausgleich. Auch bei einem Hoch kann Wind wehen.'),
      o('Ordne diese vereinfachte Erklärung einer Windentstehung.', ['Zwischen zwei Regionen besteht ein Druckunterschied.','Die Druckgradientkraft beschleunigt Luft.','Die Erdrotation lenkt die bewegte Luft ab.'],'Die Schritte beschreiben den gedanklichen Zusammenhang; in einer bestehenden Strömung wirken die Kräfte gleichzeitig.'),
      q('Du reduzierst im Lichtmodell den Winkel von 90° auf 30°. Was passiert bei gleicher Bündelbreite?', 'Die bestrahlte Bodenfläche wird größer.', ['Die Bündelbreite verdoppelt sich automatisch.','Die Bodenfläche bleibt gleich.'],'Bei flacherem Einfall verteilt sich dieselbe Strahlung auf eine größere Bodenfläche.')
    ]},
    {id:'tropen',title:'Passate & ITCZ',badge:'Passat-Pfad',tasks:[
      q('Was bedeutet Konvergenz in ITCZ?', 'Luft strömt zusammen.', ['Luft ist vollkommen unbeweglich.','Luft strömt ausschließlich auseinander.'],'Bodennahe Konvergenz und kräftiges Aufsteigen prägen die ITCZ.'),
      q('Warum kühlt aufsteigende Luft häufig ab?', 'Sie dehnt sich bei geringerem Umgebungsdruck aus.', ['Sie entfernt sich so stark von der Sonne.','Sie verliert schlagartig alle Wassermoleküle.'],'Die Expansion benötigt Energie; die Temperatur sinkt. Kondensation kann das Abkühlen abschwächen.'),
      q('Wo sinkt in der Hadley-Zirkulation ein Teil der Luft ab?', 'In den Subtropen ungefähr um 30° Breite.', ['Ausschließlich direkt am Äquator.','Nur genau am Nordpol.'],'Die genaue Lage variiert. Das Modell zeigt einen ungefähren subtropischen Absinkgürtel.'),
      q('Warum begünstigt Absinken trockenes Wetter?', 'Erwärmung beim Absinken senkt die relative Feuchte.', ['Absinken erzeugt automatisch mehr Gewitterwolken.','Die Luft verliert dabei jedes einzelne Wassermolekül.'],'Die Luft wird komprimiert und wärmer; Wolkenbildung wird häufig unterdrückt.'),
      q('Der Nordostpassat kommt …', 'aus Nordosten und weht in Richtung Südwesten.', ['aus Südwesten und weht nach Nordosten.','aus Westen und weht zum Nordpol.'],'Der Name bezeichnet die Herkunftsrichtung des Windes.'),
      m('Welche Aussagen über die ITCZ stimmen?', ['Ihre Lage verändert sich mit der Jahreszeit.','Sie besteht aus einem breiten, unterbrochenen Konvektionsband.','Sie liegt immer exakt auf 0° Breite.','Sie ist ein einzelner Hurrikan.'],[0,1],'Die ITCZ ist eine variable Konvergenzzone, kein fester Strich und kein einzelnes Wetterereignis.'),
      o('Verfolge eine vereinfachte Hadley-Schleife.', ['Bodennaher Passat strömt zur Konvergenzzone.','Feuchte Luft steigt auf und bildet Wolken.','Luft fließt in der Höhe in Richtung Subtropen.','Ein Teil sinkt in subtropischen Hochdruckgebieten ab.'],'Die Schleife veranschaulicht ein Mittelwertmuster; einzelne Luftpakete durchlaufen es nicht immer vollständig.'),
      q('Was wird im ITCZ-Komposit besonders sichtbar?', 'Ein äquatornahes Band heller Wolken.', ['Eine überall gleichmäßige Windgeschwindigkeit.','Eine exakte Wetterprognose für morgen.'],'Das Satellitenkomposit zeigt Wolken und eingefärbte Landflächen; Windwerte und Prognosen fehlen.','Achte darauf, welche Größe überhaupt dargestellt ist.','itcz'),
      q('Was lässt das Drei-Zellen-Schema bewusst weg?', 'Viele wandernde Wetterwirbel und regionale Unterschiede.', ['Die Tatsache, dass die Erde eine Atmosphäre hat.','Jede Aussage über Auf- und Absteigen.'],'Das Schema zeigt gemittelte große Muster, nicht jedes Tief und jedes Gebirge.'),
      q('Du siehst die Sahara im Satellitenmosaik. Was kannst du daraus NICHT allein ablesen?', 'Die Regenmenge an einem Ort am heutigen Tag.', ['Dass große Landschaftsräume unterschiedlich aussehen.','Dass es eine große Wüstenfläche gibt.'],'Landschaftsbild und aktueller Messwert sind verschiedene Informationsarten.','Ein Mosaik ist keine datierte Niederschlagsmessung.','sahara')
    ]},
    {id:'westwinde',title:'Westwindzone & Jetstream',badge:'Wetterlotse',tasks:[
      q('In welcher Zone liegt Deutschland überwiegend?', 'In den mittleren Breiten mit starkem Einfluss der Westwindzone.', ['Genau in der äquatorialen ITCZ.','In der südpolaren Ostwindzone.'],'Das bedeutet keine ständig gleiche Windrichtung; lokale Wetterlagen wechseln.'),
      q('Die Polarfront ist …', 'eine Grenzregion zwischen relativ kalten und warmen Luftmassen.', ['die Küstenlinie der Antarktis.','ein festes Gitter entlang eines Breitengrades.'],'Die Lage der Polarfront verändert sich und ist nicht überall gleich.'),
      q('Wo befindet sich der Polarfrontjet hauptsächlich?', 'In der oberen Troposphäre.', ['Direkt auf der Meeresoberfläche.','Im Erdkern.'],'Der Jet ist eine Höhenströmung. Er ist nicht mit Bodenwind oder einem Fluss zu verwechseln.'),
      q('Was ist an der Ferrel-Zelle besonders?', 'Sie ist ein indirektes Mittelwertmuster, stark durch Wetterwirbel geprägt.', ['Jede Luftmasse läuft täglich exakt denselben Kreis.','Sie existiert ausschließlich auf der Südhalbkugel.'],'Wandernde Tiefs und Hochs leisten in mittleren Breiten viel des Transports.'),
      q('Was geschieht vereinfacht an einer Warmfront?', 'Warme Luft gleitet über kühlere Luft auf.', ['Kalte Luft wird zu flüssigem Wasser.','Die Sonne springt näher an die Erde.'],'Die Hebung begünstigt Wolken und Niederschlag; die reale Frontstruktur ist komplexer.'),
      q('Was unterscheidet Kyrill grundsätzlich von Katrina?', 'Kyrill war ein außertropisches Wintertief, Katrina ein tropischer Wirbelsturm.', ['Kyrill hatte keine Luftbewegung.','Katrina war eine Inversion im Alpenraum.'],'Außertropische Tiefs hängen stark mit Luftmassengegensätzen und Fronten zusammen.'),
      m('Welche Schlussfolgerungen sind richtig?', ['Westwinde kommen aus Westen.','Einzelne Wetterlagen können andere Windrichtungen bringen.','Westwindzone heißt: jeden Tag exakt derselbe Wind.','Jetstream und Bodenwind sind dieselbe Messgröße.'],[0,1],'Ein statistisches Muster ist keine tägliche Garantie.'),
      q('Eine Wetterkarte zeigt 60 kn. Worum musst du dich vor einem Zahlenvergleich kümmern?', 'Die Einheit umrechnen oder durchgängig beibehalten.', ['Die Zahl einfach als 60 km/h vorlesen.','Knoten sind keine Geschwindigkeitseinheit.'],'Ein Knoten entspricht ungefähr 1,85 km/h. Verwechslung verändert die Aussage erheblich.','Lies die Beschriftung der Karte.','kyrill'),
      q('Ein Tief zieht mit einer welligen Höhenströmung. Was ist die passende Deutung?', 'Die Höhenströmung kann Zugbahn und Entwicklung beeinflussen.', ['Der Jet ist ein starres Gleis ohne Abweichungen.','Boden und Atmosphäre sind vollständig voneinander getrennt.'],'Die Wechselwirkung ist komplex; der Jetstream ist kein vorgeschriebenes Schienensystem.'),
      q('Warum kann ein Sturm auch weit entfernte Reisende betreffen?', 'Verbundene Verkehrsnetze können ausfallen oder vorsorglich gesperrt werden.', ['Wind bewegt sich nur in Bahnhöfen.','Eine Zugtafel misst den globalen Klimawandel.'],'Das Bild zeigt eine konkrete Alltagsfolge, keine globale Wind- oder Klimamessung.','Überlege, welche Netze Orte miteinander verbinden.','kyrill-trains')
    ]},
    {id:'monsun',title:'Jahreszeiten & Monsun',badge:'Regenzeit-Forscher',tasks:[
      q('Ein Monsun bezeichnet zuerst …', 'eine jahreszeitliche großräumige Windumstellung.', ['jeden beliebigen heftigen Regenschauer.','einen Sturm, der immer ein Auge hat.'],'Regen ist oft mit dem Monsun verbunden; der Begriff beschreibt nicht nur seine Regenmenge.'),
      q('Warum wandert die ITCZ im Jahreslauf?', 'Die Zone starker Erwärmung verändert ihre Lage.', ['Der Äquator wird jeden Monat verschoben.','Die Erdachse verschwindet im Winter.'],'Die Neigung der Erdachse und thermische Unterschiede beeinflussen die saisonale Lage.'),
      q('Welche Rolle spielt der Ozean für den südasiatischen Sommermonsun?', 'Er liefert Feuchte für den Transport zum Land.', ['Er verhindert grundsätzlich jede Wolkenbildung.','Er ersetzt jede Wirkung von Gebirgen.'],'Feuchtetransport und Hebung sind entscheidend; Meer, Land und Gebirge wirken zusammen.'),
      q('Was können Gebirge mit anströmender feuchter Luft machen?', 'Sie können sie zum Aufsteigen zwingen und Regen verstärken.', ['Sie wandeln sie vollständig in Gestein um.','Sie löschen den Luftdruck aus.'],'Orographische Hebung kann Niederschlag verstärken; Anströmung und Feuchte müssen passen.'),
      m('Welche Folgen kann ein Monsun haben?', ['Er kann Wasserspeicher füllen.','Sehr starke Regenphasen können Überflutungen auslösen.','Er ist nur schädlich und nie lebensnotwendig.','Sein Ausbleiben ist für Landwirtschaft immer bedeutungslos.'],[0,1],'Wasserversorgung und Gefährdung sind zwei Seiten; Zeitpunkt und Menge sind wichtig.'),
      q('Warum kann eine Region eine Regen- und eine Trockenzeit haben?', 'Die Konvektions- und Feuchtetransportzone erreicht sie jahreszeitlich unterschiedlich.', ['Die Sonne wird regelmäßig ausgeschaltet.','Die Erde stoppt in der Trockenzeit ihre Drehung.'],'Jahreszeitliche Verlagerungen verändern regionale Niederschlagschancen.'),
      o('Ordne diese vereinfachte Kette für Monsunregen.', ['Die jahreszeitliche Erwärmung verändert die Zirkulation.','Bodennahe Strömung transportiert Ozeanfeuchte zum Land.','Luft steigt auf und kühlt ab.','Wasserdampf kondensiert und Niederschlag entsteht.'],'Das Schema ordnet den Zusammenhang; der Monsun wird nicht ausschließlich durch diese vier Schritte erklärt.'),
      q('Warum ist ein Vorher-Nachher-Satellitenbild für Pakistan hilfreich?', 'Es kann Veränderungen der Wasserflächen sichtbar machen.', ['Es nennt automatisch alle sozialen Folgen.','Es beweist allein, welcher Faktor wie viel Regen verursacht hat.'],'Für soziale Folgen und Ursachen braucht es weitere Quellen. Falschfarben müssen erklärt werden.','Frage, was man sieht und was man nur erschließen möchte.','pakistan'),
      q('Was ist bei Falschfarben besonders wichtig?', 'Die Bedeutung der Farb- und Bandkombination erklären.', ['Alle Farben als natürliche Landschaftsfarben vorlesen.','Die Legende aus Platzgründen verschweigen.'],'Farben kodieren Informationen; ohne Erklärung droht eine falsche Bilddeutung.'),
      q('Welche Aussage über Wintermonsun ist angemessen?', 'Die Wirkung hängt von Region, Anströmung und Relief ab.', ['Jeder Wintermonsun ist überall völlig trocken.','Wintermonsun ist ein anderes Wort für Schneesturm.'],'Auch im Winter können bestimmte Regionen bei Anströmung vom Meer viel Regen erhalten.')
    ]},
    {id:'extreme',title:'Sturm, Starkregen & Folgen',badge:'Risiko-Blick',tasks:[
      q('Welche Energiequelle unterstützt einen tropischen Wirbelsturm?', 'Wärme, die bei Kondensation von Wasserdampf frei wird.', ['Reibung der Wolken an der Mondoberfläche.','Das Geräusch des Windes allein.'],'Das warme Meer ermöglicht Verdunstung. Kondensation setzt Energie frei und unterstützt Konvektion.'),
      q('Warum entstehen tropische Wirbelstürme normalerweise nicht direkt am Äquator?', 'Die Corioliswirkung ist dort zu schwach für die typische Organisation.', ['Dort gibt es grundsätzlich kein warmes Wasser.','Dort gibt es niemals Wolken.'],'Warmes Wasser allein genügt nicht; Rotation, Störung und Scherung spielen ebenfalls eine Rolle.'),
      q('Sturmflut entsteht vor allem dadurch, dass …', 'Wind Meerwasser zur Küste treibt; niedriger Druck trägt zusätzlich bei.', ['ein Fluss immer aus dem Meer herausgezogen wird.','jede Welle ein Tsunami ist.'],'Sturmflut und Tsunami sind unterschiedliche Vorgänge.'),
      q('Was beschreibt eine Hurrikan-Kategorie vor allem?', 'Die Stärke des anhaltenden Windes.', ['Das gesamte Risiko für alle Menschen.','Die sichere Zahl der überfluteten Häuser.'],'Windkategorie allein beschreibt nicht Sturmflut, Regen, Küstenform oder Verletzlichkeit.'),
      m('Was beeinflusst ein Hochwasserrisiko im Tal?', ['Regenmenge und Regendauer.','Einzugsgebiet, Gelände und betroffene Infrastruktur.','Ausschließlich die Farbe des Flusses.','Nie die vorangegangene Nässe.'],[0,1],'Auch Bodenfeuchte, Abflusswege und Vorsorge verändern die Situation.'),
      n('Auf eine Fläche von 10 m² fallen 20 mm Regen. Wie viele Liter Wasser sind das insgesamt?',200,'L','20 mm entsprechen 20 L/m². 20 L/m² × 10 m² = 200 L.'),
      n('Auf ein Dach von 50 m² fallen 10 mm Regen. Wie viele Liter treffen das Dach?',500,'L','10 L/m² × 50 m² = 500 L. Wie viel gespeichert oder abgeführt wird, ist eine weitere Frage.'),
      o('Ordne eine vereinfachte Kette vom Starkregen bis zum steigenden Fluss.', ['Viel Niederschlag trifft das Einzugsgebiet.','Ein Teil des Wassers fließt von Hängen und Nebenbächen ab.','Zuflüsse erreichen den Hauptfluss.','Der Wasserstand kann rasch ansteigen.'],'Nicht alles Regenwasser fließt sofort ab. Versickerung, Speicherung und Laufzeiten müssen mitbedacht werden.'),
      q('Welche Aussage über Katastrophen ist am besten begründet?', 'Gefährdung, betroffene Menschen und Verletzlichkeit wirken zusammen.', ['Jedes Naturereignis ist automatisch eine Katastrophe.','Warnungen können niemals etwas verändern.'],'Ein Ereignis kann je nach Exposition und Vorsorge sehr unterschiedliche Folgen haben.'),
      q('Was zeigt das Ahrweiler-Foto direkt?', 'Sichtbare Folgen der Flut.', ['Die exakte prozentuale Ursache des Klimawandels.','Alle Niederschlagsmessungen im Einzugsgebiet.'],'Das Foto ist ein Folgenbeleg. Für Ursachen und Quantifizierung braucht man Messungen und Untersuchungen.','Trenne Beschreibung von Erklärung.','ahr')
    ]},
    {id:'hitze',title:'Hitze & Klimasprache',badge:'Hitze-Checker',tasks:[
      q('Was ist eine blockierende Wetterlage?', 'Ein langlebiges Muster, das übliche Zugbahnen umlenkt oder hemmt.', ['Eine technische Sperre im Satelliten.','Die vollständige Beendigung aller Winde.'],'Ein persistentes Hoch kann Wetter über längere Zeit prägen.'),
      q('Wie kann ein trockener Boden Hitze verstärken?', 'Weniger Verdunstung lässt mehr Energie für Erwärmung verfügbar.', ['Er erzeugt immer mehr Nebel.','Er entfernt die Sonneneinstrahlung.'],'Verdunstung benötigt Energie und wirkt kühlend; fehlt Wasser, verändert sich die Energiebilanz.'),
      q('Warum sind Tropennächte für die Wärmebelastung wichtig?', 'Sie erschweren die Erholung von der Wärmebelastung.', ['Nachts gibt es keine Wärmebelastung.','Sie zeigen ausschließlich die Tageshöchsttemperatur.'],'Dauer und fehlende nächtliche Abkühlung sind neben dem Tagesmaximum relevante Belastungsfaktoren.'),
      q('Was misst die NASA-Wärmekarte von Paris?', 'Temperaturen von Oberflächen.', ['Lufttemperatur jeder Wohnung.','Die Körpertemperatur aller Menschen.'],'ECOSTRESS beobachtet Oberflächenstrahlung; eine Lufttemperaturmessung ist etwas anderes.','Achte auf Messgröße und Datum.','paris-thermal'),
      q('Das Wärmebild stammt aus 2025. Darfst du es im Referat zu 2026 nutzen?', 'Ja, als klar datierte Illustration, nicht als Messbeleg für 2026.', ['Ja, wenn du das Datum entfernst.','Nein, ältere Bilder dürfen niemals Prinzipien illustrieren.'],'Vergleichsbild und Ereignismessung müssen sichtbar getrennt bleiben.'),
      m('Welche Bedingungen können eine städtische Wärmeinsel begünstigen?', ['Wärmespeicherung in Asphalt und Gebäuden.','Wenig Vegetation und Verdunstung.','Jeder einzelne Baum macht die gesamte Stadt immer heißer.','Alle Flächen haben unabhängig vom Material dieselbe Temperatur.'],[0,1],'Materialien, Schatten, Vegetation und Wasser verändern die Oberflächenbilanz.'),
      q('„Heißester französischer Sommer seit 1900“ bedeutet …', 'einen Rekord für Frankreich in der genannten Messreihe.', ['denselben Rekord an jedem Ort des Planeten.','dass jeder einzelne Tag überall der heißeste war.'],'Region, Zeitraum und statistische Größe gehören immer zur Aussage.'),
      q('Wie unterscheiden sich Wetterlage und Klimawandel?', 'Die Wetterlage erklärt den Ablauf; Klimawandel verändert langfristige Ausgangsbedingungen.', ['Beide Begriffe sind immer bedeutungsgleich.','Klimawandel bestimmt den Wind jeder Minute eindeutig.'],'Die genaue Klimarolle bei einem Ereignis wird mit Attributionsmethoden untersucht.'),
      q('Welche Formulierung zu einem Einzelereignis ist angemessen?', 'Eine Attributionsstudie kann eine Änderung von Wahrscheinlichkeit oder Intensität untersuchen.', ['Jedes Foto beweist die Ursache Klimawandel.','Ein heißer Tag widerlegt sämtliche Klimadaten.'],'Einzelereignis und statistischer Trend müssen getrennt, aber nicht als völlig unabhängig verstanden werden.'),
      o('Ordne eine vereinfachte Verstärkungskette bei Hitze.', ['Eine anhaltend sonnige Sommerlage erwärmt die Oberfläche.','Bodenwasser wird knapp.','Die Verdunstungskühlung kann abnehmen.','Zusätzliche Energie kann Boden und Luft stärker erwärmen.'],'Das ist eine mögliche Rückkopplung; sie ist nicht die einzige Ursache einer Hitzewelle.')
    ]},
    {id:'enso',title:'ENSO & Belege',badge:'Pazifik-Pfad',tasks:[
      q('Wohin treiben die typischen äquatorialen Passate Oberflächenwasser im Pazifik?', 'Überwiegend nach Westen.', ['Ausschließlich zum Nordpol.','Immer senkrecht auf den Meeresboden.'],'Dadurch liegt viel warmes Oberflächenwasser im westlichen Pazifik.'),
      q('Was ändert sich bei El Niño häufig?', 'Schwächere Passate und relativ wärmeres Wasser weiter im Osten.', ['Eine neue Erdachse entsteht.','Der Pazifik wird vollständig trocken.'],'Wind, Temperaturverteilung und Konvektion verändern sich als gekoppeltes System.'),
      q('ENSO ist …', 'eine gekoppelte Schwankung von Ozean und Atmosphäre.', ['der Name eines einzigen Hurrikans.','ein Synonym für jeden heißen Tag in Europa.'],'ENSO umfasst warme, kalte und neutrale Phasen; Fernwirkungen sind regional und saisonal verschieden.'),
      q('Was ist eine Temperaturabweichung von +1,8 °C?', 'Ein Unterschied gegenüber einem definierten Vergleichswert.', ['Eine absolute Meerestemperatur von 1,8 °C.','Automatisch die Lufttemperatur in Panama.'],'Eine Anomalie braucht Referenz, Messgebiet, Messgröße und Zeitraum.'),
      q('„Über 90 % Wahrscheinlichkeit eines sehr starken Verlaufs“ ist …', 'eine Prognose mit Unsicherheit.', ['ein garantiertes zukünftiges Messergebnis.','der Beweis, dass jeder Ort dieselbe Folge erlebt.'],'Selbst hohe Wahrscheinlichkeit ist keine Gewissheit; Stärke und lokale Folgen sind verschiedene Aussagen.'),
      q('Warum braucht der Panamakanal Regenwasser?', 'Seine Seen und Schleusen nutzen Süßwasser aus dem Einzugsgebiet.', ['Die Schiffe müssen dauerhaft auf Regenwolken fahren.','Die Ozeane liegen höher als alle Schleusen.'],'Wasserspeicher werden auch für Versorgung genutzt; geringe Zuflüsse beeinflussen Betriebsmöglichkeiten.'),
      m('Welche Informationen gehören zu einer ENSO-Aussage?', ['Datum und Gebiet.','Beobachtung oder Prognose sowie Messgröße.','Nur eine auffällige Farbe ohne Legende.','Die Annahme, jede Fernwirkung sei garantiert.'],[0,1],'Kontext verhindert Verwechslungen von Index, Weltkarte und konkretem Ereignis.'),
      o('Ordne diese vereinfachte mögliche Fernwirkungskette.', ['ENSO verändert tropische Erwärmung und Konvektion.','Großräumige Strömungen und regionale Regenchancen verändern sich.','Weniger Regen im Einzugsgebiet kann Speicherzuflüsse senken.','Geringere Wasservorräte können Betrieb und Versorgung begrenzen.'],'Die örtliche Kette muss durch lokale Daten belegt werden; ENSO allein beweist nicht jeden Einzelschritt.'),
      q('Welche Aussage passt zur NOAA-Karte typischer Fernwirkungen?', 'Sie zeigt statistische saisonale Muster, keine Garantie für jedes Jahr.', ['Sie ist eine tägliche Vorhersage für jede Stadt.','Ihre Farben sind immer aktuelle Messwerte von 2026.'],'Die Übersicht stammt aus 2016 und zeigt typische Zusammenhänge.','Lies auch die Datierung und die beiden Jahreszeiten.','enso'),
      q('Woran kannst du feststellen, ob ein neuer ENSO-Bericht deine Angaben ersetzt?', 'An Veröffentlichungsdatum, Beobachtungszeitraum und neuer Aussage.', ['Am Schriftstil allein.','Jeder ältere Link bleibt automatisch aktueller.'],'Lageberichte werden fortgeschrieben. Bewahrt euer Quellenlog und prüft Angaben vor dem Vortrag.')
    ]},
    {id:'vortragen',title:'Referat, KI & Teamarbeit',badge:'Erklär-Profi',tasks:[
      q('Was ist eine hilfreiche Leitfrage?', 'Eine Frage, die Mechanismus und einen konkreten Fall verbindet.', ['Eine bloße Liste mit zehn unverbundenen Stichwörtern.','Eine Frage, die nur die Gruppe kennt und nicht erklärt.'],'Ein roter Faden verbindet großes System, konkretes Ereignis und Alltag.'),
      q('Welche Folie unterstützt einen verständlichen Vortrag am besten?', 'Eine gut lesbare Grafik mit einer Hauptaussage.', ['Ein Absatz, der vollständig vorgelesen wird.','Viele unbeschriftete Diagramme gleichzeitig.'],'Folien unterstützen Erklärung; sie ersetzen sie nicht.'),
      q('Was bedeutet freies Sprechen?', 'Mit vorbereiteten Stichwörtern erklären und auf das Publikum reagieren.', ['Ohne jede Vorbereitung improvisieren.','Den Bildschirmtext Wort für Wort ablesen.'],'Vorbereitung, Verständnis und Probevortrag ermöglichen freies Sprechen.'),
      q('Was macht ein Boardmaster?', 'Er moderiert die Boardpflege und hilft, Blockaden sichtbar zu machen.', ['Er erledigt automatisch alle Karten allein.','Er ersetzt die fachliche Mitarbeit aller anderen.'],'Organisation ist eine eigene Aufgabe; Verantwortung für Kartenergebnisse bleibt eindeutig benannt.'),
      m('Was muss aus bewertbaren Kanbankarten hervorgehen?', ['Eine eindeutig verantwortliche Person.','Ein überprüfbares Ergebnis mit Belegen und Prüfstand.','Nur eine hohe Zahl von Karten ohne Inhalte.','Ausschließlich „alle gemeinsam“ statt Zuständigkeit.'],[0,1],'Die Lehrkraft beurteilt nachvollziehbare Beiträge und Qualität, nicht bloß Kartenmengen oder Verschiebungen.'),
      q('Welche Datei wird als Board-Produkt abgegeben?', 'Der JSON-Export aus der Schüler-Kanbanboard-App.', ['Nur ein Foto des leeren Boards.','Der Wetter-App-Textplan als angeblich identische Board-Datei.'],'Der echte Board-Export enthält Karten, Zuständigkeiten und Verlauf. Ein Projektplan ist kein Ersatz.'),
      q('KI erstellt eine Erklärung für euch. Was ist danach erforderlich?', 'Aussagen prüfen und selbst erklären sowie begründen können.', ['Ungeprüft übernehmen, solange es gut klingt.','Quellenangaben der KI als automatisch echt behandeln.'],'KI-Nutzung ist erlaubt, entbindet aber nicht von Verantwortung, Quellenprüfung und eigenem Verständnis.'),
      o('Ordne einen sinnvoll geprüften Arbeitsweg.', ['Leitfrage und konkrete Arbeitsaufgabe festlegen.','Informationen und Bilder recherchieren und prüfen.','Eine eigene verständliche Erklärung erarbeiten.','Im Probevortrag prüfen, ob das Publikum sie nachvollziehen kann.'],'KI darf unterstützen. Die Gruppe bleibt für Inhalte, Nachweise und glaubwürdige Erklärung verantwortlich.'),
      q('Eine Karte „Recherche erledigt“ hat weder Quelle noch Ergebnis. Was fehlt?', 'Nachvollziehbarer Inhalt und überprüfbare Fertig-Kriterien.', ['Noch mehr dekorative Farben.','Ein zusätzliches leeres Board.'],'Fertig bedeutet fachlich geprüft, belegt und nutzbar – nicht nur ein Statuswechsel.'),
      q('Ein Einzelarbeitender nutzt das Gruppenboard. Wie wird Verantwortung dokumentiert?', 'Die eigene Person ist eindeutig verantwortlich; Prüfung wird passend mit Lehrkraft vereinbart.', ['Ohne Namen, weil Einzelarbeit keine Verantwortung braucht.','Mit einer erfundenen zweiten Person für die Prüfung.'],'Bei Einzelarbeit gilt dieselbe Nachvollziehbarkeit. Keine falschen Namen eintragen, nur um einen Ablauf zu umgehen.')
    ]}
  ];
  groups.forEach(g=>g.tasks.forEach((t,i)=>{t.id=g.id+'-'+(i+1);t.group=g.id;}));
  const data={media,projects,groups,checks:[
    'Leitfrage und roter Faden verbinden Prinzip und konkreten Ort.',
    'Eine eigene Systemskizze ist verständlich erklärt und fachlich geprüft.',
    'Ereignisangaben besitzen Quelle, Datum, Region und passende Einheit.',
    'Fotos haben Urheber, Aufnahmedatum, Lizenz und Quelle; Bildtypen sind erklärt.',
    'Folien sind lesbar; wir sprechen mit Stichworten statt Text vorzulesen.',
    'KI-Beiträge sind geprüft und im Arbeitsprozess nachvollziehbar dokumentiert.',
    'Jede Person kann ihren Beitrag und den gemeinsamen Zusammenhang erklären.',
    'Jede relevante Kanbankarte hat genau eine verantwortliche Person.',
    'Ergebnisse, Quellen, Fertig-Kriterien und Prüfungen stehen auf den Karten.',
    'Der echte Board-JSON-Export ist gesichert und zur Abgabe bereit.',
    'Die Publikumsaufgabe prüft Verständnis, nicht nur Erinnern.',
    'Der Probevortrag einschließlich Rückfragen wurde durchgeführt.'
  ]};
  if(typeof module!=='undefined'&&module.exports)module.exports=data;
  else root.WetterWelten=data;
})(typeof window!=='undefined'?window:globalThis);
